<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>ydsz-pmis-literule</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-pmis-literule</name>
    <description>DDD Module</description>
        <properties>
        <jmh.version>1.37</jmh.version>
    </properties>
    <modules>
        <module>ydsz-pmis-literule-api</module>
        <module>ydsz-pmis-literule-domain</module>
        <module>ydsz-pmis-literule-infra</module>
        <module>ydsz-pmis-literule-server</module>
        <module>ydsz-pmis-literule-web</module>
    </modules>
</project>
