apiVersion: v1
kind: Secret
metadata:
  name: pmis-db-secret
  namespace: pmis
  labels:
    app.kubernetes.io/part-of: ydsz-pmis
type: Opaque
stringData:
  # 覆盖前请用 sealed-secrets / external-secrets 替换为加密 secret
  POSTGRES_PASSWORD: "pmis123"
  REDIS_PASSWORD: "pmis123"
  NACOS_PASSWORD: "nacos"
  MINIO_ROOT_PASSWORD: "minioadmin"
