# =====================================================================
#  YDSZ PMIS · Workflow · DEV 环境配置（Nacos DataId）
#  DataId:    ydsz-workflow-dev.yaml
#  Group:     dev
#  端口:      9006
# =====================================================================

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml,classpath*:mapper/flow/**/*.xml
  type-aliases-package: com.njydsz.workflow.entity
