# =============================================================================
#  YDSZ PMIS · Helm Chart DEV 环境覆盖值
# -----------------------------------------------------------------------------
#  用法:
#    helm install pmis deploy/helm/ydsz-pmis -n pmis-dev \
#      -f deploy/helm/ydsz-pmis/values-dev.yaml
# =============================================================================

global:
  imageTag: v1.3.0-SNAPSHOT
  nacos:
    serverAddr: nacos-server.pmis-dev.svc.cluster.local:8848
    namespace: pmis-dev

backend:
  springProfile: dev
  env:
    LOGGING_LEVEL_ROOT: DEBUG
    LOGGING_LEVEL_COM_NJYDSZ_PMIS: DEBUG
    SERVER_TOMCAT_URI_ENCODING: UTF-8

services:
  gateway:
    replicas: 1
    ingress:
      enabled: false
  system:
    replicas: 1
  userinfo:
    replicas: 1
  project:
    replicas: 1
  cronjob:
    replicas: 1
  workflow:
    replicas: 1
  agent:
    replicas: 1

podDisruptionBudget:
  enabled: false
