<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>ydsz-pmis-sales</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-pmis-sales</name>
    <description>DDD Module</description>
    <modules>
        <module>ydsz-pmis-sales-api</module>
        <module>ydsz-pmis-sales-domain</module>
        <module>ydsz-pmis-sales-infra</module>
        <module>ydsz-pmis-sales-server</module>
        <module>ydsz-pmis-sales-web</module>
    </modules>
</project>
