{{- /*
  YDSZ · 后端微服务通用 Service（ClusterIP，端口 8080）
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ydsz-backend.fullname" . }}
  labels:
    {{- include "ydsz-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ydsz-backend.selectorLabels" . | nindent 4 }}
