# =============================================================================
#  YDSZ · Helm Chart SIT 环境覆盖值
# =============================================================================

global:
  imageTag: v1.0.0-rc.1
  nacos:
    serverAddr: nacos-server.ydsz-sit.svc.cluster.local:8848
    namespace: ydsz-sit

backend:
  springProfile: sit
  env:
    LOGGING_LEVEL_ROOT: INFO
    LOGGING_LEVEL_COM_NJYDSZ_YDSZ: INFO

services:
  gateway:    { replicas: 2 }
  system:     { replicas: 2 }
  userinfo:   { replicas: 2 }
  project:    { replicas: 2 }
  cronjob:    { replicas: 1 }
  workflow:   { replicas: 2 }
  agent:      { replicas: 1 }

podDisruptionBudget:
  enabled: false
