package com.njydsz.common.queue.domain;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * {@link QueueMessage} 统一消息模型测试。
 *
 * <p>验证消息创建、序列化/反序列化、过期判断、顺序消息、重试计数等核心行为。
 * 该测试不依赖任何外部资源（Redis/Kafka/Rabbit），是消息队列的核心域逻辑保障。
 *
 * @author ydsz-team
 * @since 1.0.0
 */
@DisplayName("QueueMessage 统一消息模型测试")
class QueueMessageTest {

    @Test
    @DisplayName("of(body) 创建基础消息并填充默认值")
    void testOfBasicMessage() {
        QueueMessage message = QueueMessage.of("hello");

        assertEquals("hello", message.getBody());
        assertNotNull(message.getHeaders());
        assertNotNull(message.getTraceId());
        assertEquals(0, message.getRetryCount());
        assertNotNull(message.getTimestamp());
        assertEquals(Integer.MAX_VALUE, message.getPriority());
        assertEquals(0L, message.getExpireMillis());
    }

    @Test
    @DisplayName("of(body, priority) 设置优先级")
    void testOfWithPriority() {
        QueueMessage message = QueueMessage.of("urgent", 1);

        assertEquals("urgent", message.getBody());
        assertEquals(1, message.getPriority());
    }

    @Test
    @DisplayName("of(body, expireTime, unit) 设置过期时间")
    void testOfWithExpiration() {
        QueueMessage message = QueueMessage.of("temp", 5, TimeUnit.SECONDS);

        assertEquals(5000L, message.getExpireMillis());
    }

    @Test
    @DisplayName("of(body, headers, traceId, retryCount) 完整构造")
    void testOfFullConstructor() {
        Map<String, String> headers = new HashMap<>();
        headers.put("type", "order");
        headers.put("source", "api");

        QueueMessage message = QueueMessage.of("payload", headers, "trace-123", 2);

        assertEquals("payload", message.getBody());
        assertEquals(2, headers.size());
        assertEquals("order", message.getHeader("type"));
        assertEquals("trace-123", message.getTraceId());
        assertEquals(2, message.getRetryCount());
    }

    @Test
    @DisplayName("of() 对原始 headers 做防御性拷贝")
    void testOfDefensiveCopyHeaders() {
        Map<String, String> headers = new HashMap<>();
        headers.put("k1", "v1");

        QueueMessage message = QueueMessage.of("body", headers, "trace", 0);
        headers.put("k2", "v2"); // 修改原始 map

        assertEquals(1, message.getHeaders().size());
        assertNull(message.getHeader("k2"));
    }

    @Test
    @DisplayName("of() traceId 为空时自动生成")
    void testOfNullTraceIdAutoGenerated() {
        QueueMessage message = QueueMessage.of("body", null, null, 0);

        assertNotNull(message.getTraceId());
    }

    @Test
    @DisplayName("of() retryCount 为 null 时默认为 0")
    void testOfNullRetryCountDefaultsToZero() {
        QueueMessage message = QueueMessage.of("body", null, null, null);

        assertEquals(0, message.getRetryCount());
    }

    @Test
    @DisplayName("toPayload + fromPayload 往返序列化保持核心字段一致（headers 为 transient 不参与序列化）")
    void testPayloadRoundTrip() {
        QueueMessage original = QueueMessage.of("hello world");
        original.addHeader("type", "greeting");

        String payload = QueueMessage.toPayload(original);
        assertNotNull(payload);

        QueueMessage restored = QueueMessage.fromPayload(payload);
        assertNotNull(restored);
        assertEquals(original.getBody(), restored.getBody());
        assertEquals(original.getTraceId(), restored.getTraceId());
        assertEquals(original.getRetryCount(), restored.getRetryCount());
        // headers 为 transient，反序列化后为空 Map（fromPayload 会初始化）
        assertNotNull(restored.getHeaders());
        assertTrue(restored.getHeaders().isEmpty());
    }

    @Test
    @DisplayName("toPayload(null) 返回 null")
    void testToPayloadNullReturnsNull() {
        assertNull(QueueMessage.toPayload(null));
    }

    @Test
    @DisplayName("fromPayload(null/empty/blank) 返回 null")
    void testFromPayloadNullReturnsNull() {
        assertNull(QueueMessage.fromPayload(null));
        assertNull(QueueMessage.fromPayload(""));
        assertNull(QueueMessage.fromPayload("   "));
    }

    @Test
    @DisplayName("fromPayload(非 JSON 字符串) 降级为以字符串为 body 的新消息")
    void testFromPayloadNonJsonDegradesToBody() {
        QueueMessage message = QueueMessage.fromPayload("plain text message");

        assertNotNull(message);
        assertEquals("plain text message", message.getBody());
        assertNotNull(message.getTraceId());
        assertEquals(0, message.getRetryCount());
    }

    @Test
    @DisplayName("fromPayload(超大 payload) 抛出 IllegalArgumentException")
    void testFromPayloadOversizedThrows() {
        StringBuilder sb = new StringBuilder(17 * 1024 * 1024);
        for (int i = 0; i < 17 * 1024 * 1024; i++) {
            sb.append('a');
        }
        String oversized = sb.toString();

        assertThrows(IllegalArgumentException.class, () -> QueueMessage.fromPayload(oversized));
    }

    @Test
    @DisplayName("toPayload 为 null 字段填充默认值")
    void testToPayloadFillsNullFieldsWithDefaults() {
        QueueMessage message = new QueueMessage();
        message.setBody("body");

        String payload = QueueMessage.toPayload(message);
        assertNotNull(payload);

        QueueMessage restored = QueueMessage.fromPayload(payload);
        assertNotNull(restored.getHeaders());
        assertNotNull(restored.getTraceId());
        assertNotNull(restored.getTimestamp());
        assertEquals(0, restored.getRetryCount());
        assertEquals(Integer.MAX_VALUE, restored.getPriority());
        assertEquals(0L, restored.getExpireMillis());
    }

    @Test
    @DisplayName("addHeader 链式调用并初始化 null headers")
    void testAddHeaderChaining() {
        QueueMessage message = new QueueMessage();
        message.setBody("body");

        assertNull(message.getHeaders());

        QueueMessage returned = message.addHeader("k1", "v1").addHeader("k2", "v2");
        assertSame(message, returned);
        assertEquals(2, message.getHeaders().size());
        assertEquals("v1", message.getHeader("k1"));
    }

    @Test
    @DisplayName("getHeader 在 headers 为 null 时返回 null")
    void testGetHeaderWhenHeadersNull() {
        QueueMessage message = new QueueMessage();
        message.setBody("body");

        assertNull(message.getHeader("any"));
    }

    @Test
    @DisplayName("isExpired 未设置 expireMillis 时返回 false")
    void testIsExpiredNoExpireMillis() {
        QueueMessage message = QueueMessage.of("body");
        assertFalse(message.isExpired());
    }

    @Test
    @DisplayName("isExpired expireMillis <= 0 时返回 false")
    void testIsExpiredNonPositiveExpireMillis() {
        QueueMessage message = QueueMessage.of("body");
        message.setExpireMillis(0L);
        assertFalse(message.isExpired());

        message.setExpireMillis(-1L);
        assertFalse(message.isExpired());
    }

    @Test
    @DisplayName("isExpired 过期时间已过返回 true")
    void testIsExpiredPastTime() throws InterruptedException {
        QueueMessage message = QueueMessage.of("body", 50, TimeUnit.MILLISECONDS);
        // 等待 100ms 确保已过期
        Thread.sleep(100);
        assertTrue(message.isExpired());
    }

    @Test
    @DisplayName("isExpired 过期时间未到返回 false")
    void testIsExpiredBeforeExpiry() {
        QueueMessage message = QueueMessage.of("body", 10, TimeUnit.SECONDS);
        assertFalse(message.isExpired());
    }

    @Test
    @DisplayName("isExpired timestamp 为空时返回 false（无法判断）")
    void testIsExpiredNullTimestamp() {
        QueueMessage message = QueueMessage.of("body");
        message.setExpireMillis(1000L);
        message.setTimestamp(null);
        assertFalse(message.isExpired());
    }

    @Test
    @DisplayName("isHighPriority(threshold) 数值越小优先级越高")
    void testIsHighPriorityWithThreshold() {
        QueueMessage message = QueueMessage.of("body", 5);

        assertTrue(message.isHighPriority(10));
        assertFalse(message.isHighPriority(5));
        assertFalse(message.isHighPriority(1));
    }

    @Test
    @DisplayName("isHighPriority() 默认阈值 1000")
    void testIsHighPriorityDefaultThreshold() {
        QueueMessage urgent = QueueMessage.of("body", 100);
        QueueMessage normal = QueueMessage.of("body", 2000);

        assertTrue(urgent.isHighPriority());
        assertFalse(normal.isHighPriority());
    }

    @Test
    @DisplayName("isSequential() 设置 messageGroupKey 后为顺序消息")
    void testIsSequential() {
        QueueMessage message = QueueMessage.of("body");
        assertFalse(message.isSequential());

        message.setSequential("order-123", 1L);
        assertTrue(message.isSequential());
        assertEquals("order-123", message.getMessageGroupKey());
        assertEquals(1L, message.getSequenceNumber());
    }

    @Test
    @DisplayName("isSequential() messageGroupKey 为空字符串返回 false")
    void testIsSequentialEmptyKey() {
        QueueMessage message = QueueMessage.of("body");
        message.setSequential("", null);
        assertFalse(message.isSequential());
    }

    @Test
    @DisplayName("incrementRetryCount() 递增并返回新值")
    void testIncrementRetryCount() {
        QueueMessage message = QueueMessage.of("body");

        assertEquals(1, message.incrementRetryCount());
        assertEquals(1, message.getRetryCount());

        assertEquals(2, message.incrementRetryCount());
        assertEquals(2, message.getRetryCount());

        assertEquals(3, message.incrementRetryCount());
        assertEquals(3, message.getRetryCount());
    }

    @Test
    @DisplayName("incrementRetryCount() retryCount 为 null 时从 0 开始递增")
    void testIncrementRetryCountFromNull() {
        QueueMessage message = new QueueMessage();
        message.setBody("body");
        message.setRetryCount(null);

        assertEquals(1, message.incrementRetryCount());
    }

    @Test
    @DisplayName("reset() 重置 retryCount/traceId/timestamp")
    void testReset() throws InterruptedException {
        QueueMessage message = QueueMessage.of("body");
        String originalTraceId = message.getTraceId();
        String originalTimestamp = message.getTimestamp();
        message.incrementRetryCount();
        message.incrementRetryCount();

        // 等待 5ms 确保时间戳精度（毫秒级）发生变化
        Thread.sleep(5);

        message.reset();

        assertEquals(0, message.getRetryCount());
        assertNotEquals(originalTraceId, message.getTraceId());
        assertNotEquals(originalTimestamp, message.getTimestamp());
    }

    @Test
    @DisplayName("getSummary() 返回格式化的摘要字符串")
    void testGetSummary() {
        QueueMessage message = QueueMessage.of("hello");
        message.setRetryCount(2);
        message.setPriority(1);

        String summary = message.getSummary();
        assertNotNull(summary);
        assertTrue(summary.contains("traceId="));
        assertTrue(summary.contains("retry=2"));
        assertTrue(summary.contains("priority=1"));
        assertTrue(summary.contains("bodyLen=5"));
    }

    @Test
    @DisplayName("toString() 长 body 被截断为 100 字符 + 省略号")
    void testToStringTruncatesLongBody() {
        StringBuilder longBody = new StringBuilder();
        for (int i = 0; i < 200; i++) {
            longBody.append('x');
        }
        QueueMessage message = QueueMessage.of(longBody.toString());

        String str = message.toString();
        assertNotNull(str);
        // body 部分应被截断（截断后 100 字符 + "..."）
        assertTrue(str.contains("..."));
    }

    @Test
    @DisplayName("toString() 短 body 完整输出")
    void testToStringShortBody() {
        QueueMessage message = QueueMessage.of("hi");

        String str = message.toString();
        assertTrue(str.contains("body='hi'"));
        assertFalse(str.contains("..."));
    }
}
