<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.remisoft</groupId>
        <artifactId>remi-cloud</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>remi-userinfo</artifactId>
    <packaging>pom</packaging>
    <name>remi-userinfo</name>
    <description>DDD Module</description>
    <modules>
        <module>remi-userinfo-api</module>
        <module>remi-userinfo-domain</module>
        <module>remi-userinfo-infra</module>
        <module>remi-userinfo-server</module>
        <module>remi-userinfo-web</module>
    </modules>
</project>
