<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ydsz-pmis-common</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-pmis-common</name>
    <description>DDD Module</description>

    <modules>
        <module>ydsz-pmis-common-core</module>
        <module>ydsz-pmis-common-util</module>
        <module>ydsz-pmis-common-domain</module>
        <module>ydsz-pmis-common-data</module>
        <module>ydsz-pmis-common-security</module>
        <module>ydsz-pmis-common-feign</module>
        <module>ydsz-pmis-common-web</module>
        <module>ydsz-pmis-common-infra</module>
        <module>ydsz-pmis-common-all</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-util</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-data</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-feign</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.njydsz.pmis</groupId>
                <artifactId>ydsz-pmis-common-all</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
