<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-common</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ydsz-pmis-common-file</artifactId>
    <name>ydsz-pmis-common-file</name>
    <description>PMIS Common File - 文件存储/分片上传/多平台支持</description>

    <dependencies>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-util</artifactId>
        </dependency>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-exception</artifactId>
        </dependency>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-redis</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>esdk-obs-java</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.qiniu</groupId>
            <artifactId>qiniu-java-sdk</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
