-- ============================================================================
-- ydsz-cloud 代码生成器模块数据库脚本 (ydsz-generator)
-- ============================================================================
-- 模块：ydsz-generator（代码生成器）
-- 说明：代码生成器所需的全部表结构（数据源配置、模板分组、模板、生成历史、元数据缓存）。
--       基于 MySQL 8.0 版本转译生成 (PostgreSQL 11+)
--       - 类型映射: JSON→JSONB / TINYINT(1)→SMALLINT / INT→INTEGER / DATETIME→TIMESTAMP
--       - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾统一生成)
--       - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--       - 索引/约束名按 schema 级唯一性命名: idx_{table}_{core} / uk_{table}_{core}
--       - 表名前缀 gen_ → ydzsz_gen_ (云顶编码规范要求)
--       - 执行方式: psql -U <user> -d <db> -f ydsz-generator.sql
-- 数据库：PostgreSQL 11+
-- 日期：2026-09-05
-- @author ydsz-team
-- ============================================================================


-- ============================================================================
-- 1. 数据源配置表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_datasource (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(64)              NOT NULL,
    jdbc_url                 VARCHAR(512)             NOT NULL,
    username                 VARCHAR(128)             NOT NULL,
    password                 VARCHAR(512)             NOT NULL,
    dialect                  VARCHAR(32)              NOT NULL DEFAULT 'POSTGRESQL',
    is_default               SMALLINT                 NOT NULL DEFAULT 0,
    description              VARCHAR(255)             DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_datasource PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_datasource_name UNIQUE (name)
);

COMMENT ON TABLE ydzs_gen_datasource IS '代码生成器数据源配置';
COMMENT ON COLUMN ydsz_gen_datasource.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_datasource.name IS '数据源名称（唯一标识）';
COMMENT ON COLUMN ydsz_gen_datasource.jdbc_url IS 'JDBC URL';
COMMENT ON COLUMN ydsz_gen_datasource.username IS '数据库用户名';
COMMENT ON COLUMN ydsz_gen_datasource.password IS '数据库密码（AES 加密存储）';
COMMENT ON COLUMN ydsz_gen_datasource.dialect IS '数据库方言（POSTGRESQL/MYSQL/ORACLE）';
COMMENT ON COLUMN ydsz_gen_datasource.is_default IS '是否为默认数据源（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_datasource.description IS '数据源描述';
COMMENT ON COLUMN ydsz_gen_datasource.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_datasource.updated_at IS '更新时间';


-- ============================================================================
-- 2. 模板分组表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_template_group (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(64)              NOT NULL,
    description              VARCHAR(255)             DEFAULT NULL,
    is_system                SMALLINT                 NOT NULL DEFAULT 0,
    sort_order               INTEGER                  NOT NULL DEFAULT 0,
    is_active                SMALLINT                 NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_template_group PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_template_group_name UNIQUE (name)
);

COMMENT ON TABLE ydzs_gen_template_group IS '代码生成器模板分组';
COMMENT ON COLUMN ydsz_gen_template_group.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_template_group.name IS '分组名（唯一标识，如 default、mybatis-plus）';
COMMENT ON COLUMN ydsz_gen_template_group.description IS '分组描述';
COMMENT ON COLUMN ydsz_gen_template_group.is_system IS '是否为系统分组（0=否 1=是，系统分组不可删除）';
COMMENT ON COLUMN ydsz_gen_template_group.sort_order IS '排序序号（升序）';
COMMENT ON COLUMN ydsz_gen_template_group.is_active IS '是否激活为当前使用分组（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template_group.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_template_group.updated_at IS '更新时间';


-- ============================================================================
-- 3. 模板表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_template (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id                 BIGINT                   NOT NULL,
    file_name                VARCHAR(128)             NOT NULL,
    description              VARCHAR(255)             DEFAULT NULL,
    content                  TEXT                     NOT NULL,
    is_folder                SMALLINT                 NOT NULL DEFAULT 0,
    parent_path              VARCHAR(512)             NOT NULL DEFAULT '',
    version                  INTEGER                  NOT NULL DEFAULT 1,
    hash                     CHAR(32)                 DEFAULT NULL,
    is_active                SMALLINT                 NOT NULL DEFAULT 1,
    file_type                VARCHAR(16)              NOT NULL DEFAULT 'BACKEND',
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_template_group_file UNIQUE (group_id, file_name),
    CONSTRAINT fk_ydsz_gen_template_group FOREIGN KEY (group_id) REFERENCES ydsz_gen_template_group (id)
);

COMMENT ON TABLE ydzs_gen_template IS '代码生成器模板';
COMMENT ON COLUMN ydsz_gen_template.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_template.group_id IS '关联模板分组 ID';
COMMENT ON COLUMN ydsz_gen_template.file_name IS '文件名（如 entity.vm、vue/api.vm）';
COMMENT ON COLUMN ydsz_gen_template.description IS '模板用途描述';
COMMENT ON COLUMN ydsz_gen_template.content IS '模板内容（Velocity 语法）';
COMMENT ON COLUMN ydsz_gen_template.is_folder IS '是否为虚拟文件夹标记（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template.parent_path IS '父路径（如 vue/ 表示前端子目录）';
COMMENT ON COLUMN ydsz_gen_template.version IS '当前版本号';
COMMENT ON COLUMN ydsz_gen_template.hash IS '内容 MD5 哈希（版本对比用）';
COMMENT ON COLUMN ydsz_gen_template.is_active IS '是否启用（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template.file_type IS '模板类型（BACKEND/FRONTEND）';
COMMENT ON COLUMN ydsz_gen_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_template.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_gen_template_group ON ydsz_gen_template (group_id);


-- ============================================================================
-- 4. 代码生成任务历史表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_history (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module_name              VARCHAR(64)              NOT NULL,
    datasource_id            BIGINT                   NOT NULL,
    template_group_id        BIGINT                   NOT NULL,
    table_count              INTEGER                  NOT NULL DEFAULT 0,
    file_count               INTEGER                  NOT NULL DEFAULT 0,
    status                   VARCHAR(16)              NOT NULL DEFAULT 'RUNNING',
    triggered_by             VARCHAR(64)              DEFAULT NULL,
    started_at               TIMESTAMP                NOT NULL,
    finished_at              TIMESTAMP                DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    gen_params               JSONB                    DEFAULT NULL,
    CONSTRAINT pk_ydsz_gen_history PRIMARY KEY (id),
    CONSTRAINT fk_ydsz_gen_history_datasource FOREIGN KEY (datasource_id) REFERENCES ydsz_gen_datasource (id),
    CONSTRAINT fk_ydsz_gen_history_template_group FOREIGN KEY (template_group_id) REFERENCES ydsz_gen_template_group (id)
);

COMMENT ON TABLE ydzs_gen_history IS '代码生成任务历史';
COMMENT ON COLUMN ydsz_gen_history.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_history.module_name IS '模块名称';
COMMENT ON COLUMN ydsz_gen_history.datasource_id IS '使用的数据源 ID';
COMMENT ON COLUMN ydsz_gen_history.template_group_id IS '使用的模板分组 ID';
COMMENT ON COLUMN ydsz_gen_history.table_count IS '涉及表数量';
COMMENT ON COLUMN ydsz_gen_history.file_count IS '生成文件总数';
COMMENT ON COLUMN ydsz_gen_history.status IS '执行状态（RUNNING/SUCCESS/PARTIAL/FAILED）';
COMMENT ON COLUMN ydsz_gen_history.triggered_by IS '触发人（用户名）';
COMMENT ON COLUMN ydsz_gen_history.started_at IS '开始时间';
COMMENT ON COLUMN ydsz_gen_history.finished_at IS '完成时间';
COMMENT ON COLUMN ydsz_gen_history.error_message IS '错误信息（失败时记录）';
COMMENT ON COLUMN ydsz_gen_history.gen_params IS '生成参数 JSON 快照';

CREATE INDEX IF NOT EXISTS idx_ydsz_gen_history_status ON ydsz_gen_history (status);
CREATE INDEX IF NOT EXISTS idx_ydsz_gen_history_started ON ydsz_gen_history (started_at);


-- ============================================================================
-- 5. 生成历史文件明细表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_history_file (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    history_id               BIGINT                   NOT NULL,
    file_path                VARCHAR(512)             NOT NULL,
    original_backup_path     VARCHAR(512)             DEFAULT NULL,
    file_hash                CHAR(32)                 DEFAULT NULL,
    action                   VARCHAR(16)              NOT NULL DEFAULT 'CREATED',
    CONSTRAINT pk_ydsz_gen_history_file PRIMARY KEY (id),
    CONSTRAINT fk_ydsz_gen_history_file_history FOREIGN KEY (history_id) REFERENCES ydsz_gen_history (id)
);

COMMENT ON TABLE ydzs_gen_history_file IS '生成历史文件明细';
COMMENT ON COLUMN ydsz_gen_history_file.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_history_file.history_id IS '所属任务 ID';
COMMENT ON COLUMN ydsz_gen_history_file.file_path IS '生成文件路径';
COMMENT ON COLUMN ydsz_gen_history_file.original_backup_path IS '原文件备份路径（用于回滚）';
COMMENT ON COLUMN ydsz_gen_history_file.file_hash IS '文件内容 MD5 哈希';
COMMENT ON COLUMN ydsz_gen_history_file.action IS '文件操作类型（CREATED/UPDATED/UNCHANGED）';

CREATE INDEX IF NOT EXISTS idx_ydsz_gen_history_file_history ON ydsz_gen_history_file (history_id);


-- ============================================================================
-- 6. 表元数据缓存表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_table_meta (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    datasource_id            BIGINT                   NOT NULL,
    table_name               VARCHAR(128)             NOT NULL,
    comment                  VARCHAR(255)             DEFAULT NULL,
    alias_name               VARCHAR(64)              DEFAULT NULL,
    module_name              VARCHAR(64)              DEFAULT NULL,
    cached_at                TIMESTAMP                NOT NULL,
    CONSTRAINT pk_ydsz_gen_table_meta PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_table_meta_ds_table UNIQUE (datasource_id, table_name),
    CONSTRAINT fk_ydsz_gen_table_meta_datasource FOREIGN KEY (datasource_id) REFERENCES ydsz_gen_datasource (id)
);

COMMENT ON TABLE ydzs_gen_table_meta IS '表元数据缓存';
COMMENT ON COLUMN ydsz_gen_table_meta.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_table_meta.datasource_id IS '关联数据源 ID';
COMMENT ON COLUMN ydsz_gen_table_meta.table_name IS '物理表名';
COMMENT ON COLUMN ydsz_gen_table_meta.comment IS '表注释';
COMMENT ON COLUMN ydsz_gen_table_meta.alias_name IS '用户自定义别名（用于类名生成）';
COMMENT ON COLUMN ydsz_gen_table_meta.module_name IS '模块名称（用于包路径）';
COMMENT ON COLUMN ydsz_gen_table_meta.cached_at IS '缓存时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_gen_table_meta_datasource ON ydsz_gen_table_meta (datasource_id);


-- ============================================================================
-- 7. 列元数据缓存表
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_gen_column_meta (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_meta_id            BIGINT                   NOT NULL,
    column_name              VARCHAR(128)             NOT NULL,
    data_type                VARCHAR(64)              NOT NULL,
    column_size              INTEGER                  DEFAULT NULL,
    nullable                 SMALLINT                 NOT NULL DEFAULT 1,
    is_pk                    SMALLINT                 NOT NULL DEFAULT 0,
    comment                  VARCHAR(255)             DEFAULT NULL,
    override_java_type       VARCHAR(64)              DEFAULT NULL,
    override_field_name      VARCHAR(64)              DEFAULT NULL,
    skip_dto                 SMALLINT                 NOT NULL DEFAULT 0,
    skip_vo                  SMALLINT                 NOT NULL DEFAULT 0,
    skip_query               SMALLINT                 NOT NULL DEFAULT 0,
    extra_config             JSONB                    DEFAULT NULL,
    CONSTRAINT pk_ydsz_gen_column_meta PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_column_meta_table_column UNIQUE (table_meta_id, column_name),
    CONSTRAINT fk_ydsz_gen_column_meta_table FOREIGN KEY (table_meta_id) REFERENCES ydsz_gen_table_meta (id)
);

COMMENT ON TABLE ydzs_gen_column_meta IS '列元数据缓存（含人工覆盖配置）';
COMMENT ON COLUMN ydsz_gen_column_meta.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_column_meta.table_meta_id IS '所属表元数据 ID';
COMMENT ON COLUMN ydsz_gen_column_meta.column_name IS '物理列名';
COMMENT ON COLUMN ydsz_gen_column_meta.data_type IS '物理数据类型';
COMMENT ON COLUMN ydsz_gen_column_meta.column_size IS '字段长度';
COMMENT ON COLUMN ydsz_gen_column_meta.nullable IS '是否可为空（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_column_meta.is_pk IS '是否为主键（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_column_meta.comment IS '字段注释';
COMMENT ON COLUMN ydsz_gen_column_meta.override_java_type IS '人工覆盖 Java 类型（为空则使用自动映射）';
COMMENT ON COLUMN ydsz_gen_column_meta.override_field_name IS '人工覆盖字段名（为空则使用自动命名）';
COMMENT ON COLUMN ydsz_gen_column_meta.skip_dto IS '是否在 DTO 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_column_meta.skip_vo IS '是否在 VO 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_column_meta.skip_query IS '是否在 Query 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_column_meta.extra_config IS '扩展配置 JSON（枚举值、校验规则等）';

CREATE INDEX IF NOT EXISTS idx_ydsz_gen_column_meta_table ON ydsz_gen_column_meta (table_meta_id);


-- ============================================================================
-- 8. 初始化数据（模板分组）
-- ============================================================================

INSERT INTO ydsz_gen_template_group (name, description, is_system, sort_order, is_active)
VALUES ('default', '标准 DDD 分层模板（entity/service/controller/repository...）', 1, 1, 1)
ON CONFLICT (name) DO UPDATE SET is_system = 1;

INSERT INTO ydsz_gen_template_group (name, description, is_system, sort_order, is_active)
VALUES ('mybatis-plus', 'Mybatis-Plus 增强版模板（含 Wrapper/通用 Service）', 1, 2, 0)
ON CONFLICT (name) DO UPDATE SET is_system = 1;


-- ============================================================================
-- 9. updated_at 自动更新触发器
-- ============================================================================
-- 说明：PostgreSQL 不支持 ON UPDATE CURRENT_TIMESTAMP，使用触发器实现

CREATE OR REPLACE FUNCTION ydsz_gen_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 为需要自动更新 updated_at 的表创建触发器
DO $$
DECLARE
    t TEXT;
    tbls TEXT[] := ARRAY[
        'ydsz_gen_datasource',
        'ydsz_gen_template_group',
        'ydsz_gen_template'
    ];
BEGIN
    FOREACH t IN ARRAY tbls
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I;
             CREATE TRIGGER trg_%s_updated_at
                 BEFORE UPDATE ON %I
                 FOR EACH ROW
                 EXECUTE FUNCTION ydsz_gen_update_timestamp();',
            t, t, t, t
        );
    END LOOP;
END;
$$;
