-- ============================================================================
-- ydsz-cloud: ydsz-message（消息中心模块）PostgreSQL DDL 脚本
-- ----------------------------------------------------------------------------
-- 说明: 基于 ydsz-message-infra 模块实体类整理的完整建表脚本
--       (MsgTemplate / MsgTemplateVersion / MsgNotification / MsgLog /
--        MsgBatch / MsgReceipt / MsgTrace / MsgSubscription / MsgPreference /
--        MsgOffline / MsgUserChannel / MsgVariableSource / MsgRouteRule /
--        MsgTenantConfig / MsgCanary / MsgFeedback / MsgAggregate / OutboxEvent)
-- 规范:
--   - 主键为应用层 Snowflake ID（String → VARCHAR(32)）
--   - 公共列按实体继承链累积:
--       MpBaseIdEntity     → id
--       MpBaseAuditEntity  → + created_by / created_at / updated_by / updated_at
--       MpSimpleEntity     → + deleted / status / tenant_id
--       MpBaseEntity       → + revision（乐观锁）
--   - 禁止物理外键，逻辑外键列加普通索引
--   - 日志/轨迹/回执类表对业务时间列与发送状态列加索引
-- 字符集: utf8mb4
-- 日期: 2026-08-25
-- @author ydsz-team
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 消息模板主表（支持 ${var} 嵌套占位符 / 多语言 i18n / 版本 / 审核 / 分类 / 场景）
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (PostgreSQL 11+)
--   - 类型映射: JSON→JSONB / TINYINT(1)→SMALLINT / INT→INTEGER / DATETIME→TIMESTAMP
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾统一生成)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   - 索引/约束名按 schema 级唯一性命名: idx_{table}_{core} / uk_{table}_{core}
--   - 原 MySQL 前缀索引 path(255) → 表达式索引 left(path,255)
--   - 原 MySQL FULLTEXT 索引 → GIN to_tsvector('simple', ...) 全文索引
--   - 执行方式: psql -U <user> -d <db> -f ydsz-message.sql
-- ============================================================================


CREATE TABLE IF NOT EXISTS ydsz_msg_template (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    template_code            VARCHAR(64)              NOT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    locale                   VARCHAR(16)              DEFAULT 'zh-CN',
    version                  VARCHAR(32)              NOT NULL DEFAULT '1',
    category                 VARCHAR(64)              DEFAULT NULL,
    scene_code               VARCHAR(64)              DEFAULT NULL,
    subject                  VARCHAR(255)             DEFAULT NULL,
    content                  TEXT                     NOT NULL,
    provider                 VARCHAR(64)              DEFAULT NULL,
    provider_key             VARCHAR(128)             DEFAULT NULL,
    sign_name                VARCHAR(128)             DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'DISABLED',
    audit_status             VARCHAR(32)              NOT NULL DEFAULT 'DRAFT',
    audit_by                 VARCHAR(64)              DEFAULT NULL,
    audit_at                 TIMESTAMP                DEFAULT NULL,
    audit_remark             VARCHAR(512)             DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    variable_defs            JSONB                    DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_template_template_code UNIQUE (template_code, tenant_id)
);

COMMENT ON TABLE ydsz_msg_template IS '消息模板主表';
COMMENT ON COLUMN ydsz_msg_template.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_template.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_template.template_code IS '模板唯一编码（业务标识）';
COMMENT ON COLUMN ydsz_msg_template.channel IS '发送通道（SMS/EMAIL/PUSH/INAPP/WEBHOOK/DINGTALK/DINGTALK_WORK/WECOM/WECOM_APP/FEISHU/WX_MINI/ALIPAY_MINI）';
COMMENT ON COLUMN ydsz_msg_template.locale IS '语言区域（如 zh-CN / en-US，影响 i18n 选择）';
COMMENT ON COLUMN ydsz_msg_template.version IS '模板版本号';
COMMENT ON COLUMN ydsz_msg_template.category IS '模板分类';
COMMENT ON COLUMN ydsz_msg_template.scene_code IS '场景编码';
COMMENT ON COLUMN ydsz_msg_template.subject IS '消息标题';
COMMENT ON COLUMN ydsz_msg_template.content IS '模板内容（支持 ${var} 嵌套占位符）';
COMMENT ON COLUMN ydsz_msg_template.provider IS '服务商编码';
COMMENT ON COLUMN ydsz_msg_template.provider_key IS '服务商侧模板 Key';
COMMENT ON COLUMN ydsz_msg_template.sign_name IS '签名名称（如短信签名）';
COMMENT ON COLUMN ydsz_msg_template.status IS '模板状态: ENABLED 启用 / DISABLED 禁用';
COMMENT ON COLUMN ydsz_msg_template.audit_status IS '审核状态: DRAFT 草稿 / AUDITING 审核中 / APPROVED 已通过 / REJECTED 已驳回';
COMMENT ON COLUMN ydsz_msg_template.audit_by IS '审核人';
COMMENT ON COLUMN ydsz_msg_template.audit_at IS '审核时间';
COMMENT ON COLUMN ydsz_msg_template.audit_remark IS '审核意见';
COMMENT ON COLUMN ydsz_msg_template.description IS '描述说明';
COMMENT ON COLUMN ydsz_msg_template.variable_defs IS '模板变量定义（JSON）';
COMMENT ON COLUMN ydsz_msg_template.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_template.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_template.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_template.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_template_channel ON ydsz_msg_template (channel);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_template_scene_code ON ydsz_msg_template (scene_code);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_template_tenant_deleted ON ydsz_msg_template (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_template_version (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    template_code            VARCHAR(64)              NOT NULL,
    version                  INTEGER                  NOT NULL,
    content                  TEXT                     NOT NULL,
    variable_defs            JSONB                    DEFAULT NULL,
    audit_status             VARCHAR(32)              DEFAULT NULL,
    auditor                  VARCHAR(64)              DEFAULT NULL,
    audit_remark             VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_template_version PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_template_version_tpl_version UNIQUE (template_code, version)
);

COMMENT ON TABLE ydsz_msg_template_version IS '消息模板版本历史表';
COMMENT ON COLUMN ydsz_msg_template_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_template_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_template_version.template_code IS '模板编码（关联 ydsz_msg_template.template_code）';
COMMENT ON COLUMN ydsz_msg_template_version.version IS '版本号（每次审核通过递增，如 1, 2, 3）';
COMMENT ON COLUMN ydsz_msg_template_version.content IS '模板内容快照';
COMMENT ON COLUMN ydsz_msg_template_version.variable_defs IS '模板变量定义快照（JSON）';
COMMENT ON COLUMN ydsz_msg_template_version.audit_status IS '审核状态: APPROVED 已通过 / REJECTED 已拒绝';
COMMENT ON COLUMN ydsz_msg_template_version.auditor IS '审核人';
COMMENT ON COLUMN ydsz_msg_template_version.audit_remark IS '审核意见';
COMMENT ON COLUMN ydsz_msg_template_version.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_template_version.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_template_version.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_template_version.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_template_version.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_template_version.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_template_version.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_template_version_tenant_deleted ON ydsz_msg_template_version (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_notification (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    title                    VARCHAR(255)             NOT NULL,
    content                  TEXT                    ,
    level                    VARCHAR(32)              NOT NULL DEFAULT 'INFO',
    category                 VARCHAR(32)              NOT NULL DEFAULT 'SYSTEM',
    priority                 VARCHAR(32)              NOT NULL DEFAULT 'NORMAL',
    sender_id                VARCHAR(32)              DEFAULT NULL,
    receiver_id              VARCHAR(32)              NOT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    biz_id                   VARCHAR(64)              DEFAULT NULL,
    message_group            VARCHAR(64)              DEFAULT NULL,
    batch_id                 VARCHAR(64)              DEFAULT NULL,
    action_url               VARCHAR(1024)            DEFAULT NULL,
    action_text              VARCHAR(128)             DEFAULT NULL,
    icon                     VARCHAR(255)             DEFAULT NULL,
    extra                    JSONB                    DEFAULT NULL,
    source_module            VARCHAR(64)              DEFAULT NULL,
    read_status              SMALLINT                 NOT NULL DEFAULT 0,
    read_time                TIMESTAMP                DEFAULT NULL,
    recall_status            VARCHAR(32)              NOT NULL DEFAULT 'NONE',
    recall_at                TIMESTAMP                DEFAULT NULL,
    expired_at               TIMESTAMP                DEFAULT NULL,
    mention_user_ids         JSONB                    DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_notification PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_notification IS '站内通知表';
COMMENT ON COLUMN ydsz_msg_notification.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_notification.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_notification.title IS '通知标题';
COMMENT ON COLUMN ydsz_msg_notification.content IS '通知内容';
COMMENT ON COLUMN ydsz_msg_notification.level IS '通知级别: INFO 提示 / WARN 警告 / ERROR 错误 / URGENT 紧急';
COMMENT ON COLUMN ydsz_msg_notification.category IS '通知分类: SYSTEM 系统 / WORKFLOW 流程 / ALERT 告警 / TO_DO 待办 / ANNOUNCE 公告';
COMMENT ON COLUMN ydsz_msg_notification.priority IS '发送优先级: LOW / NORMAL / HIGH / URGENT';
COMMENT ON COLUMN ydsz_msg_notification.sender_id IS '发送人用户 ID';
COMMENT ON COLUMN ydsz_msg_notification.receiver_id IS '接收人用户 ID';
COMMENT ON COLUMN ydsz_msg_notification.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_notification.biz_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_msg_notification.message_group IS '消息分组（同组消息合并展示）';
COMMENT ON COLUMN ydsz_msg_notification.batch_id IS '批次 ID（关联 ydsz_msg_batch.batch_id）';
COMMENT ON COLUMN ydsz_msg_notification.action_url IS '跳转链接';
COMMENT ON COLUMN ydsz_msg_notification.action_text IS '跳转文案';
COMMENT ON COLUMN ydsz_msg_notification.icon IS '图标';
COMMENT ON COLUMN ydsz_msg_notification.extra IS '扩展信息（JSON）';
COMMENT ON COLUMN ydsz_msg_notification.source_module IS '来源模块';
COMMENT ON COLUMN ydsz_msg_notification.read_status IS '已读状态: 0 未读 / 1 已读';
COMMENT ON COLUMN ydsz_msg_notification.read_time IS '已读时间';
COMMENT ON COLUMN ydsz_msg_notification.recall_status IS '撤回状态: NONE 未撤回 / RECALLED 已撤回';
COMMENT ON COLUMN ydsz_msg_notification.recall_at IS '撤回时间';
COMMENT ON COLUMN ydsz_msg_notification.expired_at IS '过期时间';
COMMENT ON COLUMN ydsz_msg_notification.mention_user_ids IS '提及用户 ID 列表（JSON 数组）';
COMMENT ON COLUMN ydsz_msg_notification.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_notification.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_notification.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_notification.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_notification.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_notification_receiver_read ON ydsz_msg_notification (receiver_id, read_status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_notification_biz ON ydsz_msg_notification (biz_type, biz_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_notification_batch_id ON ydsz_msg_notification (batch_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_notification_message_group ON ydsz_msg_notification (message_group);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_notification_tenant_deleted ON ydsz_msg_notification (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_user_channel (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    user_id                  VARCHAR(32)              NOT NULL,
    channel_type             VARCHAR(32)              NOT NULL,
    channel_user_id          VARCHAR(128)             NOT NULL,
    verified                 SMALLINT                 NOT NULL DEFAULT 0,
    is_primary               SMALLINT                 NOT NULL DEFAULT 0,
    extra                    JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_user_channel PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_user_channel_user_channel UNIQUE (user_id, channel_type, channel_user_id)
);

COMMENT ON TABLE ydsz_msg_user_channel IS '用户通道绑定表';
COMMENT ON COLUMN ydsz_msg_user_channel.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_user_channel.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_user_channel.user_id IS '用户 ID（关联 ydsz_employee.id）';
COMMENT ON COLUMN ydsz_msg_user_channel.channel_type IS '通道类型: SMS/EMAIL/PUSH/DINGTALK/WECOM/FEISHU 等';
COMMENT ON COLUMN ydsz_msg_user_channel.channel_user_id IS '通道用户标识（手机号/邮箱/IM userId/企微userId/个推cid）';
COMMENT ON COLUMN ydsz_msg_user_channel.verified IS '是否已验证: 0 未验证 / 1 已验证';
COMMENT ON COLUMN ydsz_msg_user_channel.is_primary IS '是否主绑定: 0 否 / 1 是（同通道多绑定时优先使用主绑定）';
COMMENT ON COLUMN ydsz_msg_user_channel.extra IS '扩展字段（JSON，如 deviceToken / openId 等）';
COMMENT ON COLUMN ydsz_msg_user_channel.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_user_channel.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_user_channel.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_user_channel.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_user_channel.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_user_channel.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_user_channel.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_user_channel_channel_user_id ON ydsz_msg_user_channel (channel_user_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_user_channel_tenant_deleted ON ydsz_msg_user_channel (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_subscription (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    user_id                  VARCHAR(32)              NOT NULL,
    topic_code               VARCHAR(64)              NOT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'SUBSCRIBED',
    role_scope               VARCHAR(128)             DEFAULT NULL,
    extra                    JSONB                    DEFAULT NULL,
    unsubscribed_at          TIMESTAMP                DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_subscription PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_subscription_subscription UNIQUE (user_id, topic_code, channel)
);

COMMENT ON TABLE ydsz_msg_subscription IS '订阅关系表';
COMMENT ON COLUMN ydsz_msg_subscription.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_subscription.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_subscription.user_id IS '用户 ID';
COMMENT ON COLUMN ydsz_msg_subscription.topic_code IS '主题编码（如 RISK_ALERT / CONTRACT_APPROVAL / APPROVAL_TODO）';
COMMENT ON COLUMN ydsz_msg_subscription.channel IS '通道';
COMMENT ON COLUMN ydsz_msg_subscription.status IS '订阅状态: SUBSCRIBED 已订阅 / UNSUBSCRIBED 已退订';
COMMENT ON COLUMN ydsz_msg_subscription.role_scope IS '角色范围（如 PM|MEMBER，限定角色内可见性）';
COMMENT ON COLUMN ydsz_msg_subscription.extra IS '扩展字段（JSON）';
COMMENT ON COLUMN ydsz_msg_subscription.unsubscribed_at IS '退订时间（仅 status=UNSUBSCRIBED 时有意义）';
COMMENT ON COLUMN ydsz_msg_subscription.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_subscription.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_subscription.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_subscription.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_subscription.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_subscription.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_subscription_topic_code ON ydsz_msg_subscription (topic_code);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_subscription_tenant_deleted ON ydsz_msg_subscription (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_preference (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    user_id                  VARCHAR(32)              NOT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    biz_type                 VARCHAR(64)              NOT NULL DEFAULT '__DEFAULT__',
    enabled                  SMALLINT                 NOT NULL DEFAULT 1,
    dnd_enabled              SMALLINT                 NOT NULL DEFAULT 0,
    dnd_start                VARCHAR(8)               DEFAULT NULL,
    dnd_end                  VARCHAR(8)               DEFAULT NULL,
    daily_limit              INTEGER                  DEFAULT NULL,
    hourly_limit             INTEGER                  DEFAULT NULL,
    digest_enabled           SMALLINT                 NOT NULL DEFAULT 0,
    digest_frequency         VARCHAR(32)              DEFAULT NULL,
    locale                   VARCHAR(16)              DEFAULT NULL,
    extra                    JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_preference PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_preference_preference UNIQUE (user_id, channel, biz_type)
);

COMMENT ON TABLE ydsz_msg_preference IS '用户消息偏好表';
COMMENT ON COLUMN ydsz_msg_preference.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_preference.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_preference.user_id IS '用户 ID（关联 ydsz_employee.id）';
COMMENT ON COLUMN ydsz_msg_preference.channel IS '通道: SMS/EMAIL/PUSH/INAPP/WEBHOOK/DINGTALK/WECOM/FEISHU';
COMMENT ON COLUMN ydsz_msg_preference.biz_type IS '业务类型（__DEFAULT__ 表示该通道全局默认偏好）';
COMMENT ON COLUMN ydsz_msg_preference.enabled IS '是否启用该通道: 0 关闭 / 1 开启（关闭后不发送）';
COMMENT ON COLUMN ydsz_msg_preference.dnd_enabled IS '免打扰开关: 0 关闭 / 1 开启';
COMMENT ON COLUMN ydsz_msg_preference.dnd_start IS '免打扰开始时间 HH:mm（如 22:00）';
COMMENT ON COLUMN ydsz_msg_preference.dnd_end IS '免打扰结束时间 HH:mm（如 08:00）';
COMMENT ON COLUMN ydsz_msg_preference.daily_limit IS '每日发送上限（超过则暂存或丢弃）';
COMMENT ON COLUMN ydsz_msg_preference.hourly_limit IS '每小时发送上限';
COMMENT ON COLUMN ydsz_msg_preference.digest_enabled IS '聚合开关: 0 即时发送 / 1 聚合摘要';
COMMENT ON COLUMN ydsz_msg_preference.digest_frequency IS '聚合频率: HOURLY / DAILY / WEEKLY';
COMMENT ON COLUMN ydsz_msg_preference.locale IS '偏好语言（如 zh-CN / en-US，影响模板 i18n 选择）';
COMMENT ON COLUMN ydsz_msg_preference.extra IS '扩展字段（JSON）';
COMMENT ON COLUMN ydsz_msg_preference.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_preference.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_preference.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_preference.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_preference.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_preference.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_preference.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_preference_tenant_deleted ON ydsz_msg_preference (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_route_rule (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    rule_code                VARCHAR(64)              NOT NULL,
    rule_name                VARCHAR(128)             NOT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    channel                  VARCHAR(32)              DEFAULT NULL,
    priority                 INTEGER                  DEFAULT NULL,
    condition_expr           VARCHAR(512)             DEFAULT NULL,
    target_channel           VARCHAR(32)              NOT NULL,
    fallback_channel         VARCHAR(32)              DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    sort_order               INTEGER                  DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_route_rule PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_route_rule_rule_code UNIQUE (rule_code, tenant_id)
);

COMMENT ON TABLE ydsz_msg_route_rule IS '消息路由规则表';
COMMENT ON COLUMN ydsz_msg_route_rule.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_route_rule.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_route_rule.rule_code IS '规则编码（唯一）';
COMMENT ON COLUMN ydsz_msg_route_rule.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_msg_route_rule.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_route_rule.channel IS '通道';
COMMENT ON COLUMN ydsz_msg_route_rule.priority IS '优先级（数值越小越优先）';
COMMENT ON COLUMN ydsz_msg_route_rule.condition_expr IS '路由条件（SpEL 表达式）';
COMMENT ON COLUMN ydsz_msg_route_rule.target_channel IS '命中后目标通道';
COMMENT ON COLUMN ydsz_msg_route_rule.fallback_channel IS '目标通道发送失败时降级通道';
COMMENT ON COLUMN ydsz_msg_route_rule.description IS '描述说明';
COMMENT ON COLUMN ydsz_msg_route_rule.sort_order IS '排序序号';
COMMENT ON COLUMN ydsz_msg_route_rule.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_route_rule.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_route_rule.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_route_rule.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_route_rule.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_route_rule.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_route_rule.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_route_rule_biz_channel ON ydsz_msg_route_rule (biz_type, channel);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_route_rule_tenant_deleted ON ydsz_msg_route_rule (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_variable_source (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    template_code            VARCHAR(64)              NOT NULL,
    variable_name            VARCHAR(64)              NOT NULL,
    source_type              VARCHAR(32)              NOT NULL,
    source_expr              VARCHAR(512)             NOT NULL,
    cache_ttl                INTEGER                  DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_variable_source PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_variable_source_variable UNIQUE (template_code, variable_name)
);

COMMENT ON TABLE ydsz_msg_variable_source IS '消息变量数据源绑定表';
COMMENT ON COLUMN ydsz_msg_variable_source.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_variable_source.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_variable_source.template_code IS '模板编码';
COMMENT ON COLUMN ydsz_msg_variable_source.variable_name IS '变量名（与模板 ${var} 对应）';
COMMENT ON COLUMN ydsz_msg_variable_source.source_type IS '数据源类型: BEAN / SQL / HTTP / STATIC';
COMMENT ON COLUMN ydsz_msg_variable_source.source_expr IS '数据源表达式';
COMMENT ON COLUMN ydsz_msg_variable_source.cache_ttl IS '缓存有效期（秒），0=不缓存';
COMMENT ON COLUMN ydsz_msg_variable_source.description IS '描述说明';
COMMENT ON COLUMN ydsz_msg_variable_source.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_variable_source.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_variable_source.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_variable_source.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_variable_source.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_variable_source.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_variable_source.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_variable_source_tenant_deleted ON ydsz_msg_variable_source (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_canary (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    canary_key               VARCHAR(128)             NOT NULL,
    experiment_name          VARCHAR(128)             NOT NULL,
    template_code            VARCHAR(64)              NOT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    bucket_total             INTEGER                  NOT NULL DEFAULT 100,
    bucket_selected          INTEGER                  NOT NULL DEFAULT 0,
    percentage               INTEGER                  NOT NULL DEFAULT 0,
    experiment_group         VARCHAR(32)              DEFAULT NULL,
    metrics_goal             VARCHAR(32)              DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'ACTIVE',
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_canary PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_canary_canary_key UNIQUE (canary_key)
);

COMMENT ON TABLE ydsz_msg_canary IS '灰度实验表';
COMMENT ON COLUMN ydsz_msg_canary.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_canary.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_canary.canary_key IS '灰度实验唯一键，格式 canary_{templateCode}_{timestamp}';
COMMENT ON COLUMN ydsz_msg_canary.experiment_name IS 'A/B 实验名称';
COMMENT ON COLUMN ydsz_msg_canary.template_code IS '关联模板编码';
COMMENT ON COLUMN ydsz_msg_canary.channel IS '通道: SMS/EMAIL/PUSH/INAPP/WEBHOOK/DINGTALK/WECOM/FEISHU';
COMMENT ON COLUMN ydsz_msg_canary.bucket_total IS '总分桶数（默认 100）';
COMMENT ON COLUMN ydsz_msg_canary.bucket_selected IS '命中桶号上限（桶号 < bucketSelected 归入 VARIANT 组）';
COMMENT ON COLUMN ydsz_msg_canary.percentage IS '当前放量百分比（0~100）';
COMMENT ON COLUMN ydsz_msg_canary.experiment_group IS '实验组: CONTROL 对照组 / VARIANT 实验组';
COMMENT ON COLUMN ydsz_msg_canary.metrics_goal IS '目标指标: DELIVERY_RATE 送达率 / READ_RATE 阅读率 / CLICK_RATE 点击率';
COMMENT ON COLUMN ydsz_msg_canary.status IS '实验状态: ACTIVE 运行中 / PAUSED 已暂停 / COMPLETED 已结束';
COMMENT ON COLUMN ydsz_msg_canary.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_canary.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_canary.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_canary.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_canary.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_canary.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_canary_template_code ON ydsz_msg_canary (template_code);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_canary_tenant_deleted ON ydsz_msg_canary (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_tenant_config (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL,
    tenant_name              VARCHAR(128)             DEFAULT NULL,
    daily_limit              BIGINT                   DEFAULT NULL,
    hourly_limit             BIGINT                   DEFAULT NULL,
    channel_overrides        JSONB                    DEFAULT NULL,
    provider_overrides       JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'ENABLED',
    CONSTRAINT pk_ydsz_msg_tenant_config PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_tenant_config_tenant_id UNIQUE (tenant_id)
);

COMMENT ON TABLE ydsz_msg_tenant_config IS '多租户消息配置表';
COMMENT ON COLUMN ydsz_msg_tenant_config.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_tenant_config.tenant_id IS '租户 ID';
COMMENT ON COLUMN ydsz_msg_tenant_config.tenant_name IS '租户名称';
COMMENT ON COLUMN ydsz_msg_tenant_config.daily_limit IS '租户级每日发送上限（null 表示使用全局默认值）';
COMMENT ON COLUMN ydsz_msg_tenant_config.hourly_limit IS '租户级每小时发送上限（null 表示使用全局默认值）';
COMMENT ON COLUMN ydsz_msg_tenant_config.channel_overrides IS '租户级通道开关（JSON Map，如 {"SMS": true, "EMAIL": false}）';
COMMENT ON COLUMN ydsz_msg_tenant_config.provider_overrides IS '租户级通道映射（JSON Map，如 {"SMS": "aliyun", "EMAIL": "sendgrid"}）';
COMMENT ON COLUMN ydsz_msg_tenant_config.status IS '配置状态: ENABLED / DISABLED';


CREATE TABLE IF NOT EXISTS ydsz_msg_batch (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    batch_id                 VARCHAR(64)              NOT NULL,
    batch_name               VARCHAR(128)             DEFAULT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    template_code            VARCHAR(64)              DEFAULT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    total                    INTEGER                  NOT NULL DEFAULT 0,
    success                  INTEGER                  NOT NULL DEFAULT 0,
    failed                   INTEGER                  NOT NULL DEFAULT 0,
    skipped                  INTEGER                  NOT NULL DEFAULT 0,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    audience_source          VARCHAR(128)             DEFAULT NULL,
    error_message            VARCHAR(512)             DEFAULT NULL,
    started_at               TIMESTAMP                DEFAULT NULL,
    completed_at             TIMESTAMP                DEFAULT NULL,
    sender_id                VARCHAR(32)              DEFAULT NULL,
    payload                  JSONB                    DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_batch PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_msg_batch_batch_id UNIQUE (batch_id)
);

COMMENT ON TABLE ydsz_msg_batch IS '消息发送批次表';
COMMENT ON COLUMN ydsz_msg_batch.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_batch.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_batch.batch_id IS '批次 ID（业务侧生成，全局唯一）';
COMMENT ON COLUMN ydsz_msg_batch.batch_name IS '批次名称';
COMMENT ON COLUMN ydsz_msg_batch.channel IS '发送通道';
COMMENT ON COLUMN ydsz_msg_batch.template_code IS '模板编码';
COMMENT ON COLUMN ydsz_msg_batch.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_batch.total IS '总数';
COMMENT ON COLUMN ydsz_msg_batch.success IS '成功数';
COMMENT ON COLUMN ydsz_msg_batch.failed IS '失败数';
COMMENT ON COLUMN ydsz_msg_batch.skipped IS '跳过数（限流/拦截）';
COMMENT ON COLUMN ydsz_msg_batch.status IS '批次状态: PENDING 待处理 / PROCESSING 处理中 / COMPLETED 已完成 / FAILED 失败';
COMMENT ON COLUMN ydsz_msg_batch.audience_source IS '人群包来源（CSV 文件名 / 标签 ID）';
COMMENT ON COLUMN ydsz_msg_batch.error_message IS '错误信息';
COMMENT ON COLUMN ydsz_msg_batch.started_at IS '开始处理时间';
COMMENT ON COLUMN ydsz_msg_batch.completed_at IS '完成时间';
COMMENT ON COLUMN ydsz_msg_batch.sender_id IS '触发发送的用户 ID';
COMMENT ON COLUMN ydsz_msg_batch.payload IS '消息请求列表 JSON（断点续传恢复用）';
COMMENT ON COLUMN ydsz_msg_batch.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_batch.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_batch.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_batch.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_batch.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_batch.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_batch_status ON ydsz_msg_batch (status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_batch_sender_id ON ydsz_msg_batch (sender_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_batch_tenant_deleted ON ydsz_msg_batch (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_aggregate (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    aggregate_group          VARCHAR(64)              NOT NULL,
    receiver                 VARCHAR(128)             NOT NULL,
    channel                  VARCHAR(32)              NOT NULL,
    batch_status             VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    message_count            INTEGER                  NOT NULL DEFAULT 0,
    first_message_at         TIMESTAMP                DEFAULT NULL,
    last_message_at          TIMESTAMP                DEFAULT NULL,
    scheduled_send_at        TIMESTAMP                DEFAULT NULL,
    sent_at                  TIMESTAMP                DEFAULT NULL,
    digest_content           TEXT                    ,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_aggregate PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_aggregate IS '聚合批次表';
COMMENT ON COLUMN ydsz_msg_aggregate.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_aggregate.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_aggregate.aggregate_group IS '聚合组';
COMMENT ON COLUMN ydsz_msg_aggregate.receiver IS '接收人';
COMMENT ON COLUMN ydsz_msg_aggregate.channel IS '通道';
COMMENT ON COLUMN ydsz_msg_aggregate.batch_status IS '批次状态: PENDING 攒批中 / READY 就绪待发 / SENT 已发送 / CANCELLED 已取消';
COMMENT ON COLUMN ydsz_msg_aggregate.message_count IS '消息数量';
COMMENT ON COLUMN ydsz_msg_aggregate.first_message_at IS '首条消息时间';
COMMENT ON COLUMN ydsz_msg_aggregate.last_message_at IS '末条消息时间';
COMMENT ON COLUMN ydsz_msg_aggregate.scheduled_send_at IS '计划发送时间（到达后触发摘要发送）';
COMMENT ON COLUMN ydsz_msg_aggregate.sent_at IS '实际发送时间';
COMMENT ON COLUMN ydsz_msg_aggregate.digest_content IS '聚合后摘要内容（渲染后）';
COMMENT ON COLUMN ydsz_msg_aggregate.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_aggregate.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_aggregate.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_aggregate.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_aggregate.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_aggregate.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_aggregate.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_aggregate_group_receiver ON ydsz_msg_aggregate (aggregate_group, receiver);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_aggregate_batch_status ON ydsz_msg_aggregate (batch_status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_aggregate_scheduled_send_at ON ydsz_msg_aggregate (scheduled_send_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_aggregate_tenant_deleted ON ydsz_msg_aggregate (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_offline (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    user_id                  VARCHAR(32)              NOT NULL,
    msg_type                 VARCHAR(32)              DEFAULT NULL,
    payload                  JSONB                    NOT NULL,
    msg_timestamp            BIGINT                   DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    pushed_at                TIMESTAMP                DEFAULT NULL,
    expired_at               TIMESTAMP                DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_offline PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_offline IS '离线消息持久化表';
COMMENT ON COLUMN ydsz_msg_offline.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_offline.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_offline.user_id IS '接收人用户 ID';
COMMENT ON COLUMN ydsz_msg_offline.msg_type IS '消息类型标签（如 NOTIFICATION / ALERT）';
COMMENT ON COLUMN ydsz_msg_offline.payload IS '消息内容（JSON）';
COMMENT ON COLUMN ydsz_msg_offline.msg_timestamp IS '消息时间戳（毫秒）';
COMMENT ON COLUMN ydsz_msg_offline.status IS '推送状态: PENDING 待推送 / PUSHED 已推送 / EXPIRED 已过期';
COMMENT ON COLUMN ydsz_msg_offline.pushed_at IS '推送时间';
COMMENT ON COLUMN ydsz_msg_offline.expired_at IS '过期时间（默认 createdAt + 30 天）';
COMMENT ON COLUMN ydsz_msg_offline.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_offline.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_offline.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_offline.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_offline.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_offline.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_offline_user_status ON ydsz_msg_offline (user_id, status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_offline_expired_at ON ydsz_msg_offline (expired_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_offline_tenant_deleted ON ydsz_msg_offline (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_log (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    channel                  VARCHAR(32)              NOT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    biz_id                   VARCHAR(64)              DEFAULT NULL,
    receiver                 VARCHAR(128)             DEFAULT NULL,
    template_code            VARCHAR(64)              DEFAULT NULL,
    template_params          JSONB                    DEFAULT NULL,
    content                  TEXT                    ,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    error_message            TEXT                    ,
    priority                 VARCHAR(32)              NOT NULL DEFAULT 'NORMAL',
    sender_id                VARCHAR(32)              DEFAULT NULL,
    message_group            VARCHAR(64)              DEFAULT NULL,
    batch_id                 VARCHAR(64)              DEFAULT NULL,
    route_rule_id            VARCHAR(32)              DEFAULT NULL,
    canary                   SMALLINT                 DEFAULT 0,
    canary_key               VARCHAR(128)             DEFAULT NULL,
    dedup_key                VARCHAR(128)             DEFAULT NULL,
    recall_status            VARCHAR(32)              NOT NULL DEFAULT 'NONE',
    recall_at                TIMESTAMP                DEFAULT NULL,
    receipt_status           VARCHAR(32)              NOT NULL DEFAULT 'NONE',
    receipt_at               TIMESTAMP                DEFAULT NULL,
    retry_count              INTEGER                  NOT NULL DEFAULT 0,
    next_retry_at            TIMESTAMP                DEFAULT NULL,
    provider_trace_id        VARCHAR(128)             DEFAULT NULL,
    cost_ms                  BIGINT                   DEFAULT NULL,
    cost                     NUMERIC(20,6)            DEFAULT NULL,
    trace_id                 VARCHAR(64)              DEFAULT NULL,
    msg_id                   VARCHAR(64)              DEFAULT NULL,
    topic                    VARCHAR(128)             DEFAULT NULL,
    reconsume_times          INTEGER                  DEFAULT NULL,
    parent_msg_id            VARCHAR(64)              DEFAULT NULL,
    scheduled_at             TIMESTAMP                DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_log PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_log IS '消息发送日志表';
COMMENT ON COLUMN ydsz_msg_log.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_log.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_log.channel IS '发送通道（SMS/EMAIL/PUSH/INAPP/WEBHOOK/HMAC/HMAC_WORK/WECOM/WECOM_APP/POST/WX_MINI/ALIPAY_MINI）';
COMMENT ON COLUMN ydsz_msg_log.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_log.biz_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_msg_log.receiver IS '接收人（手机号/邮箱/通道用户标识等）';
COMMENT ON COLUMN ydsz_msg_log.template_code IS '模板编码';
COMMENT ON COLUMN ydsz_msg_log.template_params IS '模板参数（JSON）';
COMMENT ON COLUMN ydsz_msg_log.content IS '消息内容';
COMMENT ON COLUMN ydsz_msg_log.status IS '发送状态: PENDING 待发送 / SENDING 发送中 / SUCCESS 成功 / FAILED 失败 / RETRY 重试中 / DEAD 死信 / RECALLED 已撤回 / SCHEDULED 定时 / SKIPPED 跳过';
COMMENT ON COLUMN ydsz_msg_log.error_message IS '失败错误信息';
COMMENT ON COLUMN ydsz_msg_log.priority IS '发送优先级: LOW / NORMAL / HIGH / URGENT';
COMMENT ON COLUMN ydsz_msg_log.sender_id IS '发送人用户 ID';
COMMENT ON COLUMN ydsz_msg_log.message_group IS '消息分组';
COMMENT ON COLUMN ydsz_msg_log.batch_id IS '批次 ID（关联 ydsz_msg_batch.batch_id）';
COMMENT ON COLUMN ydsz_msg_log.route_rule_id IS '命中的路由规则 ID（关联 ydsz_msg_route_rule.id）';
COMMENT ON COLUMN ydsz_msg_log.canary IS '是否命中灰度: 0 否 / 1 是';
COMMENT ON COLUMN ydsz_msg_log.canary_key IS '灰度实验标识（关联 ydsz_msg_canary.canary_key）';
COMMENT ON COLUMN ydsz_msg_log.dedup_key IS '幂等去重键';
COMMENT ON COLUMN ydsz_msg_log.recall_status IS '撤回状态: NONE 未撤回 / RECALLED 已撤回';
COMMENT ON COLUMN ydsz_msg_log.recall_at IS '撤回时间';
COMMENT ON COLUMN ydsz_msg_log.receipt_status IS '回执状态: NONE 无回执 / DELIVERED 已送达 / READ 已读 / CLICKED 已点击 / FAILED 投递失败 / TIMEOUT 回执超时';
COMMENT ON COLUMN ydsz_msg_log.receipt_at IS '回执时间';
COMMENT ON COLUMN ydsz_msg_log.retry_count IS '重试次数';
COMMENT ON COLUMN ydsz_msg_log.next_retry_at IS '下次重试时间';
COMMENT ON COLUMN ydsz_msg_log.provider_trace_id IS '服务商追踪/回执 ID';
COMMENT ON COLUMN ydsz_msg_log.cost_ms IS '发送耗时（毫秒）';
COMMENT ON COLUMN ydsz_msg_log.cost IS '发送费用';
COMMENT ON COLUMN ydsz_msg_log.trace_id IS '链路追踪 ID（跨服务链路串联）';
COMMENT ON COLUMN ydsz_msg_log.msg_id IS '消息 ID（全局唯一，串联轨迹/反馈链路）';
COMMENT ON COLUMN ydsz_msg_log.topic IS '订阅主题编码';
COMMENT ON COLUMN ydsz_msg_log.reconsume_times IS 'MQ 重新消费次数';
COMMENT ON COLUMN ydsz_msg_log.parent_msg_id IS '父消息 ID（级联消息溯源）';
COMMENT ON COLUMN ydsz_msg_log.scheduled_at IS '定时发送时间';
COMMENT ON COLUMN ydsz_msg_log.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_log.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_log.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_log.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_log.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_status_created ON ydsz_msg_log (status, created_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_receiver ON ydsz_msg_log (receiver);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_biz ON ydsz_msg_log (biz_type, biz_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_template_code ON ydsz_msg_log (template_code);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_msg_id ON ydsz_msg_log (msg_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_trace_id ON ydsz_msg_log (trace_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_batch_id ON ydsz_msg_log (batch_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_dedup_key ON ydsz_msg_log (dedup_key);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_provider_trace_id ON ydsz_msg_log (provider_trace_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_scheduled_at ON ydsz_msg_log (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_log_tenant_deleted ON ydsz_msg_log (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_receipt (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    log_id                   VARCHAR(32)              NOT NULL,
    provider_trace_id        VARCHAR(128)             DEFAULT NULL,
    receipt_type             VARCHAR(32)              NOT NULL,
    receipt_time             TIMESTAMP                NOT NULL,
    provider_code            VARCHAR(64)              DEFAULT NULL,
    provider_msg             VARCHAR(512)             DEFAULT NULL,
    raw_response             JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_receipt PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_receipt IS '消息回执表';
COMMENT ON COLUMN ydsz_msg_receipt.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_receipt.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_receipt.log_id IS '关联 ydsz_msg_log.id';
COMMENT ON COLUMN ydsz_msg_receipt.provider_trace_id IS '三方服务商回执 ID';
COMMENT ON COLUMN ydsz_msg_receipt.receipt_type IS '回执类型: DELIVERED 送达 / READ 已读 / CLICKED 点击 / FAILED 失败';
COMMENT ON COLUMN ydsz_msg_receipt.receipt_time IS '回执时间';
COMMENT ON COLUMN ydsz_msg_receipt.provider_code IS '供应商编码';
COMMENT ON COLUMN ydsz_msg_receipt.provider_msg IS '供应商消息';
COMMENT ON COLUMN ydsz_msg_receipt.raw_response IS '原始响应（JSON）';
COMMENT ON COLUMN ydsz_msg_receipt.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_receipt.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_receipt.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_receipt.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_receipt.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_receipt.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_receipt.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_receipt_log_id ON ydsz_msg_receipt (log_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_receipt_receipt_time ON ydsz_msg_receipt (receipt_time);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_receipt_provider_trace_id ON ydsz_msg_receipt (provider_trace_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_receipt_tenant_deleted ON ydsz_msg_receipt (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_trace (
    id                       VARCHAR(32)             ,
    msg_id                   VARCHAR(64)              NOT NULL,
    trace_id                 VARCHAR(64)              DEFAULT NULL,
    node                     VARCHAR(64)              NOT NULL,
    status                   VARCHAR(32)              NOT NULL,
    channel                  VARCHAR(32)              DEFAULT NULL,
    receiver                 VARCHAR(128)             DEFAULT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    biz_id                   VARCHAR(64)              DEFAULT NULL,
    template_code            VARCHAR(64)              DEFAULT NULL,
    cost_ms                  BIGINT                   DEFAULT NULL,
    message                  VARCHAR(512)             DEFAULT NULL,
    extra                    JSONB                    DEFAULT NULL,
    event_at                 TIMESTAMP                NOT NULL,
    CONSTRAINT pk_ydsz_msg_trace PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_trace IS '消息轨迹表';
COMMENT ON COLUMN ydsz_msg_trace.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_trace.msg_id IS '消息 ID（关联 ydsz_msg_log.msg_id）';
COMMENT ON COLUMN ydsz_msg_trace.trace_id IS '链路追踪 ID（关联 ydsz_msg_log.trace_id，用于跨服务链路串联）';
COMMENT ON COLUMN ydsz_msg_trace.node IS '轨迹节点类型（RECEIVED/CHANNEL_CHECK/ROUTE_MATCHED/CANARY_HIT/SUBSCRIPTION_CHECK/PREFERENCE_CHECK/DEDUP_CHECK/RATE_LIMIT_CHECK/TEMPLATE_LOADED/TEMPLATE_RENDERED/SENSITIVE_FILTERED/PERSISTED/SCHEDULED/AGGREGATED/DISPATCH_START/DISPATCH_SUCCESS/FALLBACK/RETRY/SEND_FAILED/RECEIPT_RECEIVED/RECALLED/CASCADE_SENT）';
COMMENT ON COLUMN ydsz_msg_trace.status IS '节点状态: SUCCESS / FAILED / SKIPPED / PENDING';
COMMENT ON COLUMN ydsz_msg_trace.channel IS '通道（节点关联的通道，部分节点如 RECEIVED 无通道则为 NULL）';
COMMENT ON COLUMN ydsz_msg_trace.receiver IS '接收人（脱敏后的）';
COMMENT ON COLUMN ydsz_msg_trace.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_trace.biz_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_msg_trace.template_code IS '模板编码';
COMMENT ON COLUMN ydsz_msg_trace.cost_ms IS '节点耗时（毫秒）';
COMMENT ON COLUMN ydsz_msg_trace.message IS '节点描述 / 错误信息';
COMMENT ON COLUMN ydsz_msg_trace.extra IS '扩展信息（JSON，如路由规则 ID、降级链、灰度配置等）';
COMMENT ON COLUMN ydsz_msg_trace.event_at IS '节点发生时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_trace_msg_event ON ydsz_msg_trace (msg_id, event_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_trace_trace_id ON ydsz_msg_trace (trace_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_trace_node_status ON ydsz_msg_trace (node, status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_trace_event_at ON ydsz_msg_trace (event_at);

CREATE TABLE IF NOT EXISTS ydsz_msg_feedback (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    msg_id                   VARCHAR(64)              NOT NULL,
    notification_id          VARCHAR(32)              DEFAULT NULL,
    user_id                  VARCHAR(32)              NOT NULL,
    channel                  VARCHAR(32)              DEFAULT NULL,
    biz_type                 VARCHAR(64)              DEFAULT NULL,
    rating                   INTEGER                  NOT NULL,
    feedback_type            VARCHAR(32)              DEFAULT NULL,
    content                  VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_msg_feedback PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_feedback IS '消息用户反馈表';
COMMENT ON COLUMN ydsz_msg_feedback.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_feedback.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_feedback.msg_id IS '消息 ID（关联 ydsz_msg_log.msg_id）';
COMMENT ON COLUMN ydsz_msg_feedback.notification_id IS '站内通知 ID（关联 ydsz_msg_notification.id，可为 NULL）';
COMMENT ON COLUMN ydsz_msg_feedback.user_id IS '用户 ID';
COMMENT ON COLUMN ydsz_msg_feedback.channel IS '通道';
COMMENT ON COLUMN ydsz_msg_feedback.biz_type IS '业务类型';
COMMENT ON COLUMN ydsz_msg_feedback.rating IS '评分: 1-5 分（1=非常不满意, 5=非常满意）';
COMMENT ON COLUMN ydsz_msg_feedback.feedback_type IS '反馈类型: TOO_FREQUENT 太频繁 / IRRELEVANT 不相关 / TOO_LONG 内容太长 / SPAM 垃圾信息 / GOOD 有用 / OTHER 其他';
COMMENT ON COLUMN ydsz_msg_feedback.content IS '反馈内容（用户自由文本输入）';
COMMENT ON COLUMN ydsz_msg_feedback.status IS '状态标识';
COMMENT ON COLUMN ydsz_msg_feedback.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_msg_feedback.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_msg_feedback.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_msg_feedback.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_msg_feedback.created_by IS '创建人';
COMMENT ON COLUMN ydsz_msg_feedback.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_feedback_msg_id ON ydsz_msg_feedback (msg_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_feedback_user_id ON ydsz_msg_feedback (user_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_feedback_tenant_deleted ON ydsz_msg_feedback (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_msg_outbox (
    id                       VARCHAR(32)             ,
    aggregate_type           VARCHAR(128)             NOT NULL,
    aggregate_id             VARCHAR(128)             NOT NULL,
    event_type               VARCHAR(128)             NOT NULL,
    payload                  JSONB                    NOT NULL,
    tenant_id                VARCHAR(32)              DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    publish_attempts         INTEGER                  NOT NULL DEFAULT 0,
    published_at             TIMESTAMP                DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_msg_outbox PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_msg_outbox IS 'Outbox 事件表（事务性 Outbox 模式）';
COMMENT ON COLUMN ydsz_msg_outbox.id IS '事件唯一 ID（Snowflake）';
COMMENT ON COLUMN ydsz_msg_outbox.aggregate_type IS '聚合根类型';
COMMENT ON COLUMN ydsz_msg_outbox.aggregate_id IS '聚合根 ID';
COMMENT ON COLUMN ydsz_msg_outbox.event_type IS '事件类型';
COMMENT ON COLUMN ydsz_msg_outbox.payload IS '事件负载（JSON）';
COMMENT ON COLUMN ydsz_msg_outbox.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_msg_outbox.status IS '发布状态: PENDING 待发布 / PROCESSING 发布中 / SENT 已发布 / DEAD_LETTER 死信';
COMMENT ON COLUMN ydsz_msg_outbox.publish_attempts IS '发布尝试次数';
COMMENT ON COLUMN ydsz_msg_outbox.published_at IS '发布时间';
COMMENT ON COLUMN ydsz_msg_outbox.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_msg_outbox_status_created ON ydsz_msg_outbox (status, created_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_outbox_tenant_status ON ydsz_msg_outbox (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_outbox_aggregate ON ydsz_msg_outbox (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_msg_outbox_status_published ON ydsz_msg_outbox (status, published_at);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (PostgreSQL)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_template_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_template_updated_at ON ydsz_msg_template;
CREATE TRIGGER trg_ydsz_msg_template_updated_at
BEFORE UPDATE ON ydsz_msg_template
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_template_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_template_version_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_template_version_updated_at ON ydsz_msg_template_version;
CREATE TRIGGER trg_ydsz_msg_template_version_updated_at
BEFORE UPDATE ON ydsz_msg_template_version
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_template_version_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_notification_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_notification_updated_at ON ydsz_msg_notification;
CREATE TRIGGER trg_ydsz_msg_notification_updated_at
BEFORE UPDATE ON ydsz_msg_notification
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_notification_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_user_channel_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_user_channel_updated_at ON ydsz_msg_user_channel;
CREATE TRIGGER trg_ydsz_msg_user_channel_updated_at
BEFORE UPDATE ON ydsz_msg_user_channel
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_user_channel_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_subscription_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_subscription_updated_at ON ydsz_msg_subscription;
CREATE TRIGGER trg_ydsz_msg_subscription_updated_at
BEFORE UPDATE ON ydsz_msg_subscription
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_subscription_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_preference_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_preference_updated_at ON ydsz_msg_preference;
CREATE TRIGGER trg_ydsz_msg_preference_updated_at
BEFORE UPDATE ON ydsz_msg_preference
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_preference_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_route_rule_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_route_rule_updated_at ON ydsz_msg_route_rule;
CREATE TRIGGER trg_ydsz_msg_route_rule_updated_at
BEFORE UPDATE ON ydsz_msg_route_rule
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_route_rule_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_variable_source_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_variable_source_updated_at ON ydsz_msg_variable_source;
CREATE TRIGGER trg_ydsz_msg_variable_source_updated_at
BEFORE UPDATE ON ydsz_msg_variable_source
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_variable_source_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_canary_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_canary_updated_at ON ydsz_msg_canary;
CREATE TRIGGER trg_ydsz_msg_canary_updated_at
BEFORE UPDATE ON ydsz_msg_canary
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_canary_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_batch_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_batch_updated_at ON ydsz_msg_batch;
CREATE TRIGGER trg_ydsz_msg_batch_updated_at
BEFORE UPDATE ON ydsz_msg_batch
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_batch_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_aggregate_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_aggregate_updated_at ON ydsz_msg_aggregate;
CREATE TRIGGER trg_ydsz_msg_aggregate_updated_at
BEFORE UPDATE ON ydsz_msg_aggregate
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_aggregate_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_offline_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_offline_updated_at ON ydsz_msg_offline;
CREATE TRIGGER trg_ydsz_msg_offline_updated_at
BEFORE UPDATE ON ydsz_msg_offline
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_offline_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_log_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_log_updated_at ON ydsz_msg_log;
CREATE TRIGGER trg_ydsz_msg_log_updated_at
BEFORE UPDATE ON ydsz_msg_log
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_log_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_receipt_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_receipt_updated_at ON ydsz_msg_receipt;
CREATE TRIGGER trg_ydsz_msg_receipt_updated_at
BEFORE UPDATE ON ydsz_msg_receipt
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_receipt_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_msg_feedback_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_msg_feedback_updated_at ON ydsz_msg_feedback;
CREATE TRIGGER trg_ydsz_msg_feedback_updated_at
BEFORE UPDATE ON ydsz_msg_feedback
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_msg_feedback_set_updated_at();
