-- ============================================================================
-- 模块名: ydsz-cronjob
-- 说  明: 基于 ydsz-cronjob-infra 实体类整理的完整建表脚本（PostgreSQL 8.0+）
-- 日  期: 2026-08-25
-- @author ydsz-team
-- ============================================================================
-- 规范：
--   - 主键 ID 应用层 Snowflake 生成（VARCHAR(32)），Outbox 表为自增 BIGINT
--   - 公共列按基类继承链累积：
--       MpBaseIdEntity     -> id
--       MpBaseAuditEntity  -> + created_by/created_at/updated_by/updated_at
--       MpSimpleEntity     -> + deleted/status/tenant_id
--       MpVersionedEntity / MpBaseEntity -> + revision（乐观锁）
--   - 禁止物理外键，逻辑外键加索引
--   - 字符集：utf8mb4
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 任务主表
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (PostgreSQL 11+)
--   - 类型映射: JSON→JSONB / TINYINT(1)→SMALLINT / INT→INTEGER / DATETIME→TIMESTAMP
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾统一生成)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   - 索引/约束名按 schema 级唯一性命名: idx_{table}_{core} / uk_{table}_{core}
--   - 原 MySQL 前缀索引 path(255) → 表达式索引 left(path,255)
--   - 原 MySQL FULLTEXT 索引 → GIN to_tsvector('simple', ...) 全文索引
--   - 执行方式: psql -U <user> -d <db> -f ydsz-cronjob.sql
-- ============================================================================


CREATE TABLE IF NOT EXISTS ydsz_job_main (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    job_name                 VARCHAR(128)             NOT NULL,
    job_group                VARCHAR(128)             DEFAULT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    handler                  VARCHAR(128)             NOT NULL,
    cron_expression          VARCHAR(64)              NOT NULL,
    schedule_type            VARCHAR(32)              DEFAULT NULL,
    fixed_rate_ms            BIGINT                   DEFAULT NULL,
    fixed_delay_ms           BIGINT                   DEFAULT NULL,
    params_json              JSONB                    DEFAULT NULL,
    job_remark               VARCHAR(512)             DEFAULT NULL,
    next_fire_time           TIMESTAMP                DEFAULT NULL,
    last_fire_time           TIMESTAMP                DEFAULT NULL,
    fire_count               BIGINT                   NOT NULL DEFAULT 0,
    success_count            BIGINT                   NOT NULL DEFAULT 0,
    fail_count               BIGINT                   NOT NULL DEFAULT 0,
    lock_ttl_ms              BIGINT                   DEFAULT NULL,
    timeout_ms               BIGINT                   DEFAULT NULL,
    sla_ms                   BIGINT                   DEFAULT NULL,
    slow_threshold_ms        BIGINT                   DEFAULT NULL,
    misfire_policy           VARCHAR(32)              DEFAULT NULL,
    shard_total              INTEGER                  DEFAULT NULL,
    job_type                 VARCHAR(32)              DEFAULT NULL,
    max_retries              INTEGER                  NOT NULL DEFAULT 0,
    retry_interval_ms        BIGINT                   DEFAULT NULL,
    retry_backoff            VARCHAR(32)              DEFAULT NULL,
    block_strategy           VARCHAR(32)              DEFAULT NULL,
    consecutive_fail_count   INTEGER                  NOT NULL DEFAULT 0,
    max_consecutive_fails    INTEGER                  DEFAULT NULL,
    auto_resume_after_minutes INTEGER                  DEFAULT NULL,
    priority                 INTEGER                  NOT NULL DEFAULT 0,
    version                  INTEGER                  NOT NULL DEFAULT 1,
    timezone                 VARCHAR(64)              DEFAULT NULL,
    cluster                  VARCHAR(64)              DEFAULT NULL,
    canary_ratio             INTEGER                  DEFAULT NULL,
    canary_handler           VARCHAR(128)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_job_key UNIQUE (job_key, tenant_id)
);

COMMENT ON TABLE ydsz_job_main IS '定时任务定义主表';
COMMENT ON COLUMN ydsz_job_main.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_main.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_main.job_name IS '任务名称';
COMMENT ON COLUMN ydsz_job_main.job_group IS '任务分组';
COMMENT ON COLUMN ydsz_job_main.job_key IS '任务 KEY（唯一）';
COMMENT ON COLUMN ydsz_job_main.handler IS '任务处理器 Bean 名称';
COMMENT ON COLUMN ydsz_job_main.cron_expression IS 'Cron 表达式';
COMMENT ON COLUMN ydsz_job_main.schedule_type IS '调度类型（CRON/FIXED_RATE/FIXED_DELAY）';
COMMENT ON COLUMN ydsz_job_main.fixed_rate_ms IS '固定频率执行间隔（毫秒）';
COMMENT ON COLUMN ydsz_job_main.fixed_delay_ms IS '固定延迟执行间隔（毫秒）';
COMMENT ON COLUMN ydsz_job_main.params_json IS '任务参数 JSON';
COMMENT ON COLUMN ydsz_job_main.job_remark IS '任务备注';
COMMENT ON COLUMN ydsz_job_main.next_fire_time IS '下次触发时间';
COMMENT ON COLUMN ydsz_job_main.last_fire_time IS '上次触发时间';
COMMENT ON COLUMN ydsz_job_main.fire_count IS '总触发次数';
COMMENT ON COLUMN ydsz_job_main.success_count IS '成功次数';
COMMENT ON COLUMN ydsz_job_main.fail_count IS '失败次数';
COMMENT ON COLUMN ydsz_job_main.lock_ttl_ms IS '分布式锁 TTL（毫秒）';
COMMENT ON COLUMN ydsz_job_main.timeout_ms IS '执行超时时间（毫秒）';
COMMENT ON COLUMN ydsz_job_main.sla_ms IS 'SLA 时长（毫秒）';
COMMENT ON COLUMN ydsz_job_main.slow_threshold_ms IS '慢任务阈值（毫秒）';
COMMENT ON COLUMN ydsz_job_main.misfire_policy IS 'Misfire 处理策略（如 FIRE_ONCE/SKIP）';
COMMENT ON COLUMN ydsz_job_main.shard_total IS '分片总数（非分片任务为 NULL）';
COMMENT ON COLUMN ydsz_job_main.job_type IS '任务类型（BEAN/GLUE 等）';
COMMENT ON COLUMN ydsz_job_main.max_retries IS '最大重试次数';
COMMENT ON COLUMN ydsz_job_main.retry_interval_ms IS '重试间隔（毫秒）';
COMMENT ON COLUMN ydsz_job_main.retry_backoff IS '重试退避策略（如 FIXED/EXPONENTIAL）';
COMMENT ON COLUMN ydsz_job_main.block_strategy IS '阻塞处理策略（如 SERIAL/DISCARD/COVER）';
COMMENT ON COLUMN ydsz_job_main.consecutive_fail_count IS '连续失败次数';
COMMENT ON COLUMN ydsz_job_main.max_consecutive_fails IS '最大连续失败次数（超过后自动禁用任务）';
COMMENT ON COLUMN ydsz_job_main.auto_resume_after_minutes IS '自动恢复时间（分钟）';
COMMENT ON COLUMN ydsz_job_main.priority IS '优先级';
COMMENT ON COLUMN ydsz_job_main.version IS '配置版本号';
COMMENT ON COLUMN ydsz_job_main.timezone IS '时区';
COMMENT ON COLUMN ydsz_job_main.cluster IS '执行集群';
COMMENT ON COLUMN ydsz_job_main.canary_ratio IS '金丝雀流量比例（百分比 0-100）';
COMMENT ON COLUMN ydsz_job_main.canary_handler IS '金丝雀处理器 Bean 名称';
COMMENT ON COLUMN ydsz_job_main.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_main.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_main.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_main.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_main.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_main.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_main.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_job_group ON ydsz_job_main (job_group);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_job_next_fire ON ydsz_job_main (next_fire_time);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_tenant_deleted ON ydsz_job_main (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_glue (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    job_id                   VARCHAR(32)              NOT NULL,
    source_code              TEXT                     NOT NULL,
    language                 VARCHAR(32)              NOT NULL DEFAULT 'GROOVY',
    version                  INTEGER                  NOT NULL DEFAULT 1,
    remark                   VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_glue PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_glue_glue_job_version UNIQUE (job_id, version)
);

COMMENT ON TABLE ydsz_job_glue IS 'GLUE 在线编码版本表';
COMMENT ON COLUMN ydsz_job_glue.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_glue.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_glue.job_id IS '任务 ID（关联 ydsz_job_main.id）';
COMMENT ON COLUMN ydsz_job_glue.source_code IS '源代码（Groovy/Python/Shell/JavaScript 脚本内容）';
COMMENT ON COLUMN ydsz_job_glue.language IS '语言: GROOVY(默认)/PYTHON/SHELL/JAVASCRIPT/JAVA';
COMMENT ON COLUMN ydsz_job_glue.version IS '版本号（从 1 递增）';
COMMENT ON COLUMN ydsz_job_glue.remark IS '版本备注';
COMMENT ON COLUMN ydsz_job_glue.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_glue.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_glue.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_glue.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_glue.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_glue.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_glue.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_glue_tenant_deleted ON ydsz_job_glue (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_task (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    job_id                   VARCHAR(32)              NOT NULL,
    log_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    task_name                VARCHAR(128)             NOT NULL,
    task_params              JSONB                    DEFAULT NULL,
    task_type                VARCHAR(32)              NOT NULL,
    task_status              VARCHAR(32)              NOT NULL,
    result                   JSONB                    DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    exec_node_id             VARCHAR(64)              DEFAULT NULL,
    retry_count              INTEGER                  NOT NULL DEFAULT 0,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_task PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_task IS 'MapReduce 子任务记录表';
COMMENT ON COLUMN ydsz_job_task.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_task.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_task.job_id IS '任务 ID（关联 ydsz_job_main.id）';
COMMENT ON COLUMN ydsz_job_task.log_id IS '执行日志 ID（关联 ydsz_job_log.id）';
COMMENT ON COLUMN ydsz_job_task.job_key IS '任务 KEY（冗余，便于查询）';
COMMENT ON COLUMN ydsz_job_task.task_name IS '子任务名称（root task 为 "root"）';
COMMENT ON COLUMN ydsz_job_task.task_params IS '子任务参数 JSON';
COMMENT ON COLUMN ydsz_job_task.task_type IS '子任务类型: ROOT 根任务 / SUB_TASK 子任务';
COMMENT ON COLUMN ydsz_job_task.task_status IS '执行状态: PENDING 待执行 / RUNNING 执行中 / SUCCESS 成功 / FAILED 失败';
COMMENT ON COLUMN ydsz_job_task.result IS '执行结果 JSON（ProcessResult.result 序列化后的字符串）';
COMMENT ON COLUMN ydsz_job_task.error_message IS '错误信息（失败时填充）';
COMMENT ON COLUMN ydsz_job_task.exec_node_id IS '执行节点 ID（hostname:port）';
COMMENT ON COLUMN ydsz_job_task.retry_count IS '重试次数（默认 0，每次重试递增）';
COMMENT ON COLUMN ydsz_job_task.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_task.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_task.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_task.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_task.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_task.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_task.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_task_jt_job_id ON ydsz_job_task (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_task_jt_log_id ON ydsz_job_task (log_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_task_tenant_deleted ON ydsz_job_task (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_node (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    node_id                  VARCHAR(64)              NOT NULL,
    app_name                 VARCHAR(128)             DEFAULT NULL,
    host                     VARCHAR(128)             NOT NULL,
    port                     INTEGER                  NOT NULL,
    last_heartbeat           TIMESTAMP                NOT NULL,
    node_status              VARCHAR(32)              DEFAULT NULL,
    cpu_usage                NUMERIC(20,6)            DEFAULT NULL,
    mem_usage_pct            NUMERIC(20,6)            DEFAULT NULL,
    running_count            INTEGER                  NOT NULL DEFAULT 0,
    tags                     JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_node PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_node_node_id UNIQUE (node_id)
);

COMMENT ON TABLE ydsz_job_node IS '调度节点心跳表';
COMMENT ON COLUMN ydsz_job_node.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_node.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_node.node_id IS '节点 ID（hostname:port 或 hostname:pid）';
COMMENT ON COLUMN ydsz_job_node.app_name IS '应用名称';
COMMENT ON COLUMN ydsz_job_node.host IS '主机名';
COMMENT ON COLUMN ydsz_job_node.port IS '端口';
COMMENT ON COLUMN ydsz_job_node.last_heartbeat IS '最后心跳时间';
COMMENT ON COLUMN ydsz_job_node.node_status IS '节点状态: ONLINE 在线 / OFFLINE 离线 / DRAINING 排空退出中';
COMMENT ON COLUMN ydsz_job_node.cpu_usage IS 'CPU 使用率（百分比，0-100）';
COMMENT ON COLUMN ydsz_job_node.mem_usage_pct IS '内存使用率（百分比，0-100）';
COMMENT ON COLUMN ydsz_job_node.running_count IS '当前正在执行的任务数';
COMMENT ON COLUMN ydsz_job_node.tags IS '节点标签 JSON（用于任务亲和性选择）';
COMMENT ON COLUMN ydsz_job_node.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_node.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_node.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_node.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_node.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_node.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_node.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_node_last_heartbeat ON ydsz_job_node (last_heartbeat);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_node_tenant_deleted ON ydsz_job_node (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_history (
    id                       VARCHAR(32)             ,
    job_id                   VARCHAR(32)              NOT NULL,
    version                  INTEGER                  NOT NULL,
    snapshot                 JSONB                    DEFAULT NULL,
    change_type              VARCHAR(32)              NOT NULL,
    before_snapshot          JSONB                    DEFAULT NULL,
    change_remark            VARCHAR(512)             DEFAULT NULL,
    job_name                 VARCHAR(128)             DEFAULT NULL,
    job_key                  VARCHAR(64)              DEFAULT NULL,
    handler                  VARCHAR(128)             DEFAULT NULL,
    cron_expression          VARCHAR(64)              DEFAULT NULL,
    params_json              JSONB                    DEFAULT NULL,
    remark                   VARCHAR(512)             DEFAULT NULL,
    changed_by               VARCHAR(64)              DEFAULT NULL,
    changed_at               TIMESTAMP                DEFAULT NULL,
    history_deleted          SMALLINT                 NOT NULL DEFAULT 0,
    CONSTRAINT pk_ydsz_job_history PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_history_jh_job_version UNIQUE (job_id, version)
);

COMMENT ON TABLE ydsz_job_history IS '任务配置历史版本表';
COMMENT ON COLUMN ydsz_job_history.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_history.job_id IS '任务 ID（关联 ydsz_job_main.id）';
COMMENT ON COLUMN ydsz_job_history.version IS '版本号（对应更新前的 job.version）';
COMMENT ON COLUMN ydsz_job_history.snapshot IS '完整 Job JSON 快照（变更后状态; DELETE 时为 NULL）';
COMMENT ON COLUMN ydsz_job_history.change_type IS '变更类型: CREATE / UPDATE / DELETE';
COMMENT ON COLUMN ydsz_job_history.before_snapshot IS '变更前快照 JSON（CREATE 时为 NULL; UPDATE/DELETE 时记录变更前状态）';
COMMENT ON COLUMN ydsz_job_history.change_remark IS '变更说明（如"任务创建"、"任务更新"、"任务删除"）';
COMMENT ON COLUMN ydsz_job_history.job_name IS '任务名称（冗余，便于列表展示）';
COMMENT ON COLUMN ydsz_job_history.job_key IS '任务 KEY（冗余）';
COMMENT ON COLUMN ydsz_job_history.handler IS '处理器（冗余）';
COMMENT ON COLUMN ydsz_job_history.cron_expression IS 'Cron 表达式（冗余）';
COMMENT ON COLUMN ydsz_job_history.params_json IS '参数 JSON（冗余）';
COMMENT ON COLUMN ydsz_job_history.remark IS '备注（冗余）';
COMMENT ON COLUMN ydsz_job_history.changed_by IS '修改人 ID';
COMMENT ON COLUMN ydsz_job_history.changed_at IS '修改时间';
COMMENT ON COLUMN ydsz_job_history.history_deleted IS '逻辑删除标记: 0 未删除 / 1 已删除';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_history_jh_job_id ON ydsz_job_history (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_history_jh_changed_at ON ydsz_job_history (changed_at);

CREATE TABLE IF NOT EXISTS ydsz_job_artifact (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    job_id                   VARCHAR(32)              NOT NULL,
    log_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    artifact_name            VARCHAR(128)             NOT NULL,
    artifact_type            VARCHAR(32)              NOT NULL,
    storage_path             VARCHAR(1024)            NOT NULL,
    size_bytes               BIGINT                   DEFAULT NULL,
    content_type             VARCHAR(128)             DEFAULT NULL,
    metadata                 JSONB                    DEFAULT NULL,
    expire_at                TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_artifact PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_artifact IS '执行产物记录表';
COMMENT ON COLUMN ydsz_job_artifact.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_artifact.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_artifact.job_id IS '任务 ID';
COMMENT ON COLUMN ydsz_job_artifact.log_id IS '执行日志 ID';
COMMENT ON COLUMN ydsz_job_artifact.job_key IS '任务 KEY（冗余）';
COMMENT ON COLUMN ydsz_job_artifact.artifact_name IS '产物名称';
COMMENT ON COLUMN ydsz_job_artifact.artifact_type IS '产物类型: FILE / REPORT / DATA / LOG';
COMMENT ON COLUMN ydsz_job_artifact.storage_path IS '存储路径（文件系统路径或对象存储 URL）';
COMMENT ON COLUMN ydsz_job_artifact.size_bytes IS '产物大小（字节）';
COMMENT ON COLUMN ydsz_job_artifact.content_type IS '内容类型（MIME type）';
COMMENT ON COLUMN ydsz_job_artifact.metadata IS '产物元数据 JSON';
COMMENT ON COLUMN ydsz_job_artifact.expire_at IS '过期时间（null=不过期）';
COMMENT ON COLUMN ydsz_job_artifact.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_artifact.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_artifact.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_artifact.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_artifact.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_artifact.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_artifact.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_artifact_ja_job_id ON ydsz_job_artifact (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_artifact_ja_log_id ON ydsz_job_artifact (log_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_artifact_ja_expire_at ON ydsz_job_artifact (expire_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_artifact_tenant_deleted ON ydsz_job_artifact (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_webhook (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    name                     VARCHAR(128)             NOT NULL,
    event_type               VARCHAR(64)              NOT NULL,
    job_key                  VARCHAR(64)              DEFAULT NULL,
    job_group                VARCHAR(128)             DEFAULT NULL,
    callback_url             VARCHAR(1024)            NOT NULL,
    http_method              VARCHAR(32)              DEFAULT NULL,
    headers                  JSONB                    DEFAULT NULL,
    secret                   VARCHAR(256)             DEFAULT NULL,
    webhook_status           VARCHAR(32)              DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_webhook PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_webhook IS 'WebHook 事件订阅表';
COMMENT ON COLUMN ydsz_job_webhook.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_webhook.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_webhook.name IS 'WebHook 名称';
COMMENT ON COLUMN ydsz_job_webhook.event_type IS '订阅的事件类型: TASK_STARTED / TASK_SUCCESS / TASK_FAILED / TASK_TIMEOUT / DAG_COMPLETED';
COMMENT ON COLUMN ydsz_job_webhook.job_key IS '订阅的任务 KEY（null=所有任务）';
COMMENT ON COLUMN ydsz_job_webhook.job_group IS '订阅的任务组（null=所有分组）';
COMMENT ON COLUMN ydsz_job_webhook.callback_url IS 'WebHook 回调 URL';
COMMENT ON COLUMN ydsz_job_webhook.http_method IS '请求方法: POST / PUT';
COMMENT ON COLUMN ydsz_job_webhook.headers IS '请求头 JSON';
COMMENT ON COLUMN ydsz_job_webhook.secret IS '密钥（用于签名验证）';
COMMENT ON COLUMN ydsz_job_webhook.webhook_status IS '状态: ACTIVE / INACTIVE';
COMMENT ON COLUMN ydsz_job_webhook.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_webhook.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_webhook.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_webhook.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_webhook.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_webhook.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_webhook.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_webhook_event_type ON ydsz_job_webhook (event_type);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_webhook_jw_job_key ON ydsz_job_webhook (job_key);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_webhook_tenant_deleted ON ydsz_job_webhook (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_alert_rule (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    rule_name                VARCHAR(128)             NOT NULL,
    job_id                   VARCHAR(32)              DEFAULT NULL,
    job_key                  VARCHAR(64)              DEFAULT NULL,
    alert_type               VARCHAR(32)              NOT NULL,
    alert_level              VARCHAR(32)              NOT NULL,
    threshold                BIGINT                   DEFAULT NULL,
    time_window_minutes      INTEGER                  DEFAULT NULL,
    channels                 JSONB                    DEFAULT NULL,
    receivers                JSONB                    DEFAULT NULL,
    cooldown_minutes         INTEGER                  DEFAULT NULL,
    enabled                  SMALLINT                 NOT NULL DEFAULT 1,
    source_type              VARCHAR(32)              DEFAULT NULL,
    last_alert_at            TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_alert_rule PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_alert_rule IS '任务告警规则表';
COMMENT ON COLUMN ydsz_job_alert_rule.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_alert_rule.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_alert_rule.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_job_alert_rule.job_id IS '关联任务 ID（NULL 表示全局规则）';
COMMENT ON COLUMN ydsz_job_alert_rule.job_key IS '任务 KEY 冗余（NULL 表示全局规则）';
COMMENT ON COLUMN ydsz_job_alert_rule.alert_type IS '告警类型: FAIL / TIMEOUT / SLOW / FAIL_RATE / DURATION_P95';
COMMENT ON COLUMN ydsz_job_alert_rule.alert_level IS '告警级别: INFO / WARN / ERROR / CRITICAL';
COMMENT ON COLUMN ydsz_job_alert_rule.threshold IS '阈值（按 alertType 解释: FAIL_RATE 百分比 0-100 / SLOW+DURATION_P95 毫秒）';
COMMENT ON COLUMN ydsz_job_alert_rule.time_window_minutes IS '统计时间窗口（分钟），仅 FAIL_RATE / DURATION_P95 生效';
COMMENT ON COLUMN ydsz_job_alert_rule.channels IS '通知通道（JSON 数组: ["EMAIL","DINGTALK","WECOM","WEBHOOK"]）';
COMMENT ON COLUMN ydsz_job_alert_rule.receivers IS '接收人（JSON 数组: 邮箱/手机号/userId 列表）';
COMMENT ON COLUMN ydsz_job_alert_rule.cooldown_minutes IS '冷却时间（分钟），同一规则在冷却期内不重复告警';
COMMENT ON COLUMN ydsz_job_alert_rule.enabled IS '是否启用: 0 禁用 / 1 启用';
COMMENT ON COLUMN ydsz_job_alert_rule.source_type IS '规则来源: MANUAL 手动创建(默认) / SLA 由SLA规则自动生成';
COMMENT ON COLUMN ydsz_job_alert_rule.last_alert_at IS '最后告警时间（用于冷却判断）';
COMMENT ON COLUMN ydsz_job_alert_rule.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_alert_rule.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_alert_rule.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_alert_rule.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_alert_rule.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_alert_rule.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_alert_rule.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_alert_rule_ar_job_id ON ydsz_job_alert_rule (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_alert_rule_ar_alert_type ON ydsz_job_alert_rule (alert_type);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_alert_rule_tenant_deleted ON ydsz_job_alert_rule (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_tenant_quota (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    max_jobs                 INTEGER                  DEFAULT NULL,
    max_concurrent           INTEGER                  DEFAULT NULL,
    max_daily_executions     INTEGER                  DEFAULT NULL,
    enabled                  SMALLINT                 NOT NULL DEFAULT 1,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_tenant_quota PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_tenant_quota_tq_tenant UNIQUE (tenant_id)
);

COMMENT ON TABLE ydsz_job_tenant_quota IS '租户级配额表';
COMMENT ON COLUMN ydsz_job_tenant_quota.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_tenant_quota.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_tenant_quota.max_jobs IS '任务数上限（NULL=unlimited；超过此值拒绝创建新任务）';
COMMENT ON COLUMN ydsz_job_tenant_quota.max_concurrent IS '并发执行上限（NULL=unlimited；超过此值拒绝派发）';
COMMENT ON COLUMN ydsz_job_tenant_quota.max_daily_executions IS '日执行量上限（NULL=unlimited；超过此值拒绝派发）';
COMMENT ON COLUMN ydsz_job_tenant_quota.enabled IS '是否启用配额检查: 0 禁用 / 1 启用';
COMMENT ON COLUMN ydsz_job_tenant_quota.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_tenant_quota.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_tenant_quota.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_tenant_quota.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_tenant_quota.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_tenant_quota.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_tenant_quota.updated_by IS '最后更新人';


CREATE TABLE IF NOT EXISTS ydsz_job_dag (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    dag_key                  VARCHAR(64)              NOT NULL,
    dag_name                 VARCHAR(128)             NOT NULL,
    dag_definition           JSONB                    NOT NULL,
    dag_status               VARCHAR(32)              DEFAULT NULL,
    trigger_type             VARCHAR(32)              DEFAULT NULL,
    cron_expression          VARCHAR(64)              DEFAULT NULL,
    max_concurrent_instances INTEGER                  NOT NULL DEFAULT 1,
    fail_strategy            VARCHAR(32)              DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    timeout_ms               BIGINT                   DEFAULT NULL,
    next_fire_time           TIMESTAMP                DEFAULT NULL,
    last_fire_time           TIMESTAMP                DEFAULT NULL,
    fire_count               BIGINT                   NOT NULL DEFAULT 0,
    success_count            BIGINT                   NOT NULL DEFAULT 0,
    fail_count               BIGINT                   NOT NULL DEFAULT 0,
    version                  INTEGER                  NOT NULL DEFAULT 1,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_dag PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_dag_dag_key UNIQUE (dag_key, tenant_id)
);

COMMENT ON TABLE ydsz_job_dag IS 'DAG 工作流定义表';
COMMENT ON COLUMN ydsz_job_dag.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_dag.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_dag.dag_key IS 'DAG 唯一 KEY（调度与触发使用）';
COMMENT ON COLUMN ydsz_job_dag.dag_name IS 'DAG 名称（展示用）';
COMMENT ON COLUMN ydsz_job_dag.dag_definition IS 'DAG 定义 JSON（nodes + edges + 可视化坐标）';
COMMENT ON COLUMN ydsz_job_dag.dag_status IS 'DAG 状态: DRAFT 草稿 / ENABLED 启用 / DISABLED 禁用';
COMMENT ON COLUMN ydsz_job_dag.trigger_type IS '触发类型: MANUAL 手动 / CRON 定时';
COMMENT ON COLUMN ydsz_job_dag.cron_expression IS 'Cron 表达式（triggerType=CRON 时必填）';
COMMENT ON COLUMN ydsz_job_dag.max_concurrent_instances IS '最大并发实例数(0=不限制, 默认1)';
COMMENT ON COLUMN ydsz_job_dag.fail_strategy IS 'DAG 级失败策略: FAIL_FAST 中止 / CONTINUE_ON_FAIL 继续';
COMMENT ON COLUMN ydsz_job_dag.description IS 'DAG 描述';
COMMENT ON COLUMN ydsz_job_dag.timeout_ms IS 'DAG 超时时间（毫秒，null=不限时）';
COMMENT ON COLUMN ydsz_job_dag.next_fire_time IS '下次触发时间（CRON 模式）';
COMMENT ON COLUMN ydsz_job_dag.last_fire_time IS '上次触发时间';
COMMENT ON COLUMN ydsz_job_dag.fire_count IS '总触发次数';
COMMENT ON COLUMN ydsz_job_dag.success_count IS '成功次数';
COMMENT ON COLUMN ydsz_job_dag.fail_count IS '失败次数';
COMMENT ON COLUMN ydsz_job_dag.version IS '版本号(乐观锁)';
COMMENT ON COLUMN ydsz_job_dag.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_dag.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_dag.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_dag.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_dag.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_dag.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_dag.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_dag_next_fire ON ydsz_job_dag (next_fire_time);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_tenant_deleted ON ydsz_job_dag (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_dag_version (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    dag_id                   VARCHAR(32)              NOT NULL,
    dag_key                  VARCHAR(64)              NOT NULL,
    version                  INTEGER                  NOT NULL,
    dag_definition           JSONB                    NOT NULL,
    dag_name                 VARCHAR(128)             DEFAULT NULL,
    trigger_type             VARCHAR(32)              DEFAULT NULL,
    cron_expression          VARCHAR(64)              DEFAULT NULL,
    fail_strategy            VARCHAR(32)              DEFAULT NULL,
    remark                   VARCHAR(512)             DEFAULT NULL,
    changed_by               VARCHAR(64)              DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_dag_version PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_dag_version_dv_dag_version UNIQUE (dag_id, version)
);

COMMENT ON TABLE ydsz_job_dag_version IS 'DAG 工作流版本历史表';
COMMENT ON COLUMN ydsz_job_dag_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_dag_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_dag_version.dag_id IS 'DAG ID（关联 ydsz_job_dag.id）';
COMMENT ON COLUMN ydsz_job_dag_version.dag_key IS 'DAG KEY（冗余字段，便于查询）';
COMMENT ON COLUMN ydsz_job_dag_version.version IS '版本号（从 1 递增）';
COMMENT ON COLUMN ydsz_job_dag_version.dag_definition IS 'DAG 定义 JSON 快照';
COMMENT ON COLUMN ydsz_job_dag_version.dag_name IS 'DAG 名称快照';
COMMENT ON COLUMN ydsz_job_dag_version.trigger_type IS '触发类型快照';
COMMENT ON COLUMN ydsz_job_dag_version.cron_expression IS 'Cron 表达式快照';
COMMENT ON COLUMN ydsz_job_dag_version.fail_strategy IS '失败策略快照';
COMMENT ON COLUMN ydsz_job_dag_version.remark IS '版本备注（如"新增节点A"、"修改条件分支"）';
COMMENT ON COLUMN ydsz_job_dag_version.changed_by IS '变更操作人';
COMMENT ON COLUMN ydsz_job_dag_version.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_dag_version.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_dag_version.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_dag_version.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_dag_version.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_dag_version.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_dag_version.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_version_dv_dag_key ON ydsz_job_dag_version (dag_key);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_version_tenant_deleted ON ydsz_job_dag_version (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_dag_instance (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    dag_id                   VARCHAR(32)              NOT NULL,
    dag_key                  VARCHAR(64)              NOT NULL,
    instance_status          VARCHAR(32)              NOT NULL,
    trigger_type             VARCHAR(32)              DEFAULT NULL,
    trigger_by               VARCHAR(64)              DEFAULT NULL,
    trigger_trace_id         VARCHAR(64)              DEFAULT NULL,
    context_json             JSONB                    DEFAULT NULL,
    started_at               TIMESTAMP                DEFAULT NULL,
    finished_at              TIMESTAMP                DEFAULT NULL,
    duration_ms              BIGINT                   DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    total_nodes              INTEGER                  DEFAULT NULL,
    success_nodes            INTEGER                  DEFAULT NULL,
    failed_nodes             INTEGER                  DEFAULT NULL,
    skipped_nodes            INTEGER                  DEFAULT NULL,
    next_fire_time           TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_dag_instance PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_dag_instance IS 'DAG 工作流实例表';
COMMENT ON COLUMN ydsz_job_dag_instance.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_dag_instance.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_dag_instance.dag_id IS 'DAG 定义 ID';
COMMENT ON COLUMN ydsz_job_dag_instance.dag_key IS 'DAG KEY（冗余，便于查询）';
COMMENT ON COLUMN ydsz_job_dag_instance.instance_status IS '实例状态: PENDING/RUNNING/SUCCESS/FAILED/PARTIAL_SUCCESS/PAUSED/CANCELED';
COMMENT ON COLUMN ydsz_job_dag_instance.trigger_type IS '触发类型: MANUAL/CRON/DEPENDENT';
COMMENT ON COLUMN ydsz_job_dag_instance.trigger_by IS '触发人（MANUAL 时为用户 ID）';
COMMENT ON COLUMN ydsz_job_dag_instance.trigger_trace_id IS '触发 traceId（用于链路追踪）';
COMMENT ON COLUMN ydsz_job_dag_instance.context_json IS 'DAG 实例级上下文 JSON（跨节点传参）';
COMMENT ON COLUMN ydsz_job_dag_instance.started_at IS '开始时间';
COMMENT ON COLUMN ydsz_job_dag_instance.finished_at IS '结束时间';
COMMENT ON COLUMN ydsz_job_dag_instance.duration_ms IS '执行耗时（毫秒）';
COMMENT ON COLUMN ydsz_job_dag_instance.error_message IS '错误信息（FAILED 时填充）';
COMMENT ON COLUMN ydsz_job_dag_instance.total_nodes IS '总节点数';
COMMENT ON COLUMN ydsz_job_dag_instance.success_nodes IS '成功节点数';
COMMENT ON COLUMN ydsz_job_dag_instance.failed_nodes IS '失败节点数';
COMMENT ON COLUMN ydsz_job_dag_instance.skipped_nodes IS '跳过节点数';
COMMENT ON COLUMN ydsz_job_dag_instance.next_fire_time IS '下次触发时间（用于 DAG 的 CRON 调度）';
COMMENT ON COLUMN ydsz_job_dag_instance.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_dag_instance.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_dag_instance.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_dag_instance.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_dag_instance.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_dag_instance.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_dag_instance.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_instance_di_dag_id ON ydsz_job_dag_instance (dag_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_instance_di_status ON ydsz_job_dag_instance (instance_status);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_instance_di_started_at ON ydsz_job_dag_instance (started_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_instance_tenant_deleted ON ydsz_job_dag_instance (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_dag_node_instance (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    dag_instance_id          VARCHAR(32)              NOT NULL,
    dag_id                   VARCHAR(32)              NOT NULL,
    job_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    node_status              VARCHAR(32)              DEFAULT NULL,
    log_id                   VARCHAR(32)              DEFAULT NULL,
    retry_count              INTEGER                  DEFAULT NULL,
    max_retries              INTEGER                  DEFAULT NULL,
    started_at               TIMESTAMP                DEFAULT NULL,
    finished_at              TIMESTAMP                DEFAULT NULL,
    duration_ms              BIGINT                   DEFAULT NULL,
    result_json              JSONB                    DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_dag_node_instance PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_dag_node_instance IS 'DAG 节点实例表';
COMMENT ON COLUMN ydsz_job_dag_node_instance.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.dag_instance_id IS 'DAG 实例 ID';
COMMENT ON COLUMN ydsz_job_dag_node_instance.dag_id IS 'DAG 定义 ID';
COMMENT ON COLUMN ydsz_job_dag_node_instance.job_id IS '任务 ID';
COMMENT ON COLUMN ydsz_job_dag_node_instance.job_key IS '任务 KEY（冗余）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.node_status IS '节点状态: PENDING/RUNNING/SUCCESS/FAILED/SKIPPED/RETRYING';
COMMENT ON COLUMN ydsz_job_dag_node_instance.log_id IS '关联的任务执行日志 ID（ydsz_job_log.id）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.retry_count IS '节点级重试次数';
COMMENT ON COLUMN ydsz_job_dag_node_instance.max_retries IS '节点级最大重试次数';
COMMENT ON COLUMN ydsz_job_dag_node_instance.started_at IS '节点开始时间';
COMMENT ON COLUMN ydsz_job_dag_node_instance.finished_at IS '节点结束时间';
COMMENT ON COLUMN ydsz_job_dag_node_instance.duration_ms IS '节点执行耗时（毫秒）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.result_json IS '节点执行结果 JSON';
COMMENT ON COLUMN ydsz_job_dag_node_instance.error_message IS '节点错误信息';
COMMENT ON COLUMN ydsz_job_dag_node_instance.status IS '状态标识';
COMMENT ON COLUMN ydsz_job_dag_node_instance.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_job_dag_node_instance.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_job_dag_node_instance.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_dag_node_instance.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_job_dag_node_instance.created_by IS '创建人';
COMMENT ON COLUMN ydsz_job_dag_node_instance.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_node_instance_dni_dag_instance_id ON ydsz_job_dag_node_instance (dag_instance_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_node_instance_dni_job_id ON ydsz_job_dag_node_instance (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_node_instance_dni_log_id ON ydsz_job_dag_node_instance (log_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_dag_node_instance_tenant_deleted ON ydsz_job_dag_node_instance (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_job_log (
    id                       VARCHAR(32)             ,
    job_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    start_time               TIMESTAMP                DEFAULT NULL,
    end_time                 TIMESTAMP                DEFAULT NULL,
    duration_ms              BIGINT                   DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    params_json              JSONB                    DEFAULT NULL,
    result_json              JSONB                    DEFAULT NULL,
    trace_id                 VARCHAR(64)              DEFAULT NULL,
    trigger_type             VARCHAR(32)              DEFAULT NULL,
    lock_holder              VARCHAR(64)              DEFAULT NULL,
    exec_node_id             VARCHAR(64)              DEFAULT NULL,
    exec_thread_id           BIGINT                   DEFAULT NULL,
    shard_index              INTEGER                  DEFAULT NULL,
    shard_total              INTEGER                  DEFAULT NULL,
    is_slow                  SMALLINT                 NOT NULL DEFAULT 0,
    slow_threshold_ms        BIGINT                   DEFAULT NULL,
    queue_time               TIMESTAMP                DEFAULT NULL,
    dispatch_time            TIMESTAMP                DEFAULT NULL,
    handler_init_time        TIMESTAMP                DEFAULT NULL,
    handler_end_time         TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_job_log PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_job_log IS '任务执行日志表';
COMMENT ON COLUMN ydsz_job_log.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_log.job_id IS '任务 ID';
COMMENT ON COLUMN ydsz_job_log.job_key IS '任务 KEY';
COMMENT ON COLUMN ydsz_job_log.start_time IS '开始时间';
COMMENT ON COLUMN ydsz_job_log.end_time IS '结束时间';
COMMENT ON COLUMN ydsz_job_log.duration_ms IS '耗时(毫秒)';
COMMENT ON COLUMN ydsz_job_log.error_message IS '错误信息';
COMMENT ON COLUMN ydsz_job_log.params_json IS '参数 JSON';
COMMENT ON COLUMN ydsz_job_log.result_json IS '结果 JSON';
COMMENT ON COLUMN ydsz_job_log.trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_job_log.trigger_type IS '触发类型: CRON 定时 / MANUAL 手动 / RETRY 重试 / MISFIRED Misfire 触发';
COMMENT ON COLUMN ydsz_job_log.lock_holder IS '持锁者标识（hostname:pid，用于超时后安全释放分布式锁）';
COMMENT ON COLUMN ydsz_job_log.exec_node_id IS '执行节点 ID（hostname:port，用于故障转移时定位任务所在节点）';
COMMENT ON COLUMN ydsz_job_log.exec_thread_id IS '执行线程 ID（用于超时强制中断时定位执行线程）';
COMMENT ON COLUMN ydsz_job_log.shard_index IS '分片索引（非分片任务为 NULL；分片任务为 0-based 索引）';
COMMENT ON COLUMN ydsz_job_log.shard_total IS '分片总数（非分片任务为 NULL）';
COMMENT ON COLUMN ydsz_job_log.is_slow IS '慢任务标记（0=非慢 / 1=慢）';
COMMENT ON COLUMN ydsz_job_log.slow_threshold_ms IS '慢任务阈值快照（毫秒，NULL=未配置慢任务检测）';
COMMENT ON COLUMN ydsz_job_log.queue_time IS '入队时间（任务被 JobScanner 扫描到并入队的时刻）';
COMMENT ON COLUMN ydsz_job_log.dispatch_time IS '派发时间（任务被 Dispatcher 从队列取出并派发的时刻）';
COMMENT ON COLUMN ydsz_job_log.handler_init_time IS 'Handler 初始化时间（JobHandler 实例化/资源准备完成的时刻）';
COMMENT ON COLUMN ydsz_job_log.handler_end_time IS 'Handler 执行结束时间（JobHandler.execute() 返回的时刻）';
COMMENT ON COLUMN ydsz_job_log.status IS '执行状态: RUNNING/SUCCESS/FAILED/TIMEOUT';
COMMENT ON COLUMN ydsz_job_log.deleted IS '逻辑删除标识：0=未删除，1=已删除';
COMMENT ON COLUMN ydsz_job_log.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_job_log.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_jl_job_id ON ydsz_job_log (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_jl_job_key ON ydsz_job_log (job_key);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_jl_status ON ydsz_job_log (status);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_jl_start_time ON ydsz_job_log (start_time);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_jl_trace_id ON ydsz_job_log (trace_id);

CREATE TABLE IF NOT EXISTS ydsz_job_log_content (
    id                       VARCHAR(32)             ,
    log_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    line_no                  INTEGER                  NOT NULL,
    log_level                VARCHAR(32)              DEFAULT NULL,
    content                  VARCHAR(4000)            NOT NULL,
    CONSTRAINT pk_ydsz_job_log_content PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_log_content_jlc_log_line UNIQUE (log_id, line_no)
);

COMMENT ON TABLE ydsz_job_log_content IS '任务执行日志内容表（行级明细）';
COMMENT ON COLUMN ydsz_job_log_content.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_log_content.log_id IS '任务执行日志 ID（关联 ydsz_job_log.id）';
COMMENT ON COLUMN ydsz_job_log_content.job_key IS '任务 KEY（冗余，避免连表查询）';
COMMENT ON COLUMN ydsz_job_log_content.line_no IS '行号（从 1 递增）';
COMMENT ON COLUMN ydsz_job_log_content.log_level IS '日志级别：DEBUG / INFO / WARN / ERROR';
COMMENT ON COLUMN ydsz_job_log_content.content IS '日志内容（单行文本，最长 4000 字符）';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_log_content_jlc_job_key ON ydsz_job_log_content (job_key);

CREATE TABLE IF NOT EXISTS ydsz_job_daily_stats (
    id                       VARCHAR(32)             ,
    job_id                   VARCHAR(32)              NOT NULL,
    job_key                  VARCHAR(64)              NOT NULL,
    stats_date               DATE                     NOT NULL,
    fire_count               BIGINT                   NOT NULL DEFAULT 0,
    success_count            BIGINT                   NOT NULL DEFAULT 0,
    fail_count               BIGINT                   NOT NULL DEFAULT 0,
    timeout_count            BIGINT                   NOT NULL DEFAULT 0,
    avg_duration_ms          BIGINT                   DEFAULT NULL,
    max_duration_ms          BIGINT                   DEFAULT NULL,
    min_duration_ms          BIGINT                   DEFAULT NULL,
    p95_duration_ms          BIGINT                   DEFAULT NULL,
    CONSTRAINT pk_ydsz_job_daily_stats PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_daily_stats_jds_job_date UNIQUE (job_id, stats_date)
);

COMMENT ON TABLE ydsz_job_daily_stats IS '任务执行每日统计表';
COMMENT ON COLUMN ydsz_job_daily_stats.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_daily_stats.job_id IS '任务 ID';
COMMENT ON COLUMN ydsz_job_daily_stats.job_key IS '任务 KEY（冗余）';
COMMENT ON COLUMN ydsz_job_daily_stats.stats_date IS '统计日期';
COMMENT ON COLUMN ydsz_job_daily_stats.fire_count IS '当日触发次数';
COMMENT ON COLUMN ydsz_job_daily_stats.success_count IS '当日成功次数';
COMMENT ON COLUMN ydsz_job_daily_stats.fail_count IS '当日失败次数';
COMMENT ON COLUMN ydsz_job_daily_stats.timeout_count IS '当日超时次数';
COMMENT ON COLUMN ydsz_job_daily_stats.avg_duration_ms IS '平均耗时（毫秒）';
COMMENT ON COLUMN ydsz_job_daily_stats.max_duration_ms IS '最大耗时（毫秒）';
COMMENT ON COLUMN ydsz_job_daily_stats.min_duration_ms IS '最小耗时（毫秒）';
COMMENT ON COLUMN ydsz_job_daily_stats.p95_duration_ms IS 'P95 耗时（毫秒）';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_daily_stats_jds_stats_date ON ydsz_job_daily_stats (stats_date);

CREATE TABLE IF NOT EXISTS ydsz_job_alert_dispatch (
    id                       VARCHAR(32)             ,
    alert_code               VARCHAR(64)              NOT NULL,
    source_type              VARCHAR(32)              NOT NULL,
    rule_id                  VARCHAR(32)              DEFAULT NULL,
    rule_name                VARCHAR(128)             DEFAULT NULL,
    job_id                   VARCHAR(32)              DEFAULT NULL,
    job_key                  VARCHAR(64)              DEFAULT NULL,
    alert_type               VARCHAR(32)              DEFAULT NULL,
    alert_level              VARCHAR(32)              DEFAULT NULL,
    trigger_value            VARCHAR(64)              DEFAULT NULL,
    threshold                BIGINT                   DEFAULT NULL,
    channels                 VARCHAR(256)             DEFAULT NULL,
    alert_status             VARCHAR(32)              DEFAULT NULL,
    error_message            TEXT                     DEFAULT NULL,
    trace_id                 VARCHAR(64)              DEFAULT NULL,
    trigger_log_id           VARCHAR(32)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_alert_dispatch PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_alert_dispatch_ad_alert_code UNIQUE (alert_code)
);

COMMENT ON TABLE ydsz_job_alert_dispatch IS '告警派发日志表（cronjob 告警记录，source_type=CRONJOB）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.alert_code IS '预警编码（cronjob 自动生成: CRONJOB-{timestamp}-{ruleId}）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.source_type IS '触发源类型（cronjob 告警固定为 CRONJOB）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.rule_id IS '规则 ID（映射到 rule_id）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.rule_name IS '规则名称（映射到 title）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.job_id IS '任务 ID（NULL 表示全局告警; 映射到 source_id）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.job_key IS '任务 KEY（冗余）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.alert_type IS '告警类型: FAIL / TIMEOUT / SLOW / FAIL_RATE / DURATION_P95';
COMMENT ON COLUMN ydsz_job_alert_dispatch.alert_level IS '告警级别: INFO / WARN / ERROR / CRITICAL';
COMMENT ON COLUMN ydsz_job_alert_dispatch.trigger_value IS '触发时的实际值（如失败率 85.5、耗时 5000）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.threshold IS '规则阈值（冗余）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.channels IS '实际发送通道（逗号分隔: INAPP,EMAIL,DINGTALK）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.alert_status IS '告警状态: PENDING / SUCCESS / PARTIAL / FAILED / *_RECOVERY';
COMMENT ON COLUMN ydsz_job_alert_dispatch.error_message IS '错误信息（部分通道失败时记录; 映射到 fail_reason）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.trace_id IS '链路追踪 ID（映射到 provider_trace_id）';
COMMENT ON COLUMN ydsz_job_alert_dispatch.trigger_log_id IS '触发该告警的任务日志 ID（关联 ydsz_job_log.id）';

CREATE INDEX IF NOT EXISTS idx_ydsz_alert_dispatch_ad_rule_id ON ydsz_job_alert_dispatch (rule_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_alert_dispatch_ad_job_id ON ydsz_job_alert_dispatch (job_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_alert_dispatch_ad_source_status ON ydsz_job_alert_dispatch (source_type, alert_status);

CREATE TABLE IF NOT EXISTS ydsz_job_outbox (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_key                VARCHAR(64)              NOT NULL,
    event_type               VARCHAR(128)             NOT NULL,
    topic                    VARCHAR(128)             NOT NULL,
    payload                  JSONB                    NOT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    retry_count              INTEGER                  NOT NULL DEFAULT 0,
    next_retry_time          TIMESTAMP(3)             DEFAULT NULL,
    create_time              TIMESTAMP(3)             NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time              TIMESTAMP(3)             NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT pk_ydsz_job_outbox PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_job_outbox_jo_event_key UNIQUE (event_key)
);

COMMENT ON TABLE ydsz_job_outbox IS 'Outbox 事务性事件表：存储待发布的领域事件，保障业务写操作与事件投递的事务一致性';
COMMENT ON COLUMN ydsz_job_outbox.id IS '事件 ID（自增）';
COMMENT ON COLUMN ydsz_job_outbox.event_key IS '事件 KEY（幂等去重标识）';
COMMENT ON COLUMN ydsz_job_outbox.event_type IS '事件类型';
COMMENT ON COLUMN ydsz_job_outbox.topic IS '目标 topic（webhook / metrics / audit）';
COMMENT ON COLUMN ydsz_job_outbox.payload IS '事件 payload（JSON 字符串）';
COMMENT ON COLUMN ydsz_job_outbox.status IS '事件状态: PENDING 待发布 / PUBLISHED 已发布 / DEAD 死亡信（重试耗尽）';
COMMENT ON COLUMN ydsz_job_outbox.retry_count IS '已重试次数';
COMMENT ON COLUMN ydsz_job_outbox.next_retry_time IS '下次重试时间';
COMMENT ON COLUMN ydsz_job_outbox.create_time IS '创建时间';
COMMENT ON COLUMN ydsz_job_outbox.update_time IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_job_outbox_jo_status_retry ON ydsz_job_outbox (status, next_retry_time);
CREATE INDEX IF NOT EXISTS idx_ydsz_job_outbox_jo_status_created ON ydsz_job_outbox (status, create_time);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (PostgreSQL)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_updated_at ON ydsz_job_main;
CREATE TRIGGER trg_ydsz_job_updated_at
BEFORE UPDATE ON ydsz_job_main
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_glue_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_glue_updated_at ON ydsz_job_glue;
CREATE TRIGGER trg_ydsz_job_glue_updated_at
BEFORE UPDATE ON ydsz_job_glue
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_glue_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_task_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_task_updated_at ON ydsz_job_task;
CREATE TRIGGER trg_ydsz_job_task_updated_at
BEFORE UPDATE ON ydsz_job_task
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_task_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_node_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_node_updated_at ON ydsz_job_node;
CREATE TRIGGER trg_ydsz_job_node_updated_at
BEFORE UPDATE ON ydsz_job_node
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_node_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_artifact_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_artifact_updated_at ON ydsz_job_artifact;
CREATE TRIGGER trg_ydsz_job_artifact_updated_at
BEFORE UPDATE ON ydsz_job_artifact
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_artifact_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_webhook_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_webhook_updated_at ON ydsz_job_webhook;
CREATE TRIGGER trg_ydsz_job_webhook_updated_at
BEFORE UPDATE ON ydsz_job_webhook
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_webhook_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_alert_rule_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_alert_rule_updated_at ON ydsz_job_alert_rule;
CREATE TRIGGER trg_ydsz_job_alert_rule_updated_at
BEFORE UPDATE ON ydsz_job_alert_rule
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_alert_rule_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_tenant_quota_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_tenant_quota_updated_at ON ydsz_job_tenant_quota;
CREATE TRIGGER trg_ydsz_tenant_quota_updated_at
BEFORE UPDATE ON ydsz_job_tenant_quota
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_tenant_quota_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_dag_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_dag_updated_at ON ydsz_job_dag;
CREATE TRIGGER trg_ydsz_job_dag_updated_at
BEFORE UPDATE ON ydsz_job_dag
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_dag_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_dag_version_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_dag_version_updated_at ON ydsz_job_dag_version;
CREATE TRIGGER trg_ydsz_job_dag_version_updated_at
BEFORE UPDATE ON ydsz_job_dag_version
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_dag_version_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_dag_instance_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_dag_instance_updated_at ON ydsz_job_dag_instance;
CREATE TRIGGER trg_ydsz_job_dag_instance_updated_at
BEFORE UPDATE ON ydsz_job_dag_instance
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_dag_instance_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_dag_node_instance_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_dag_node_instance_updated_at ON ydsz_job_dag_node_instance;
CREATE TRIGGER trg_ydsz_job_dag_node_instance_updated_at
BEFORE UPDATE ON ydsz_job_dag_node_instance
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_dag_node_instance_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_log_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_log_updated_at ON ydsz_job_log;
CREATE TRIGGER trg_ydsz_job_log_updated_at
BEFORE UPDATE ON ydsz_job_log
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_log_set_updated_at();

-- 自动更新 update_time（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_job_outbox_set_update_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_job_outbox_update_time ON ydsz_job_outbox;
CREATE TRIGGER trg_ydsz_job_outbox_update_time
BEFORE UPDATE ON ydsz_job_outbox
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_job_outbox_set_update_time();
