apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-gateway
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-system
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-userinfo
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-project
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-cronjob
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-workflow
spec:
  replicas: 2
