-- ----------------------------------------------------------------------------
-- 模块名   : ydsz-workflow（工作流模块）
-- 说明     : 基于 ydsz-workflow-infra 实体类整理的完整建表脚本
--            （流程分类/定义/模板、节点/跳转、实例、待办任务、定时器、
--              事件订阅、历史归档、评论/常用语、抄送/抄送规则、附件、
--              委派授权、管理员角色、自动触发、审计日志）
-- 日期     : 2026-08-25
-- @author  : ydsz-team
-- ----------------------------------------------------------------------------
-- 说明：
--   1. 表名统一前缀 ydsz_flow_。
--   2. 继承 MpBaseEntity<String> 的实体含全量公共列
--      （tenant_id / status / deleted / revision / created_by / created_at /
--       updated_by / updated_at）。
--   3. 历史归档/审计类实体（FlowHisTask / FlowHisInstance / FlowAuditLog）
--      同样继承 MpBaseEntity<String>，含全量公共列。
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 流程定义 / 模板（模板层）
-- ============================================================================

-- 流程分类表（按业务线分组的树形分类，流程定义引用）
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (Oracle 12.2+ / 19c)
--   - 类型映射: JSON→CLOB+CHECK(IS JSON) / TINYINT(1)→NUMBER(1) / INT→NUMBER(10)
--       / BIGINT→NUMBER(19) / DATETIME→TIMESTAMP / BOOLEAN→NUMBER(1)
--   - VARCHAR2 采用 CHAR 语义 VARCHAR2(n CHAR), 字符集建议 AL32UTF8
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾生成, 以 / 提交)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY (12c+)
--   - 索引/约束名按 schema 级唯一性命名 (Oracle 12.2+ 标识符 ≤128 字节)
--   - 原 MySQL 前缀索引 path(255) → SUBSTR(path,1,255) 函数索引
--   - 原 MySQL FULLTEXT 索引 → 普通复合索引 (全文检索建议由 ES/应用层承担)
--   - 执行方式: sqlplus / SQLcl 执行本脚本 (触发器以 / 提交)
-- ============================================================================


CREATE TABLE ydsz_flow_category (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    category_code            VARCHAR2(64 CHAR)        NOT NULL,
    category_name            VARCHAR2(128 CHAR)       NOT NULL,
    parent_id                VARCHAR2(32 CHAR)        DEFAULT NULL,
    sort_num                 NUMBER(10)               NOT NULL DEFAULT 0,
    icon                     VARCHAR2(128 CHAR)       DEFAULT NULL,
    remark                   VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_category PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_category_category_code UNIQUE (category_code, tenant_id)
);

COMMENT ON TABLE ydsz_flow_category IS '流程分类表（树形结构，流程定义分组归类）';
COMMENT ON COLUMN ydsz_flow_category.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_category.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_category.category_code IS '分类编码（唯一，业务语义，建议 snake_case）';
COMMENT ON COLUMN ydsz_flow_category.category_name IS '分类名称（前端展示）';
COMMENT ON COLUMN ydsz_flow_category.parent_id IS '父分类 ID（支持多级树形结构，顶级为 NULL）';
COMMENT ON COLUMN ydsz_flow_category.sort_num IS '排序号（越小越靠前）';
COMMENT ON COLUMN ydsz_flow_category.icon IS '图标（前端展示用，如 Element Plus icon 名称）';
COMMENT ON COLUMN ydsz_flow_category.remark IS '备注（说明分类的业务用途）';
COMMENT ON COLUMN ydsz_flow_category.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_category.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_category.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_category.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_category.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_category.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_category.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_category_parent_id ON ydsz_flow_category (parent_id);
CREATE INDEX idx_ydsz_flow_category_tenant_deleted ON ydsz_flow_category (tenant_id, deleted);

CREATE TABLE ydsz_flow_definition (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    flow_name                VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    flow_version             VARCHAR2(32 CHAR)        NOT NULL,
    model_value              VARCHAR2(32 CHAR)        DEFAULT NULL,
    form_custom              VARCHAR2(8 CHAR)         DEFAULT NULL,
    form_path                VARCHAR2(1024 CHAR)      DEFAULT NULL,
    activity_status          NUMBER(10)               NOT NULL DEFAULT 1,
    is_publish               NUMBER(10)               NOT NULL DEFAULT 0,
    listener_type            VARCHAR2(32 CHAR)        DEFAULT NULL,
    listener_path            VARCHAR2(128 CHAR)       DEFAULT NULL,
    ext                      CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_definition_ext CHECK (ext IS JSON),
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    canary_percent           NUMBER(10)               NOT NULL DEFAULT 0,
    canary_status            VARCHAR2(32 CHAR)        DEFAULT NULL,
    canary_strategy          VARCHAR2(32 CHAR)        DEFAULT NULL,
    canary_rollout_log       CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_definition_canary_rollout_log CHECK (canary_rollout_log IS JSON),
    locked_by                VARCHAR2(32 CHAR)        DEFAULT NULL,
    locked_at                TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_definition PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_definition_flow_code_version UNIQUE (flow_code, flow_version, tenant_id)
);

COMMENT ON TABLE ydsz_flow_definition IS '流程定义表（流程模板元数据）';
COMMENT ON COLUMN ydsz_flow_definition.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_definition.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_definition.flow_code IS '流程编码（业务语义，如 project_initiation / contract_change）';
COMMENT ON COLUMN ydsz_flow_definition.flow_name IS '流程名称（前端展示）';
COMMENT ON COLUMN ydsz_flow_definition.category IS '流程类别（用于分类筛选，如「项目类」「合同类」「人事类」）';
COMMENT ON COLUMN ydsz_flow_definition.flow_version IS '流程版本号（如 v1 / v2，同一 flowCode 下不同版本独立发布）';
COMMENT ON COLUMN ydsz_flow_definition.model_value IS '设计器模型（CLASSICS=经典横向流转图，MIMIC=纵向审批面板）';
COMMENT ON COLUMN ydsz_flow_definition.form_custom IS '审批表单是否自定义（Y=自定义表单，N=系统内置表单）';
COMMENT ON COLUMN ydsz_flow_definition.form_path IS '审批表单路径（formCustom=Y 时为 Vue 组件路径，否则为表单定义 ID）';
COMMENT ON COLUMN ydsz_flow_definition.activity_status IS '激活状态（0=挂起不可发起新实例，1=激活正常接收新实例）';
COMMENT ON COLUMN ydsz_flow_definition.is_publish IS '发布状态（0=未发布草稿，1=已发布可发起，9=失效已废弃）';
COMMENT ON COLUMN ydsz_flow_definition.listener_type IS '监听器类型（NONE=无，GLOBAL=全局，FLOW=流程级）';
COMMENT ON COLUMN ydsz_flow_definition.listener_path IS '监听器 Spring Bean 路径（如 projectFlowListener）';
COMMENT ON COLUMN ydsz_flow_definition.ext IS '扩展字段 JSON（业务侧自定义元数据：超时配置/抄送规则/审批人默认值等）';
COMMENT ON COLUMN ydsz_flow_definition.description IS '流程描述（说明流程的业务用途与适用场景）';
COMMENT ON COLUMN ydsz_flow_definition.provider_trace_id IS '链路追踪 ID（跨系统全链路追踪，与 ydsz_provider_trace_id 协议对齐）';
COMMENT ON COLUMN ydsz_flow_definition.canary_percent IS '灰度比例 0-100（0=全量稳定版，100=全量灰度版，1-99 按策略切流）';
COMMENT ON COLUMN ydsz_flow_definition.canary_status IS '灰度状态（NONE=未启用，CANARYING=灰度中，PROMOTED=已全量，ROLLED_BACK=已回滚）';
COMMENT ON COLUMN ydsz_flow_definition.canary_strategy IS '灰度切流策略（USER_HASH=按发起人取模，RANDOM=随机，WHITELIST=白名单）';
COMMENT ON COLUMN ydsz_flow_definition.canary_rollout_log IS '灰度发布历史 JSON 数组（[{operatorId,operatorName,fromPercent,toPercent,operateAt,note}]）';
COMMENT ON COLUMN ydsz_flow_definition.locked_by IS '当前持锁人 ID（设计器协同编辑锁定，NULL=未锁定）';
COMMENT ON COLUMN ydsz_flow_definition.locked_at IS '加锁时间（超过 30 分钟可强制抢占）';
COMMENT ON COLUMN ydsz_flow_definition.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_definition.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_definition.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_definition.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_definition.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_definition.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_definition.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_definition_category ON ydsz_flow_definition (category);
CREATE INDEX idx_ydsz_flow_definition_tenant_deleted ON ydsz_flow_definition (tenant_id, deleted);

CREATE TABLE ydsz_flow_template (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    template_code            VARCHAR2(64 CHAR)        NOT NULL,
    template_name            VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(32 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    icon                     VARCHAR2(128 CHAR)       DEFAULT NULL,
    bpmn_xml                 CLOB                    ,
    form_path                VARCHAR2(1024 CHAR)      DEFAULT NULL,
    use_count                NUMBER(10)               NOT NULL DEFAULT 0,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    parent_template_id       VARCHAR2(32 CHAR)        DEFAULT NULL,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    version_label            VARCHAR2(32 CHAR)        DEFAULT NULL,
    inherit_type             VARCHAR2(32 CHAR)        DEFAULT NULL,
    is_latest                NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_template_template_code_version UNIQUE (template_code, version, tenant_id)
);

COMMENT ON TABLE ydsz_flow_template IS '流程模板表（模板市场预置模板，BPMN 2.0 XML）';
COMMENT ON COLUMN ydsz_flow_template.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_template.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_template.template_code IS '模板编码（唯一标识，如 hr_leave_approval）';
COMMENT ON COLUMN ydsz_flow_template.template_name IS '模板名称（前端展示）';
COMMENT ON COLUMN ydsz_flow_template.category IS '分类（HR / FINANCE / ADMIN / PROJECT / GENERAL）';
COMMENT ON COLUMN ydsz_flow_template.description IS '模板描述（说明适用场景、必填字段、注意事项）';
COMMENT ON COLUMN ydsz_flow_template.icon IS '图标路径（前端展示用）';
COMMENT ON COLUMN ydsz_flow_template.bpmn_xml IS 'BPMN 2.0 XML 流程定义（<bpmn:definitions>...</bpmn:definitions>）';
COMMENT ON COLUMN ydsz_flow_template.form_path IS '默认表单路径（导入后默认关联的审批表单）';
COMMENT ON COLUMN ydsz_flow_template.use_count IS '使用次数（被导入到流程定义的累计计数，用于热门度排序）';
COMMENT ON COLUMN ydsz_flow_template.sort_order IS '排序权重（越大越靠前，模板市场首页展示用）';
COMMENT ON COLUMN ydsz_flow_template.parent_template_id IS '父模板 ID（跨模板继承关系，STANDALONE 时为 NULL）';
COMMENT ON COLUMN ydsz_flow_template.version IS '模板版本号（从 1 开始单调递增，同一 templateCode 下唯一）';
COMMENT ON COLUMN ydsz_flow_template.version_label IS '版本标签（如 1.0.0 / 1.0.0-rc1，可选可读标识）';
COMMENT ON COLUMN ydsz_flow_template.inherit_type IS '继承类型（STANDALONE=独立，CLONE=克隆，INHERIT=继承）';
COMMENT ON COLUMN ydsz_flow_template.is_latest IS '是否当前 templateCode 下最新版本（0=否，1=是）';
COMMENT ON COLUMN ydsz_flow_template.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_template.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_template.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_template.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_template.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_template.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_template_category ON ydsz_flow_template (category);
CREATE INDEX idx_ydsz_flow_template_parent_template_id ON ydsz_flow_template (parent_template_id);
CREATE INDEX idx_ydsz_flow_template_tenant_deleted ON ydsz_flow_template (tenant_id, deleted);

CREATE TABLE ydsz_flow_node (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_type                NUMBER(10)               NOT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_name                VARCHAR2(128 CHAR)       NOT NULL,
    permission_flag          VARCHAR2(512 CHAR)       DEFAULT NULL,
    skip_any_node            VARCHAR2(512 CHAR)       DEFAULT NULL,
    coordinate               CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_node_coordinate CHECK (coordinate IS JSON),
    skip_list                CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_node_skip_list CHECK (skip_list IS JSON),
    ext                      CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_node_ext CHECK (ext IS JSON),
    form_fields_config       CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_node_form_fields_config CHECK (form_fields_config IS JSON),
    sla_config               CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_node_sla_config CHECK (sla_config IS JSON),
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_node PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_node_definition_node_code UNIQUE (definition_id, node_code)
);

COMMENT ON TABLE ydsz_flow_node IS '流程节点表（流程定义结构最小单元）';
COMMENT ON COLUMN ydsz_flow_node.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_node.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_node.definition_id IS '所属流程定义 ID（关联 ydsz_flow_definition.id）';
COMMENT ON COLUMN ydsz_flow_node.flow_code IS '流程编码（冗余字段，避免 JOIN 流程定义）';
COMMENT ON COLUMN ydsz_flow_node.node_type IS '节点类型（0=开始，1=审批，2=网关，3=结束，4=子流程，5=抄送）';
COMMENT ON COLUMN ydsz_flow_node.node_code IS '节点编码（流程内唯一，用于 SpEL 引用与跳转）';
COMMENT ON COLUMN ydsz_flow_node.node_name IS '节点名称（设计器展示与审批页标题）';
COMMENT ON COLUMN ydsz_flow_node.permission_flag IS '办理人权限标识（role:/dept:/user:/post:/initiator/initiatorLeader/${spel}，逗号分隔）';
COMMENT ON COLUMN ydsz_flow_node.skip_any_node IS '任意跳转目标节点编码集合（逗号分隔，空=不允许任意跳转）';
COMMENT ON COLUMN ydsz_flow_node.coordinate IS '设计器坐标 JSON（{"x":100,"y":200,"width":120,"height":60}，bpmn-js 生成）';
COMMENT ON COLUMN ydsz_flow_node.skip_list IS '节点跳转路由集合 JSON（[{toNodeCode,condition,priority},...]，按优先级匹配）';
COMMENT ON COLUMN ydsz_flow_node.ext IS '扩展字段 JSON（priority/emptyStrategy/collection/votePassRate/userWeights/autoDedup/freeJump）';
COMMENT ON COLUMN ydsz_flow_node.form_fields_config IS '表单字段权限配置 JSON（{"fieldKey":"EDIT|READONLY|HIDDEN",...}）';
COMMENT ON COLUMN ydsz_flow_node.sla_config IS 'SLA 超时配置 JSON（{"timeoutMinutes":120,"action":"REMIND|ESCALATE|AUTO_PASS|AUTO_REJECT",...}）';
COMMENT ON COLUMN ydsz_flow_node.provider_trace_id IS '链路追踪 ID（关联 MDC traceId，用于跨服务追踪）';
COMMENT ON COLUMN ydsz_flow_node.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_node.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_node.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_node.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_node.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_node.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_node.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_node_flow_code ON ydsz_flow_node (flow_code);
CREATE INDEX idx_ydsz_flow_node_tenant_deleted ON ydsz_flow_node (tenant_id, deleted);

CREATE TABLE ydsz_flow_skip (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    skip_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    skip_type                VARCHAR2(32 CHAR)        NOT NULL,
    coordinate               CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_skip_coordinate CHECK (coordinate IS JSON),
    skip_condition           VARCHAR2(512 CHAR)       DEFAULT NULL,
    next_node_code           VARCHAR2(64 CHAR)        NOT NULL,
    source_node_code         VARCHAR2(64 CHAR)        DEFAULT NULL,
    next_node_type           NUMBER(10)               DEFAULT NULL,
    coordinate_next          CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_skip_coordinate_next CHECK (coordinate_next IS JSON),
    skip_list                CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_skip_skip_list CHECK (skip_list IS JSON),
    ext                      CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_skip_ext CHECK (ext IS JSON),
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_skip PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_skip IS '节点跳转关联表（流程图有向边）';
COMMENT ON COLUMN ydsz_flow_skip.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_skip.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_skip.definition_id IS '所属流程定义 ID';
COMMENT ON COLUMN ydsz_flow_skip.flow_code IS '流程编码（冗余字段）';
COMMENT ON COLUMN ydsz_flow_skip.skip_name IS '跳转名称（线上标签，如「同意」「金额 > 1万」）';
COMMENT ON COLUMN ydsz_flow_skip.skip_type IS '跳转类型（FlowSkipType 枚举名，如 PASS/REJECT）';
COMMENT ON COLUMN ydsz_flow_skip.coordinate IS '设计器坐标 JSON（当前节点端点）';
COMMENT ON COLUMN ydsz_flow_skip.skip_condition IS '跳转条件表达式（SpEL 或 ${var} 语法）';
COMMENT ON COLUMN ydsz_flow_skip.next_node_code IS '下一节点编码';
COMMENT ON COLUMN ydsz_flow_skip.source_node_code IS '源节点编码（独立列，便于 REJECT 回退场景索引与联查）';
COMMENT ON COLUMN ydsz_flow_skip.next_node_type IS '下一节点类型（FlowNodeType.code）';
COMMENT ON COLUMN ydsz_flow_skip.coordinate_next IS '下一节点坐标 JSON（设计器渲染终点）';
COMMENT ON COLUMN ydsz_flow_skip.skip_list IS '跳转路由集合 JSON';
COMMENT ON COLUMN ydsz_flow_skip.ext IS '扩展字段 JSON（存储 sourceRef / sequenceFlowId 等 BPMN 派生信息）';
COMMENT ON COLUMN ydsz_flow_skip.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_skip.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_skip.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_skip.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_skip.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_skip.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_skip.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_skip.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_skip_definition_id ON ydsz_flow_skip (definition_id);
CREATE INDEX idx_ydsz_flow_skip_flow_code ON ydsz_flow_skip (flow_code);
CREATE INDEX idx_ydsz_flow_skip_source_node_code ON ydsz_flow_skip (source_node_code);
CREATE INDEX idx_ydsz_flow_skip_tenant_deleted ON ydsz_flow_skip (tenant_id, deleted);

CREATE TABLE ydsz_flow_auto_trigger (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    source_flow_code         VARCHAR2(64 CHAR)        NOT NULL,
    target_flow_code         VARCHAR2(64 CHAR)        NOT NULL,
    condition_expression     VARCHAR2(512 CHAR)       DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    enabled                  NUMBER(10)               NOT NULL DEFAULT 1,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_auto_trigger PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_auto_trigger IS '流程自动触发规则表（流程触发流程的自动化配置）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.source_flow_code IS '源流程编码（触发方）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.target_flow_code IS '目标流程编码（被触发方）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.condition_expression IS '条件表达式（Aviator 语法，为空则无条件触发）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.description IS '规则描述（说明触发场景与业务背景）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.enabled IS '是否启用（0=禁用，1=启用）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.sort_order IS '排序权重（升序执行）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_auto_trigger.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_auto_trigger.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_auto_trigger.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_auto_trigger.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_auto_trigger.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_auto_trigger.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_auto_trigger_source_flow_code ON ydsz_flow_auto_trigger (source_flow_code);
CREATE INDEX idx_ydsz_flow_auto_trigger_target_flow_code ON ydsz_flow_auto_trigger (target_flow_code);
CREATE INDEX idx_ydsz_flow_auto_trigger_enabled ON ydsz_flow_auto_trigger (enabled);
CREATE INDEX idx_ydsz_flow_auto_trigger_tenant_deleted ON ydsz_flow_auto_trigger (tenant_id, deleted);

CREATE TABLE ydsz_flow_instance (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    flow_name                VARCHAR2(128 CHAR)       NOT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_version             VARCHAR2(32 CHAR)        NOT NULL,
    business_type            VARCHAR2(64 CHAR)        NOT NULL,
    business_id              VARCHAR2(64 CHAR)        NOT NULL,
    business_no              VARCHAR2(64 CHAR)        DEFAULT NULL,
    title                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    initiator_id             VARCHAR2(32 CHAR)        NOT NULL,
    initiator_name           VARCHAR2(64 CHAR)        DEFAULT NULL,
    current_node_code        VARCHAR2(64 CHAR)        DEFAULT NULL,
    current_node_name        VARCHAR2(128 CHAR)       DEFAULT NULL,
    variable                 CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_instance_variable CHECK (variable IS JSON),
    flow_status              VARCHAR2(32 CHAR)        NOT NULL,
    activity_status          NUMBER(10)               NOT NULL DEFAULT 1,
    start_at                 TIMESTAMP                DEFAULT NULL,
    end_at                   TIMESTAMP                DEFAULT NULL,
    duration_ms              NUMBER(19)               DEFAULT NULL,
    parent_instance_id       VARCHAR2(32 CHAR)        DEFAULT NULL,
    parent_node_code         VARCHAR2(64 CHAR)        DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    due_at                   TIMESTAMP                DEFAULT NULL,
    reject_reason            VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_instance PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_instance_business_type_id UNIQUE (business_type, business_id)
);

COMMENT ON TABLE ydsz_flow_instance IS '流程实例表（一次完整流程审批的运行时上下文）';
COMMENT ON COLUMN ydsz_flow_instance.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_instance.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_instance.flow_code IS '流程编码（业务侧使用，如 project_initiation）';
COMMENT ON COLUMN ydsz_flow_instance.flow_name IS '流程名称（冗余，避免 JOIN 流程定义）';
COMMENT ON COLUMN ydsz_flow_instance.definition_id IS '流程定义 ID（关联 ydsz_flow_definition.id）';
COMMENT ON COLUMN ydsz_flow_instance.flow_version IS '流程版本（关联 ydsz_flow_definition.flow_version）';
COMMENT ON COLUMN ydsz_flow_instance.business_type IS '业务类型（如 PROJECT / CONTRACT / LEAVE）';
COMMENT ON COLUMN ydsz_flow_instance.business_id IS '业务单据 ID（业务侧主键）';
COMMENT ON COLUMN ydsz_flow_instance.business_no IS '业务单据编号（业务侧编号，可读）';
COMMENT ON COLUMN ydsz_flow_instance.title IS '流程标题（展示用，默认为「{业务类型}-{业务编号}」）';
COMMENT ON COLUMN ydsz_flow_instance.initiator_id IS '发起人 ID（关联 ydsz_user_account.id）';
COMMENT ON COLUMN ydsz_flow_instance.initiator_name IS '发起人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_instance.current_node_code IS '当前节点编码（流程图高亮 + 进度提示）';
COMMENT ON COLUMN ydsz_flow_instance.current_node_name IS '当前节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_instance.variable IS '流程变量 JSON（动态参数）';
COMMENT ON COLUMN ydsz_flow_instance.flow_status IS '实例状态（FlowInstanceStatus 枚举名，如 RUNNING/APPROVED/REJECTED）';
COMMENT ON COLUMN ydsz_flow_instance.activity_status IS '激活状态（0=挂起，1=激活，与 flowStatus 解耦）';
COMMENT ON COLUMN ydsz_flow_instance.start_at IS '启动时间';
COMMENT ON COLUMN ydsz_flow_instance.end_at IS '结束时间（终态实例有值，活跃实例为 NULL）';
COMMENT ON COLUMN ydsz_flow_instance.duration_ms IS '流程耗时（毫秒，endAt - startAt，结束时由引擎填充）';
COMMENT ON COLUMN ydsz_flow_instance.parent_instance_id IS '父流程实例 ID（子流程场景，可空）';
COMMENT ON COLUMN ydsz_flow_instance.parent_node_code IS '父流程中触发子流程的节点编码（可空）';
COMMENT ON COLUMN ydsz_flow_instance.provider_trace_id IS '链路追踪 ID（关联 MDC traceId，用于跨服务追踪）';
COMMENT ON COLUMN ydsz_flow_instance.due_at IS '子流程超时时间（超时自动终止子流程，可空）';
COMMENT ON COLUMN ydsz_flow_instance.reject_reason IS '退回原因（最近一次 REJECT 操作的备注，重审时清空）';
COMMENT ON COLUMN ydsz_flow_instance.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_instance.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_instance.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_instance.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_instance.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_instance.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_instance.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_instance_initiator_id ON ydsz_flow_instance (initiator_id);
CREATE INDEX idx_ydsz_flow_instance_flow_status ON ydsz_flow_instance (flow_status);
CREATE INDEX idx_ydsz_flow_instance_tenant_deleted ON ydsz_flow_instance (tenant_id, deleted);

CREATE TABLE ydsz_flow_run_task (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    node_type                NUMBER(10)               DEFAULT NULL,
    business_type            VARCHAR2(64 CHAR)        DEFAULT NULL,
    business_id              VARCHAR2(64 CHAR)        DEFAULT NULL,
    business_no              VARCHAR2(64 CHAR)        DEFAULT NULL,
    flow_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    title                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    assignor_id              VARCHAR2(32 CHAR)        DEFAULT NULL,
    assignor_name            VARCHAR2(64 CHAR)        DEFAULT NULL,
    assignee_type            VARCHAR2(32 CHAR)        DEFAULT NULL,
    assignee_id              VARCHAR2(64 CHAR)        NOT NULL,
    assignee_name            VARCHAR2(64 CHAR)        DEFAULT NULL,
    permission_flag          VARCHAR2(512 CHAR)       DEFAULT NULL,
    perform_type             VARCHAR2(32 CHAR)        DEFAULT NULL,
    approve_count            NUMBER(10)               DEFAULT NULL,
    approve_finished         NUMBER(10)               DEFAULT NULL,
    vote_pass_rate           NUMBER(20,6)             DEFAULT NULL,
    user_weight              NUMBER(10)               DEFAULT NULL,
    approve_weight           NUMBER(10)               DEFAULT NULL,
    total_weight             NUMBER(10)               DEFAULT NULL,
    task_status              VARCHAR2(32 CHAR)        NOT NULL,
    comment                  VARCHAR2(512 CHAR)       DEFAULT NULL,
    claim_at                 TIMESTAMP                DEFAULT NULL,
    finish_at                TIMESTAMP                DEFAULT NULL,
    effective_time           TIMESTAMP                DEFAULT NULL,
    duration_ms              NUMBER(19)               DEFAULT NULL,
    due_at                   TIMESTAMP                DEFAULT NULL,
    priority                 NUMBER(10)               NOT NULL DEFAULT 50,
    urge_count               NUMBER(10)               NOT NULL DEFAULT 0,
    last_urged_at            TIMESTAMP                DEFAULT NULL,
    sla_action               VARCHAR2(32 CHAR)        DEFAULT NULL,
    sla_escalated            NUMBER(10)               NOT NULL DEFAULT 0,
    -- GAP-P0 幂等修复: iter_var 非空占位（对齐 MySQL 版），保证 uk 约束对非 FOREACH 任务生效
    -- （Oracle 唯一约束视 NULL 为互异值，若允许 NULL 则重复任务无法被约束拦截）
    iter_var                 VARCHAR2(128 CHAR)       DEFAULT '' NOT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_run_task PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_run_task_instance_node_assignee UNIQUE (instance_id, node_code, assignee_id, iter_var)
);

COMMENT ON TABLE ydsz_flow_run_task IS '待办任务运行表（我的待办核心查询表）';
COMMENT ON COLUMN ydsz_flow_run_task.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_run_task.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_run_task.instance_id IS '流程实例 ID（关联 ydsz_flow_instance.id）';
COMMENT ON COLUMN ydsz_flow_run_task.flow_code IS '流程编码（冗余字段）';
COMMENT ON COLUMN ydsz_flow_run_task.definition_id IS '流程定义 ID';
COMMENT ON COLUMN ydsz_flow_run_task.node_code IS '节点编码';
COMMENT ON COLUMN ydsz_flow_run_task.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_run_task.node_type IS '节点类型（FlowNodeType.code）';
COMMENT ON COLUMN ydsz_flow_run_task.business_type IS '业务类型';
COMMENT ON COLUMN ydsz_flow_run_task.business_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_flow_run_task.business_no IS '业务单据编号';
COMMENT ON COLUMN ydsz_flow_run_task.flow_name IS '流程名称（冗余）';
COMMENT ON COLUMN ydsz_flow_run_task.title IS '任务标题（默认为「{流程名}-{节点名}-{业务编号}」）';
COMMENT ON COLUMN ydsz_flow_run_task.assignor_id IS '委托人 ID（委托操作产生，被委托人完成任务后回填）';
COMMENT ON COLUMN ydsz_flow_run_task.assignor_name IS '委托人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_run_task.assignee_type IS '办理人类型（FlowAssigneeType 枚举名：USER/ROLE/DEPT/POST）';
COMMENT ON COLUMN ydsz_flow_run_task.assignee_id IS '办理人 ID（按 type 解析，USER 传 userId，ROLE 传 roleCode）';
COMMENT ON COLUMN ydsz_flow_run_task.assignee_name IS '办理人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_run_task.permission_flag IS '办理人权限标识（原始 SpEL 表达式，存档便于回溯）';
COMMENT ON COLUMN ydsz_flow_run_task.perform_type IS '会签类型（FlowPerformType 枚举名：OR=或签，PARALLEL=并行会签，WEIGHTED=票签）';
COMMENT ON COLUMN ydsz_flow_run_task.approve_count IS '会签所需通过人数（PARALLEL 模式：会签总人数）';
COMMENT ON COLUMN ydsz_flow_run_task.approve_finished IS '会签当前已通过人数';
COMMENT ON COLUMN ydsz_flow_run_task.vote_pass_rate IS '通过率阈值（0~1，默认 0.5 表示过半数）';
COMMENT ON COLUMN ydsz_flow_run_task.user_weight IS '当前办理人的权重值（票签模式，未配置默认 1）';
COMMENT ON COLUMN ydsz_flow_run_task.approve_weight IS '累计已通过权重（票签模式：每次通过时累加 userWeight）';
COMMENT ON COLUMN ydsz_flow_run_task.total_weight IS '节点总权重（票签模式：所有办理人权重之和）';
COMMENT ON COLUMN ydsz_flow_run_task.task_status IS '任务状态（FlowTaskStatus 枚举名）';
COMMENT ON COLUMN ydsz_flow_run_task.comment IS '审批意见';
COMMENT ON COLUMN ydsz_flow_run_task.claim_at IS '签收时间（多人会签时记录每个办理人的签收时间）';
COMMENT ON COLUMN ydsz_flow_run_task.finish_at IS '完成时间';
COMMENT ON COLUMN ydsz_flow_run_task.duration_ms IS '耗时（毫秒，finishAt - claimAt）';
COMMENT ON COLUMN ydsz_flow_run_task.due_at IS '截止时间（SLA 阈值，由 slaConfig.timeoutMinutes 计算）';
COMMENT ON COLUMN ydsz_flow_run_task.priority IS '任务优先级（1-100，默认 50，待办按 priority DESC, created_at ASC 排序）';
COMMENT ON COLUMN ydsz_flow_run_task.urge_count IS '已发送的 SLA 催办次数（超过配置上限后停止）';
COMMENT ON COLUMN ydsz_flow_run_task.last_urged_at IS '最近一次催办时间';
COMMENT ON COLUMN ydsz_flow_run_task.sla_action IS '最终触发的 SLA 动作（REMIND/ESCALATE/AUTO_PASS/AUTO_REJECT）';
COMMENT ON COLUMN ydsz_flow_run_task.sla_escalated IS '是否已升级（0=否，1=是，避免重复升级）';
COMMENT ON COLUMN ydsz_flow_run_task.iter_var IS 'FOREACH 节点当前迭代元素值（如 userId/deptId，非循环节点为空字符串占位，保证唯一约束幂等生效）';
COMMENT ON COLUMN ydsz_flow_run_task.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_run_task.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_run_task.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_run_task.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_run_task.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_run_task.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_run_task.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_run_task.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_run_task_assignee_id ON ydsz_flow_run_task (assignee_id);
CREATE INDEX idx_ydsz_flow_run_task_business ON ydsz_flow_run_task (business_type, business_id);
CREATE INDEX idx_ydsz_flow_run_task_due_at ON ydsz_flow_run_task (due_at);
CREATE INDEX idx_ydsz_flow_run_task_tenant_deleted ON ydsz_flow_run_task (tenant_id, deleted);

CREATE TABLE ydsz_flow_user (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    task_id                  VARCHAR2(32 CHAR)        NOT NULL,
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    user_type                VARCHAR2(32 CHAR)        DEFAULT NULL,
    user_id                  VARCHAR2(64 CHAR)        NOT NULL,
    user_name                VARCHAR2(64 CHAR)        DEFAULT NULL,
    processed                NUMBER(10)               NOT NULL DEFAULT 0,
    process_at               TIMESTAMP                DEFAULT NULL,
    comment                  VARCHAR2(512 CHAR)       DEFAULT NULL,
    weight                   NUMBER(10)               NOT NULL DEFAULT 1,
    sign_type                VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'ORIGINAL',
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_user PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_user_task_user UNIQUE (task_id, user_id, sign_type)
);

COMMENT ON TABLE ydsz_flow_user IS '流程任务-办理人关系表（会签/加签多对多关系）';
COMMENT ON COLUMN ydsz_flow_user.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_user.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_user.task_id IS '任务 ID（关联 ydsz_flow_run_task.id）';
COMMENT ON COLUMN ydsz_flow_user.instance_id IS '流程实例 ID（冗余便于查询）';
COMMENT ON COLUMN ydsz_flow_user.node_code IS '节点编码';
COMMENT ON COLUMN ydsz_flow_user.user_type IS '用户类型（USER=具体用户，ROLE=角色展开，DEPT=部门展开）';
COMMENT ON COLUMN ydsz_flow_user.user_id IS '用户/角色/部门 ID';
COMMENT ON COLUMN ydsz_flow_user.user_name IS '用户姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_user.processed IS '是否已处理（0=否，1=是）';
COMMENT ON COLUMN ydsz_flow_user.process_at IS '处理时间';
COMMENT ON COLUMN ydsz_flow_user.comment IS '审批意见';
COMMENT ON COLUMN ydsz_flow_user.weight IS '办理人权重（默认 1，可配置 2/3 等，用于加权会签）';
COMMENT ON COLUMN ydsz_flow_user.sign_type IS '加签类型（ORIGINAL=原始审批人，BEFORE=前加签，AFTER=后加签，PARALLEL=并加签，ADD=追加处理人）';
COMMENT ON COLUMN ydsz_flow_user.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_user.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_user.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_user.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_user.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_user.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_user.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_user.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_user_instance_id ON ydsz_flow_user (instance_id);
CREATE INDEX idx_ydsz_flow_user_tenant_deleted ON ydsz_flow_user (tenant_id, deleted);

CREATE TABLE ydsz_flow_timer (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    timer_type               VARCHAR2(32 CHAR)        NOT NULL,
    boundary_task_id         VARCHAR2(32 CHAR)        DEFAULT NULL,
    fire_at                  TIMESTAMP                NOT NULL,
    cycle                    VARCHAR2(64 CHAR)        DEFAULT NULL,
    timer_status             VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'PENDING',
    fired_at                 TIMESTAMP                DEFAULT NULL,
    cancel_reason            VARCHAR2(512 CHAR)       DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_timer PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_timer IS '工作流定时器表（中间/边界定时器调度）';
COMMENT ON COLUMN ydsz_flow_timer.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_timer.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_timer.instance_id IS '流程实例 ID';
COMMENT ON COLUMN ydsz_flow_timer.definition_id IS '流程定义 ID';
COMMENT ON COLUMN ydsz_flow_timer.flow_code IS '流程编码（冗余）';
COMMENT ON COLUMN ydsz_flow_timer.node_code IS '节点编码';
COMMENT ON COLUMN ydsz_flow_timer.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_timer.timer_type IS '定时器类型（INTERMEDIATE=中间定时器，BOUNDARY=边界定时器）';
COMMENT ON COLUMN ydsz_flow_timer.boundary_task_id IS '边界定时器关联的 userTask ID（INTERMEDIATE 为 NULL）';
COMMENT ON COLUMN ydsz_flow_timer.fire_at IS '到点时间（cronjob 按 fire_at <= now() AND timer_status = PENDING 扫描）';
COMMENT ON COLUMN ydsz_flow_timer.cycle IS 'CRON 表达式（循环定时器，可空）';
COMMENT ON COLUMN ydsz_flow_timer.timer_status IS '状态（PENDING=待触发，FIRED=已触发，CANCELLED=已取消）';
COMMENT ON COLUMN ydsz_flow_timer.fired_at IS '实际触发时间';
COMMENT ON COLUMN ydsz_flow_timer.cancel_reason IS '取消原因（userTask 完成时关闭）';
COMMENT ON COLUMN ydsz_flow_timer.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_timer.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_timer.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_timer.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_timer.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_timer.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_timer.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_timer.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_timer_fire_at ON ydsz_flow_timer (fire_at);
CREATE INDEX idx_ydsz_flow_timer_instance_id ON ydsz_flow_timer (instance_id);
CREATE INDEX idx_ydsz_flow_timer_timer_status ON ydsz_flow_timer (timer_status);
CREATE INDEX idx_ydsz_flow_timer_tenant_deleted ON ydsz_flow_timer (tenant_id, deleted);

CREATE TABLE ydsz_flow_event_subscription (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    event_type               VARCHAR2(32 CHAR)        NOT NULL,
    event_ref                VARCHAR2(64 CHAR)        NOT NULL,
    correlation_key          VARCHAR2(64 CHAR)        DEFAULT NULL,
    boundary_task_id         VARCHAR2(32 CHAR)        DEFAULT NULL,
    subscription_status      VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'WAITING',
    payload                  CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_event_subscription_payload CHECK (payload IS JSON),
    triggered_at             TIMESTAMP                DEFAULT NULL,
    trigger_source           VARCHAR2(32 CHAR)        DEFAULT NULL,
    cancel_reason            VARCHAR2(512 CHAR)       DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_event_subscription PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_event_subscription IS '工作流事件订阅表（消息/错误/信号事件运行时等待）';
COMMENT ON COLUMN ydsz_flow_event_subscription.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_event_subscription.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_event_subscription.instance_id IS '流程实例 ID';
COMMENT ON COLUMN ydsz_flow_event_subscription.definition_id IS '流程定义 ID';
COMMENT ON COLUMN ydsz_flow_event_subscription.flow_code IS '流程编码（冗余）';
COMMENT ON COLUMN ydsz_flow_event_subscription.node_code IS '节点编码（事件捕获节点）';
COMMENT ON COLUMN ydsz_flow_event_subscription.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_event_subscription.event_type IS '事件类型（MESSAGE=消息，ERROR=错误，SIGNAL=信号）';
COMMENT ON COLUMN ydsz_flow_event_subscription.event_ref IS '事件引用标识（messageRef / errorRef / signalRef）';
COMMENT ON COLUMN ydsz_flow_event_subscription.correlation_key IS '消息关联键（业务级匹配，SIGNAL 广播匹配时可空）';
COMMENT ON COLUMN ydsz_flow_event_subscription.boundary_task_id IS '边界事件关联的 userTask ID（中间事件为 NULL）';
COMMENT ON COLUMN ydsz_flow_event_subscription.subscription_status IS '订阅状态（WAITING=等待中，COMPLETED=已完成，CANCELLED=已取消）';
COMMENT ON COLUMN ydsz_flow_event_subscription.payload IS '触发时携带的业务数据 JSON';
COMMENT ON COLUMN ydsz_flow_event_subscription.triggered_at IS '实际触发时间';
COMMENT ON COLUMN ydsz_flow_event_subscription.trigger_source IS '触发来源（API=外部系统调用，SERVICE_TASK=服务任务抛出，BOUNDARY=边界事件超时）';
COMMENT ON COLUMN ydsz_flow_event_subscription.cancel_reason IS '取消原因';
COMMENT ON COLUMN ydsz_flow_event_subscription.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_event_subscription.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_event_subscription.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_event_subscription.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_event_subscription.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_event_subscription.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_event_subscription.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_event_subscription.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_event_subscription_instance_id ON ydsz_flow_event_subscription (instance_id);
CREATE INDEX idx_ydsz_flow_event_subscription_event_ref ON ydsz_flow_event_subscription (event_ref);
CREATE INDEX idx_ydsz_flow_event_subscription_subscription_status ON ydsz_flow_event_subscription (subscription_status);
CREATE INDEX idx_ydsz_flow_event_subscription_correlation_key ON ydsz_flow_event_subscription (correlation_key);
CREATE INDEX idx_ydsz_flow_event_subscription_tenant_deleted ON ydsz_flow_event_subscription (tenant_id, deleted);

CREATE TABLE ydsz_flow_his_task (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    task_id                  VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    node_code                VARCHAR2(64 CHAR)        NOT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    node_type                NUMBER(10)               DEFAULT NULL,
    business_type            VARCHAR2(64 CHAR)        DEFAULT NULL,
    business_id              VARCHAR2(64 CHAR)        DEFAULT NULL,
    business_no              VARCHAR2(64 CHAR)        DEFAULT NULL,
    flow_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    title                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    assignee_type            VARCHAR2(32 CHAR)        DEFAULT NULL,
    assignee_id              VARCHAR2(64 CHAR)        DEFAULT NULL,
    assignee_name            VARCHAR2(64 CHAR)        DEFAULT NULL,
    perform_type             VARCHAR2(32 CHAR)        DEFAULT NULL,
    approve_count            NUMBER(10)               DEFAULT NULL,
    approve_finished         NUMBER(10)               DEFAULT NULL,
    vote_pass_rate           NUMBER(20,6)             DEFAULT NULL,
    task_status              VARCHAR2(32 CHAR)        NOT NULL,
    comment                  VARCHAR2(512 CHAR)       DEFAULT NULL,
    claim_at                 TIMESTAMP                DEFAULT NULL,
    finish_at                TIMESTAMP                DEFAULT NULL,
    effective_time           TIMESTAMP                DEFAULT NULL,
    duration_ms              NUMBER(19)               DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    iter_var                 VARCHAR2(128 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_his_task PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_his_task IS '历史任务表（已完成任务归档，按月分区）';
COMMENT ON COLUMN ydsz_flow_his_task.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_his_task.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_his_task.instance_id IS '流程实例 ID（归档时从 ydsz_flow_run_task.instance_id 复制）';
COMMENT ON COLUMN ydsz_flow_his_task.task_id IS '原始任务 ID（指向源 ydsz_flow_run_task.id，归档后源表清理前可关联）';
COMMENT ON COLUMN ydsz_flow_his_task.flow_code IS '流程编码';
COMMENT ON COLUMN ydsz_flow_his_task.definition_id IS '流程定义 ID';
COMMENT ON COLUMN ydsz_flow_his_task.node_code IS '节点编码';
COMMENT ON COLUMN ydsz_flow_his_task.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_his_task.node_type IS '节点类型（FlowNodeType.code）';
COMMENT ON COLUMN ydsz_flow_his_task.business_type IS '业务类型';
COMMENT ON COLUMN ydsz_flow_his_task.business_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_flow_his_task.business_no IS '业务单据编号';
COMMENT ON COLUMN ydsz_flow_his_task.flow_name IS '流程名称（冗余）';
COMMENT ON COLUMN ydsz_flow_his_task.title IS '任务标题';
COMMENT ON COLUMN ydsz_flow_his_task.assignee_type IS '办理人类型（FlowAssigneeType 枚举名）';
COMMENT ON COLUMN ydsz_flow_his_task.assignee_id IS '办理人 ID';
COMMENT ON COLUMN ydsz_flow_his_task.assignee_name IS '办理人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_his_task.perform_type IS '会签类型（FlowPerformType 枚举名）';
COMMENT ON COLUMN ydsz_flow_his_task.approve_count IS '会签所需通过人数';
COMMENT ON COLUMN ydsz_flow_his_task.approve_finished IS '会签当前已通过人数';
COMMENT ON COLUMN ydsz_flow_his_task.vote_pass_rate IS '通过率阈值（0~1，从源 task 复制）';
COMMENT ON COLUMN ydsz_flow_his_task.task_status IS '任务状态（终态：APPROVED/REJECTED/CANCELED/DELEGATED）';
COMMENT ON COLUMN ydsz_flow_his_task.comment IS '审批意见（终态时填写）';
COMMENT ON COLUMN ydsz_flow_his_task.claim_at IS '签收时间';
COMMENT ON COLUMN ydsz_flow_his_task.finish_at IS '完成时间（终态时刻）';
COMMENT ON COLUMN ydsz_flow_his_task.effective_time IS '生效时间（P2-1 穿越时空/补录审批，从源 task 复制，NULL=即时生效）';
COMMENT ON COLUMN ydsz_flow_his_task.duration_ms IS '耗时（毫秒）';
COMMENT ON COLUMN ydsz_flow_his_task.provider_trace_id IS '链路追踪 ID（保留原始 trace 便于历史回溯）';
COMMENT ON COLUMN ydsz_flow_his_task.iter_var IS 'FOREACH 迭代元素值（从源 task 复制，非循环节点为 NULL）';
COMMENT ON COLUMN ydsz_flow_his_task.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_his_task.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_his_task.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_his_task.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_his_task.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_his_task.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_his_task.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_his_task_instance_id ON ydsz_flow_his_task (instance_id);
CREATE INDEX idx_ydsz_flow_his_task_assignee_id ON ydsz_flow_his_task (assignee_id);
CREATE INDEX idx_ydsz_flow_his_task_business ON ydsz_flow_his_task (business_type, business_id);
CREATE INDEX idx_ydsz_flow_his_task_finish_at ON ydsz_flow_his_task (finish_at);
CREATE INDEX idx_ydsz_flow_his_task_tenant_deleted ON ydsz_flow_his_task (tenant_id, deleted);

CREATE TABLE ydsz_flow_his_instance (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    flow_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    definition_id            VARCHAR2(32 CHAR)        NOT NULL,
    flow_version             VARCHAR2(32 CHAR)        DEFAULT NULL,
    business_type            VARCHAR2(64 CHAR)        NOT NULL,
    business_id              VARCHAR2(64 CHAR)        NOT NULL,
    business_no              VARCHAR2(64 CHAR)        DEFAULT NULL,
    title                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    initiator_id             VARCHAR2(32 CHAR)        NOT NULL,
    initiator_name           VARCHAR2(64 CHAR)        DEFAULT NULL,
    current_node_code        VARCHAR2(64 CHAR)        DEFAULT NULL,
    current_node_name        VARCHAR2(128 CHAR)       DEFAULT NULL,
    variable                 CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_flow_his_instance_variable CHECK (variable IS JSON),
    flow_status              VARCHAR2(32 CHAR)        NOT NULL,
    activity_status          NUMBER(10)               DEFAULT NULL,
    start_at                 TIMESTAMP                DEFAULT NULL,
    end_at                   TIMESTAMP                DEFAULT NULL,
    duration_ms              NUMBER(19)               DEFAULT NULL,
    archived_at              TIMESTAMP                DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_his_instance PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_his_instance_business_type_id UNIQUE (business_type, business_id)
);

COMMENT ON TABLE ydsz_flow_his_instance IS '历史流程实例表（终态实例冷数据归档，按月分区）';
COMMENT ON COLUMN ydsz_flow_his_instance.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_his_instance.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_his_instance.flow_code IS '流程编码';
COMMENT ON COLUMN ydsz_flow_his_instance.flow_name IS '流程名称（冗余）';
COMMENT ON COLUMN ydsz_flow_his_instance.definition_id IS '流程定义 ID';
COMMENT ON COLUMN ydsz_flow_his_instance.flow_version IS '流程版本';
COMMENT ON COLUMN ydsz_flow_his_instance.business_type IS '业务类型';
COMMENT ON COLUMN ydsz_flow_his_instance.business_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_flow_his_instance.business_no IS '业务单据编号';
COMMENT ON COLUMN ydsz_flow_his_instance.title IS '流程标题';
COMMENT ON COLUMN ydsz_flow_his_instance.initiator_id IS '发起人 ID';
COMMENT ON COLUMN ydsz_flow_his_instance.initiator_name IS '发起人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_his_instance.current_node_code IS '当前节点编码（终态时为结束节点编码）';
COMMENT ON COLUMN ydsz_flow_his_instance.current_node_name IS '当前节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_his_instance.variable IS '流程变量 JSON 快照';
COMMENT ON COLUMN ydsz_flow_his_instance.flow_status IS '终态状态（APPROVED / REJECTED / CANCELED）';
COMMENT ON COLUMN ydsz_flow_his_instance.activity_status IS '激活状态（终态时固定为 0）';
COMMENT ON COLUMN ydsz_flow_his_instance.start_at IS '启动时间';
COMMENT ON COLUMN ydsz_flow_his_instance.end_at IS '结束时间';
COMMENT ON COLUMN ydsz_flow_his_instance.duration_ms IS '流程耗时（毫秒）';
COMMENT ON COLUMN ydsz_flow_his_instance.archived_at IS '归档时间（由调度器在迁移时填充）';
COMMENT ON COLUMN ydsz_flow_his_instance.provider_trace_id IS '链路追踪 ID（保留原始 trace 便于历史回溯）';
COMMENT ON COLUMN ydsz_flow_his_instance.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_his_instance.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_his_instance.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_his_instance.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_his_instance.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_his_instance.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_his_instance.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_his_instance_archived_at ON ydsz_flow_his_instance (archived_at);
CREATE INDEX idx_ydsz_flow_his_instance_end_at ON ydsz_flow_his_instance (end_at);

CREATE TABLE ydsz_flow_comment (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    task_id                  VARCHAR2(32 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    user_id                  VARCHAR2(32 CHAR)        NOT NULL,
    user_name                VARCHAR2(64 CHAR)        DEFAULT NULL,
    content                  VARCHAR2(2000 CHAR)      NOT NULL,
    type                     VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'COMMENT',
    parent_comment_id        VARCHAR2(32 CHAR)        DEFAULT NULL,
    reply_to_user_id         VARCHAR2(32 CHAR)        DEFAULT NULL,
    reply_to_user_name       VARCHAR2(64 CHAR)        DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_comment PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_comment IS '流程评论表（审批人沟通讨论，支持多级回复）';
COMMENT ON COLUMN ydsz_flow_comment.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_comment.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_comment.instance_id IS '关联流程实例 ID';
COMMENT ON COLUMN ydsz_flow_comment.task_id IS '关联任务 ID（实例级评论可为空）';
COMMENT ON COLUMN ydsz_flow_comment.node_code IS '关联节点编码（任务级评论时记录所在节点）';
COMMENT ON COLUMN ydsz_flow_comment.user_id IS '评论人 ID';
COMMENT ON COLUMN ydsz_flow_comment.user_name IS '评论人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_comment.content IS '评论内容（TEXT 类型，最大长度 2000）';
COMMENT ON COLUMN ydsz_flow_comment.type IS '评论类型（COMMENT=普通评论，QUESTION=提问，REPLY=回复）';
COMMENT ON COLUMN ydsz_flow_comment.parent_comment_id IS '父评论 ID（一级评论为 NULL）';
COMMENT ON COLUMN ydsz_flow_comment.reply_to_user_id IS '被回复人 ID（回复某条评论时标记，一级评论为 NULL）';
COMMENT ON COLUMN ydsz_flow_comment.reply_to_user_name IS '被回复人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_comment.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_comment.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_comment.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_comment.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_comment.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_comment.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_comment.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_comment.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_comment_instance_id ON ydsz_flow_comment (instance_id);
CREATE INDEX idx_ydsz_flow_comment_parent_comment_id ON ydsz_flow_comment (parent_comment_id);
CREATE INDEX idx_ydsz_flow_comment_tenant_deleted ON ydsz_flow_comment (tenant_id, deleted);

CREATE TABLE ydsz_flow_quick_comment (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    user_id                  VARCHAR2(32 CHAR)        NOT NULL,
    content                  VARCHAR2(500 CHAR)       NOT NULL,
    comment_type             VARCHAR2(32 CHAR)        DEFAULT NULL,
    sort_num                 NUMBER(10)               NOT NULL DEFAULT 0,
    use_count                NUMBER(10)               NOT NULL DEFAULT 0,
    is_system                NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_quick_comment PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_quick_comment IS '审批常用语表（用户预设常用审批意见）';
COMMENT ON COLUMN ydsz_flow_quick_comment.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_quick_comment.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_quick_comment.user_id IS '用户 ID（所属用户，常用语按用户隔离）';
COMMENT ON COLUMN ydsz_flow_quick_comment.content IS '常用语内容（审批意见文本，最大长度 500）';
COMMENT ON COLUMN ydsz_flow_quick_comment.comment_type IS '意见分类（AGREE=同意，DISAGREE=不同意，SUGGEST=建议，INQUIRE=询问，可空）';
COMMENT ON COLUMN ydsz_flow_quick_comment.sort_num IS '排序号（越小越靠前，默认 0）';
COMMENT ON COLUMN ydsz_flow_quick_comment.use_count IS '使用次数（统计用，前端可按使用频率排序）';
COMMENT ON COLUMN ydsz_flow_quick_comment.is_system IS '是否系统预设（0=用户自定义，1=系统预置所有用户可见）';
COMMENT ON COLUMN ydsz_flow_quick_comment.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_quick_comment.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_quick_comment.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_quick_comment.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_quick_comment.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_quick_comment.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_quick_comment.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_quick_comment_user_id ON ydsz_flow_quick_comment (user_id);
CREATE INDEX idx_ydsz_flow_quick_comment_sort_num ON ydsz_flow_quick_comment (sort_num);
CREATE INDEX idx_ydsz_flow_quick_comment_use_count ON ydsz_flow_quick_comment (use_count);
CREATE INDEX idx_ydsz_flow_quick_comment_tenant_deleted ON ydsz_flow_quick_comment (tenant_id, deleted);

CREATE TABLE ydsz_flow_cc (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    task_id                  VARCHAR2(32 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    flow_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    business_key             VARCHAR2(64 CHAR)        DEFAULT NULL,
    cc_user_id               VARCHAR2(32 CHAR)        NOT NULL,
    cc_user_name             VARCHAR2(64 CHAR)        DEFAULT NULL,
    cc_type                  VARCHAR2(32 CHAR)        NOT NULL,
    trigger_user_id          VARCHAR2(32 CHAR)        DEFAULT NULL,
    trigger_user_name        VARCHAR2(64 CHAR)        DEFAULT NULL,
    title                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    content                  VARCHAR2(512 CHAR)       DEFAULT NULL,
    read_status              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'UNREAD',
    read_at                  TIMESTAMP                DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_cc PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_cc IS '流程抄送表（抄送中心通知记录）';
COMMENT ON COLUMN ydsz_flow_cc.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_cc.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_cc.instance_id IS '流程实例 ID';
COMMENT ON COLUMN ydsz_flow_cc.task_id IS '触发的任务 ID（CC 节点任务，可空）';
COMMENT ON COLUMN ydsz_flow_cc.node_code IS '触发抄送的节点编码';
COMMENT ON COLUMN ydsz_flow_cc.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_cc.flow_code IS '流程编码';
COMMENT ON COLUMN ydsz_flow_cc.flow_name IS '流程名称（冗余）';
COMMENT ON COLUMN ydsz_flow_cc.business_key IS '业务单据 ID';
COMMENT ON COLUMN ydsz_flow_cc.cc_user_id IS '抄送接收人 ID';
COMMENT ON COLUMN ydsz_flow_cc.cc_user_name IS '抄送接收人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_cc.cc_type IS '抄送类型（CC_NODE=CC 节点，MANUAL_CC=人工抄送，AUTO_CC=系统规则）';
COMMENT ON COLUMN ydsz_flow_cc.trigger_user_id IS '触发抄送的人 ID（AUTO_CC 时为 SYSTEM）';
COMMENT ON COLUMN ydsz_flow_cc.trigger_user_name IS '触发抄送的人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_cc.title IS '抄送标题';
COMMENT ON COLUMN ydsz_flow_cc.content IS '抄送内容/意见（人工抄送时填写）';
COMMENT ON COLUMN ydsz_flow_cc.read_status IS '已读状态（UNREAD=未读，READ=已读）';
COMMENT ON COLUMN ydsz_flow_cc.read_at IS '已读时间（标记 READ 时由后端填充）';
COMMENT ON COLUMN ydsz_flow_cc.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_cc.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_cc.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_cc.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_cc.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_cc.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_cc.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_cc.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_cc_cc_user_id ON ydsz_flow_cc (cc_user_id);
CREATE INDEX idx_ydsz_flow_cc_instance_id ON ydsz_flow_cc (instance_id);
CREATE INDEX idx_ydsz_flow_cc_business_key ON ydsz_flow_cc (business_key);
CREATE INDEX idx_ydsz_flow_cc_tenant_deleted ON ydsz_flow_cc (tenant_id, deleted);

CREATE TABLE ydsz_flow_cc_rule (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    flow_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    rule_type                VARCHAR2(32 CHAR)        NOT NULL,
    rule_target              VARCHAR2(512 CHAR)       DEFAULT NULL,
    enabled                  NUMBER(10)               NOT NULL DEFAULT 1,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_cc_rule PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_cc_rule IS '流程抄送规则表（自动抄送规则配置）';
COMMENT ON COLUMN ydsz_flow_cc_rule.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_cc_rule.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_cc_rule.flow_code IS '流程编码（NULL=所有流程生效）';
COMMENT ON COLUMN ydsz_flow_cc_rule.node_code IS '节点编码（NULL=该流程所有节点生效）';
COMMENT ON COLUMN ydsz_flow_cc_rule.rule_type IS '规则类型（USER=指定用户，ROLE=角色展开，DEPT=部门展开，SPEL=表达式动态解析）';
COMMENT ON COLUMN ydsz_flow_cc_rule.rule_target IS '规则目标（按 ruleType 解析：USER 传 userId / ROLE 传 roleCode / DEPT 传 deptId / SPEL 传表达式）';
COMMENT ON COLUMN ydsz_flow_cc_rule.enabled IS '是否启用（0=禁用，1=启用）';
COMMENT ON COLUMN ydsz_flow_cc_rule.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_cc_rule.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_cc_rule.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_cc_rule.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_cc_rule.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_cc_rule.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_cc_rule.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_cc_rule.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_cc_rule_flow_node ON ydsz_flow_cc_rule (flow_code, node_code);
CREATE INDEX idx_ydsz_flow_cc_rule_enabled ON ydsz_flow_cc_rule (enabled);
CREATE INDEX idx_ydsz_flow_cc_rule_tenant_deleted ON ydsz_flow_cc_rule (tenant_id, deleted);

CREATE TABLE ydsz_flow_attachment (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    task_id                  VARCHAR2(32 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    biz_type                 VARCHAR2(32 CHAR)        NOT NULL,
    file_name                VARCHAR2(255 CHAR)       NOT NULL,
    file_ext                 VARCHAR2(32 CHAR)        DEFAULT NULL,
    file_size                NUMBER(19)               NOT NULL,
    content_type             VARCHAR2(128 CHAR)       DEFAULT NULL,
    storage_key              VARCHAR2(512 CHAR)       NOT NULL,
    storage_type             VARCHAR2(32 CHAR)        NOT NULL,
    uploader_id              VARCHAR2(32 CHAR)        NOT NULL,
    uploader_name            VARCHAR2(64 CHAR)        DEFAULT NULL,
    download_url             VARCHAR2(1024 CHAR)      DEFAULT NULL,
    md5                      VARCHAR2(64 CHAR)        DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_attachment PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_attachment IS '审批附件表（附件元数据，支持 MD5 秒传）';
COMMENT ON COLUMN ydsz_flow_attachment.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_attachment.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_attachment.instance_id IS '关联流程实例 ID';
COMMENT ON COLUMN ydsz_flow_attachment.task_id IS '关联任务 ID（实例级附件可为空）';
COMMENT ON COLUMN ydsz_flow_attachment.node_code IS '关联节点编码';
COMMENT ON COLUMN ydsz_flow_attachment.biz_type IS '附件业务类型（TASK=任务级，INSTANCE=实例级，COMMENT=评论）';
COMMENT ON COLUMN ydsz_flow_attachment.file_name IS '原始文件名（含扩展名）';
COMMENT ON COLUMN ydsz_flow_attachment.file_ext IS '文件扩展名（jpg/pdf/docx...，小写不带点）';
COMMENT ON COLUMN ydsz_flow_attachment.file_size IS '字节大小';
COMMENT ON COLUMN ydsz_flow_attachment.content_type IS 'MIME 类型（如 image/jpeg / application/pdf）';
COMMENT ON COLUMN ydsz_flow_attachment.storage_key IS '存储 key（OSS/COS/MinIO 对象 key 或本地相对路径）';
COMMENT ON COLUMN ydsz_flow_attachment.storage_type IS '存储类型（OSS=阿里云，MINIO=自建对象存储，LOCAL=本地文件系统）';
COMMENT ON COLUMN ydsz_flow_attachment.uploader_id IS '上传人 ID';
COMMENT ON COLUMN ydsz_flow_attachment.uploader_name IS '上传人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_attachment.download_url IS '临时下载地址（由签名接口刷新，避免长 URL 泄露）';
COMMENT ON COLUMN ydsz_flow_attachment.md5 IS '文件 MD5（去重/校验）';
COMMENT ON COLUMN ydsz_flow_attachment.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_attachment.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_attachment.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_attachment.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_attachment.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_attachment.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_attachment.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_attachment.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_attachment_instance_id ON ydsz_flow_attachment (instance_id);
CREATE INDEX idx_ydsz_flow_attachment_task_id ON ydsz_flow_attachment (task_id);
CREATE INDEX idx_ydsz_flow_attachment_md5 ON ydsz_flow_attachment (md5);
CREATE INDEX idx_ydsz_flow_attachment_tenant_deleted ON ydsz_flow_attachment (tenant_id, deleted);

CREATE TABLE ydsz_flow_delegate_auth (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    owner_user_id            VARCHAR2(32 CHAR)        NOT NULL,
    owner_user_name          VARCHAR2(64 CHAR)        DEFAULT NULL,
    delegate_user_id         VARCHAR2(32 CHAR)        NOT NULL,
    delegate_user_name       VARCHAR2(64 CHAR)        DEFAULT NULL,
    scope_type               VARCHAR2(32 CHAR)        NOT NULL,
    flow_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    role_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    start_time               TIMESTAMP                NOT NULL,
    end_time                 TIMESTAMP                NOT NULL,
    auth_status              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'ENABLED',
    reason                   VARCHAR2(512 CHAR)       DEFAULT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_delegate_auth PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_delegate_auth IS '流程委派代理表（长期授权规则）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.owner_user_id IS '授权人（原办理人）ID';
COMMENT ON COLUMN ydsz_flow_delegate_auth.owner_user_name IS '授权人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.delegate_user_id IS '被授权人（代理人）ID';
COMMENT ON COLUMN ydsz_flow_delegate_auth.delegate_user_name IS '被授权人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.scope_type IS '匹配模式（ALL=所有流程，FLOW=指定流程，FLOW_NODE=指定流程节点，ROLE=指定角色）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.flow_code IS '流程编码（FLOW/FLOW_NODE 模式必填）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.node_code IS '节点编码（FLOW_NODE 模式必填）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.role_code IS '角色编码（ROLE 模式必填）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.start_time IS '生效开始时间';
COMMENT ON COLUMN ydsz_flow_delegate_auth.end_time IS '生效结束时间';
COMMENT ON COLUMN ydsz_flow_delegate_auth.auth_status IS '授权状态（ENABLED=生效中，DISABLED=手动停用，EXPIRED=已过期，REVOKED=已撤销）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.reason IS '授权原因（如「出差 3 天」「部门调整」）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_delegate_auth.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_delegate_auth.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_delegate_auth.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_delegate_auth.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_delegate_auth.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_delegate_auth.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_delegate_auth.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_delegate_auth_owner_user_id ON ydsz_flow_delegate_auth (owner_user_id);
CREATE INDEX idx_ydsz_flow_delegate_auth_delegate_user_id ON ydsz_flow_delegate_auth (delegate_user_id);
CREATE INDEX idx_ydsz_flow_delegate_auth_status_time ON ydsz_flow_delegate_auth (auth_status, end_time);
CREATE INDEX idx_ydsz_flow_delegate_auth_tenant_deleted ON ydsz_flow_delegate_auth (tenant_id, deleted);

CREATE TABLE ydsz_flow_admin_role (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    user_id                  VARCHAR2(32 CHAR)        NOT NULL,
    role_code                VARCHAR2(64 CHAR)        NOT NULL,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    granted_by               VARCHAR2(32 CHAR)        DEFAULT NULL,
    granted_at               TIMESTAMP                DEFAULT NULL,
    expire_at                TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_admin_role PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_flow_admin_role_user_role UNIQUE (user_id, role_code)
);

COMMENT ON TABLE ydsz_flow_admin_role IS '流程管理员角色映射表（用户-角色多对多）';
COMMENT ON COLUMN ydsz_flow_admin_role.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_admin_role.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_admin_role.user_id IS '用户 ID';
COMMENT ON COLUMN ydsz_flow_admin_role.role_code IS '角色编码（FLOW_ADMIN=流程管理员，FLOW_DESIGNER=流程设计者，FLOW_AUDITOR=流程审计员）';
COMMENT ON COLUMN ydsz_flow_admin_role.enabled IS '是否启用（0=撤销授权但保留历史记录，1=启用中）';
COMMENT ON COLUMN ydsz_flow_admin_role.granted_by IS '授权人 ID（NULL 表示系统预置角色）';
COMMENT ON COLUMN ydsz_flow_admin_role.granted_at IS '授权时间';
COMMENT ON COLUMN ydsz_flow_admin_role.expire_at IS '过期时间（NULL 表示永不过期）';
COMMENT ON COLUMN ydsz_flow_admin_role.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_admin_role.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_admin_role.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_admin_role.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_admin_role.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_admin_role.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_admin_role.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_admin_role_role_code ON ydsz_flow_admin_role (role_code);
CREATE INDEX idx_ydsz_flow_admin_role_tenant_deleted ON ydsz_flow_admin_role (tenant_id, deleted);

CREATE TABLE ydsz_flow_audit_log (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    instance_id              VARCHAR2(32 CHAR)        NOT NULL,
    task_id                  VARCHAR2(32 CHAR)        DEFAULT NULL,
    flow_code                VARCHAR2(64 CHAR)        NOT NULL,
    business_type            VARCHAR2(64 CHAR)        DEFAULT NULL,
    business_id              VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_code                VARCHAR2(64 CHAR)        DEFAULT NULL,
    node_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    action                   VARCHAR2(32 CHAR)        NOT NULL,
    operator_id              VARCHAR2(32 CHAR)        NOT NULL,
    operator_name            VARCHAR2(64 CHAR)        DEFAULT NULL,
    target_id                VARCHAR2(32 CHAR)        DEFAULT NULL,
    target_name              VARCHAR2(64 CHAR)        DEFAULT NULL,
    comment                  VARCHAR2(512 CHAR)       DEFAULT NULL,
    comment_type             VARCHAR2(32 CHAR)        DEFAULT NULL,
    operated_at              TIMESTAMP                NOT NULL,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_flow_audit_log PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_flow_audit_log IS '流程审计日志表（全生命周期操作轨迹，只追加）';
COMMENT ON COLUMN ydsz_flow_audit_log.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_flow_audit_log.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_flow_audit_log.instance_id IS '流程实例 ID';
COMMENT ON COLUMN ydsz_flow_audit_log.task_id IS '任务 ID（实例级操作可为空）';
COMMENT ON COLUMN ydsz_flow_audit_log.flow_code IS '流程编码';
COMMENT ON COLUMN ydsz_flow_audit_log.business_type IS '业务类型';
COMMENT ON COLUMN ydsz_flow_audit_log.business_id IS '业务单据 ID';
COMMENT ON COLUMN ydsz_flow_audit_log.node_code IS '节点编码';
COMMENT ON COLUMN ydsz_flow_audit_log.node_name IS '节点名称（冗余）';
COMMENT ON COLUMN ydsz_flow_audit_log.action IS '操作类型（START/PASS/REJECT/TRANSFER/DELEGATE/COUNTERSIGN/RECALL/URGE/TERMINATE/SUSPEND/ACTIVATE/CLAIM）';
COMMENT ON COLUMN ydsz_flow_audit_log.operator_id IS '操作人 ID';
COMMENT ON COLUMN ydsz_flow_audit_log.operator_name IS '操作人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_audit_log.target_id IS '目标人 ID（转办/委派/加签/抄送时使用）';
COMMENT ON COLUMN ydsz_flow_audit_log.target_name IS '目标人姓名（冗余）';
COMMENT ON COLUMN ydsz_flow_audit_log.comment IS '审批意见';
COMMENT ON COLUMN ydsz_flow_audit_log.comment_type IS '审批意见分类（AGREE=同意，DISAGREE=不同意，SUGGEST=建议，INQUIRE=询问）';
COMMENT ON COLUMN ydsz_flow_audit_log.operated_at IS '操作时间（精确到毫秒）';
COMMENT ON COLUMN ydsz_flow_audit_log.provider_trace_id IS '链路追踪 ID';
COMMENT ON COLUMN ydsz_flow_audit_log.status IS '状态标识';
COMMENT ON COLUMN ydsz_flow_audit_log.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_flow_audit_log.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_flow_audit_log.created_by IS '创建人';
COMMENT ON COLUMN ydsz_flow_audit_log.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_flow_audit_log.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_flow_audit_log.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_flow_audit_log_instance_id ON ydsz_flow_audit_log (instance_id);
CREATE INDEX idx_ydsz_flow_audit_log_business ON ydsz_flow_audit_log (business_type, business_id);
CREATE INDEX idx_ydsz_flow_audit_log_operator_id ON ydsz_flow_audit_log (operator_id);
CREATE INDEX idx_ydsz_flow_audit_log_operated_at ON ydsz_flow_audit_log (operated_at);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (Oracle)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_category_updated_at
BEFORE UPDATE ON ydsz_flow_category
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_definition_updated_at
BEFORE UPDATE ON ydsz_flow_definition
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_template_updated_at
BEFORE UPDATE ON ydsz_flow_template
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_node_updated_at
BEFORE UPDATE ON ydsz_flow_node
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_skip_updated_at
BEFORE UPDATE ON ydsz_flow_skip
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_auto_trigger_updated_at
BEFORE UPDATE ON ydsz_flow_auto_trigger
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_instance_updated_at
BEFORE UPDATE ON ydsz_flow_instance
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_run_task_updated_at
BEFORE UPDATE ON ydsz_flow_run_task
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_user_updated_at
BEFORE UPDATE ON ydsz_flow_user
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_timer_updated_at
BEFORE UPDATE ON ydsz_flow_timer
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_event_subscription_updated_at
BEFORE UPDATE ON ydsz_flow_event_subscription
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_comment_updated_at
BEFORE UPDATE ON ydsz_flow_comment
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_quick_comment_updated_at
BEFORE UPDATE ON ydsz_flow_quick_comment
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_cc_updated_at
BEFORE UPDATE ON ydsz_flow_cc
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_cc_rule_updated_at
BEFORE UPDATE ON ydsz_flow_cc_rule
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_attachment_updated_at
BEFORE UPDATE ON ydsz_flow_attachment
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_delegate_auth_updated_at
BEFORE UPDATE ON ydsz_flow_delegate_auth
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_admin_role_updated_at
BEFORE UPDATE ON ydsz_flow_admin_role
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP，历史归档表补列后追加）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_his_task_updated_at
BEFORE UPDATE ON ydsz_flow_his_task
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP，历史归档表补列后追加）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_his_instance_updated_at
BEFORE UPDATE ON ydsz_flow_his_instance
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP，审计日志表补列后追加）
CREATE OR REPLACE TRIGGER trg_ydsz_flow_audit_log_updated_at
BEFORE UPDATE ON ydsz_flow_audit_log
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- GAP-P0 存量环境升级脚本（2026-08-27）：iter_var 幂等修复
-- 说明：run_task 唯一约束 uk_ydsz_flow_run_task_instance_node_assignee 含 iter_var，
--       旧版允许 NULL，Oracle 视 NULL 为互异值导致非 FOREACH 任务防重失效。
--       新装环境已由上方建表语句直接生效；存量环境按需执行以下步骤（先去重再改列）。
-- ============================================================================

-- 步骤 1：清理历史 NULL 占位（若存在 iter_var IS NULL 的行，占位为空字符串）
-- UPDATE ydsz_flow_run_task SET iter_var = '' WHERE iter_var IS NULL;

-- 步骤 2：收紧列为 NOT NULL DEFAULT ''
-- ALTER TABLE ydsz_flow_run_task MODIFY (iter_var DEFAULT '' NOT NULL);

-- 步骤 3：验证约束生效（应返回 0 行重复组合）
-- SELECT instance_id, node_code, assignee_id, iter_var, COUNT(1)
--   FROM ydsz_flow_run_task
--  GROUP BY instance_id, node_code, assignee_id, iter_var HAVING COUNT(1) > 1;
