-- ============================================================================
-- ydsz-cloud 代码生成器模块数据库脚本 (ydsz-generator)
-- ============================================================================
-- 模块：ydsz-generator（代码生成器）
-- 说明：代码生成器所需的全部表结构（数据源配置、模板分组、模板、生成历史、元数据缓存）。
--       基于 MySQL 8.0 版本转译生成 (Oracle 12.2+)
--       - 类型映射: JSON→CLOB / TINYINT(1)→NUMBER(1) / INT→NUMBER(10) / BIGINT→NUMBER(19)
--       / DATETIME→TIMESTAMP
--       - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾生成, 以 / 提交)
--       - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--       - VARCHAR2 采用 CHAR 语义 VARCHAR2(n CHAR)
-- 数据库：Oracle 12.2+（由 MySQL 8.0 转译）
-- 日期：2026-09-05
-- @author ydsz-team
-- ============================================================================


-- ============================================================================
-- 1. 数据源配置表
-- ============================================================================

CREATE TABLE ydsz_gen_datasource (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR2(64 CHAR)        NOT NULL,
    jdbc_url                 VARCHAR2(512 CHAR)       NOT NULL,
    username                 VARCHAR2(128 CHAR)       NOT NULL,
    password                 VARCHAR2(512 CHAR)       NOT NULL,
    dialect                  VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'ORACLE',
    is_default               NUMBER(1)                NOT NULL DEFAULT 0,
    description              VARCHAR2(255 CHAR)       DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_datasource PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_datasource_name UNIQUE (name)
);

COMMENT ON TABLE ydsz_gen_datasource IS '代码生成器数据源配置';
COMMENT ON COLUMN ydsz_gen_datasource.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_datasource.name IS '数据源名称（唯一标识）';
COMMENT ON COLUMN ydsz_gen_datasource.jdbc_url IS 'JDBC URL';
COMMENT ON COLUMN ydsz_gen_datasource.username IS '数据库用户名';
COMMENT ON COLUMN ydsz_gen_datasource.password IS '数据库密码（AES 加密存储）';
COMMENT ON COLUMN ydsz_gen_datasource.dialect IS '数据库方言（POSTGRESQL/MYSQL/ORACLE）';
COMMENT ON COLUMN ydsz_gen_datasource.is_default IS '是否为默认数据源（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_datasource.description IS '数据源描述';
COMMENT ON COLUMN ydsz_gen_datasource.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_datasource.updated_at IS '更新时间';


-- ============================================================================
-- 2. 模板分组表
-- ============================================================================

CREATE TABLE ydsz_gen_template_group (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR2(64 CHAR)        NOT NULL,
    description              VARCHAR2(255 CHAR)       DEFAULT NULL,
    is_system                NUMBER(1)                NOT NULL DEFAULT 0,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    is_active                NUMBER(1)                NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_template_group PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_template_group_name UNIQUE (name)
);

COMMENT ON TABLE ydsz_gen_template_group IS '代码生成器模板分组';
COMMENT ON COLUMN ydsz_gen_template_group.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_template_group.name IS '分组名（唯一标识，如 default、mybatis-plus）';
COMMENT ON COLUMN ydsz_gen_template_group.description IS '分组描述';
COMMENT ON COLUMN ydsz_gen_template_group.is_system IS '是否为系统分组（0=否 1=是，系统分组不可删除）';
COMMENT ON COLUMN ydsz_gen_template_group.sort_order IS '排序序号（升序）';
COMMENT ON COLUMN ydsz_gen_template_group.is_active IS '是否激活为当前使用分组（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template_group.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_template_group.updated_at IS '更新时间';


-- ============================================================================
-- 3. 模板表
-- ============================================================================

CREATE TABLE ydsz_gen_template (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id                 NUMBER(19)               NOT NULL,
    file_name                VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(255 CHAR)       DEFAULT NULL,
    content                  CLOB                     NOT NULL,
    is_folder                NUMBER(1)                NOT NULL DEFAULT 0,
    parent_path              VARCHAR2(512 CHAR)       NOT NULL DEFAULT '',
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    hash                     CHAR(32)                 DEFAULT NULL,
    is_active                NUMBER(1)                NOT NULL DEFAULT 1,
    file_type                VARCHAR2(16 CHAR)        NOT NULL DEFAULT 'BACKEND',
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_gen_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_template_group_file UNIQUE (group_id, file_name),
    CONSTRAINT fk_ydsz_gen_template_group FOREIGN KEY (group_id) REFERENCES ydsz_gen_template_group (id)
);

COMMENT ON TABLE ydsz_gen_template IS '代码生成器模板';
COMMENT ON COLUMN ydsz_gen_template.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_template.group_id IS '关联模板分组 ID';
COMMENT ON COLUMN ydsz_gen_template.file_name IS '文件名（如 entity.vm、vue/api.vm）';
COMMENT ON COLUMN ydsz_gen_template.description IS '模板用途描述';
COMMENT ON COLUMN ydsz_gen_template.content IS '模板内容（Velocity 语法）';
COMMENT ON COLUMN ydsz_gen_template.is_folder IS '是否为虚拟文件夹标记（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template.parent_path IS '父路径（如 vue/ 表示前端子目录）';
COMMENT ON COLUMN ydsz_gen_template.version IS '当前版本号';
COMMENT ON COLUMN ydsz_gen_template.hash IS '内容 MD5 哈希（版本对比用）';
COMMENT ON COLUMN ydsz_gen_template.is_active IS '是否启用（0=否 1=是）';
COMMENT ON COLUMN ydsz_gen_template.file_type IS '模板类型（BACKEND/FRONTEND）';
COMMENT ON COLUMN ydsz_gen_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_gen_template.updated_at IS '更新时间';

CREATE INDEX idx_ydsz_gen_template_group ON ydsz_gen_template (group_id);


-- ============================================================================
-- 4. 代码生成任务历史表
-- ============================================================================

CREATE TABLE ydsz_gen_history (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    module_name              VARCHAR2(64 CHAR)        NOT NULL,
    datasource_id            NUMBER(19)               NOT NULL,
    template_group_id        NUMBER(19)               NOT NULL,
    table_count              NUMBER(10)               NOT NULL DEFAULT 0,
    file_count               NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(16 CHAR)        NOT NULL DEFAULT 'RUNNING',
    triggered_by             VARCHAR2(64 CHAR)        DEFAULT NULL,
    started_at               TIMESTAMP                NOT NULL,
    finished_at              TIMESTAMP                DEFAULT NULL,
    error_message            CLOB                     DEFAULT NULL,
    gen_params               CLOB                     DEFAULT NULL,
    CONSTRAINT pk_ydsz_gen_history PRIMARY KEY (id),
    CONSTRAINT fk_ydsz_gen_history_datasource FOREIGN KEY (datasource_id) REFERENCES ydsz_gen_datasource (id),
    CONSTRAINT fk_ydsz_gen_history_template_group FOREIGN KEY (template_group_id) REFERENCES ydsz_gen_template_group (id)
);

COMMENT ON TABLE ydsz_gen_history IS '代码生成任务历史';
COMMENT ON COLUMN ydsz_gen_history.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_history.module_name IS '模块名称';
COMMENT ON COLUMN ydsz_gen_history.datasource_id IS '使用的数据源 ID';
COMMENT ON COLUMN ydsz_gen_history.template_group_id IS '使用的模板分组 ID';
COMMENT ON COLUMN ydsz_gen_history.table_count IS '涉及表数量';
COMMENT ON COLUMN ydsz_gen_history.file_count IS '生成文件总数';
COMMENT ON COLUMN ydsz_gen_history.status IS '执行状态（RUNNING/SUCCESS/PARTIAL/FAILED）';
COMMENT ON COLUMN ydsz_gen_history.triggered_by IS '触发人（用户名）';
COMMENT ON COLUMN ydsz_gen_history.started_at IS '开始时间';
COMMENT ON COLUMN ydsz_gen_history.finished_at IS '完成时间';
COMMENT ON COLUMN ydsz_gen_history.error_message IS '错误信息（失败时记录）';
COMMENT ON COLUMN ydsz_gen_history.gen_params IS '生成参数 JSON 快照';

CREATE INDEX idx_ydsz_gen_history_status ON ydsz_gen_history (status);
CREATE INDEX idx_ydsz_gen_history_started ON ydsz_gen_history (started_at);


-- ============================================================================
-- 5. 生成历史文件明细表
-- ============================================================================

CREATE TABLE ydsz_gen_history_file (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    history_id               NUMBER(19)               NOT NULL,
    file_path                VARCHAR2(512 CHAR)       NOT NULL,
    original_backup_path     VARCHAR2(512 CHAR)       DEFAULT NULL,
    file_hash                CHAR(32)                 DEFAULT NULL,
    action                   VARCHAR2(16 CHAR)        NOT NULL DEFAULT 'CREATED',
    CONSTRAINT pk_ydsz_gen_history_file PRIMARY KEY (id),
    CONSTRAINT fk_ydsz_gen_history_file_history FOREIGN KEY (history_id) REFERENCES ydsz_gen_history (id)
);

COMMENT ON TABLE ydzs_gen_history_file IS '生成历史文件明细';
COMMENT ON COLUMN ydsz_gen_history_file.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_history_file.history_id IS '所属任务 ID';
COMMENT ON COLUMN ydsz_gen_history_file.file_path IS '生成文件路径';
COMMENT ON COLUMN ydsz_gen_history_file.original_backup_path IS '原文件备份路径（用于回滚）';
COMMENT ON COLUMN ydsz_gen_history_file.file_hash IS '文件内容 MD5 哈希';
COMMENT ON COLUMN ydsz_gen_history_file.action IS '文件操作类型（CREATED/UPDATED/UNCHANGED）';

CREATE INDEX idx_ydsz_gen_history_file_history ON ydsz_gen_history_file (history_id);


-- ============================================================================
-- 6. 表元数据缓存表
-- ============================================================================

CREATE TABLE ydsz_gen_table_meta (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    datasource_id            NUMBER(19)               NOT NULL,
    table_name               VARCHAR2(128 CHAR)       NOT NULL,
    comment                  VARCHAR2(255 CHAR)       DEFAULT NULL,
    alias_name               VARCHAR2(64 CHAR)        DEFAULT NULL,
    module_name              VARCHAR2(64 CHAR)        DEFAULT NULL,
    cached_at                TIMESTAMP                NOT NULL,
    CONSTRAINT pk_ydsz_gen_table_meta PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_table_meta_ds_table UNIQUE (datasource_id, table_name),
    CONSTRAINT fk_ydsz_gen_table_meta_datasource FOREIGN KEY (datasource_id) REFERENCES ydsz_gen_datasource (id)
);

COMMENT ON TABLE ydsz_gen_table_meta IS '表元数据缓存';
COMMENT ON COLUMN ydsz_gen_table_meta.id IS '主键 ID';
COMMENT ON COLUMN ydsz_gen_table_meta.datasource_id IS '关联数据源 ID';
COMMENT ON COLUMN ydsz_gen_table_meta.table_name IS '物理表名';
COMMENT ON COLUMN ydsz_gen_table_meta.comment IS '表注释';
COMMENT ON COLUMN ydsz_gen_table_meta.alias_name IS '用户自定义别名（用于类名生成）';
COMMENT ON COLUMN ydsz_gen_table_meta.module_name IS '模块名称（用于包路径）';
COMMENT ON COLUMN ydsz_gen_table_meta.cached_at IS '缓存时间';

CREATE INDEX idx_ydsz_gen_table_meta_datasource ON ydsz_gen_table_meta (datasource_id);


-- ============================================================================
-- 7. 列元数据缓存表
-- ============================================================================

CREATE TABLE ydzs_gen_column_meta (
    id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_meta_id            NUMBER(19)               NOT NULL,
    column_name              VARCHAR2(128 CHAR)       NOT NULL,
    data_type                VARCHAR2(64 CHAR)        NOT NULL,
    column_size              NUMBER(10)               DEFAULT NULL,
    nullable                 NUMBER(1)                NOT NULL DEFAULT 1,
    is_pk                    NUMBER(1)                NOT NULL DEFAULT 0,
    comment                  VARCHAR2(255 CHAR)        DEFAULT NULL,
    override_java_type       VARCHAR2(64 CHAR)        DEFAULT NULL,
    override_field_name      VARCHAR2(64 CHAR)        DEFAULT NULL,
    skip_dto                 NUMBER(1)                NOT NULL DEFAULT 0,
    skip_vo                  NUMBER(1)                NOT NULL DEFAULT 0,
    skip_query               NUMBER(1)                NOT NULL DEFAULT 0,
    extra_config             CLOB                     DEFAULT NULL,
    CONSTRAINT pk_ydsz_gen_column_meta PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_gen_column_meta_table_column UNIQUE (table_meta_id, column_name),
    CONSTRAINT fk_ydsz_gen_column_meta_table FOREIGN KEY (table_meta_id) REFERENCES ydsz_gen_table_meta (id)
);

COMMENT ON TABLE ydzs_gen_column_meta IS '列元数据缓存（含人工覆盖配置）';
COMMENT ON COLUMN ydzs_gen_column_meta.id IS '主键 ID';
COMMENT ON COLUMN ydzs_gen_column_meta.table_meta_id IS '所属表元数据 ID';
COMMENT ON COLUMN ydzs_gen_column_meta.column_name IS '物理列名';
COMMENT ON COLUMN ydzs_gen_column_meta.data_type IS '物理数据类型';
COMMENT ON COLUMN ydzs_gen_column_meta.column_size IS '字段长度';
COMMENT ON COLUMN ydzs_gen_column_meta.nullable IS '是否可为空（0=否 1=是）';
COMMENT ON COLUMN ydzs_gen_column_meta.is_pk IS '是否为主键（0=否 1=是）';
COMMENT ON COLUMN ydzs_gen_column_meta.comment IS '字段注释';
COMMENT ON COLUMN ydzs_gen_column_meta.override_java_type IS '人工覆盖 Java 类型（为空则使用自动映射）';
COMMENT ON COLUMN ydzs_gen_column_meta.override_field_name IS '人工覆盖字段名（为空则使用自动命名）';
COMMENT ON COLUMN ydzs_gen_column_meta.skip_dto IS '是否在 DTO 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydzs_gen_column_meta.skip_vo IS '是否在 VO 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydzs_gen_column_meta.skip_query IS '是否在 Query 中跳过（0=否 1=是）';
COMMENT ON COLUMN ydzs_gen_column_meta.extra_config IS '扩展配置 JSON（枚举值、校验规则等）';

CREATE INDEX idx_ydsz_gen_column_meta_table ON ydzs_gen_column_meta (table_meta_id);


-- ============================================================================
-- 8. 初始化数据（模板分组）
-- ============================================================================

MERGE INTO ydsz_gen_template_group t
USING (SELECT 'default' AS name FROM dual) s
ON (t.name = s.name)
WHEN MATCHED THEN UPDATE SET is_system = 1
WHEN NOT MATCHED THEN
    INSERT (name, description, is_system, sort_order, is_active)
    VALUES ('default', '标准 DDD 分层模板（entity/service/controller/repository...）', 1, 1, 1);

MERGE INTO ydsz_gen_template_group t
USING (SELECT 'mybatis-plus' AS name FROM dual) s
ON (t.name = s.name)
WHEN MATCHED THEN UPDATE SET is_system = 1
WHEN NOT MATCHED THEN
    INSERT (name, description, is_system, sort_order, is_active)
    VALUES ('mybatis-plus', 'Mybatis-Plus 增强版模板（含 Wrapper/通用 Service）', 1, 2, 0);

COMMIT;


-- ============================================================================
-- 9. updated_at 自动更新触发器
-- ============================================================================

CREATE OR REPLACE TRIGGER trg_ydsz_gen_datasource_updated_at
BEFORE UPDATE ON ydsz_gen_datasource
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_ydsz_gen_template_group_updated_at
BEFORE UPDATE ON ydsz_gen_template_group
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_ydsz_gen_template_updated_at
BEFORE UPDATE ON ydsz_gen_template
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
