{{/*
生成 ServiceAccount
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ydsz.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ydsz.labels" (dict "name" "service-account" "Release" .Release "Chart" .Chart) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
