<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.njydsz</groupId>
        <artifactId>ydsz-cloud</artifactId>
        <version>26.09.01-SNAPSHOT</version>
    </parent>
    <artifactId>ydsz-literule</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-literule</name>
    <description>DDD Module</description>
    <modules>
        <module>ydsz-literule-domain</module>
        <module>ydsz-literule-infra</module>
        <module>ydsz-literule-server</module>
        <module>ydsz-literule-api</module>
        <module>ydsz-literule-app</module>
        <module>ydsz-literule-web</module>
    </modules>
</project>
