-- ====================================================================
-- Common Base (Dict/Ext/Tx/Trigger)
-- Module: common | Version: V1.0.0 | Target: PostgreSQL 18
-- Generated from deploy/sql/V1.0.0.sql
-- ====================================================================

-- ====================================================================
-- Nanjing Yunding PMIS database initialization script (single-file merge)
-- Version: V1.0.0
-- Target: PostgreSQL 18
-- Description: This file is generated by merging all V1.0.0_xxx SQL
--   migration scripts under deploy/sql/ in version order. It is
--   equivalent to running the migrations end-to-end, suitable for
--   one-shot initialization of fresh environments.
--   任何 schema 调整请直接编辑本文件，禁止新增增量脚本
--   (deploy/sql/V*__*.sql)。本项目已统一为单文件初始化模式。
--
-- Usage:
--   psql "host=... user=... dbname=... password=..." -v ON_ERROR_STOP=1 -f V1.0.0.sql
--
-- Safety:
--   * -v ON_ERROR_STOP=1 is REQUIRED; otherwise a single failure
--     in the middle will leave the script in an indeterminate state.
--   * The whole script runs inside one transaction (BEGIN; COMMIT;).
--     Any failure rolls back the entire init.
--   * CREATE TABLE / CREATE INDEX 全部使用 IF NOT EXISTS,保证可重复执行
--   * P1-6 清理: 历史 [SKIPPED-CLEANUP] / [SKIPPED-FWD-REF] 标记已全部移除
--     (DROP 改 CREATE IF NOT EXISTS 即可重入;前置引用表在文件头 §Missing-Tables 列出)
-- ====================================================================
-- Generated at: 2026-07-04
-- Files merged: 58
-- ====================================================================

-- Pure-SQL server-side safety settings. These work whether the
-- script is loaded via psql, JDBC, pg_dump, or any other PG
-- client. For psql-specific behavior (ON_ERROR_STOP, QUIET) you
-- should pass -v ON_ERROR_STOP=1 on the psql command line; see
-- the Usage block above.
--
-- Reduce NOTICE/INFO noise; keep WARNING and ERROR visible.
SET client_min_messages = WARNING;
-- Lock down search_path so unqualified table names resolve only
-- to the expected schema. (We use qualified names throughout, but
-- this guards against future contributors adding unqualified DDL.)
SET search_path = public, pg_catalog;

-- Wrap the entire init in one transaction so any failure rolls
-- back cleanly. If the script is already inside a transaction
-- (e.g. a tool-driven init), SAVEPOINTs below still isolate us.
BEGIN;
-- ====================================================================
-- [GENERATOR NOTE] 历史前向引用表已全部落地(表名经重命名规范后已存在)：
--   - pmis_after_sales_ops_ticket  -> pmis_ops_ticket                 (已存在)
--   - pmis_after_sales_satisfaction -> pmis_satisfaction              (已存在)
--   - pmis_after_sales_warranty    -> pmis_warranty                   (已存在)
--   - pmis_project_closure         -> pmis_execution_closure          (已存在)
--   - pmis_evm_record              -> pmis_evm_measure                (已存在)
--   - pmis_contract_template       -> pmis_project_contract_template  (已存在)
--   - pmis_daily_reconcile         -> pmis_reconcile_daily            (已存在)
--   - pmis_project_delivery        -> pmis_execution_delivery_standard/item (已存在)
--   - pmis_agent_blackboard        -> 运行时对象(Blackboard 模式,非持久化实体)
--   - pmis_agent_orchestration     -> 服务层编排概念(无实体类,非 DB 表)
--   NOTE 中所列"前向引用缺失表"经核对后确认全部落地或为运行时对象,
--   无需补建任何 CREATE TABLE。
-- ====================================================================


-- ============================ [001] init pmis schema ============================

-- ====================================================================
-- 南京云顶 PMIS 数据库初始化脚本
-- V1.0.0
-- 对应 PRD V3.2 + 开发计划 V1.0
-- ====================================================================

-- 启用扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ====================================================================
-- Schema 划分
-- ====================================================================
-- ====================================================================
-- 1. 字典/枚举值模块
-- ====================================================================

-- 字典类型表
CREATE TABLE IF NOT EXISTS pmis_dict_type(
    id              VARCHAR(20)      PRIMARY KEY,
    type_code       VARCHAR(64)    NOT NULL,
    type_name       VARCHAR(128)   NOT NULL,
    description     TEXT,
    status          VARCHAR(16)    NOT NULL DEFAULT 'ENABLED',
    created_by      VARCHAR(20)         NOT NULL DEFAULT 'SYSTEM',
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      VARCHAR(20)         NOT NULL DEFAULT 'SYSTEM',
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT       NOT NULL DEFAULT 0,
    tenant_id       VARCHAR(20)         NOT NULL DEFAULT '1',
    -- 数据完整性约束
    CONSTRAINT uk_pmis_dict_type_code UNIQUE (type_code, deleted),
    CONSTRAINT ck_pdt_status_enum    CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_pdt_deleted_enum   CHECK (deleted IN (0, 1))
);
COMMENT ON TABLE pmis_dict_type IS '字典类型表: 业务字典分类定义(如项目类型、招采方式、计费方式)';
COMMENT ON COLUMN pmis_dict_type.id IS '主键 ID';
COMMENT ON COLUMN pmis_dict_type.type_code IS '字典类型编码(全局唯一,如 project_type/expense_category)';
COMMENT ON COLUMN pmis_dict_type.type_name IS '字典类型名称(中文展示名)';
COMMENT ON COLUMN pmis_dict_type.description IS '字典类型业务说明';
COMMENT ON COLUMN pmis_dict_type.status IS '启用状态: ENABLED 启用 / DISABLED 停用';
COMMENT ON COLUMN pmis_dict_type.created_by IS '创建人 ID(SYSTEM=系统初始化)';
COMMENT ON COLUMN pmis_dict_type.created_at IS '创建时间';
COMMENT ON COLUMN pmis_dict_type.updated_by IS '最后修改人 ID';
COMMENT ON COLUMN pmis_dict_type.updated_at IS '最后修改时间';
COMMENT ON COLUMN pmis_dict_type.deleted IS '逻辑删除标记: 0 未删除 / 1 已删除';
COMMENT ON COLUMN pmis_dict_type.tenant_id IS '租户 ID(单租户部署默认 1)';

CREATE INDEX IF NOT EXISTS idx_pmis_dict_type_status ON pmis_dict_type (status) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_pmis_dict_type_tenant_created
    ON pmis_dict_type (tenant_id, created_at DESC) WHERE deleted = 0;

-- 字典项表
CREATE TABLE IF NOT EXISTS pmis_dict_item(
    id              VARCHAR(20)      PRIMARY KEY,
    type_code       VARCHAR(64)    NOT NULL,
    item_code       VARCHAR(64)    NOT NULL,
    item_value      VARCHAR(255)   NOT NULL,
    sort_order      INTEGER        NOT NULL DEFAULT 0,
    parent_id       VARCHAR(20)         NOT NULL DEFAULT 0,
    description     TEXT,
    ext_json        JSONB,
    status          VARCHAR(16)    NOT NULL DEFAULT 'ENABLED',
    created_by      VARCHAR(20)         NOT NULL DEFAULT 'SYSTEM',
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      VARCHAR(20)         NOT NULL DEFAULT 'SYSTEM',
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT       NOT NULL DEFAULT 0,
    tenant_id       VARCHAR(20)         NOT NULL DEFAULT '1',
    -- 数据完整性约束
    CONSTRAINT uk_pmis_dict_item UNIQUE (type_code, item_code, deleted),
    CONSTRAINT ck_pdi_status_enum   CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_pdi_deleted_enum  CHECK (deleted IN (0, 1)),
    CONSTRAINT ck_pdi_sort_nonneg   CHECK (sort_order >= 0)
);
COMMENT ON TABLE pmis_dict_item IS '字典项表: 字典类型下的具体枚举值(如项目类型下的 SYSTEM_DEV/T_M 等)';
COMMENT ON COLUMN pmis_dict_item.id IS '主键 ID';
COMMENT ON COLUMN pmis_dict_item.type_code IS '所属字典类型编码(关联 pmis_dict_type.type_code)';
COMMENT ON COLUMN pmis_dict_item.item_code IS '字典项编码(type_code 下唯一,如 SYSTEM_DEV/T_M)';
COMMENT ON COLUMN pmis_dict_item.item_value IS '字典项展示值(中文)';
COMMENT ON COLUMN pmis_dict_item.sort_order IS '字典项排序号(升序)';
COMMENT ON COLUMN pmis_dict_item.parent_id IS '父级字典项 ID(0=根,支持树形字典)';
COMMENT ON COLUMN pmis_dict_item.description IS '字典项业务说明';
COMMENT ON COLUMN pmis_dict_item.ext_json IS '扩展属性 JSONB(如颜色/图标/跳转链接)';
COMMENT ON COLUMN pmis_dict_item.status IS '启用状态: ENABLED 启用 / DISABLED 停用';
COMMENT ON COLUMN pmis_dict_item.created_by IS '创建人 ID';
COMMENT ON COLUMN pmis_dict_item.created_at IS '创建时间';
COMMENT ON COLUMN pmis_dict_item.updated_by IS '最后修改人 ID';
COMMENT ON COLUMN pmis_dict_item.updated_at IS '最后修改时间';
COMMENT ON COLUMN pmis_dict_item.deleted IS '逻辑删除标记: 0 未删除 / 1 已删除';

CREATE INDEX IF NOT EXISTS idx_pmis_dict_item_type ON pmis_dict_item (type_code) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_pmis_dict_item_status ON pmis_dict_item (status) WHERE deleted = 0;

-- 字典版本表
CREATE TABLE IF NOT EXISTS pmis_dict_version(
    id              VARCHAR(20)      PRIMARY KEY,
    type_code       VARCHAR(64)    NOT NULL,
    version         VARCHAR(32)    NOT NULL,
    change_log      TEXT,
    effective_date  TIMESTAMP      NOT NULL,
    created_by      VARCHAR(20)         NOT NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT       NOT NULL DEFAULT 0
);
COMMENT ON TABLE pmis_dict_version IS '字典版本表: 字典变更历史快照,支持回滚与变更审计';
COMMENT ON COLUMN pmis_dict_version.id IS '主键 ID';
COMMENT ON COLUMN pmis_dict_version.type_code IS '字典类型编码';
COMMENT ON COLUMN pmis_dict_version.version IS '版本号(语义化版本,如 1.0.0)';
COMMENT ON COLUMN pmis_dict_version.change_log IS '变更说明';
COMMENT ON COLUMN pmis_dict_version.effective_date IS '生效时间';
COMMENT ON COLUMN pmis_dict_version.created_by IS '发布人 ID';
COMMENT ON COLUMN pmis_dict_version.created_at IS '发布时间';
COMMENT ON COLUMN pmis_dict_version.deleted IS '逻辑删除标记: 0 未删除 / 1 已删除';

-- 初始化字典类型（PRD 2.3 节要求）
INSERT INTO pmis_dict_type (type_code, type_name, description, created_by) VALUES
    ('procurement_method', '招采方式', '招采方式枚举', 0),
    ('project_type', '项目类型', '8 类项目类型', 0),
    ('product_type', '产品类型', '产品线', 0),
    ('delivery_mode', '开发交付方式', '驻场/远程/混合', 0),
    ('pricing_mode', '定价方式', '固定总价/单价/框架等', 0),
    ('settlement_mode', '结算方式', '里程碑/月度/季度等', 0),
    ('expense_category', '费用类别', '差旅/团建等', 0),
    ('procurement_category', '采购类别', '硬件/软件/服务等', 0),
    ('project_phase', '项目阶段', '调研/开发/测试等', 0),
    ('project_level', '项目级别', 'A/B/C 级', 0)
ON CONFLICT DO NOTHING;

-- 初始化项目类型字典项
INSERT INTO pmis_dict_item (type_code, item_code, item_value, sort_order, created_by) VALUES
    ('project_type', 'SYSTEM_DEV',     '系统开发',   1, 0),
    ('project_type', 'SYSTEM_INTEG',   '系统集成',   2, 0),
    ('project_type', 'SYSTEM_MAINT',   '系统维护',   3, 0),
    ('project_type', 'SOFTWARE_PROD',  '软件产品',   4, 0),
    ('project_type', 'HARDWARE_PROD',  '硬件产品',   5, 0),
    ('project_type', 'TECH_CONSULT',   '技术咨询',   6, 0),
    ('project_type', 'HARDWARE_MAINT', '硬件运维',   7, 0),
    ('project_type', 'STAFF_OUTSRC',   '人力外包服务', 8, 0)
ON CONFLICT DO NOTHING;

-- 初始化项目阶段字典项
INSERT INTO pmis_dict_item (type_code, item_code, item_value, sort_order, created_by) VALUES
    ('project_phase', 'REQUIREMENT', '需求调研', 1, 0),
    ('project_phase', 'DEVELOPMENT', '功能开发', 2, 0),
    ('project_phase', 'TESTING',     '测试阶段', 3, 0),
    ('project_phase', 'DEPLOYMENT',  '实施上线', 4, 0),
    ('project_phase', 'ACCEPTANCE',  '项目验收', 5, 0),
    ('project_phase', 'WARRANTY',    '质保运维', 6, 0)
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------------


-- --------------------------------------------------------------------

-- ============================ [027] init undo log ============================

-- ====================================================================
--  Seata AT 模式 undo_log 表
--  --------------------------------------------------------------------
--  说明：
--    1) AT 模式依赖此表保存 before/after 镜像，用于分支事务回滚
--    2) 必须在每个业务库（pmis / pmis_bill / pmis_archive ...）都建
--    3) 配套 Nacos 配置：data-id = seata-client.properties
--    4) 配套脚本：deploy/seata/verify-seata.sh 会自动检查本表存在
--  --------------------------------------------------------------------
--  版本：V1.0.0_027
--  适用：PostgreSQL 16+
-- ====================================================================

-- ---------- 表结构 ----------
-- id            主键自增
-- branch_id     分支事务 ID（Seata 生成）
-- xid           全局事务 ID（跨服务唯一）
-- context       事务上下文（序列化信息）
-- rollback_info 回滚信息（before/after 镜像 ZIP 压缩）
-- log_status    日志状态 0=正常 1=全局完成 2=全局回滚
-- log_created   创建时间
-- log_modified  最后修改时间
CREATE TABLE IF NOT EXISTS undo_log (
    id            VARCHAR(20)    PRIMARY KEY,
    branch_id     VARCHAR(20)       NOT NULL,
    xid           VARCHAR(100) NOT NULL,
    context       VARCHAR(128) NOT NULL,
    rollback_info BYTEA        NOT NULL,
    log_status    INT          NOT NULL,
    log_created   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_modified  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_undo_log UNIQUE (xid, branch_id)
);

-- ---------- 字段注释 ----------
COMMENT ON TABLE  undo_log             IS 'Seata AT 模式分布式事务回滚日志表（每个业务库都需要）';
COMMENT ON COLUMN undo_log.id          IS '主键 ID';
COMMENT ON COLUMN undo_log.branch_id   IS '分支事务 ID（Seata 内部生成）';
COMMENT ON COLUMN undo_log.xid         IS '全局事务 ID（跨服务唯一标识）';
COMMENT ON COLUMN undo_log.context     IS '事务上下文（序列化信息，如应用名、分组等）';
COMMENT ON COLUMN undo_log.rollback_info IS '回滚信息（ZIP 压缩的 before/after 镜像，Base64 编码）';
COMMENT ON COLUMN undo_log.log_status  IS '日志状态：0=正常 1=全局完成 2=全局回滚';
COMMENT ON COLUMN undo_log.log_created IS '创建时间';
COMMENT ON COLUMN undo_log.log_modified IS '最后修改时间';

-- ---------- 性能索引 ----------
-- 建议添加以下索引（百万行级别可显著提升回滚扫描性能）
-- CREATE INDEX IF NOT EXISTS idx_undo_log_xid ON undo_log (xid);
-- CREATE INDEX IF NOT EXISTS idx_undo_log_status_modified ON undo_log (log_status, log_modified);

-- --------------------------------------------------------------------

-- ============================ [056] add tenant id to base tables ============================

-- ============================================================
-- 基础表多租户字段预留 + 关键查询路径复合索引
--
-- H2.1 修复：
--   README 声明"每一张业务表都带 tenant_id"，但 V1.0.0_001 中的
--   17 张核心基础表全部缺失 tenant_id 字段。本次补齐。
--
-- H2.4 修复：
--   实际业务查询几乎都是
--     WHERE tenant_id = ? AND deleted = 0 ORDER BY created_at DESC LIMIT 20
--   单列 tenant_id 索引选择率约等于全表（单租户 90%+ 数据）。
--   对未建复合索引的核心业务表统一补 (tenant_id, created_at DESC) WHERE deleted = 0。
--
-- H2.3 修复：
--   外键关联列的反向查询无索引，补 permission_id / position_id / employee_id
--   / leader_id / sender_id 索引。
--
-- H3.2 修复：
--   逻辑删除字段索引覆盖不全，对 V1.0.0_001 中缺 deleted 索引的表补建。
--
-- 兼容性：
--   - tenant_id 默认值 1，单租户部署不影响数据
--   - 多租户部署后由 TenantLineInnerInterceptor 强制 WHERE tenant_id = ?
--   - 全部使用 IF NOT EXISTS，可重复执行
-- ============================================================

-- ============================================================
-- 一、基础表 tenant_id 字段补齐（H2.1）
-- ============================================================

-- 1. 字典类型
ALTER TABLE pmis_dict_type ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(20) NOT NULL DEFAULT '1';
CREATE INDEX IF NOT EXISTS idx_dict_type_tenant ON pmis_dict_type(tenant_id);

-- 2. 字典项
ALTER TABLE pmis_dict_item ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(20) NOT NULL DEFAULT '1';
CREATE INDEX IF NOT EXISTS idx_dict_item_tenant ON pmis_dict_item(tenant_id);

-- 3. 字典版本
ALTER TABLE pmis_dict_version ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(20) NOT NULL DEFAULT '1';
CREATE INDEX IF NOT EXISTS idx_dict_version_tenant ON pmis_dict_version(tenant_id);

-- 15. 通知
ALTER TABLE pmis_notification ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(20) NOT NULL DEFAULT '1';
CREATE INDEX IF NOT EXISTS idx_notification_tenant ON pmis_notification(tenant_id);

-- ============================================================
-- 二、关键查询路径复合索引（H2.4）
--   覆盖分页查询 WHERE tenant_id = ? AND deleted = 0 ORDER BY created_at DESC
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_dict_type_tenant_created
    ON pmis_dict_type(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_dict_item_tenant_created
    ON pmis_dict_item(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_role_tenant_created
    ON pmis_role(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_department_tenant_created
    ON pmis_department(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_position_tenant_created
    ON pmis_position(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_job_level_tenant_created
    ON pmis_job_level(tenant_id, sort_order) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_employee_tenant_created
    ON pmis_employee(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_user_account_tenant_created
    ON pmis_user_account(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_notification_tenant_created
    ON pmis_notification(tenant_id, created_at DESC) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_config_tenant_created
    ON pmis_config(tenant_id, created_at DESC) WHERE deleted = 0;

-- ============================================================
-- 三、外键关联列反向查询索引（H2.3）
-- ============================================================

-- 角色-权限：按 permission_id 反向查询"该权限被哪些角色引用"
CREATE INDEX IF NOT EXISTS idx_role_permission_perm
    ON pmis_role_permission(permission_id) WHERE deleted = 0;

-- 员工-岗位：按 position_id 查询"该岗位下的员工"
CREATE INDEX IF NOT EXISTS idx_pmis_emp_position
    ON pmis_employee(position_id) WHERE deleted = 0;

-- 用户账号-员工：按 employee_id 反向查询
CREATE INDEX IF NOT EXISTS idx_pmis_user_employee
    ON pmis_user_account(employee_id) WHERE deleted = 0;

-- 部门-负责人：按 leader_id 反向查询
CREATE INDEX IF NOT EXISTS idx_pmis_dept_leader
    ON pmis_department(leader_id) WHERE deleted = 0;

-- 通知-发送人：按 sender_id 查询"我发出的通知"
CREATE INDEX IF NOT EXISTS idx_pmis_notif_sender
    ON pmis_notification(sender_id) WHERE deleted = 0;

-- ============================================================
-- 四、逻辑删除字段索引覆盖（H3.2）
--   对 V1.0.0_001 中未建 deleted 索引的表补建
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_pmis_dict_version_deleted ON pmis_dict_version(deleted);

-- ============================================================
-- 五、pmis_flow_notify_outbox 表 tenant_id 索引（H2.5）
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_peo_tenant_status
    ON pmis_flow_notify_outbox(tenant_id, status, next_retry_at) WHERE deleted = 0;

-- ============================================================
-- 六、undo_log 性能索引（H1.8）
--   Seata AT 模式回滚按 xid 扫描，无索引会全表扫描
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_undo_log_xid ON undo_log(xid);
CREATE INDEX IF NOT EXISTS idx_undo_log_status_modified ON undo_log(log_status, log_modified);

ANALYZE pmis_dict_type;
ANALYZE pmis_dict_item;
ANALYZE pmis_dict_version;
ANALYZE pmis_role;
ANALYZE pmis_permission;
ANALYZE pmis_user_role;
ANALYZE pmis_role_permission;
ANALYZE pmis_department;
ANALYZE pmis_position;
ANALYZE pmis_job_level;
ANALYZE pmis_job_level_rate;
ANALYZE pmis_employee;
ANALYZE pmis_employee_tag;
ANALYZE pmis_user_account;
ANALYZE pmis_notification;
ANALYZE pmis_config;
ANALYZE pmis_operation_log;
ANALYZE pmis_flow_notify_outbox;
ANALYZE undo_log;
ANALYZE pmis_job_log;
ANALYZE pmis_project_opportunity_follow;
ANALYZE pmis_project_budget_item;
ANALYZE pmis_project_gate_review;
ANALYZE pmis_report_subscription;
ANALYZE pmis_export_record;
ANALYZE pmis_flow_his_variable;
ANALYZE pmis_rule_template;
ANALYZE pmis_rule_test_case;

-- --------------------------------------------------------------------

-- ====================================================================
-- 可选扩展(性能监控/Hint 优化) - H6.2 修复
-- ====================================================================
-- 说明:
--   - pg_stat_statements / pg_hint_plan 需在 postgresql.conf 的
--     shared_preload_libraries 中预加载后才可创建扩展
--   - uuid-ossp / pgcrypto 已在文件首部创建, 此处不再重复
--   - 此脚本在已创建扩展的环境中执行会返回 NOTICE 而非 ERROR(IF NOT EXISTS)
--   - pg_hint_plan 在某些环境(如未配置 preload) 不可用, 使用 DO 块容错

-- pg_stat_statements: 需 shared_preload_libraries 预加载, 未加载时跳过
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'pg_stat_statements 不可用, 跳过: %', SQLERRM;
END $$;

-- pg_hint_plan: 需 preload 预加载, 未加载时跳过
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_hint_plan;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'pg_hint_plan 不可用, 跳过: %', SQLERRM;
END $$;

-- ====================================================================


-- 同步主表与历史表 assignor_id 索引(若已存在则跳过)
CREATE INDEX IF NOT EXISTS idx_pfrt_assignor
    ON pmis_flow_run_task (assignor_id)
    WHERE deleted = 0 AND assignor_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pfht_assignor
    ON pmis_flow_his_task (assignor_id)
    WHERE deleted = 0 AND assignor_id IS NOT NULL;

-- FOREACH 节点 partial unique index(替代原 UNIQUE ... WHERE 约束,PG 不支持该约束语法)
CREATE UNIQUE INDEX IF NOT EXISTS uk_pfrt_foreach_iter
    ON pmis_flow_run_task (instance_id, node_code, iter_var)
    WHERE iter_var IS NOT NULL AND deleted = 0;

-- ----------------------------------------------------------------------------
-- 3) pmis_dict_version 字段补齐
--    - 新增 updated_at / updated_by / tenant_id(对齐 BaseDO 5 字段基线)
--    - created_at / effective_date 统一为 TIMESTAMPTZ(全工程时间字段统一约定)
-- ----------------------------------------------------------------------------
ALTER TABLE pmis_dict_version ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pmis_dict_version ADD COLUMN IF NOT EXISTS updated_by    VARCHAR(20) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE pmis_dict_version ADD COLUMN IF NOT EXISTS tenant_id     VARCHAR(20) NOT NULL DEFAULT '1';
ALTER TABLE pmis_dict_version ALTER COLUMN created_at     TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE pmis_dict_version ALTER COLUMN effective_date TYPE TIMESTAMPTZ USING effective_date AT TIME ZONE 'UTC';

COMMENT ON COLUMN pmis_dict_version.updated_by    IS '最后修改人 ID';
COMMENT ON COLUMN pmis_dict_version.updated_at    IS '最后修改时间';
COMMENT ON COLUMN pmis_dict_version.tenant_id     IS '租户 ID(单租户部署默认 1)';

-- 复合索引(与全工程惯例一致)
CREATE INDEX IF NOT EXISTS idx_pdv_tenant_type
    ON pmis_dict_version (tenant_id, type_code)
    WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_pdv_tenant_type_created
    ON pmis_dict_version (tenant_id, type_code, created_at DESC)
    WHERE deleted = 0;

ANALYZE pmis_dict_version;
ANALYZE pmis_flow_run_task;
ANALYZE pmis_flow_his_task;
ANALYZE pmis_finance_invoice;

ANALYZE pmis_profit_revenue;
ANALYZE pmis_finance_payment;

-- ====================================================================
-- ============================ [063] tg_set_updated_at trigger ============================
-- ====================================================================
-- V1.0.0_063  P1-5 通用 updated_at 数据库触发器
-- ----------------------------------------------------------------------------
-- 背景:
--   AuditFieldFiller 仅在 MyBatis-Plus 写路径生效,以下场景会导致 updated_at 失真:
--     1. 原始 SQL / psql / 批量脚本更新
--     2. 跨服务 Feign 调用后由对方直连 PG 写库
--     3. 定时任务中通过 JdbcTemplate.update 直接 UPDATE
--   解决: 数据库层兜底触发器,确保 updated_at 始终反映真实变更时间
--
-- 设计:
--   - 通用函数 pmis_set_updated_at(): 取 NEW.updated_at 与 CURRENT_TIMESTAMP 的较大值
--   - 触发器命名: tg_<table>_updated_at,行级 BEFORE UPDATE
--   - 仅当 NEW 与 OLD 实际有差异时才更新(避免无意义 UPDATE 触发)
--   - 不影响 created_at / created_by(只读)
--
-- 挂载原则:
--   - 仅挂载"核心业务表"(用户/权限/项目/合同/财务/工作流主表)
--   - 不挂载日志表(pmis_operation_log/flow_audit_log 自身无 updated_at)
--   - 不挂载字典/配置/只读表
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 1) 通用触发器函数(BEFORE UPDATE 行级,只更新 updated_at)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pmis_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    -- 行无实际变更时不更新(避免 no-op UPDATE 触发)
    IF NEW IS DISTINCT FROM OLD THEN
        NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION pmis_set_updated_at() IS
    '通用 updated_at 维护:BEFORE UPDATE 时将 NEW.updated_at 置为 CURRENT_TIMESTAMP;'
    '仅当 NEW 与 OLD 实际不同时触发(避免 no-op UPDATE 引起的批量时间漂移)';

-- ----------------------------------------------------------------------------
-- 2) 通用挂载辅助函数
--    用法: SELECT pmis_attach_updated_at_trigger('pmis_user_account');
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pmis_attach_updated_at_trigger(p_table_name TEXT)
RETURNS VOID AS $$
DECLARE
    trigger_name TEXT;
BEGIN
    trigger_name := 'tg_' || p_table_name || '_updated_at';

    -- 已挂载则跳过
    IF EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = trigger_name
          AND tgrelid = (p_table_name)::regclass
    ) THEN
        RETURN;
    END IF;

    -- 表必须存在
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = p_table_name
    ) THEN
        RAISE WARNING '[pmis_attach_updated_at_trigger] 表不存在,跳过: %', p_table_name;
        RETURN;
    END IF;

    -- 表必须有 updated_at 列
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = p_table_name
          AND column_name = 'updated_at'
    ) THEN
        RAISE WARNING '[pmis_attach_updated_at_trigger] 表无 updated_at 列,跳过: %', p_table_name;
        RETURN;
    END IF;

    EXECUTE FORMAT(
        'CREATE TRIGGER %I BEFORE UPDATE ON %I '
        'FOR EACH ROW EXECUTE FUNCTION pmis_set_updated_at()',
        trigger_name, p_table_name
    );

    RAISE NOTICE '[pmis_attach_updated_at_trigger] 挂载成功: % (trigger: %)',
        p_table_name, trigger_name;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION pmis_attach_updated_at_trigger(TEXT) IS
    '通用挂载函数: 为指定 public 表添加 tg_<table>_updated_at BEFORE UPDATE 触发器;'
    '已挂载 / 表不存在 / 缺 updated_at 列时静默跳过';

-- ----------------------------------------------------------------------------
-- 3) 挂载到核心业务表(15 张)
--    选择标准: 频繁 UPDATE + updated_at 业务强相关 + 跨服务写路径多
-- ----------------------------------------------------------------------------
SELECT pmis_attach_updated_at_trigger('pmis_user_account');         -- 用户账号
SELECT pmis_attach_updated_at_trigger('pmis_employee');             -- 员工
SELECT pmis_attach_updated_at_trigger('pmis_department');           -- 部门
SELECT pmis_attach_updated_at_trigger('pmis_position');             -- 岗位
SELECT pmis_attach_updated_at_trigger('pmis_role');                 -- 角色
SELECT pmis_attach_updated_at_trigger('pmis_config');               -- 系统配置
SELECT pmis_attach_updated_at_trigger('pmis_dict_item');            -- 字典项
SELECT pmis_attach_updated_at_trigger('pmis_dict_version');         -- 字典版本
SELECT pmis_attach_updated_at_trigger('pmis_project_initiation');   -- 立项
SELECT pmis_attach_updated_at_trigger('pmis_project_change');       -- 变更
SELECT pmis_attach_updated_at_trigger('pmis_finance_contract');     -- 合同
SELECT pmis_attach_updated_at_trigger('pmis_finance_invoice');      -- 发票
SELECT pmis_attach_updated_at_trigger('pmis_finance_payment');      -- 回款
SELECT pmis_attach_updated_at_trigger('pmis_flow_instance');        -- 流程实例
SELECT pmis_attach_updated_at_trigger('pmis_flow_definition');      -- 流程定义

-- ----------------------------------------------------------------------------
-- 3.1) 批量挂载剩余所有含 updated_at 列的 pmis_ 表
--      上方 15 张核心表已显式挂载; 此处用 DO 块动态扫描 information_schema,
--      为所有尚未挂载触发器且含 updated_at 列的 pmis_ 表自动挂载。
--      pmis_attach_updated_at_trigger() 自身幂等: 已挂载 / 表不存在 / 缺
--      updated_at 列时均静默跳过, 故可安全覆盖全部表。
--      覆盖: 规则/成本/利润/EVM/费率/资源/考勤/运维/工单/满意度/对账/
--      利用率/工作流子表/报表/导出/2FA/会话/敏感操作等(约 80+ 张表)。
--      日志表(pmis_operation_log / pmis_flow_audit_log 等)无 updated_at 列,
--      会被辅助函数自动跳过。
-- ----------------------------------------------------------------------------
DO $$
DECLARE
    t_name TEXT;
BEGIN
    FOR t_name IN
        SELECT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema
         AND t.table_name = c.table_name
        WHERE c.table_schema = 'public'
          AND c.column_name = 'updated_at'
          AND t.table_type = 'BASE TABLE'
          AND c.table_name LIKE 'pmis\_%' ESCAPE '\'
          -- 排除分区子表(由父表继承,无需单独挂载)
          AND c.table_name NOT LIKE '%_default'
    LOOP
        PERFORM pmis_attach_updated_at_trigger(t_name);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ====================================================================

-- ====================================================================
-- All DDL has been applied. Commit the transaction. If any DDL above
-- failed, the implicit ROLLBACK from psql -v ON_ERROR_STOP=1 will
-- have already aborted the transaction and the COMMIT below will
-- error out harmlessly. Tool-driven inits should ignore the COMMIT
-- line and roll back manually on exception.
-- ====================================================================
COMMIT;

