<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.njydsz</groupId>
        <artifactId>ydsz-cloud</artifactId>
        <version>26.09.01-SNAPSHOT</version>
    </parent>
    <artifactId>ydsz-workflow</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-workflow</name>
    <description>DDD Module</description>
    <modules>
        <module>ydsz-workflow-domain</module>
        <module>ydsz-workflow-infra</module>
        <module>ydsz-workflow-server</module>
        <module>ydsz-workflow-api</module>
        <module>ydsz-workflow-app</module>
        <module>ydsz-workflow-web</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <configuration>
                    <configLocation>${maven.multiModuleProjectDirectory}/docs/checkstyle.xml</configLocation>
                    <propertyExpansion>config_loc=${maven.multiModuleProjectDirectory}/docs</propertyExpansion>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
