<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-common</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ydsz-pmis-common-lock</artifactId>
    <name>ydsz-pmis-common-lock</name>
    <description>PMIS Common Lock - 分布式锁/看门狗/信号量</description>

    <dependencies>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-util</artifactId>
        </dependency>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
        </dependency>
    </dependencies>
</project>
