server:
  port: 9001

spring:
  application:
    name: ydsz-pmis-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:pmis}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yaml
        group: ${spring.profiles.active}
        namespace: ${NACOS_NAMESPACE:pmis}
        # 引入共享配置：datasource / redis / mybatis-plus / springdoc / logging
        shared-configs:
          - data-id: pmis-common-shared.yaml
            group: PMIS_GROUP_${spring.profiles.active}
            refresh: true

# 服务特有配置
pmis:
  jwt:
    secret: ${JWT_SECRET}
    issuer: pmis
