<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.njydsz.pmis</groupId>
        <artifactId>ydsz-pmis-common</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ydsz-pmis-common-util</artifactId>
    <name>ydsz-pmis-common-util</name>
    <description>工具集：加密、JSON、IP、雪花ID、PDF、路径守护等</description>

    <dependencies>
        <dependency>
            <groupId>com.njydsz.pmis</groupId>
            <artifactId>ydsz-pmis-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
        </dependency>
    </dependencies>
</project>
