apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# UAT 环境:用户验收测试,2-3 副本 + INFO 日志
# 用法:kubectl apply -k deploy/k8s/overlays/uat

namespace: pmis-uat

resources:
  - ../../base

namePrefix: uat-

images:
  - name: ydsz-pmis/gateway
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/system
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/userinfo
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/project
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/cronjob
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/workflow
    newTag: v1.3.0-rc.2
  - name: ydsz-pmis/agent
    newTag: v1.3.0-rc.2

patches:
  - path: patch-replicas.yaml
