-- ============================================================================
-- 模块：ydsz-agent
-- 说明：基于 ydsz-agent-infra 实体类与既有迁移脚本（V1__prompt_template.sql、
--       V2__trace_step_cost.sql）整理的完整建表脚本
-- 日期：2026-08-25
-- @author ydsz-team
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Prompt 模板主表（沿用 V1__prompt_template.sql 定义）
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (PostgreSQL 11+)
--   - 类型映射: JSON→JSONB / TINYINT(1)→SMALLINT / INT→INTEGER / DATETIME→TIMESTAMP
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾统一生成)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   - 索引/约束名按 schema 级唯一性命名: idx_{table}_{core} / uk_{table}_{core}
--   - 原 MySQL 前缀索引 path(255) → 表达式索引 left(path,255)
--   - 原 MySQL FULLTEXT 索引 → GIN to_tsvector('simple', ...) 全文索引
--   - 执行方式: psql -U <user> -d <db> -f ydsz-agent.sql
-- ============================================================================


CREATE TABLE IF NOT EXISTS ydsz_prompt_template (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    template_code            VARCHAR(64)              NOT NULL,
    template_name            VARCHAR(128)             NOT NULL,
    content                  TEXT                     NOT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    category                 VARCHAR(64)              DEFAULT NULL,
    current_version          INTEGER                  NOT NULL DEFAULT 1,
    deleted                  BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_prompt_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_prompt_template_template_code UNIQUE (template_code, tenant_id)
);

COMMENT ON TABLE ydsz_prompt_template IS 'Prompt 模板主表';
COMMENT ON COLUMN ydsz_prompt_template.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_prompt_template.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_prompt_template.template_code IS '模板唯一编码（业务标识，创建后不可变）';
COMMENT ON COLUMN ydsz_prompt_template.template_name IS '模板名称（展示用）';
COMMENT ON COLUMN ydsz_prompt_template.content IS '模板内容，支持 #{var} 占位符';
COMMENT ON COLUMN ydsz_prompt_template.description IS '模板描述';
COMMENT ON COLUMN ydsz_prompt_template.category IS '分类（用于分组检索）';
COMMENT ON COLUMN ydsz_prompt_template.current_version IS '当前版本号，自 1 起每次更新递增';
COMMENT ON COLUMN ydsz_prompt_template.deleted IS '逻辑删除标识';
COMMENT ON COLUMN ydsz_prompt_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_prompt_template.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_prompt_template.created_by IS '创建人';
COMMENT ON COLUMN ydsz_prompt_template.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_prompt_template_category ON ydsz_prompt_template (category);
CREATE INDEX IF NOT EXISTS idx_ydsz_prompt_template_tenant_deleted ON ydsz_prompt_template (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_prompt_version (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    template_code            VARCHAR(64)              NOT NULL,
    version                  INTEGER                  NOT NULL,
    content                  TEXT                     NOT NULL,
    change_note              VARCHAR(512)             DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_prompt_version PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_prompt_version_template_version UNIQUE (template_code, version, tenant_id)
);

COMMENT ON TABLE ydsz_prompt_version IS 'Prompt 模板版本历史表';
COMMENT ON COLUMN ydsz_prompt_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_prompt_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_prompt_version.template_code IS '所属模板编码（关联 ydsz_prompt_template.template_code）';
COMMENT ON COLUMN ydsz_prompt_version.version IS '版本号（与 template 的 current_version 对应）';
COMMENT ON COLUMN ydsz_prompt_version.content IS '该版本的模板内容快照';
COMMENT ON COLUMN ydsz_prompt_version.change_note IS '版本备注（描述本次变更内容）';
COMMENT ON COLUMN ydsz_prompt_version.created_at IS '版本创建时间';
COMMENT ON COLUMN ydsz_prompt_version.created_by IS '操作人';

CREATE INDEX IF NOT EXISTS idx_ydsz_prompt_version_template_code ON ydsz_prompt_version (template_code);

CREATE TABLE IF NOT EXISTS ydsz_agent_definition (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    agent_code               VARCHAR(64)              NOT NULL,
    agent_name               VARCHAR(128)             NOT NULL,
    agent_type               VARCHAR(32)              NOT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    system_prompt            TEXT                     DEFAULT NULL,
    model_config             JSONB                    DEFAULT NULL,
    tool_names               JSONB                    DEFAULT NULL,
    temperature              DOUBLE PRECISION         DEFAULT NULL,
    max_tokens               INTEGER                  DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_agent_definition PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_agent_definition_agent_code UNIQUE (agent_code, tenant_id)
);

COMMENT ON TABLE ydsz_agent_definition IS 'Agent 定义（Agent 的完整配置信息）';
COMMENT ON COLUMN ydsz_agent_definition.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_agent_definition.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_agent_definition.agent_code IS 'Agent 编码（业务唯一键）';
COMMENT ON COLUMN ydsz_agent_definition.agent_name IS 'Agent 名称（展示用）';
COMMENT ON COLUMN ydsz_agent_definition.agent_type IS 'Agent 类型（CHAT/REACT/RAG/PLAN_EXECUTE/ROUTER）';
COMMENT ON COLUMN ydsz_agent_definition.description IS 'Agent 描述';
COMMENT ON COLUMN ydsz_agent_definition.system_prompt IS '系统提示词';
COMMENT ON COLUMN ydsz_agent_definition.model_config IS '模型配置 JSON（temperature/maxTokens/modelId 等）';
COMMENT ON COLUMN ydsz_agent_definition.tool_names IS '工具名称列表 JSON（["tool1","tool2"]）';
COMMENT ON COLUMN ydsz_agent_definition.temperature IS '温度参数';
COMMENT ON COLUMN ydsz_agent_definition.max_tokens IS '最大生成 Token 数';
COMMENT ON COLUMN ydsz_agent_definition.status IS '状态标识';
COMMENT ON COLUMN ydsz_agent_definition.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_agent_definition.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_agent_definition.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_agent_definition.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_agent_definition.created_by IS '创建人';
COMMENT ON COLUMN ydsz_agent_definition.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_agent_definition_agent_type ON ydsz_agent_definition (agent_type);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_definition_tenant_deleted ON ydsz_agent_definition (tenant_id, deleted);

CREATE TABLE IF NOT EXISTS ydsz_agent_trace (
    trace_id                 VARCHAR(64)             ,
    conversation_id          VARCHAR(64)              NOT NULL,
    agent_id                 VARCHAR(64)              NOT NULL,
    status                   VARCHAR(32)              NOT NULL,
    total_duration_ms        BIGINT                   DEFAULT NULL,
    CONSTRAINT pk_ydsz_agent_trace PRIMARY KEY (trace_id)
);

COMMENT ON TABLE ydsz_agent_trace IS 'Agent 执行链路（记录一次 Agent 执行的完整元数据）';
COMMENT ON COLUMN ydsz_agent_trace.trace_id IS '链路唯一 ID（主键，业务生成非自增）';
COMMENT ON COLUMN ydsz_agent_trace.conversation_id IS '所属对话 ID';
COMMENT ON COLUMN ydsz_agent_trace.agent_id IS 'Agent 类型标识（CHAT/REACT/RAG/PLAN_EXECUTE/SUPERVISOR）';
COMMENT ON COLUMN ydsz_agent_trace.status IS '执行状态（RUNNING/SUCCESS/FAILED/MAX_ITERATIONS/GUARDRAIL_REJECTED）';
COMMENT ON COLUMN ydsz_agent_trace.total_duration_ms IS '总耗时（毫秒）';

CREATE INDEX IF NOT EXISTS idx_ydsz_agent_trace_trace_conversation ON ydsz_agent_trace (conversation_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_trace_trace_agent ON ydsz_agent_trace (agent_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_trace_trace_status ON ydsz_agent_trace (status);

CREATE TABLE IF NOT EXISTS ydsz_agent_trace_step (
    trace_id                 VARCHAR(64)              NOT NULL,
    step_index               INTEGER                  NOT NULL,
    step_type                VARCHAR(32)              NOT NULL,
    content                  TEXT                     DEFAULT NULL,
    input_json               JSONB                    DEFAULT NULL,
    output_json              JSONB                    DEFAULT NULL,
    duration_ms              BIGINT                   DEFAULT NULL,
    cost                     NUMERIC(12,6)            NOT NULL DEFAULT 0.0,
    CONSTRAINT pk_ydsz_agent_trace_step PRIMARY KEY (trace_id, step_index)
);

COMMENT ON TABLE ydsz_agent_trace_step IS 'Agent 执行链路步骤（记录单个执行步骤，支持回放与调试）';
COMMENT ON COLUMN ydsz_agent_trace_step.trace_id IS '链路 ID（关联 ydsz_agent_trace.trace_id）';
COMMENT ON COLUMN ydsz_agent_trace_step.step_index IS '步骤序号（从 0 开始递增）';
COMMENT ON COLUMN ydsz_agent_trace_step.step_type IS '步骤类型（LLM_CALL/TOOL_CALL/THOUGHT/OBSERVATION/ROUTE/LLM_CALL_ERROR）';
COMMENT ON COLUMN ydsz_agent_trace_step.content IS '步骤内容描述';
COMMENT ON COLUMN ydsz_agent_trace_step.input_json IS '步骤输入（JSON 字符串）';
COMMENT ON COLUMN ydsz_agent_trace_step.output_json IS '步骤输出（JSON 字符串）';
COMMENT ON COLUMN ydsz_agent_trace_step.duration_ms IS '耗时（毫秒）';
COMMENT ON COLUMN ydsz_agent_trace_step.cost IS 'Token 成本（USD，精确到 6 位小数；非 LLM 调用步骤为 0）';

CREATE INDEX IF NOT EXISTS idx_ydsz_agent_trace_step_trace_step_cost ON ydsz_agent_trace_step (cost);

CREATE TABLE IF NOT EXISTS ydsz_agent_approval (
    id                       VARCHAR(64)             ,
    conversation_id          VARCHAR(64)              DEFAULT NULL,
    trace_id                 VARCHAR(64)              DEFAULT NULL,
    step_description         VARCHAR(512)             DEFAULT NULL,
    context_json             TEXT                     DEFAULT NULL,
    status                   VARCHAR(32)              NOT NULL DEFAULT 'PENDING',
    approver                 VARCHAR(64)              DEFAULT NULL,
    comment                  VARCHAR(512)             DEFAULT NULL,
    tenant_id                VARCHAR(64)              NOT NULL DEFAULT '0',
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at              TIMESTAMP                DEFAULT NULL,
    CONSTRAINT pk_ydsz_agent_approval PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_agent_approval IS 'Agent 人工审批请求（Human-in-the-Loop 审批持久化）';
COMMENT ON COLUMN ydsz_agent_approval.id IS '审批请求 ID（主键，业务生成非自增）';
COMMENT ON COLUMN ydsz_agent_approval.conversation_id IS '所属对话 ID';
COMMENT ON COLUMN ydsz_agent_approval.trace_id IS '执行链路 ID';
COMMENT ON COLUMN ydsz_agent_approval.step_description IS '待审批步骤的业务描述';
COMMENT ON COLUMN ydsz_agent_approval.context_json IS '审批上下文（JSON 字符串，含用户输入、已有结果等）';
COMMENT ON COLUMN ydsz_agent_approval.status IS '审批状态（PENDING/APPROVED/REJECTED/EXPIRED）';
COMMENT ON COLUMN ydsz_agent_approval.approver IS '审批人标识';
COMMENT ON COLUMN ydsz_agent_approval.comment IS '审批意见';
COMMENT ON COLUMN ydsz_agent_approval.tenant_id IS '租户 ID';
COMMENT ON COLUMN ydsz_agent_approval.created_at IS '请求创建时间';
COMMENT ON COLUMN ydsz_agent_approval.resolved_at IS '审批完成时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_agent_approval_approval_conversation ON ydsz_agent_approval (conversation_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_approval_approval_trace ON ydsz_agent_approval (trace_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_approval_approval_status ON ydsz_agent_approval (status);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_approval_approval_tenant ON ydsz_agent_approval (tenant_id);

CREATE TABLE IF NOT EXISTS ydsz_agent_token_usage (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    conversation_id          VARCHAR(64)              NOT NULL,
    model_name               VARCHAR(64)              NOT NULL,
    prompt_tokens            BIGINT                   NOT NULL DEFAULT 0,
    completion_tokens        BIGINT                   NOT NULL DEFAULT 0,
    total_tokens             BIGINT                   NOT NULL DEFAULT 0,
    status                   VARCHAR(32)              DEFAULT NULL,
    deleted                  SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)              DEFAULT NULL,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    CONSTRAINT pk_ydsz_agent_token_usage PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_agent_token_usage IS 'Token 用量记录（LLM 调用 Token 消耗明细）';
COMMENT ON COLUMN ydsz_agent_token_usage.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_agent_token_usage.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_agent_token_usage.conversation_id IS '所属对话 ID（关联 ydsz_agent_conversation）';
COMMENT ON COLUMN ydsz_agent_token_usage.model_name IS '使用的模型标识';
COMMENT ON COLUMN ydsz_agent_token_usage.prompt_tokens IS '提示词 Token 数';
COMMENT ON COLUMN ydsz_agent_token_usage.completion_tokens IS '补全 Token 数';
COMMENT ON COLUMN ydsz_agent_token_usage.total_tokens IS '总 Token 数（prompt + completion）';
COMMENT ON COLUMN ydsz_agent_token_usage.status IS '状态标识';
COMMENT ON COLUMN ydsz_agent_token_usage.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_agent_token_usage.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_agent_token_usage.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_agent_token_usage.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_agent_token_usage.created_by IS '创建人';
COMMENT ON COLUMN ydsz_agent_token_usage.updated_by IS '最后更新人';

CREATE INDEX IF NOT EXISTS idx_ydsz_agent_token_usage_conversation_created ON ydsz_agent_token_usage (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ydsz_agent_token_usage_tenant_deleted ON ydsz_agent_token_usage (tenant_id, deleted);

INSERT INTO ydsz_prompt_template (id, tenant_id, template_code, template_name, content, description, category, current_version, deleted)
VALUES ('100000000000000001', '0', 'DEFAULT_SYSTEM', '默认系统 Prompt', '你是 YDSZ 项目管理信息系统的智能助手。你可以帮助用户查询项目信息、分析项目进度、发起审批流程、发送消息通知等。请用中文回答。', '系统默认的通用助手 Prompt', 'system', 1, FALSE);

INSERT INTO ydsz_prompt_version (id, tenant_id, template_code, version, content, change_note)
VALUES ('100000000000000002', '0', 'DEFAULT_SYSTEM', 1, '你是 YDSZ 项目管理信息系统的智能助手。你可以帮助用户查询项目信息、分析项目进度、发起审批流程、发送消息通知等。请用中文回答。', '初始版本');

INSERT INTO ydsz_prompt_template (id, tenant_id, template_code, template_name, content, description, category, current_version, deleted)
VALUES ('100000000000000003', '0', 'REACT_SYSTEM', 'ReAct Agent Prompt', '你是 YDSZ 项目管理信息系统的智能助手。你可以使用工具来帮助用户完成任务。请根据用户需求决定是否使用工具。如果不需要工具，直接回答即可。', 'ReAct 模式下的工具调用助手 Prompt', 'system', 1, FALSE);

INSERT INTO ydsz_prompt_version (id, tenant_id, template_code, version, content, change_note)
VALUES ('100000000000000004', '0', 'REACT_SYSTEM', 1, '你是 YDSZ 项目管理信息系统的智能助手。你可以使用工具来帮助用户完成任务。请根据用户需求决定是否使用工具。如果不需要工具，直接回答即可。', '初始版本');

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (PostgreSQL)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_prompt_template_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_prompt_template_updated_at ON ydsz_prompt_template;
CREATE TRIGGER trg_ydsz_prompt_template_updated_at
BEFORE UPDATE ON ydsz_prompt_template
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_prompt_template_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_agent_definition_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_agent_definition_updated_at ON ydsz_agent_definition;
CREATE TRIGGER trg_ydsz_agent_definition_updated_at
BEFORE UPDATE ON ydsz_agent_definition
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_agent_definition_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_agent_token_usage_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_agent_token_usage_updated_at ON ydsz_agent_token_usage;
CREATE TRIGGER trg_ydsz_agent_token_usage_updated_at
BEFORE UPDATE ON ydsz_agent_token_usage
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_agent_token_usage_set_updated_at();
