# =====================================================================
#  YDSZ · System · DEV 环境配置（Nacos DataId）
#  DataId:    ydsz-system-dev.yaml
#  Group:     dev
#  端口:      9002
# =====================================================================

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

# MinIO 对象存储
minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9100}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  default-bucket: ${MINIO_BUCKET:ydsz}
  url-expire-seconds: 3600

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.njydsz.system.entity
