{{- range $name, $svc := .Values.microservices }}
{{- if $svc.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pmis.fullname" $ }}-{{ $name }}
  labels:
    {{- include "pmis.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $svc.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "pmis.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
