apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pmis.fullname" . }}-secret
  labels:
    {{- include "pmis.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_USER: {{ .Values.db.user | default "pmis" | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
