const fs = require('fs');
const targetPath = process.argv[2];
const spel = '"T(com.njyzsz.common.cache.support.CacheKeyBuilder).build(' + "'system', 'dict:type', 'all'" + ')"';

const content = [
'package com.njyzsz.system.server.service.impl;',
'import java.util.List;',
'',
'import lombok.RequiredArgsConstructor;',
'import lombok.extern.slf4j.Slf4j;',
'import org.springframework.beans.factory.ObjectProvider;',
'import org.springframework.cache.annotation.CacheEvict;',
'import org.springframework.stereotype.Service;',
'import org.springframework.transaction.annotation.Transactional;',
'',
'import com.njyzsz.common.cache.spring.YdszCacheable;',
'import com.njyzsz.system.server.constant.SystemCacheConstants;',
'import com.njyzsz.common.core.response.PageResponse;',
'import com.njyzsz.common.event.api.DomainEvent;',
'import com.njyzsz.common.event.api.DomainEventTypes;',
'import com.njyzsz.common.event.publish.DomainEventPublisher;',
'import com.njyzsz.common.exception.custom.BusinessException;',
'import com.njyzsz.system.domain.dto.DictTypeDTO;',
'import com.njyzsz.system.domain.enums.SystemExceptionCode;',
'import com.njyzsz.system.domain.query.DictPageQuery;',
'import com.njyzsz.system.domain.repository.DictRepository;',
'import com.njyzsz.system.domain.vo.DictTypeVO;',
'import com.njyzsz.system.server.service.DictService;',
'import com.njyzsz.system.server.service.event.DictChangeEventConstants;',
'import com.njyzsz.system.server.service.event.DictChangeEventPublisher;',
'',
'',
'/**',
' * \\u5b57\\u5178\\u7c7b\\u578b Service \\u5b9e\\u73b0',
' *',
' * <p>\\u5bf9 {@link DictService} \\u63a5\\u53e3\\u7684\\u5b8c\\u6574\\u5b9e\\u73b0\\uff0c\\u7ef4\\u62a4 {@code ydsz_sys_dict_type} \\u5b57\\u5178\\u7c7b\\u578b\\u8868\\u3002',
' */',
'@Slf4j',
'@Service',
'@RequiredArgsConstructor',
'public class DictServiceImpl implements DictService {',
'',
'  /** \\u5b57\\u5178\\u4ed3\\u50a8\\uff08\\u805a\\u5408 DictTypeMapper / DictItemMapper\\uff09 */',
'  private final DictRepository dictRepository;',
'',
'  /** \\u7edf\\u4e00\\u9886\\u57df\\u4e8b\\u4ef6\\u53d1\\u5e03\\u95e8\\u9762 */',
'  private final ObjectProvider<DomainEventPublisher> eventPublisherProvider;',
'',
'  /** Redis \\u5b57\\u5178\\u53d8\\u66f4\\u4e8b\\u4ef6\\u53d1\\u5e03\\u5668\\uff08\\u7528\\u4e8e SSE \\u591a\\u7aef\\u5e7f\\u64ad\\uff09 */',
'  private final DictChangeEventPublisher dictChangeEventPublisher;',
'',
'  // ============================== CRUD ==============================',
'',
'  /** \\u5206\\u9875\\u67e5\\u8be2\\u5b57\\u5178\\u7c7b\\u578b */',
'  @Override',
'  public PageResponse<List<DictTypeVO>> page(DictPageQuery query) {',
'    return dictRepository.findTypePage(query);',
'  }',
'',
'  /** \\u6839\\u636e\\u4e3b\\u952e\\u67e5\\u8be2\\u5b57\\u5178\\u7c7b\\u578b */',
'  @Override',
'  public DictTypeVO getById(String id) {',
'    return dictRepository.findTypeById(id).orElse(null);',
'  }',
'',
'  /**',
'   * \\u65b0\\u589e\\u5b57\\u5178\\u7c7b\\u578b',
'   *',
'   * <p>\\u6267\\u884c\\u94fe\\u8def\\uff1a\\u552f\\u4e00\\u6027\\u6821\\u9a8c \\u2192 \\u63d2\\u5165 DB \\u2192 \\u53d1\\u5e03\\u9886\\u57df\\u4e8b\\u4ef6 + Redis \\u901a\\u9053\\u4e8b\\u4ef6',
'   *',
'   * @return \\u65b0\\u521b\\u5efa\\u7684\\u5b57\\u5178\\u7c7b\\u578b ID',
'   */',
'  @Override',
'  @CacheEvict(',
'      value = SystemCacheConstants.SYSTEM_DICT_TYPE_CACHE,',
'      key = ' + spel + ')',
'  @Transactional(rollbackFor = Exception.class)',
'  public String save(DictTypeDTO dto) {',
'    checkDuplicateTypeCode(dto);',
'    dictRepository.insertType(dto);',
'    publishDictTypeChangedEvent(dto.getTypeCode(), "' + [char]228 + [char]237 + [char]237 + [char]235).Normalize() + '");',
'    dictChangeEVentPublisher.publishDictTypeEvent(',
'        dto.getTypeCode(), DictChangeEventConstants.EVENT_TYPE_CREATED);',
'    return dto.getId();',
'  }',
].join('\\n');

fs.writeFileSync(targetPath, content + '\\n', 'utf-8');
console.log('Written: ' + (content.length + 1));