const fs = require('fs');
const path = process.argv[2];

const line = (s) => lines.push(s);
const lines = [];
line('package com.njyzsz.system.server.service.impl;');
line('import java.util.List;');
line('');
line('import lombok.RequiredArgsConstructor;');
line('import lombok.extern.slf4j.Slf4j;');
line('import org.springframework.beans.factory.ObjectProvider;');
line('import org.springframework.cache.annotation.CacheEvict;');
line('import org.springframework.stereotype.Service;');
line('import org.springframework.transaction.annotation.Transactional;');
line('');
line('import com.njyzsz.common.cache.spring.YdszCacheable;');
line('import com.njyzsz.system.server.constant.SystemCacheConstants;');
line('import com.njyzsz.common.core.response.PageResponse;');
line('import com.njyzsz.common.event.api.DomainEvent;');
line('import com.njyzsz.common.event.api.DomainEventTypes;');
line('import com.njyzsz.common.event.publish.DomainEventPublisher;');
line('import com.njyzsz.common.exception.custom.BusinessException;');
line('import com.njyzsz.system.domain.dto.DictTypeDTO;');
line('import com.njyzsz.system.domain.enums.SystemExceptionCode;');
line('import com.njyzsz.system.domain.query.DictPageQuery;');
line('import com.njyzsz.system.domain.repository.DictRepository;');
line('import com.njyzsz.system.domain.vo.DictTypeVO;');
line('import com.njyzsz.system.server.service.DictService;');
line('import com.njyzsz.system.server.service.event.DictChangeEventConstants;');
line('import com.njyzsz.system.server.service.event.DictChangeEventPublisher;');
line('');
line('');
line('/**');
line(' * \\u5b57\\u5178\\u7c7b\\u578b Service \\u5b9e\\u73b0');
line(' */');
line('@Slf4j');
line('@Service');
line('@RequiredArgsConstructor');
line('public class DictServiceImpl implements DictService {');
line('');
line('  /** \\u5b57\\u5178\\u4ed3\\u50a8 */');
line('  private final DictRepository dictRepository;');
line('');
line('  /** \\u7edf\\u4e00\\u9886\\u57df\\u4e8b\\u4ef6\\u53d1\\u5e03\\u95e8\\u9762 */');
line('  private final ObjectProvider<DomainEventPublisher> eventPublisherProvider;');
line('');
line('  /** Redis \\u5b57\\u5178\\u53d8\\u66f4\\u4e8b\\u4ef6\\u53d1\\u5e03\\u5668\\uff08\\u7528\\u4e8e SSE \\u591a\\u7aef\\u5e7f\\u64ad\\uff09 */');
line('  private final DictChangeEventPublisher dictChangeEventPublisher;');
line('');
line('  // ============================== CRUD ==============================');
line('');
line('  /** \\u5206\\u9875\\u67e5\\u8be2 */');
line('  @Override');
line('  public PageResponse<List<DictTypeVO>> page(DictPageQuery query) {');
line('    return dictRepository.findTypePage(query);');
line('  }');
line('');
line('  /** \\u6839\\u636e\\u4e3b\\u952e\\u67e5\\u8be2 */');
line('  @Override');
line('  public DictTypeVO getById(String id) {');
line('    return dictRepository.findTypeById(id).orElse(null);');
line('  }');
line('');
line('  /** \\u65b0\\u589e\\u5b57\\u5178\\u7c7b\\u578b */');
line('  @Override');
line('  @CacheEvict(');
line('      value = SystemCacheConstants.SYSTEM_DICT_TYPE_CACHE,');
line('      key = "T(com.njyzsz.common.cache.support.CacheKeyBuilder).build(\'system\',\'dict:type\',\'all\')")');
line('  @Transactional(rollbackFor = Exception.class)');
line('  public String save(DictTypeDTO dto) {');
line('    checkDuplicateTypeCode(dto);');
line('    dictRepository.insertType(dto);');
line('    publishDictTypeChangedEvent(dto.getTypeCode(), "\\u521b\\u5efa\\u5b57\\u5178\\u7c7b\\u578b");');
line('    dictChangeEventPublisher.publishDictTypeEvent(');
line('        dto.getTypeCode(), DictChangeEventConstants.EVENT_TYPE_CREATED);');
line('    return dto.getId();');
line('  }');
line('');
line('  /** \\u66f4\\u65b0\\u5b57\\u5178\\u7c7b\\u578b */');
line('  @Override');
line('  @CacheEvict(');
line('      value = SystemCacheConstants.SYSTEM_DICT_TYPE_CACHE,');
line('      key = "T(com.njyzsz.common.cache.support.CacheKeyBuilder).build(\'system\',\'dict:type\',\'all\')")');
line('  @Transactional(rollbackFor = Exception.class)');
line('  public boolean updateById(DictTypeDTO dto) {');
line('    checkDuplicateTypeCode(dto);');
line('    boolean updated = dictRepository.updateTypeById(dto);');
line('    if (updated) {');
line('      publishDictTypeChangedEvent(dto.getTypeCode(), "\\u66f4\\u65b0\\u5b57\\u5178\\u7c7b\\u578b");');
line('      dictChangeEventPublisher.publishDictTypeEvent(');
line('          dto.getTypeCode(), DictChangeEventConstants.EVENT_TYPE_UPDATED);');
line('    }');
line('    return updated;');
line('  }');
line('');
line('  /** \\u903b\\u8f91\\u5220\\u9664\\u5b57\\u5178\\u7c7b\\u578b */');
line('  @Override');
line('  @CacheEvict(');
line('      value = SystemCacheConstants.SYSTEM_DICT_TYPE_CACHE,');
line('      key = "T(com.njyzsz.common.cache.support.CacheKeyBuilder).build(\'system\',\'dict:type\',\'all\')")');
line('  @Transactional(rollbackFor = Exception.class)');
line('  public boolean removeById(String id) {');
line('    DictTypeVO vo = dictRepository.findTypeById(id).orElse(null);');
line('    if (vo == null) {');
line('      return false;');
line('    }');
line('    long itemCount = dictRepository.countItemsByTypeCode(vo.getTypeCode());');
line('    if (itemCount > 0) {');
line('      throw BusinessException.of(SystemExceptionCode.DICT_TYPE_HAS_ITEMS)');
line('          .data("typeCode", vo.getTypeCode())');
line('          .data("itemCount", itemCount);');
line('    }');
line('    boolean removed = dictRepository.deleteTypeById(id);');
line('    if (removed) {');
line('      publishDictTypeChangedEvent(vo.getTypeCode(), "\\u5220\\u9664\\u5b57\\u5178\\u7c7b\\u578b");');
line('      dictChangeEventPublisher.publishDictTypeEvent(');
line('          vo.getTypeCode(), DictChangeEventConstants.EVENT_TYPE_DELETED);');
line('    }');
line('    return removed;');
line('  }');
line('');
line('  // ============================== \\u79c1\\u6709\\u65b9\\u6cd5 ==============================');
line('');
line('  /** \\u5e7f\\u64ad\\u5b57\\u5178\\u7c7b\\u578b\\u53d8\\u66f4\\u4e8b\\u4ef6 */');
line('  private void publishDictTypeChangedEvent(String typeCode, String action) {');
line('    DomainEventPublisher publisher = eventPublisherProvider.getIfAvailable();');
line('    if (publisher == null) {');
line('      return;');
line('    }');
line('    publisher.publish(');
line('        DomainEvent.builder()');
line('            .aggregateType("DictType")');
line('            .aggregateId(typeCode)');
line('            .eventType(DomainEventTypes.DICT_TYPE_CHANGED)');
line('            .metadata("typeCode", typeCode)');
line('            .metadata("action", action)');
line('            .build());');
line('  }');
line('');
line('  // ============================== \\u4e1a\\u52a1\\u67e5\\u8be2 ==============================');
line('');
line('  /** \\u67e5\\u8be2\\u5168\\u90e8\\u5b57\\u5178\\u7c7b\\u578b */');
line('  @Override');
line('  @YdszCacheable(');
line('      value = SystemCacheConstants.SYSTEM_DICT_TYPE_CACHE,');
line('      key = "T(com.njyzsz.common.cache.support.CacheKeyBuilder).build(\'system\',\'dict:type\',\'all\')")');
line('  public List<DictTypeVO> listAll() {');
line('    return dictRepository.findAllTypes();');
line('  }');
line('');
line('  // ============================== \\u79c1\\u6709\\u65b9\\u6cd5 ==============================');
line('');
line('  /** \\u552f\\u4e00\\u6027\\u6821\\u9a8c */');
line('  private void checkDuplicateTypeCode(DictTypeDTO dto) {');
line('    if (dictRepository.existsTypeCode(dto.getTypeCode(), dto.getId())) {');
line('      throw BusinessException.of(SystemExceptionCode.DICT_TYPE_CODE_DUPLICATE)');
line('          .data("typeCode", dto.getTypeCode());');
line('    }');
line('  }');
line('}');

fs.writeFileSync(path, lines.join('\n') + '\n', 'utf-8');
console.log('Written: ' + lines.length + ' lines');