#!/usr/bin/env python3
"""Fix duplicate '对应数据表' lines generated by comment-remaining-mappers.py.

The script's template adds a `<p>对应数据表 <code>{table}</code>。` line, but
the MAPPERS dict desc arrays also start with "对应数据表 {@code xxx}，...". This
script removes the redundant second line from generated Javadocs.
"""
import pathlib
import re

BASE = pathlib.Path(r"d:\Code\ydsz\ydsz-pmis\ydsz-backend")

# All Mapper files that were updated
MAPPER_FILES = [
    # ydsz-message
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgAggregateMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgBatchMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgCanaryMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgFeedbackMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgPreferenceMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgRouteRuleMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgSubscriptionMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgTraceMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgUserChannelMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgVariableSourceMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgLogMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgNotificationMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgReceiptMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgTemplateMapper.java",
    "ydsz-message/ydsz-message-infra/src/main/java/com/njydsz/message/infra/mapper/MsgTemplateVersionMapper.java",
    # ydsz-literule
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleDefinitionMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleVersionHistoryMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleVariableDefMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleTemplateMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleTestCaseMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RulePackMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RulePackInstallMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleExecutionTraceMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleDependencyMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleChainGraphMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleCanaryBucketMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleABPolicyMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/RuleABRollbackMapper.java",
    "ydsz-literule/ydsz-literule-infra/src/main/java/com/njydsz/literule/infra/mapper/DecisionTableMapper.java",
    # ydsz-cronjob
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobWebhookMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobNodeMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobLogMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobLogContentMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobHistoryMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobDailyStatsMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobDagMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobDagVersionMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobDagInstanceMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobDagNodeInstanceMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobArtifactMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobAlertRuleMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/JobAlertLogMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/GlueCodeMapper.java",
    "ydsz-cronjob/ydsz-cronjob-infra/src/main/java/com/njydsz/cronjob/infra/mapper/TenantQuotaMapper.java",
    # ydsz-nextwiki
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/FileNodeMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/FileVersionMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/FileAclMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/ShareLinkMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/TagMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/StorageQuotaMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/TrashItemMapper.java",
    "ydsz-nextwiki/ydsz-nextwiki-infra/src/main/java/com/njydsz/nextwiki/infra/mapper/SearchIndexMapper.java",
    # ydsz-agent
    "ydsz-agent/ydsz-agent-infra/src/main/java/com/njydsz/agent/infra/mapper/AgentDefinitionMapper.java",
    # ydsz-system
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/DictTypeMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/DictVersionMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/TenantMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/TenantPlanMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/TenantPlanMenuMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/VariableMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/ConfigMapper.java",
    "ydsz-system/ydsz-system-infra/src/main/java/com/njydsz/system/infra/mapper/AppInfoMapper.java",
]

# Pattern matches: <p>对应数据表 {@code xxx}，...</p> followed by newline+space+<p>
# We want to remove this redundant line
DUPLICATE_PATTERN = re.compile(
    r" \* <p>对应数据表 \{@code [^}]+\}，[^\n]*?</p>\n"
)


def fix_file(path: pathlib.Path) -> bool:
    if not path.exists():
        print(f"SKIP (not found): {path.name}")
        return False
    content = path.read_text(encoding="utf-8")
    new_content, count = DUPLICATE_PATTERN.subn("", content)
    if count > 0:
        path.write_text(new_content, encoding="utf-8")
        print(f"FIXED ({count}): {path.name}")
        return True
    return False


def main():
    fixed = 0
    for rel in MAPPER_FILES:
        if fix_file(BASE / rel):
            fixed += 1
    print(f"\nTotal fixed: {fixed} files")


if __name__ == "__main__":
    main()
