-- =====================================================================
-- V1.0.0 - 初始 Schema（占位）
--
-- ⚠️ 占位说明：
--   本文件为框架占位。真实 DDL 需按 README.md「首次初始化流程」从现有
--   开发/生产库导出后整体替换本文件内容（勿手动编造 DDL）。
--
-- 预期规模（基于代码审计）：
--   - 表：126+ 张（ydsz_user_* / ydsz_project_* / ydsz_flow_* / ydsz_msg_* /
--                   ydsz_job_* / ydsz_config_* / ydsz_dict_* 等）
--   - 视图：5 个
--
-- 导出命令参考：
--   pg_dump --host=<PG_HOST> --port=5432 --username=ydsz \
--     --schema-only --no-owner --no-privileges \
--     --file=V1.0.0__init.sql ydsz
--
-- ROLLBACK: N/A（初始版本）
-- =====================================================================

-- 创建扩展（pgvector 用于 ydsz-agent RAG 向量检索）
-- CREATE EXTENSION IF NOT EXISTS vector;

-- 创建默认租户
-- INSERT INTO ydsz_tenant (tenant_code, tenant_name, status) VALUES ('default', '默认租户', 'ACTIVE');
