-- ----------------------------------------------------------------------------
-- 模块名   : ydsz-literule（规则引擎模块）
-- 说明     : 基于 ydsz-literule-infra 实体类整理的完整建表脚本
--            （MyBatis-Plus 实体 -> Oracle DDL，含公共审计/租户/乐观锁列）
-- 日期     : 2026-08-25
-- @author  : ydsz-team
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 1. 规则定义主表
-- ============================================================================

-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (Oracle 12.2+ / 19c)
--   - 类型映射: JSON→CLOB+CHECK(IS JSON) / TINYINT(1)→NUMBER(1) / INT→NUMBER(10)
--       / BIGINT→NUMBER(19) / DATETIME→TIMESTAMP / BOOLEAN→NUMBER(1)
--   - VARCHAR2 采用 CHAR 语义 VARCHAR2(n CHAR), 字符集建议 AL32UTF8
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾生成, 以 / 提交)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY (12c+)
--   - 索引/约束名按 schema 级唯一性命名 (Oracle 12.2+ 标识符 ≤128 字节)
--   - 原 MySQL 前缀索引 path(255) → SUBSTR(path,1,255) 函数索引
--   - 原 MySQL FULLTEXT 索引 → 普通复合索引 (全文检索建议由 ES/应用层承担)
--   - 执行方式: sqlplus / SQLcl 执行本脚本 (触发器以 / 提交)
-- ============================================================================


CREATE TABLE ydsz_rule_def (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    rule_name                VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    category_path            VARCHAR2(255 CHAR)       DEFAULT NULL,
    owner                    VARCHAR2(64 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    condition_expression     CLOB                    ,
    severity_expression      CLOB                    ,
    default_severity         VARCHAR2(32 CHAR)        DEFAULT NULL,
    title_template           VARCHAR2(512 CHAR)       DEFAULT NULL,
    description_template     VARCHAR2(512 CHAR)       DEFAULT NULL,
    priority                 NUMBER(10)               NOT NULL DEFAULT 100,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    scope                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    mutex_group              VARCHAR2(128 CHAR)       DEFAULT NULL,
    drilldown_available      NUMBER(1)                NOT NULL DEFAULT 0,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    effective_from           TIMESTAMP                DEFAULT NULL,
    effective_to             TIMESTAMP                DEFAULT NULL,
    reviewed_by              VARCHAR2(64 CHAR)        DEFAULT NULL,
    reviewed_at              TIMESTAMP                DEFAULT NULL,
    review_comment           VARCHAR2(512 CHAR)       DEFAULT NULL,
    canary_ratio             NUMBER(5,4)              DEFAULT NULL,
    canary_conditions        CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_def_canary_conditions CHECK (canary_conditions IS JSON),
    canary_condition_expression CLOB                    ,
    canary_severity_expression CLOB                    ,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_def PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_def_rule_code UNIQUE (rule_code, tenant_id)
);

COMMENT ON TABLE ydsz_rule_def IS 'LiteRule 规则定义主表';
COMMENT ON COLUMN ydsz_rule_def.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_def.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_def.rule_code IS '规则编码，业务唯一';
COMMENT ON COLUMN ydsz_rule_def.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_rule_def.category IS '规则分类编码（一级分类标识）';
COMMENT ON COLUMN ydsz_rule_def.category_path IS '分类路径（/ 分隔的多级分类，如 finance/credit/loan）';
COMMENT ON COLUMN ydsz_rule_def.owner IS '责任人（规则负责人工号/用户名）';
COMMENT ON COLUMN ydsz_rule_def.description IS '规则描述';
COMMENT ON COLUMN ydsz_rule_def.condition_expression IS '条件表达式（LiteExpr 语法）';
COMMENT ON COLUMN ydsz_rule_def.severity_expression IS '严重度表达式，可选';
COMMENT ON COLUMN ydsz_rule_def.default_severity IS '默认严重级别';
COMMENT ON COLUMN ydsz_rule_def.title_template IS '告警标题模板';
COMMENT ON COLUMN ydsz_rule_def.description_template IS '告警描述模板';
COMMENT ON COLUMN ydsz_rule_def.priority IS '优先级，数值越小优先级越高';
COMMENT ON COLUMN ydsz_rule_def.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_def.scope IS '适用范围';
COMMENT ON COLUMN ydsz_rule_def.mutex_group IS '互斥组名称（同组内首个命中后跳过其余规则；NULL 表示无互斥组）';
COMMENT ON COLUMN ydsz_rule_def.drilldown_available IS '是否支持下钻查看详情（1=支持，0=不支持）';
COMMENT ON COLUMN ydsz_rule_def.version IS '乐观锁版本号（并发更新规则时防止覆盖）';
COMMENT ON COLUMN ydsz_rule_def.status IS '生命周期状态（DRAFT/PUBLISHED/DISABLED）';
COMMENT ON COLUMN ydsz_rule_def.effective_from IS '生效时间（NULL 表示立即生效）';
COMMENT ON COLUMN ydsz_rule_def.effective_to IS '失效时间（NULL 表示永不过期）';
COMMENT ON COLUMN ydsz_rule_def.reviewed_by IS '审核人';
COMMENT ON COLUMN ydsz_rule_def.reviewed_at IS '审核时间';
COMMENT ON COLUMN ydsz_rule_def.review_comment IS '审核意见';
COMMENT ON COLUMN ydsz_rule_def.canary_ratio IS '灰度比例（0.0~1.0，0 表示不启用灰度）';
COMMENT ON COLUMN ydsz_rule_def.canary_conditions IS '灰度条件表达式列表（JSON 数组）';
COMMENT ON COLUMN ydsz_rule_def.canary_condition_expression IS '灰度候选版本条件表达式';
COMMENT ON COLUMN ydsz_rule_def.canary_severity_expression IS '灰度候选版本严重度表达式';
COMMENT ON COLUMN ydsz_rule_def.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_def.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_def.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_def.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_def.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_def.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_def_category ON ydsz_rule_def (category);
CREATE INDEX idx_ydsz_rule_def_status ON ydsz_rule_def (status);
CREATE INDEX idx_ydsz_rule_def_tenant_deleted ON ydsz_rule_def (tenant_id, deleted);

CREATE TABLE ydsz_rule_variable_def (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    var_name                 VARCHAR2(128 CHAR)       NOT NULL,
    var_type                 VARCHAR2(32 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    sample_value             CLOB                    ,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    required                 NUMBER(1)                NOT NULL DEFAULT 0,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_variable_def PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_variable_def_var_name UNIQUE (var_name, tenant_id)
);

COMMENT ON TABLE ydsz_rule_variable_def IS '规则变量定义表';
COMMENT ON COLUMN ydsz_rule_variable_def.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_variable_def.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_variable_def.var_name IS '变量名（如 cpi / budgetAmount / evmRedCount）';
COMMENT ON COLUMN ydsz_rule_variable_def.var_type IS '变量类型（Number / String 等）';
COMMENT ON COLUMN ydsz_rule_variable_def.description IS '变量描述（中文，供前端编辑器提示）';
COMMENT ON COLUMN ydsz_rule_variable_def.sample_value IS '示例值（存储为字符串，用于前端编辑器预览和 dryRun 默认 facts）';
COMMENT ON COLUMN ydsz_rule_variable_def.category IS '变量来源类别（EVM / PROJECT / FINANCE / BENCH 等）';
COMMENT ON COLUMN ydsz_rule_variable_def.required IS '是否必填（1=必填，0=可选）';
COMMENT ON COLUMN ydsz_rule_variable_def.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_variable_def.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_variable_def.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_variable_def.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_variable_def.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_variable_def.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_variable_def.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_variable_def.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_variable_def_category ON ydsz_rule_variable_def (category);
CREATE INDEX idx_ydsz_rule_variable_def_tenant_deleted ON ydsz_rule_variable_def (tenant_id, deleted);

CREATE TABLE ydsz_rule_template (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    template_code            VARCHAR2(64 CHAR)        NOT NULL,
    template_name            VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    condition_expression     CLOB                    ,
    severity_expression      CLOB                    ,
    default_severity         VARCHAR2(32 CHAR)        DEFAULT NULL,
    title_template           VARCHAR2(512 CHAR)       DEFAULT NULL,
    description_template     VARCHAR2(512 CHAR)       DEFAULT NULL,
    priority                 NUMBER(10)               DEFAULT NULL,
    scope                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    industry                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    tags                     VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_template PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_template_template_code UNIQUE (template_code, tenant_id)
);

COMMENT ON TABLE ydsz_rule_template IS 'LiteRule 规则模板表';
COMMENT ON COLUMN ydsz_rule_template.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_template.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_template.template_code IS '模板编码，业务唯一';
COMMENT ON COLUMN ydsz_rule_template.template_name IS '模板名称';
COMMENT ON COLUMN ydsz_rule_template.category IS '分类编码';
COMMENT ON COLUMN ydsz_rule_template.description IS '模板描述';
COMMENT ON COLUMN ydsz_rule_template.condition_expression IS '预置条件表达式';
COMMENT ON COLUMN ydsz_rule_template.severity_expression IS '预置严重度表达式';
COMMENT ON COLUMN ydsz_rule_template.default_severity IS '默认严重级别';
COMMENT ON COLUMN ydsz_rule_template.title_template IS '告警标题模板';
COMMENT ON COLUMN ydsz_rule_template.description_template IS '告警描述模板';
COMMENT ON COLUMN ydsz_rule_template.priority IS '优先级，数值越小优先级越高';
COMMENT ON COLUMN ydsz_rule_template.scope IS '适用范围';
COMMENT ON COLUMN ydsz_rule_template.industry IS '所属行业';
COMMENT ON COLUMN ydsz_rule_template.tags IS '标签，逗号分隔';
COMMENT ON COLUMN ydsz_rule_template.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_template.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_template.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_template.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_template.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_template.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_template_category ON ydsz_rule_template (category);
CREATE INDEX idx_ydsz_rule_template_tenant_deleted ON ydsz_rule_template (tenant_id, deleted);

CREATE TABLE ydsz_rule_script (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    rule_name                VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    script                   CLOB                    ,
    default_severity         VARCHAR2(32 CHAR)        DEFAULT NULL,
    sandbox_enabled          NUMBER(1)                NOT NULL DEFAULT 1,
    priority                 NUMBER(10)               DEFAULT NULL,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    scope                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_script PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_script IS '规则脚本表';
COMMENT ON COLUMN ydsz_rule_script.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_script.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_script.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_script.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_rule_script.category IS '规则分类';
COMMENT ON COLUMN ydsz_rule_script.description IS '规则描述';
COMMENT ON COLUMN ydsz_rule_script.script IS 'Groovy 脚本源码（运行在沙箱中）';
COMMENT ON COLUMN ydsz_rule_script.default_severity IS '默认严重级别（INFO/WARN/ERROR/CRITICAL）';
COMMENT ON COLUMN ydsz_rule_script.sandbox_enabled IS '是否启用沙箱（1=启用安全限制，0=关闭）';
COMMENT ON COLUMN ydsz_rule_script.priority IS '优先级';
COMMENT ON COLUMN ydsz_rule_script.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_script.scope IS '适用范围';
COMMENT ON COLUMN ydsz_rule_script.version IS '版本号';
COMMENT ON COLUMN ydsz_rule_script.provider_trace_id IS '供应商侧追踪 ID';
COMMENT ON COLUMN ydsz_rule_script.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_script.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_script.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_script.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_script.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_script.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_script.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_script_rule_code ON ydsz_rule_script (rule_code);
CREATE INDEX idx_ydsz_rule_script_tenant_deleted ON ydsz_rule_script (tenant_id, deleted);

CREATE TABLE ydsz_rule_decision_table (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    table_code               VARCHAR2(64 CHAR)        NOT NULL,
    table_name               VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    condition_columns        CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_decision_table_condition_columns CHECK (condition_columns IS JSON),
    action_columns           CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_decision_table_action_columns CHECK (action_columns IS JSON),
    rows                     CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_decision_table_rows CHECK (rows IS JSON),
    default_actions          CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_decision_table_default_actions CHECK (default_actions IS JSON),
    hit_policy               VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'FIRST',
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    priority                 NUMBER(10)               DEFAULT NULL,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_decision_table PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_decision_table_table_code UNIQUE (table_code, tenant_id)
);

COMMENT ON TABLE ydsz_rule_decision_table IS '决策表实体表';
COMMENT ON COLUMN ydsz_rule_decision_table.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_decision_table.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_decision_table.table_code IS '决策表编码';
COMMENT ON COLUMN ydsz_rule_decision_table.table_name IS '决策表名称';
COMMENT ON COLUMN ydsz_rule_decision_table.description IS '描述';
COMMENT ON COLUMN ydsz_rule_decision_table.category IS '类别';
COMMENT ON COLUMN ydsz_rule_decision_table.condition_columns IS '条件列定义（JSON 数组）';
COMMENT ON COLUMN ydsz_rule_decision_table.action_columns IS '动作列定义（JSON 数组）';
COMMENT ON COLUMN ydsz_rule_decision_table.rows IS '决策行（JSON 数组）';
COMMENT ON COLUMN ydsz_rule_decision_table.default_actions IS '默认动作（JSON 对象）';
COMMENT ON COLUMN ydsz_rule_decision_table.hit_policy IS '命中策略（UNIQUE/FIRST/PRIORITY/COLLECT/ANY，默认 FIRST）';
COMMENT ON COLUMN ydsz_rule_decision_table.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_decision_table.priority IS '优先级';
COMMENT ON COLUMN ydsz_rule_decision_table.version IS '版本';
COMMENT ON COLUMN ydsz_rule_decision_table.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_decision_table.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_decision_table.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_decision_table.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_decision_table.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_decision_table.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_decision_table.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_decision_table_category ON ydsz_rule_decision_table (category);
CREATE INDEX idx_ydsz_rule_decision_table_tenant_deleted ON ydsz_rule_decision_table (tenant_id, deleted);

CREATE TABLE ydsz_rule_decision_tree (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    rule_name                VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    root_node                CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_decision_tree_root_node CHECK (root_node IS JSON),
    priority                 NUMBER(10)               DEFAULT NULL,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    scope                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_decision_tree PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_decision_tree IS '规则决策树表';
COMMENT ON COLUMN ydsz_rule_decision_tree.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_decision_tree.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_decision_tree.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_decision_tree.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_rule_decision_tree.category IS '规则分类';
COMMENT ON COLUMN ydsz_rule_decision_tree.description IS '规则描述';
COMMENT ON COLUMN ydsz_rule_decision_tree.root_node IS '根节点 JSON（嵌套结构，节点类型 CONDITION/ACTION/DEFAULT）';
COMMENT ON COLUMN ydsz_rule_decision_tree.priority IS '优先级（数字越小越优先）';
COMMENT ON COLUMN ydsz_rule_decision_tree.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_decision_tree.scope IS '适用范围';
COMMENT ON COLUMN ydsz_rule_decision_tree.version IS '版本号';
COMMENT ON COLUMN ydsz_rule_decision_tree.provider_trace_id IS '供应商侧追踪 ID';
COMMENT ON COLUMN ydsz_rule_decision_tree.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_decision_tree.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_decision_tree.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_decision_tree.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_decision_tree.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_decision_tree.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_decision_tree.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_decision_tree_rule_code ON ydsz_rule_decision_tree (rule_code);
CREATE INDEX idx_ydsz_rule_decision_tree_tenant_deleted ON ydsz_rule_decision_tree (tenant_id, deleted);

CREATE TABLE ydsz_rule_scorecard (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    rule_name                VARCHAR2(128 CHAR)       NOT NULL,
    category                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    base_score               NUMBER(20,6)             NOT NULL DEFAULT 100,
    red_threshold            NUMBER(20,6)             DEFAULT NULL,
    yellow_threshold         NUMBER(20,6)             DEFAULT NULL,
    factors                  CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_scorecard_factors CHECK (factors IS JSON),
    priority                 NUMBER(10)               DEFAULT NULL,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    scope                    VARCHAR2(128 CHAR)       DEFAULT NULL,
    version                  NUMBER(10)               NOT NULL DEFAULT 1,
    provider_trace_id        VARCHAR2(64 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_scorecard PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_scorecard IS '规则评分卡表';
COMMENT ON COLUMN ydsz_rule_scorecard.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_scorecard.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_scorecard.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_scorecard.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_rule_scorecard.category IS '规则分类（RISK / QUALITY / PROFIT 等）';
COMMENT ON COLUMN ydsz_rule_scorecard.description IS '规则描述';
COMMENT ON COLUMN ydsz_rule_scorecard.base_score IS '基础分（满分，默认 100）';
COMMENT ON COLUMN ydsz_rule_scorecard.red_threshold IS '红灯阈值（≤ 触发红灯）';
COMMENT ON COLUMN ydsz_rule_scorecard.yellow_threshold IS '黄灯阈值（≤ 触发黄灯）';
COMMENT ON COLUMN ydsz_rule_scorecard.factors IS '评分因子 JSON：[{conditionExpression, score, description}]';
COMMENT ON COLUMN ydsz_rule_scorecard.priority IS '优先级（数字越小越优先）';
COMMENT ON COLUMN ydsz_rule_scorecard.enabled IS '是否启用（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_scorecard.scope IS '适用范围（如 ALL / PROJECT_TYPE:CONSTRUCTION）';
COMMENT ON COLUMN ydsz_rule_scorecard.version IS '版本号';
COMMENT ON COLUMN ydsz_rule_scorecard.provider_trace_id IS '供应商侧追踪 ID';
COMMENT ON COLUMN ydsz_rule_scorecard.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_scorecard.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_scorecard.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_scorecard.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_scorecard.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_scorecard.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_scorecard.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_scorecard_rule_code ON ydsz_rule_scorecard (rule_code);
CREATE INDEX idx_ydsz_rule_scorecard_category ON ydsz_rule_scorecard (category);
CREATE INDEX idx_ydsz_rule_scorecard_tenant_deleted ON ydsz_rule_scorecard (tenant_id, deleted);

CREATE TABLE ydsz_rule_chain_graph (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    name                     VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    scenario                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    graph_version            NUMBER(10)               NOT NULL DEFAULT 1,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    content_json             CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_chain_graph_content_json CHECK (content_json IS JSON),
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_chain_graph PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_chain_graph_rule_code UNIQUE (rule_code, tenant_id)
);

COMMENT ON TABLE ydsz_rule_chain_graph IS '规则链画布表';
COMMENT ON COLUMN ydsz_rule_chain_graph.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_chain_graph.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_chain_graph.rule_code IS '关联规则编码（一对一）';
COMMENT ON COLUMN ydsz_rule_chain_graph.name IS '画布名称';
COMMENT ON COLUMN ydsz_rule_chain_graph.description IS '画布描述';
COMMENT ON COLUMN ydsz_rule_chain_graph.scenario IS '适用场景（与 RuleContext.scenario 对应）';
COMMENT ON COLUMN ydsz_rule_chain_graph.graph_version IS '画布版本号（独立递增）';
COMMENT ON COLUMN ydsz_rule_chain_graph.status IS '画布状态（DRAFT/PUBLISHED/ARCHIVED）';
COMMENT ON COLUMN ydsz_rule_chain_graph.content_json IS '画布内容 JSON（包含 nodes/edges/viewport/metadata）';
COMMENT ON COLUMN ydsz_rule_chain_graph.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_chain_graph.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_chain_graph.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_chain_graph.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_chain_graph.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_chain_graph.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_chain_graph_tenant_deleted ON ydsz_rule_chain_graph (tenant_id, deleted);

CREATE TABLE ydsz_rule_dependency (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    depends_on_rule_code     VARCHAR2(64 CHAR)        NOT NULL,
    dependency_type          VARCHAR2(32 CHAR)        NOT NULL,
    cascade_on_disable       NUMBER(1)                NOT NULL DEFAULT 0,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_dependency PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_dependency_rule_dep UNIQUE (rule_code, depends_on_rule_code)
);

COMMENT ON TABLE ydsz_rule_dependency IS '规则依赖关系表';
COMMENT ON COLUMN ydsz_rule_dependency.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_dependency.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_dependency.rule_code IS '主规则编码（依赖方）';
COMMENT ON COLUMN ydsz_rule_dependency.depends_on_rule_code IS '被依赖的规则编码';
COMMENT ON COLUMN ydsz_rule_dependency.dependency_type IS '依赖类型（EXECUTE/READ_RESULT/SOFT）';
COMMENT ON COLUMN ydsz_rule_dependency.cascade_on_disable IS '被依赖规则被禁用时是否级联禁用本规则（1=级联，0=不级联）';
COMMENT ON COLUMN ydsz_rule_dependency.description IS '依赖说明';
COMMENT ON COLUMN ydsz_rule_dependency.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_dependency.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_dependency.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_dependency.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_dependency.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_dependency.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_dependency.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_dependency_depends_on_rule_code ON ydsz_rule_dependency (depends_on_rule_code);
CREATE INDEX idx_ydsz_rule_dependency_tenant_deleted ON ydsz_rule_dependency (tenant_id, deleted);

CREATE TABLE ydsz_rule_pack (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    pack_code                VARCHAR2(64 CHAR)        NOT NULL,
    pack_version             VARCHAR2(32 CHAR)        NOT NULL,
    pack_name                VARCHAR2(128 CHAR)       NOT NULL,
    industry                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    tags                     CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_pack_tags CHECK (tags IS JSON),
    rule_codes               CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_pack_rule_codes CHECK (rule_codes IS JSON),
    rule_snapshots           CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_pack_rule_snapshots CHECK (rule_snapshots IS JSON),
    previous_version         VARCHAR2(32 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    author                   VARCHAR2(64 CHAR)        DEFAULT NULL,
    download_count           NUMBER(19)               NOT NULL DEFAULT 0,
    rating                   NUMBER(20,6)             DEFAULT NULL,
    enabled                  NUMBER(1)                NOT NULL DEFAULT 1,
    official                 NUMBER(1)                NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_pack PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_pack_pack_code UNIQUE (pack_code, pack_version)
);

COMMENT ON TABLE ydsz_rule_pack IS '规则集（知识包）表';
COMMENT ON COLUMN ydsz_rule_pack.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_pack.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_pack.pack_code IS '规则集编码（全局唯一，用于版本间关联）';
COMMENT ON COLUMN ydsz_rule_pack.pack_version IS '规则集版本号（如 1.0.0）';
COMMENT ON COLUMN ydsz_rule_pack.pack_name IS '规则集名称';
COMMENT ON COLUMN ydsz_rule_pack.industry IS '所属行业（FINANCE / MANUFACTURING / HEALTHCARE）';
COMMENT ON COLUMN ydsz_rule_pack.tags IS '标签（JSON 数组，如 ["风控", "审批"]）';
COMMENT ON COLUMN ydsz_rule_pack.rule_codes IS '包含的规则编码列表（JSON 数组）';
COMMENT ON COLUMN ydsz_rule_pack.rule_snapshots IS '规则定义快照（发布时固化的 List<RuleDefinition> JSON，保证版本内容可复现）';
COMMENT ON COLUMN ydsz_rule_pack.previous_version IS '升级来源版本号（回滚/升级时记录前一版本，便于审计）';
COMMENT ON COLUMN ydsz_rule_pack.description IS '规则集描述';
COMMENT ON COLUMN ydsz_rule_pack.author IS '作者（创建人用户名）';
COMMENT ON COLUMN ydsz_rule_pack.download_count IS '下载次数（安装时 +1）';
COMMENT ON COLUMN ydsz_rule_pack.rating IS '评分（0-5，保留 1 位小数）';
COMMENT ON COLUMN ydsz_rule_pack.enabled IS '是否启用（1=可用，0=已下架）';
COMMENT ON COLUMN ydsz_rule_pack.official IS '是否官方认证规则集（1=官方发布，0=社区贡献）';
COMMENT ON COLUMN ydsz_rule_pack.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_pack.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_pack.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_pack.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_pack.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_pack.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_pack.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_pack_pack_code ON ydsz_rule_pack (pack_code);
CREATE INDEX idx_ydsz_rule_pack_industry ON ydsz_rule_pack (industry);
CREATE INDEX idx_ydsz_rule_pack_tenant_deleted ON ydsz_rule_pack (tenant_id, deleted);

CREATE TABLE ydsz_rule_pack_install (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    installed_by             VARCHAR2(64 CHAR)        DEFAULT NULL,
    installed_at             TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    error_message            CLOB                    ,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_pack_install PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_pack_install IS '规则包安装记录表';
COMMENT ON COLUMN ydsz_rule_pack_install.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_pack_install.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_pack_install.installed_by IS '安装操作人 ID';
COMMENT ON COLUMN ydsz_rule_pack_install.installed_at IS '安装时间';
COMMENT ON COLUMN ydsz_rule_pack_install.status IS '安装状态（INSTALLING/INSTALLED/FAILED/UNINSTALLING/UNINSTALLED）';
COMMENT ON COLUMN ydsz_rule_pack_install.error_message IS '失败原因（status=FAILED 时记录异常信息）';
COMMENT ON COLUMN ydsz_rule_pack_install.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_pack_install.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_pack_install.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_pack_install.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_pack_install.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_pack_install.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_pack_install_status ON ydsz_rule_pack_install (status);
CREATE INDEX idx_ydsz_rule_pack_install_installed_at ON ydsz_rule_pack_install (installed_at);
CREATE INDEX idx_ydsz_rule_pack_install_tenant_deleted ON ydsz_rule_pack_install (tenant_id, deleted);

CREATE TABLE ydsz_rule_ab_policy (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    auto_rollback_enabled    NUMBER(1)                NOT NULL DEFAULT 0,
    rollback_action          VARCHAR2(32 CHAR)        DEFAULT NULL,
    error_rate_threshold     NUMBER(20,6)             DEFAULT NULL,
    min_sample_size          NUMBER(10)               DEFAULT NULL,
    check_window_minutes     NUMBER(10)               DEFAULT NULL,
    notify_channels          VARCHAR2(255 CHAR)       DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    last_evaluated_at        TIMESTAMP                DEFAULT NULL,
    last_rollback_at         TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_ab_policy PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_ab_policy_rule_code UNIQUE (rule_code, tenant_id)
);

COMMENT ON TABLE ydsz_rule_ab_policy IS 'AB Test 自动回滚策略表';
COMMENT ON COLUMN ydsz_rule_ab_policy.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_ab_policy.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_ab_policy.rule_code IS '关联规则编码（一对一）';
COMMENT ON COLUMN ydsz_rule_ab_policy.auto_rollback_enabled IS '是否启用自动回滚（1=启用，0=停用）';
COMMENT ON COLUMN ydsz_rule_ab_policy.rollback_action IS '回滚动作（AUTO 自动回滚 / NOTIFY 仅通知 Owner）';
COMMENT ON COLUMN ydsz_rule_ab_policy.error_rate_threshold IS 'canary 桶错误率阈值（0~1.0）';
COMMENT ON COLUMN ydsz_rule_ab_policy.min_sample_size IS '最小样本数';
COMMENT ON COLUMN ydsz_rule_ab_policy.check_window_minutes IS '监控窗口（分钟）';
COMMENT ON COLUMN ydsz_rule_ab_policy.notify_channels IS '通知渠道（INAPP / EMAIL / SMS / WEBHOOK，逗号分隔）';
COMMENT ON COLUMN ydsz_rule_ab_policy.description IS '描述';
COMMENT ON COLUMN ydsz_rule_ab_policy.last_evaluated_at IS '最近一次评估时间';
COMMENT ON COLUMN ydsz_rule_ab_policy.last_rollback_at IS '最近一次回滚时间';
COMMENT ON COLUMN ydsz_rule_ab_policy.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_ab_policy.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_ab_policy.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_ab_policy.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_ab_policy.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_ab_policy.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_ab_policy.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_ab_policy_tenant_deleted ON ydsz_rule_ab_policy (tenant_id, deleted);

CREATE TABLE ydsz_rule_canary_bucket (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    bucket_type              VARCHAR2(32 CHAR)        NOT NULL,
    bucket_count             NUMBER(19)               NOT NULL DEFAULT 0,
    stat_date                DATE                     NOT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_canary_bucket PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_rule_canary_bucket_rule_bucket_date UNIQUE (rule_code, bucket_type, stat_date)
);

COMMENT ON TABLE ydsz_rule_canary_bucket IS '规则灰度分桶统计表';
COMMENT ON COLUMN ydsz_rule_canary_bucket.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_canary_bucket.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_canary_bucket.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_canary_bucket.bucket_type IS '桶类型（PRIMARY/CANARY）';
COMMENT ON COLUMN ydsz_rule_canary_bucket.bucket_count IS '桶命中次数';
COMMENT ON COLUMN ydsz_rule_canary_bucket.stat_date IS '统计日期';
COMMENT ON COLUMN ydsz_rule_canary_bucket.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_canary_bucket.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_canary_bucket.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_canary_bucket.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_rule_canary_bucket.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_canary_bucket.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_canary_bucket.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_canary_bucket_stat_date ON ydsz_rule_canary_bucket (stat_date);
CREATE INDEX idx_ydsz_rule_canary_bucket_tenant_deleted ON ydsz_rule_canary_bucket (tenant_id, deleted);

CREATE TABLE ydsz_rule_ab_rollback (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    trigger_reason           VARCHAR2(32 CHAR)        NOT NULL,
    error_rate               NUMBER(20,6)             DEFAULT NULL,
    sample_size              NUMBER(19)               DEFAULT NULL,
    from_canary              NUMBER(1)                NOT NULL DEFAULT 0,
    operator                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    notify_status            VARCHAR2(32 CHAR)        DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_ab_rollback PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_ab_rollback IS 'AB Test 回滚历史表';
COMMENT ON COLUMN ydsz_rule_ab_rollback.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.rule_code IS '规则编码（关联 ydsz_rule_def.rule_code）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.trigger_reason IS '触发原因（ERROR_RATE/MANUAL/OWNER_REQUEST）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.error_rate IS '回滚时的错误率（triggerReason=ERROR_RATE 时记录）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.sample_size IS '回滚时的样本量（参与 AB Test 的事件总数）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.from_canary IS '是否已从 canary 切换回主版本（1=已回滚，0=仅通知未回滚）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.operator IS '操作人 ID（自动回滚时为 SYSTEM）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.notify_status IS '通知状态（PENDING/SENT/FAILED，回滚后通知规则责任人）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.status IS '状态标识';
COMMENT ON COLUMN ydsz_rule_ab_rollback.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_rule_ab_rollback.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_rule_ab_rollback.created_at IS '回滚时间';
COMMENT ON COLUMN ydsz_rule_ab_rollback.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_rule_ab_rollback.created_by IS '创建人';
COMMENT ON COLUMN ydsz_rule_ab_rollback.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_rule_ab_rollback_rule_code ON ydsz_rule_ab_rollback (rule_code);
CREATE INDEX idx_ydsz_rule_ab_rollback_created_at ON ydsz_rule_ab_rollback (created_at);
CREATE INDEX idx_ydsz_rule_ab_rollback_tenant_deleted ON ydsz_rule_ab_rollback (tenant_id, deleted);

CREATE TABLE ydsz_rule_version_history (
    id                       VARCHAR2(32 CHAR)       ,
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    version                  NUMBER(10)               NOT NULL,
    definition_json          CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_version_history_definition_json CHECK (definition_json IS JSON),
    change_desc              VARCHAR2(512 CHAR)       DEFAULT NULL,
    operator                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_rule_version_history PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_version_history IS 'LiteRule 规则版本历史表';
COMMENT ON COLUMN ydsz_rule_version_history.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_version_history.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_version_history.version IS '版本号';
COMMENT ON COLUMN ydsz_rule_version_history.definition_json IS '该版本的规则定义 JSON 快照';
COMMENT ON COLUMN ydsz_rule_version_history.change_desc IS '变更说明';
COMMENT ON COLUMN ydsz_rule_version_history.operator IS '操作人';

CREATE INDEX idx_ydsz_rule_version_history_rule_version ON ydsz_rule_version_history (rule_code, version);

CREATE TABLE ydsz_rule_execution_trace (
    id                       VARCHAR2(32 CHAR)       ,
    trace_id                 VARCHAR2(64 CHAR)        NOT NULL,
    rule_code                VARCHAR2(64 CHAR)        NOT NULL,
    rule_name                VARCHAR2(128 CHAR)       DEFAULT NULL,
    scenario                 VARCHAR2(64 CHAR)        DEFAULT NULL,
    triggered                NUMBER(1)                DEFAULT NULL,
    severity                 VARCHAR2(32 CHAR)        DEFAULT NULL,
    condition_result         CLOB                    ,
    elapsed_ms               NUMBER(19)               DEFAULT NULL,
    facts_snapshot           CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_execution_trace_facts_snapshot CHECK (facts_snapshot IS JSON),
    result_snapshot          CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_rule_execution_trace_result_snapshot CHECK (result_snapshot IS JSON),
    error_message            CLOB                    ,
    CONSTRAINT pk_ydsz_rule_execution_trace PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_rule_execution_trace IS '规则执行链路追踪表';
COMMENT ON COLUMN ydsz_rule_execution_trace.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_rule_execution_trace.trace_id IS '追踪 ID（同一批次评估共享）';
COMMENT ON COLUMN ydsz_rule_execution_trace.rule_code IS '规则编码';
COMMENT ON COLUMN ydsz_rule_execution_trace.rule_name IS '规则名称';
COMMENT ON COLUMN ydsz_rule_execution_trace.scenario IS '业务场景';
COMMENT ON COLUMN ydsz_rule_execution_trace.triggered IS '是否触发（1=触发，0=未触发）';
COMMENT ON COLUMN ydsz_rule_execution_trace.severity IS '触发严重度';
COMMENT ON COLUMN ydsz_rule_execution_trace.condition_result IS '条件表达式求值结果描述';
COMMENT ON COLUMN ydsz_rule_execution_trace.elapsed_ms IS '执行耗时（毫秒）';
COMMENT ON COLUMN ydsz_rule_execution_trace.facts_snapshot IS '事实数据快照（JSON 对象）';
COMMENT ON COLUMN ydsz_rule_execution_trace.result_snapshot IS '结果快照（JSON 对象）';
COMMENT ON COLUMN ydsz_rule_execution_trace.error_message IS '错误信息';

CREATE INDEX idx_ydsz_rule_execution_trace_trace_id ON ydsz_rule_execution_trace (trace_id);
CREATE INDEX idx_ydsz_rule_execution_trace_rule_code ON ydsz_rule_execution_trace (rule_code);
CREATE INDEX idx_ydsz_rule_execution_trace_scenario ON ydsz_rule_execution_trace (scenario);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (Oracle)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_def_updated_at
BEFORE UPDATE ON ydsz_rule_def
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_variable_def_updated_at
BEFORE UPDATE ON ydsz_rule_variable_def
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_template_updated_at
BEFORE UPDATE ON ydsz_rule_template
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_script_updated_at
BEFORE UPDATE ON ydsz_rule_script
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_decision_table_updated_at
BEFORE UPDATE ON ydsz_rule_decision_table
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_decision_tree_updated_at
BEFORE UPDATE ON ydsz_rule_decision_tree
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_scorecard_updated_at
BEFORE UPDATE ON ydsz_rule_scorecard
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_chain_graph_updated_at
BEFORE UPDATE ON ydsz_rule_chain_graph
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_dependency_updated_at
BEFORE UPDATE ON ydsz_rule_dependency
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_pack_updated_at
BEFORE UPDATE ON ydsz_rule_pack
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_pack_install_updated_at
BEFORE UPDATE ON ydsz_rule_pack_install
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_ab_policy_updated_at
BEFORE UPDATE ON ydsz_rule_ab_policy
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_canary_bucket_updated_at
BEFORE UPDATE ON ydsz_rule_canary_bucket
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_rule_ab_rollback_updated_at
BEFORE UPDATE ON ydsz_rule_ab_rollback
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
