-- ----------------------------------------------------------------------------
-- 模块名   : ydsz-system（系统管理模块）
-- 说明     : 基于 ydsz-system-infra 实体类整理的完整建表脚本
--            （租户/套餐、字典、配置、应用、变量、实体版本）
-- 日期     : 2026-08-25
-- @author  : ydsz-team
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 租户 / 套餐
-- ============================================================================

-- 租户主表（SaaS 多租户核心元数据）
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (Oracle 12.2+ / 19c)
--   - 类型映射: JSON→CLOB+CHECK(IS JSON) / TINYINT(1)→NUMBER(1) / INT→NUMBER(10)
--       / BIGINT→NUMBER(19) / DATETIME→TIMESTAMP / BOOLEAN→NUMBER(1)
--   - VARCHAR2 采用 CHAR 语义 VARCHAR2(n CHAR), 字符集建议 AL32UTF8
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾生成, 以 / 提交)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY (12c+)
--   - 索引/约束名按 schema 级唯一性命名 (Oracle 12.2+ 标识符 ≤128 字节)
--   - 原 MySQL 前缀索引 path(255) → SUBSTR(path,1,255) 函数索引
--   - 原 MySQL FULLTEXT 索引 → 普通复合索引 (全文检索建议由 ES/应用层承担)
--   - 执行方式: sqlplus / SQLcl 执行本脚本 (触发器以 / 提交)
-- ============================================================================


CREATE TABLE ydsz_tenant (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    tenant_code              VARCHAR2(64 CHAR)        NOT NULL,
    tenant_name              VARCHAR2(128 CHAR)       NOT NULL,
    contact_name             VARCHAR2(64 CHAR)        DEFAULT NULL,
    contact_phone            VARCHAR2(32 CHAR)        DEFAULT NULL,
    contact_email            VARCHAR2(128 CHAR)       DEFAULT NULL,
    plan_id                  VARCHAR2(32 CHAR)        DEFAULT NULL,
    expire_at                TIMESTAMP                DEFAULT NULL,
    datasource_key           VARCHAR2(64 CHAR)        DEFAULT NULL,
    remark                   VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_tenant PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_tenant_tenant_code UNIQUE (tenant_code)
);

COMMENT ON TABLE ydsz_tenant IS '租户主表';
COMMENT ON COLUMN ydsz_tenant.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_tenant.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_tenant.tenant_code IS '租户编码（唯一业务标识，租户登录/调用使用）';
COMMENT ON COLUMN ydsz_tenant.tenant_name IS '租户名称（展示用）';
COMMENT ON COLUMN ydsz_tenant.contact_name IS '联系人姓名';
COMMENT ON COLUMN ydsz_tenant.contact_phone IS '联系电话（脱敏返回）';
COMMENT ON COLUMN ydsz_tenant.contact_email IS '联系邮箱（脱敏返回）';
COMMENT ON COLUMN ydsz_tenant.plan_id IS '关联套餐 ID（ydsz_tenant_plan.id）';
COMMENT ON COLUMN ydsz_tenant.expire_at IS '订阅到期时间（到期后租户被自动锁定/降级）';
COMMENT ON COLUMN ydsz_tenant.datasource_key IS '独立数据源标识（ISOLATE_DB 模式下使用）';
COMMENT ON COLUMN ydsz_tenant.remark IS '备注';
COMMENT ON COLUMN ydsz_tenant.status IS '状态标识（ENABLED/DISABLED，启用状态值）';
COMMENT ON COLUMN ydsz_tenant.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_tenant.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_tenant.created_by IS '创建人';
COMMENT ON COLUMN ydsz_tenant.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_tenant.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_tenant.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_tenant_plan_id ON ydsz_tenant (plan_id);
CREATE INDEX idx_ydsz_tenant_tenant_deleted ON ydsz_tenant (tenant_id, deleted);

CREATE TABLE ydsz_tenant_plan (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    plan_code                VARCHAR2(64 CHAR)        NOT NULL,
    plan_name                VARCHAR2(128 CHAR)       NOT NULL,
    description              CLOB                     DEFAULT NULL,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    quota_json               CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_tenant_plan_quota_json CHECK (quota_json IS JSON),
    feature_json             CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_tenant_plan_feature_json CHECK (feature_json IS JSON),
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_tenant_plan PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_tenant_plan_plan_code UNIQUE (plan_code)
);

COMMENT ON TABLE ydsz_tenant_plan IS '租户套餐表';
COMMENT ON COLUMN ydsz_tenant_plan.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_tenant_plan.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_tenant_plan.plan_code IS '套餐编码（唯一标识，如 TRIAL/STANDARD/ENTERPRISE）';
COMMENT ON COLUMN ydsz_tenant_plan.plan_name IS '套餐名称（展示用，如「试用版」「企业版」）';
COMMENT ON COLUMN ydsz_tenant_plan.description IS '套餐描述（包含价格、功能清单、配额上限）';
COMMENT ON COLUMN ydsz_tenant_plan.sort_order IS '排序号（升序，影响前端套餐选择器顺序）';
COMMENT ON COLUMN ydsz_tenant_plan.quota_json IS '资源配额 JSON（如 {"maxUsers":50,"maxProjects":10,"storageGb":100}）';
COMMENT ON COLUMN ydsz_tenant_plan.feature_json IS '功能开关 JSON（如 {"workflow":true,"dataAnalytics":false}）';
COMMENT ON COLUMN ydsz_tenant_plan.status IS '状态标识';
COMMENT ON COLUMN ydsz_tenant_plan.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_tenant_plan.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_tenant_plan.created_by IS '创建人';
COMMENT ON COLUMN ydsz_tenant_plan.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_tenant_plan.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_tenant_plan.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_tenant_plan_tenant_deleted ON ydsz_tenant_plan (tenant_id, deleted);

CREATE TABLE ydsz_tenant_plan_menu (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    plan_id                  VARCHAR2(32 CHAR)        NOT NULL,
    menu_id                  VARCHAR2(64 CHAR)        NOT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_tenant_plan_menu PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_tenant_plan_menu_plan_menu UNIQUE (plan_id, menu_id)
);

COMMENT ON TABLE ydsz_tenant_plan_menu IS '租户套餐菜单关联表';
COMMENT ON COLUMN ydsz_tenant_plan_menu.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_tenant_plan_menu.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_tenant_plan_menu.plan_id IS '套餐 ID（ydsz_tenant_plan.id）';
COMMENT ON COLUMN ydsz_tenant_plan_menu.menu_id IS '菜单 ID（ydsz_menu.id 或权限码 ydsz:xxx）';
COMMENT ON COLUMN ydsz_tenant_plan_menu.status IS '状态标识';
COMMENT ON COLUMN ydsz_tenant_plan_menu.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_tenant_plan_menu.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_tenant_plan_menu.created_by IS '创建人';
COMMENT ON COLUMN ydsz_tenant_plan_menu.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_tenant_plan_menu.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_tenant_plan_menu.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_tenant_plan_menu_tenant_deleted ON ydsz_tenant_plan_menu (tenant_id, deleted);

CREATE TABLE ydsz_dict_type (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    type_code                VARCHAR2(64 CHAR)        NOT NULL,
    type_name                VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_dict_type PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_dict_type_type_code UNIQUE (type_code)
);

COMMENT ON TABLE ydsz_dict_type IS '字典类型表';
COMMENT ON COLUMN ydsz_dict_type.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_dict_type.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_dict_type.type_code IS '类型编码（唯一标识，用于业务引用）';
COMMENT ON COLUMN ydsz_dict_type.type_name IS '类型名称（展示用）';
COMMENT ON COLUMN ydsz_dict_type.description IS '类型描述';
COMMENT ON COLUMN ydsz_dict_type.status IS '状态标识';
COMMENT ON COLUMN ydsz_dict_type.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_dict_type.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_dict_type.created_by IS '创建人';
COMMENT ON COLUMN ydsz_dict_type.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_dict_type.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_dict_type.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_dict_type_tenant_deleted ON ydsz_dict_type (tenant_id, deleted);

CREATE TABLE ydsz_dict_item (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    type_code                VARCHAR2(64 CHAR)        NOT NULL,
    item_code                VARCHAR2(64 CHAR)        NOT NULL,
    item_value               VARCHAR2(128 CHAR)       NOT NULL,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    parent_id                VARCHAR2(32 CHAR)        DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    ext_json                 CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_dict_item_ext_json CHECK (ext_json IS JSON),
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_dict_item PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_dict_item_type_item_code UNIQUE (type_code, item_code)
);

COMMENT ON TABLE ydsz_dict_item IS '字典项表';
COMMENT ON COLUMN ydsz_dict_item.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_dict_item.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_dict_item.type_code IS '所属字典类型编码（逻辑外键 → ydsz_dict_type.type_code）';
COMMENT ON COLUMN ydsz_dict_item.item_code IS '字典项编码（同 typeCode 内唯一）';
COMMENT ON COLUMN ydsz_dict_item.item_value IS '字典项真实值（业务代码引用的枚举值，如 "PAID"）';
COMMENT ON COLUMN ydsz_dict_item.sort_order IS '展示排序序号（升序）';
COMMENT ON COLUMN ydsz_dict_item.parent_id IS '父级字典项 ID（支持树形字典，如行政区划）';
COMMENT ON COLUMN ydsz_dict_item.description IS '字典项描述';
COMMENT ON COLUMN ydsz_dict_item.ext_json IS '扩展属性 JSON（承载自定义属性，如色值、图标、URL 等）';
COMMENT ON COLUMN ydsz_dict_item.status IS '状态标识';
COMMENT ON COLUMN ydsz_dict_item.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_dict_item.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_dict_item.created_by IS '创建人';
COMMENT ON COLUMN ydsz_dict_item.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_dict_item.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_dict_item.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_dict_item_parent_id ON ydsz_dict_item (parent_id);
CREATE INDEX idx_ydsz_dict_item_tenant_deleted ON ydsz_dict_item (tenant_id, deleted);

CREATE TABLE ydsz_config (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    config_group             VARCHAR2(64 CHAR)        NOT NULL,
    config_key               VARCHAR2(128 CHAR)       NOT NULL,
    config_value             CLOB                     DEFAULT NULL,
    value_type               VARCHAR2(32 CHAR)        NOT NULL,
    default_value            CLOB                     DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    is_public                NUMBER(1)                NOT NULL DEFAULT 0,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_config PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_config_config_group_key UNIQUE (config_group, config_key)
);

COMMENT ON TABLE ydsz_config IS '系统配置表';
COMMENT ON COLUMN ydsz_config.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_config.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_config.config_group IS '配置分组（按业务域分类管理配置）';
COMMENT ON COLUMN ydsz_config.config_key IS '配置键（同组内唯一标识）';
COMMENT ON COLUMN ydsz_config.config_value IS '配置值';
COMMENT ON COLUMN ydsz_config.value_type IS '值类型（STRING/NUMBER/BOOLEAN/JSON）';
COMMENT ON COLUMN ydsz_config.default_value IS '默认值（配置未设置时使用）';
COMMENT ON COLUMN ydsz_config.description IS '配置描述';
COMMENT ON COLUMN ydsz_config.is_public IS '是否公开配置（1=公开，前端可查；0=私有，仅后端可查）';
COMMENT ON COLUMN ydsz_config.sort_order IS '排序序号';
COMMENT ON COLUMN ydsz_config.status IS '状态标识';
COMMENT ON COLUMN ydsz_config.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_config.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_config.created_by IS '创建人';
COMMENT ON COLUMN ydsz_config.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_config.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_config.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_config_tenant_deleted ON ydsz_config (tenant_id, deleted);

CREATE TABLE ydsz_variable (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    variable_key             VARCHAR2(128 CHAR)       NOT NULL,
    variable_value           CLOB                     DEFAULT NULL,
    value_type               VARCHAR2(32 CHAR)        NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_variable PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_variable_variable_key UNIQUE (variable_key)
);

COMMENT ON TABLE ydsz_variable IS '系统变量表';
COMMENT ON COLUMN ydsz_variable.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_variable.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_variable.variable_key IS '变量键（唯一标识，全局唯一）';
COMMENT ON COLUMN ydsz_variable.variable_value IS '变量值（按 valueType 反序列化为 String/Number/Boolean/JSON）';
COMMENT ON COLUMN ydsz_variable.value_type IS '值类型（STRING/NUMBER/BOOLEAN/JSON）';
COMMENT ON COLUMN ydsz_variable.description IS '变量描述（业务含义说明）';
COMMENT ON COLUMN ydsz_variable.status IS '状态标识（ENABLED/DISABLED）';
COMMENT ON COLUMN ydsz_variable.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_variable.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_variable.created_by IS '创建人';
COMMENT ON COLUMN ydsz_variable.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_variable.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_variable.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_variable_tenant_deleted ON ydsz_variable (tenant_id, deleted);

CREATE TABLE ydsz_app_info (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    app_code                 VARCHAR2(64 CHAR)        NOT NULL,
    app_name                 VARCHAR2(128 CHAR)       NOT NULL,
    app_key                  VARCHAR2(64 CHAR)        NOT NULL,
    app_secret               VARCHAR2(128 CHAR)       NOT NULL,
    redirect_url             VARCHAR2(1024 CHAR)      DEFAULT NULL,
    scopes                   VARCHAR2(512 CHAR)       DEFAULT NULL,
    bound_ips                VARCHAR2(512 CHAR)       DEFAULT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_app_info PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_app_info_app_code UNIQUE (app_code),
    CONSTRAINT uk_ydsz_app_info_tenant_app_key UNIQUE (tenant_id, app_key)
);

COMMENT ON TABLE ydsz_app_info IS '应用信息表';
COMMENT ON COLUMN ydsz_app_info.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_app_info.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_app_info.app_code IS '应用业务编码（对外展示/业务标识，全局唯一）';
COMMENT ON COLUMN ydsz_app_info.app_name IS '应用名称';
COMMENT ON COLUMN ydsz_app_info.app_key IS '应用唯一标识（认证查询入口，语义等价 OAuth2 client_id，租户内唯一）';
COMMENT ON COLUMN ydsz_app_info.app_secret IS '应用安全密钥（BCrypt 哈希存储，语义等价 OAuth2 client_secret）';
COMMENT ON COLUMN ydsz_app_info.redirect_url IS 'OAuth2 授权回调地址';
COMMENT ON COLUMN ydsz_app_info.scopes IS 'OAuth2 授权范围（CSV 格式，如 "user.read,order.write"）';
COMMENT ON COLUMN ydsz_app_info.bound_ips IS 'IP 绑定白名单（CSV 格式；为空表示不限制 IP）';
COMMENT ON COLUMN ydsz_app_info.description IS '应用描述';
COMMENT ON COLUMN ydsz_app_info.status IS '状态标识';
COMMENT ON COLUMN ydsz_app_info.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_app_info.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_app_info.created_by IS '创建人';
COMMENT ON COLUMN ydsz_app_info.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_app_info.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_app_info.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_app_info_tenant_deleted ON ydsz_app_info (tenant_id, deleted);

CREATE TABLE ydsz_entity_version (
    id                       VARCHAR2(32 CHAR)       ,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    resource_type            VARCHAR2(32 CHAR)        NOT NULL,
    resource_key             VARCHAR2(128 CHAR)       NOT NULL,
    resource_group           VARCHAR2(64 CHAR)        DEFAULT NULL,
    version                  VARCHAR2(32 CHAR)        NOT NULL,
    change_log               VARCHAR2(512 CHAR)       DEFAULT NULL,
    snapshot_json            CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_entity_version_snapshot_json CHECK (snapshot_json IS JSON),
    effective_date           TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_entity_version PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_entity_version IS '统一实体版本表';
COMMENT ON COLUMN ydsz_entity_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_entity_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_entity_version.resource_type IS '资源类型（CONFIG/DICT/VARIABLE）';
COMMENT ON COLUMN ydsz_entity_version.resource_key IS '资源唯一标识（configKey/typeCode/variableKey）';
COMMENT ON COLUMN ydsz_entity_version.resource_group IS '资源分组（仅 CONFIG 类型使用，其他为 null）';
COMMENT ON COLUMN ydsz_entity_version.version IS '版本号字符串';
COMMENT ON COLUMN ydsz_entity_version.change_log IS '变更说明';
COMMENT ON COLUMN ydsz_entity_version.snapshot_json IS '变更前 JSON 快照（用于回滚）';
COMMENT ON COLUMN ydsz_entity_version.effective_date IS '生效时间';
COMMENT ON COLUMN ydsz_entity_version.status IS '状态标识';
COMMENT ON COLUMN ydsz_entity_version.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_entity_version.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_entity_version.created_by IS '创建人';
COMMENT ON COLUMN ydsz_entity_version.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_entity_version.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_entity_version.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_entity_version_resource_type_key_version ON ydsz_entity_version (resource_type, resource_key, version);
CREATE INDEX idx_ydsz_entity_version_tenant_deleted ON ydsz_entity_version (tenant_id, deleted);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (Oracle)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_tenant_updated_at
BEFORE UPDATE ON ydsz_tenant
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_tenant_plan_updated_at
BEFORE UPDATE ON ydsz_tenant_plan
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_tenant_plan_menu_updated_at
BEFORE UPDATE ON ydsz_tenant_plan_menu
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_dict_type_updated_at
BEFORE UPDATE ON ydsz_dict_type
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_dict_item_updated_at
BEFORE UPDATE ON ydsz_dict_item
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_config_updated_at
BEFORE UPDATE ON ydsz_config
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_variable_updated_at
BEFORE UPDATE ON ydsz_variable
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_app_info_updated_at
BEFORE UPDATE ON ydsz_app_info
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_entity_version_updated_at
BEFORE UPDATE ON ydsz_entity_version
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
