-- ============================================================================
-- 模块名：ydsz-nextwiki（知识库/网盘模块）
-- 说明：基于 ydsz-nextwiki-infra 实体类与既有迁移脚本（V2~V6）整理的完整建表脚本
--       （Oracle 方言，已将 PostgreSQL 迁移脚本中的部分索引/函数式归档策略转译为 Oracle 等价形式，
--        所有变更合并为完整 CREATE TABLE 语句，无 ALTER）
-- 日期：2026-08-25
-- @author ydsz-team
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 文件节点主表（网盘文件/目录树）
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (Oracle 12.2+ / 19c)
--   - 类型映射: JSON→CLOB+CHECK(IS JSON) / TINYINT(1)→NUMBER(1) / INT→NUMBER(10)
--       / BIGINT→NUMBER(19) / DATETIME→TIMESTAMP / BOOLEAN→NUMBER(1)
--   - VARCHAR2 采用 CHAR 语义 VARCHAR2(n CHAR), 字符集建议 AL32UTF8
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾生成, 以 / 提交)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY (12c+)
--   - 索引/约束名按 schema 级唯一性命名 (Oracle 12.2+ 标识符 ≤128 字节)
--   - 原 MySQL 前缀索引 path(255) → SUBSTR(path,1,255) 函数索引
--   - 原 MySQL FULLTEXT 索引 → 普通复合索引 (全文检索建议由 ES/应用层承担)
--   - 执行方式: sqlplus / SQLcl 执行本脚本 (触发器以 / 提交)
-- ============================================================================


CREATE TABLE ydsz_file_node (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    parent_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    name                     VARCHAR2(255 CHAR)       NOT NULL,
    node_type                VARCHAR2(32 CHAR)        NOT NULL,
    suffix                   VARCHAR2(64 CHAR)        DEFAULT NULL,
    size                     NUMBER(19)               NOT NULL DEFAULT 0,
    storage_key              VARCHAR2(1024 CHAR)      DEFAULT NULL,
    bucket_name              VARCHAR2(128 CHAR)       DEFAULT NULL,
    mime_type                VARCHAR2(128 CHAR)       DEFAULT NULL,
    path                     VARCHAR2(1024 CHAR)      NOT NULL,
    level                    NUMBER(10)               NOT NULL DEFAULT 0,
    sort                     NUMBER(10)               NOT NULL DEFAULT 0,
    current_version          NUMBER(10)               NOT NULL DEFAULT 1,
    file_hash                VARCHAR2(64 CHAR)        DEFAULT NULL,
    thumbnail_key            VARCHAR2(1024 CHAR)      DEFAULT NULL,
    preview_ready            NUMBER(1)                NOT NULL DEFAULT 0,
    starred                  NUMBER(1)                NOT NULL DEFAULT 0,
    share_status             VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'private',
    deleted_time             TIMESTAMP                DEFAULT NULL,
    original_path            VARCHAR2(1024 CHAR)      DEFAULT NULL,
    storage_class            VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'STANDARD',
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_file_node PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_file_node IS '网盘文件节点（统一表示文件和目录，构成目录树的核心节点）';
COMMENT ON COLUMN ydsz_file_node.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_file_node.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_file_node.parent_id IS '父节点ID（根目录为 "0"）';
COMMENT ON COLUMN ydsz_file_node.name IS '节点名称（文件名或目录名）';
COMMENT ON COLUMN ydsz_file_node.node_type IS '节点类型：folder / file';
COMMENT ON COLUMN ydsz_file_node.suffix IS '文件扩展名（小写，不含点；文件夹为空）';
COMMENT ON COLUMN ydsz_file_node.size IS '文件大小（字节；文件夹为 0）';
COMMENT ON COLUMN ydsz_file_node.storage_key IS '底层存储对象键（objectName）';
COMMENT ON COLUMN ydsz_file_node.bucket_name IS '存储桶名称';
COMMENT ON COLUMN ydsz_file_node.mime_type IS 'MIME 类型';
COMMENT ON COLUMN ydsz_file_node.path IS '目录路径（如 /root/docs/contract/），用于快速判断层级关系';
COMMENT ON COLUMN ydsz_file_node.level IS '层级深度（根为 0）';
COMMENT ON COLUMN ydsz_file_node.sort IS '排序序号';
COMMENT ON COLUMN ydsz_file_node.current_version IS '当前版本号（从 1 开始，每次更新 +1）';
COMMENT ON COLUMN ydsz_file_node.file_hash IS '文件 SHA-256 哈希（用于秒传去重）';
COMMENT ON COLUMN ydsz_file_node.thumbnail_key IS '缩略图存储键';
COMMENT ON COLUMN ydsz_file_node.preview_ready IS '是否已生成预览';
COMMENT ON COLUMN ydsz_file_node.starred IS '是否星标文件';
COMMENT ON COLUMN ydsz_file_node.share_status IS '共享状态：private / shared / public';
COMMENT ON COLUMN ydsz_file_node.deleted_time IS '逻辑删除时间（回收站功能：删除时记录时间，30 天后永久删除）';
COMMENT ON COLUMN ydsz_file_node.original_path IS '原始路径（删除前的完整路径，用于恢复）';
COMMENT ON COLUMN ydsz_file_node.storage_class IS '存储类型：STANDARD / GLACIER / DEEP_ARCHIVE（冷数据归档）';
COMMENT ON COLUMN ydsz_file_node.status IS '状态标识';
COMMENT ON COLUMN ydsz_file_node.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_file_node.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_file_node.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_file_node.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_file_node.created_by IS '创建人';
COMMENT ON COLUMN ydsz_file_node.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_file_node_parent_id ON ydsz_file_node (parent_id);
CREATE INDEX idx_ydsz_file_node_tenant_deleted ON ydsz_file_node (tenant_id, deleted);
CREATE INDEX idx_ydsz_file_node_parent_deleted_updated ON ydsz_file_node (parent_id, deleted, updated_at);
CREATE INDEX idx_ydsz_file_node_parent_deleted_type_updated ON ydsz_file_node (parent_id, deleted, node_type, updated_at);
CREATE INDEX idx_ydsz_file_node_path ON ydsz_file_node (SUBSTR(path, 1, 255));
CREATE INDEX idx_ydsz_file_node_created_deleted_type ON ydsz_file_node (created_by, deleted, node_type);
CREATE INDEX idx_ydsz_file_node_file_hash ON ydsz_file_node (file_hash);
CREATE INDEX idx_ydsz_file_node_not_deleted ON ydsz_file_node (id, parent_id, tenant_id);
CREATE INDEX idx_ydsz_file_node_storage_class ON ydsz_file_node (node_type, deleted, storage_class, updated_at);

CREATE TABLE ydsz_file_version (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    version_number           NUMBER(10)               NOT NULL,
    storage_key              VARCHAR2(1024 CHAR)      DEFAULT NULL,
    size                     NUMBER(19)               NOT NULL DEFAULT 0,
    file_hash                VARCHAR2(64 CHAR)        DEFAULT NULL,
    mime_type                VARCHAR2(128 CHAR)       DEFAULT NULL,
    remark                   VARCHAR2(512 CHAR)       DEFAULT NULL,
    change_type              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'update',
    active                   NUMBER(1)                NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_file_version PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_file_version_file_node_version UNIQUE (file_node_id, version_number)
);

COMMENT ON TABLE ydsz_file_version IS '文件版本历史（每次文件更新生成一条版本记录，支持版本回溯）';
COMMENT ON COLUMN ydsz_file_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_file_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_file_version.file_node_id IS '关联的文件节点ID';
COMMENT ON COLUMN ydsz_file_version.version_number IS '版本号（从 1 开始递增）';
COMMENT ON COLUMN ydsz_file_version.storage_key IS '该版本的存储对象键';
COMMENT ON COLUMN ydsz_file_version.size IS '该版本的文件大小（字节）';
COMMENT ON COLUMN ydsz_file_version.file_hash IS '该版本的文件 SHA-256 哈希';
COMMENT ON COLUMN ydsz_file_version.mime_type IS '该版本的 MIME 类型';
COMMENT ON COLUMN ydsz_file_version.remark IS '版本说明（用户自定义的版本备注）';
COMMENT ON COLUMN ydsz_file_version.change_type IS '变更类型：create / update / rollback';
COMMENT ON COLUMN ydsz_file_version.active IS '是否为当前活跃版本';
COMMENT ON COLUMN ydsz_file_version.status IS '状态标识';
COMMENT ON COLUMN ydsz_file_version.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_file_version.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_file_version.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_file_version.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_file_version.created_by IS '创建人';
COMMENT ON COLUMN ydsz_file_version.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_file_version_tenant_deleted ON ydsz_file_version (tenant_id, deleted);

CREATE TABLE ydsz_tag (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    name                     VARCHAR2(255 CHAR)       NOT NULL,
    color                    VARCHAR2(32 CHAR)        DEFAULT NULL,
    type                     VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'manual',
    usage_count              NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_tag PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_tag_tenant_tag_name UNIQUE (tenant_id, name)
);

COMMENT ON TABLE ydsz_tag IS '标签（对文件/文件夹打标签，用于知识库分类和检索）';
COMMENT ON COLUMN ydsz_tag.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_tag.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_tag.name IS '标签名称';
COMMENT ON COLUMN ydsz_tag.color IS '标签颜色（十六进制颜色码，如 #1890ff）';
COMMENT ON COLUMN ydsz_tag.type IS '标签类型：manual（手动）/ auto（自动推荐）/ system（系统预设）';
COMMENT ON COLUMN ydsz_tag.usage_count IS '使用次数（文件关联数）';
COMMENT ON COLUMN ydsz_tag.status IS '状态标识';
COMMENT ON COLUMN ydsz_tag.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_tag.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_tag.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_tag.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_tag.created_by IS '创建人';
COMMENT ON COLUMN ydsz_tag.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_tag_tenant_deleted ON ydsz_tag (tenant_id, deleted);

CREATE TABLE ydsz_file_tag (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    tag_id                   VARCHAR2(32 CHAR)        NOT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_file_tag PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_file_tag_file_node_tag UNIQUE (file_node_id, tag_id)
);

COMMENT ON TABLE ydsz_file_tag IS '文件-标签关联（多对多）';
COMMENT ON COLUMN ydsz_file_tag.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_file_tag.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_file_tag.file_node_id IS '文件节点ID';
COMMENT ON COLUMN ydsz_file_tag.tag_id IS '标签ID';
COMMENT ON COLUMN ydsz_file_tag.status IS '状态标识';
COMMENT ON COLUMN ydsz_file_tag.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_file_tag.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_file_tag.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_file_tag.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_file_tag.created_by IS '创建人';
COMMENT ON COLUMN ydsz_file_tag.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_file_tag_tag_id ON ydsz_file_tag (tag_id);
CREATE INDEX idx_ydsz_file_tag_tenant_deleted ON ydsz_file_tag (tenant_id, deleted);

CREATE TABLE ydsz_file_comment (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    content                  CLOB                     NOT NULL,
    parent_comment_id        VARCHAR2(32 CHAR)        DEFAULT NULL,
    resolved                 NUMBER(1)                NOT NULL DEFAULT 0,
    position                 CLOB                     DEFAULT NULL CONSTRAINT ck_ydsz_file_comment_position CHECK (position IS JSON),
    edited                   NUMBER(1)                NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_file_comment PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_file_comment IS '文件评论（支持文件级别的评论和回复，用于知识库协作讨论）';
COMMENT ON COLUMN ydsz_file_comment.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_file_comment.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_file_comment.file_node_id IS '关联的文件节点ID';
COMMENT ON COLUMN ydsz_file_comment.content IS '评论内容';
COMMENT ON COLUMN ydsz_file_comment.parent_comment_id IS '父评论ID（用于回复，null 表示顶级评论）';
COMMENT ON COLUMN ydsz_file_comment.resolved IS '是否已解决（用于批注功能）';
COMMENT ON COLUMN ydsz_file_comment.position IS '评论位置信息（JSON，用于文档内定位批注）';
COMMENT ON COLUMN ydsz_file_comment.edited IS '是否被编辑过';
COMMENT ON COLUMN ydsz_file_comment.status IS '状态标识';
COMMENT ON COLUMN ydsz_file_comment.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_file_comment.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_file_comment.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_file_comment.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_file_comment.created_by IS '创建人';
COMMENT ON COLUMN ydsz_file_comment.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_file_comment_file_node_id ON ydsz_file_comment (file_node_id);
CREATE INDEX idx_ydsz_file_comment_parent_comment_id ON ydsz_file_comment (parent_comment_id);
CREATE INDEX idx_ydsz_file_comment_tenant_deleted ON ydsz_file_comment (tenant_id, deleted);

CREATE TABLE ydsz_file_acl (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    grantee_type             VARCHAR2(32 CHAR)        NOT NULL,
    grantee_id               VARCHAR2(64 CHAR)        NOT NULL,
    permission_mask          NUMBER(10)               NOT NULL DEFAULT 0,
    inherited                NUMBER(1)                NOT NULL DEFAULT 1,
    owner                    NUMBER(1)                NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_file_acl PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_file_acl_file_grantee UNIQUE (file_node_id, grantee_type, grantee_id)
);

COMMENT ON TABLE ydsz_file_acl IS '文件级 ACL 权限（文件/文件夹级别的细粒度权限控制）';
COMMENT ON COLUMN ydsz_file_acl.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_file_acl.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_file_acl.file_node_id IS '文件节点ID';
COMMENT ON COLUMN ydsz_file_acl.grantee_type IS '授权对象类型：user / role / group / tenant';
COMMENT ON COLUMN ydsz_file_acl.grantee_id IS '授权对象ID（用户ID / 角色ID / 组ID / 租户ID）';
COMMENT ON COLUMN ydsz_file_acl.permission_mask IS '权限位掩码（read=1, write=2, delete=4, share=8, download=16）';
COMMENT ON COLUMN ydsz_file_acl.inherited IS '是否继承自父目录';
COMMENT ON COLUMN ydsz_file_acl.owner IS '是否为所有者（所有者拥有全部权限）';
COMMENT ON COLUMN ydsz_file_acl.status IS '状态标识';
COMMENT ON COLUMN ydsz_file_acl.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_file_acl.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_file_acl.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_file_acl.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_file_acl.created_by IS '创建人';
COMMENT ON COLUMN ydsz_file_acl.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_file_acl_grantee ON ydsz_file_acl (grantee_type, grantee_id);
CREATE INDEX idx_ydsz_file_acl_tenant_deleted ON ydsz_file_acl (tenant_id, deleted);

CREATE TABLE ydsz_share_link (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    share_code               VARCHAR2(64 CHAR)        NOT NULL,
    extract_code             VARCHAR2(8 CHAR)         DEFAULT NULL,
    share_type               VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'view',
    expire_time              TIMESTAMP                DEFAULT NULL,
    max_access_count         NUMBER(10)               DEFAULT NULL,
    access_count             NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'active',
    password                 VARCHAR2(128 CHAR)       DEFAULT NULL,
    share_target_type        VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'PUBLIC',
    reminder_sent            NUMBER(1)                NOT NULL DEFAULT 0,
    title                    VARCHAR2(255 CHAR)       DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_share_link PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_share_link_share_code UNIQUE (share_code)
);

COMMENT ON TABLE ydsz_share_link IS '文件分享链接（带密码和过期时间的文件级临时授权机制）';
COMMENT ON COLUMN ydsz_share_link.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_share_link.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_share_link.file_node_id IS '关联的文件节点ID';
COMMENT ON COLUMN ydsz_share_link.share_code IS '分享码（URL 中的唯一标识，UUID 生成）';
COMMENT ON COLUMN ydsz_share_link.extract_code IS '提取码（4 位数字，访问时需要输入）';
COMMENT ON COLUMN ydsz_share_link.share_type IS '分享类型：view（仅查看）/ download（可下载）/ edit（可编辑）';
COMMENT ON COLUMN ydsz_share_link.expire_time IS '过期时间（null 表示永久有效）';
COMMENT ON COLUMN ydsz_share_link.max_access_count IS '最大访问次数（null 表示不限）';
COMMENT ON COLUMN ydsz_share_link.access_count IS '已访问次数';
COMMENT ON COLUMN ydsz_share_link.status IS '分享状态：active / expired / revoked';
COMMENT ON COLUMN ydsz_share_link.password IS '分享密码（BCrypt 加密；空表示无密码）';
COMMENT ON COLUMN ydsz_share_link.share_target_type IS '分享目标类型：PUBLIC(公开) / USER(指定用户) / DEPT(部门)';
COMMENT ON COLUMN ydsz_share_link.reminder_sent IS '到期提醒是否已发送';
COMMENT ON COLUMN ydsz_share_link.title IS '分享标题（可选）';
COMMENT ON COLUMN ydsz_share_link.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_share_link.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_share_link.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_share_link.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_share_link.created_by IS '创建人';
COMMENT ON COLUMN ydsz_share_link.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_share_link_file_node_id ON ydsz_share_link (file_node_id);
CREATE INDEX idx_ydsz_share_link_expire_reminder ON ydsz_share_link (status, expire_time, reminder_sent);
CREATE INDEX idx_ydsz_share_link_tenant_deleted ON ydsz_share_link (tenant_id, deleted);

CREATE TABLE ydsz_share_recipient (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    share_id                 VARCHAR2(32 CHAR)        NOT NULL,
    recipient_type           VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'USER',
    recipient_id             VARCHAR2(64 CHAR)        NOT NULL,
    recipient_name           VARCHAR2(128 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'ACTIVE',
    viewed_at                TIMESTAMP                DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_share_recipient PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_share_recipient_share_recipient UNIQUE (share_id, recipient_type, recipient_id)
);

COMMENT ON TABLE ydsz_share_recipient IS '分享目标用户（定向分享，记录分享链接的目标接收者）';
COMMENT ON COLUMN ydsz_share_recipient.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_share_recipient.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_share_recipient.share_id IS '分享链接 ID';
COMMENT ON COLUMN ydsz_share_recipient.recipient_type IS '接收者类型：USER/DEPT/ROLE';
COMMENT ON COLUMN ydsz_share_recipient.recipient_id IS '接收者 ID';
COMMENT ON COLUMN ydsz_share_recipient.recipient_name IS '接收者名称';
COMMENT ON COLUMN ydsz_share_recipient.status IS '状态：ACTIVE/VIEWED/REVOKED';
COMMENT ON COLUMN ydsz_share_recipient.viewed_at IS '首次查看时间';
COMMENT ON COLUMN ydsz_share_recipient.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_share_recipient.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_share_recipient.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_share_recipient.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_share_recipient.created_by IS '创建人';
COMMENT ON COLUMN ydsz_share_recipient.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_share_recipient_share ON ydsz_share_recipient (share_id, deleted);
CREATE INDEX idx_ydsz_share_recipient_user ON ydsz_share_recipient (recipient_id, status, deleted);
CREATE INDEX idx_ydsz_share_recipient_tenant_deleted ON ydsz_share_recipient (tenant_id, deleted);

CREATE TABLE ydsz_share_access_log (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    share_id                 VARCHAR2(32 CHAR)        NOT NULL,
    share_code               VARCHAR2(64 CHAR)        NOT NULL,
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    visitor_id               VARCHAR2(64 CHAR)        DEFAULT NULL,
    visitor_name             VARCHAR2(128 CHAR)       DEFAULT NULL,
    visitor_ip               VARCHAR2(64 CHAR)        DEFAULT NULL,
    user_agent               VARCHAR2(512 CHAR)       DEFAULT NULL,
    access_type              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'VIEW',
    access_status            VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'SUCCESS',
    fail_reason              VARCHAR2(255 CHAR)       DEFAULT NULL,
    access_time              TIMESTAMP                NOT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_share_access_log PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_share_access_log IS '分享链接访问日志（记录每次分享链接被访问的详细信息，用于安全审计和访问统计）';
COMMENT ON COLUMN ydsz_share_access_log.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_share_access_log.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_share_access_log.share_id IS '分享链接 ID';
COMMENT ON COLUMN ydsz_share_access_log.share_code IS '分享码';
COMMENT ON COLUMN ydsz_share_access_log.file_node_id IS '文件节点 ID';
COMMENT ON COLUMN ydsz_share_access_log.visitor_id IS '访问者用户 ID（匿名为空）';
COMMENT ON COLUMN ydsz_share_access_log.visitor_name IS '访问者名称';
COMMENT ON COLUMN ydsz_share_access_log.visitor_ip IS '访问者 IP 地址';
COMMENT ON COLUMN ydsz_share_access_log.user_agent IS '访问者 User-Agent';
COMMENT ON COLUMN ydsz_share_access_log.access_type IS '访问类型：VIEW/DOWNLOAD/EDIT';
COMMENT ON COLUMN ydsz_share_access_log.access_status IS '访问状态：SUCCESS/FAIL';
COMMENT ON COLUMN ydsz_share_access_log.fail_reason IS '失败原因';
COMMENT ON COLUMN ydsz_share_access_log.access_time IS '访问时间';
COMMENT ON COLUMN ydsz_share_access_log.status IS '状态标识';
COMMENT ON COLUMN ydsz_share_access_log.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_share_access_log.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_share_access_log.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_share_access_log.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_share_access_log.created_by IS '创建人';
COMMENT ON COLUMN ydsz_share_access_log.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_share_access_log_access_time ON ydsz_share_access_log (access_time);
CREATE INDEX idx_ydsz_share_access_log_share_id ON ydsz_share_access_log (share_id, created_at);
CREATE INDEX idx_ydsz_share_access_log_created ON ydsz_share_access_log (created_at);
CREATE INDEX idx_ydsz_share_access_log_visitor ON ydsz_share_access_log (visitor_id, created_at);
CREATE INDEX idx_ydsz_share_access_log_tenant_deleted ON ydsz_share_access_log (tenant_id, deleted);

CREATE TABLE ydsz_share_access_log_archive (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    share_id                 VARCHAR2(32 CHAR)        NOT NULL,
    share_code               VARCHAR2(64 CHAR)        NOT NULL,
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    visitor_id               VARCHAR2(64 CHAR)        DEFAULT NULL,
    visitor_name             VARCHAR2(128 CHAR)       DEFAULT NULL,
    visitor_ip               VARCHAR2(64 CHAR)        DEFAULT NULL,
    user_agent               VARCHAR2(512 CHAR)       DEFAULT NULL,
    access_type              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'VIEW',
    access_status            VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'SUCCESS',
    fail_reason              VARCHAR2(255 CHAR)       DEFAULT NULL,
    access_time              TIMESTAMP                NOT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_share_access_log_archive PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_share_access_log_archive IS '分享访问日志归档表（归档 90 天前访问日志，防止主表无限膨胀）';
COMMENT ON COLUMN ydsz_share_access_log_archive.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_share_access_log_archive.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_share_access_log_archive.share_id IS '分享链接 ID';
COMMENT ON COLUMN ydsz_share_access_log_archive.share_code IS '分享码';
COMMENT ON COLUMN ydsz_share_access_log_archive.file_node_id IS '文件节点 ID';
COMMENT ON COLUMN ydsz_share_access_log_archive.visitor_id IS '访问者用户 ID（匿名为空）';
COMMENT ON COLUMN ydsz_share_access_log_archive.visitor_name IS '访问者名称';
COMMENT ON COLUMN ydsz_share_access_log_archive.visitor_ip IS '访问者 IP 地址';
COMMENT ON COLUMN ydsz_share_access_log_archive.user_agent IS '访问者 User-Agent';
COMMENT ON COLUMN ydsz_share_access_log_archive.access_type IS '访问类型：VIEW/DOWNLOAD/EDIT';
COMMENT ON COLUMN ydsz_share_access_log_archive.access_status IS '访问状态：SUCCESS/FAIL';
COMMENT ON COLUMN ydsz_share_access_log_archive.fail_reason IS '失败原因';
COMMENT ON COLUMN ydsz_share_access_log_archive.access_time IS '访问时间';
COMMENT ON COLUMN ydsz_share_access_log_archive.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_share_access_log_archive.created_at IS '创建时间';

CREATE INDEX idx_ydsz_share_access_log_archive_archive_share_created ON ydsz_share_access_log_archive (share_id, created_at);
CREATE INDEX idx_ydsz_share_access_log_archive_archive_created ON ydsz_share_access_log_archive (created_at);
CREATE INDEX idx_ydsz_share_access_log_archive_archive_access_time ON ydsz_share_access_log_archive (access_time);
CREATE INDEX idx_ydsz_share_access_log_archive_tenant_deleted ON ydsz_share_access_log_archive (tenant_id, deleted);

CREATE TABLE ydsz_space (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    name                     VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    icon_url                 VARCHAR2(1024 CHAR)      DEFAULT NULL,
    cover_url                VARCHAR2(1024 CHAR)      DEFAULT NULL,
    owner_id                 VARCHAR2(64 CHAR)        NOT NULL,
    status                   VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'active',
    visibility               VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'private',
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    member_count             NUMBER(10)               NOT NULL DEFAULT 1,
    node_count               NUMBER(10)               NOT NULL DEFAULT 0,
    quota_limit              NUMBER(19)               DEFAULT NULL,
    quota_used               NUMBER(19)               NOT NULL DEFAULT 0,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    deleted_time             TIMESTAMP                DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_space PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_space_tenant_name UNIQUE (tenant_id, name)
);

COMMENT ON TABLE ydsz_space IS '知识库空间（空间管理聚合根，文件节点的顶级容器）';
COMMENT ON COLUMN ydsz_space.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_space.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_space.name IS '空间名称';
COMMENT ON COLUMN ydsz_space.description IS '空间描述';
COMMENT ON COLUMN ydsz_space.icon_url IS '空间图标 URL';
COMMENT ON COLUMN ydsz_space.cover_url IS '空间封面 URL';
COMMENT ON COLUMN ydsz_space.owner_id IS '空间所有者（创建者）';
COMMENT ON COLUMN ydsz_space.status IS '空间状态：active / archived / deleted';
COMMENT ON COLUMN ydsz_space.visibility IS '可见性：private / organization / public';
COMMENT ON COLUMN ydsz_space.sort_order IS '排序序号';
COMMENT ON COLUMN ydsz_space.member_count IS '成员数量';
COMMENT ON COLUMN ydsz_space.node_count IS '节点数量（文件/目录总数）';
COMMENT ON COLUMN ydsz_space.quota_limit IS '空间独立配额（字节，NULL 表示使用租户配额）';
COMMENT ON COLUMN ydsz_space.quota_used IS '已使用配额（字节）';
COMMENT ON COLUMN ydsz_space.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_space.deleted_time IS '删除时间';
COMMENT ON COLUMN ydsz_space.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_space.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_space.created_by IS '创建人';
COMMENT ON COLUMN ydsz_space.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_space_tenant_sort ON ydsz_space (tenant_id, sort_order);
CREATE INDEX idx_ydsz_space_owner ON ydsz_space (owner_id);
CREATE INDEX idx_ydsz_space_tenant_deleted ON ydsz_space (tenant_id, deleted);

CREATE TABLE ydsz_space_member (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    space_id                 VARCHAR2(32 CHAR)        NOT NULL,
    user_id                  VARCHAR2(64 CHAR)        NOT NULL,
    role                     VARCHAR2(32 CHAR)        NOT NULL,
    joined_at                TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_space_member PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_space_member_space_user UNIQUE (space_id, user_id)
);

COMMENT ON TABLE ydsz_space_member IS '空间成员（记录用户与空间的归属关系及角色）';
COMMENT ON COLUMN ydsz_space_member.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_space_member.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_space_member.space_id IS '空间ID';
COMMENT ON COLUMN ydsz_space_member.user_id IS '用户ID';
COMMENT ON COLUMN ydsz_space_member.role IS '角色：owner / admin / editor / viewer';
COMMENT ON COLUMN ydsz_space_member.joined_at IS '加入时间';
COMMENT ON COLUMN ydsz_space_member.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_space_member.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_space_member.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_space_member.created_by IS '创建人';
COMMENT ON COLUMN ydsz_space_member.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_space_member_space_role ON ydsz_space_member (space_id, role);
CREATE INDEX idx_ydsz_space_member_user ON ydsz_space_member (user_id);
CREATE INDEX idx_ydsz_space_member_tenant_deleted ON ydsz_space_member (tenant_id, deleted);

CREATE TABLE ydsz_space_template (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        DEFAULT NULL,
    name                     VARCHAR2(128 CHAR)       NOT NULL,
    description              VARCHAR2(512 CHAR)       DEFAULT NULL,
    category                 VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'general',
    icon_url                 VARCHAR2(1024 CHAR)      DEFAULT NULL,
    is_system                NUMBER(1)                NOT NULL DEFAULT 0,
    is_public                NUMBER(1)                NOT NULL DEFAULT 1,
    structure_json           CLOB                     NOT NULL CONSTRAINT ck_ydsz_space_template_structure_json CHECK (structure_json IS JSON),
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    usage_count              NUMBER(10)               NOT NULL DEFAULT 0,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_space_template PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_space_template IS '空间模板（预定义可复用的空间结构模板）';
COMMENT ON COLUMN ydsz_space_template.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_space_template.tenant_id IS '租户 ID（系统模板为 NULL）';
COMMENT ON COLUMN ydsz_space_template.name IS '模板名称';
COMMENT ON COLUMN ydsz_space_template.description IS '模板描述';
COMMENT ON COLUMN ydsz_space_template.category IS '模板分类：general / project / meeting / knowledge';
COMMENT ON COLUMN ydsz_space_template.icon_url IS '模板图标 URL';
COMMENT ON COLUMN ydsz_space_template.is_system IS '是否为系统内置模板（不可删除）';
COMMENT ON COLUMN ydsz_space_template.is_public IS '是否公开（所有租户可见）';
COMMENT ON COLUMN ydsz_space_template.structure_json IS '模板结构 JSON（定义目录树、初始页面、权限配置等）';
COMMENT ON COLUMN ydsz_space_template.sort_order IS '排序序号';
COMMENT ON COLUMN ydsz_space_template.usage_count IS '使用次数';
COMMENT ON COLUMN ydsz_space_template.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_space_template.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_space_template.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_space_template.created_by IS '创建人';
COMMENT ON COLUMN ydsz_space_template.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_space_template_tenant_category ON ydsz_space_template (tenant_id, category);
CREATE INDEX idx_ydsz_space_template_system ON ydsz_space_template (is_system, is_public);
CREATE INDEX idx_ydsz_space_template_tenant_deleted ON ydsz_space_template (tenant_id, deleted);

CREATE TABLE ydsz_trash_item (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    original_name            VARCHAR2(255 CHAR)       NOT NULL,
    original_path            VARCHAR2(1024 CHAR)      DEFAULT NULL,
    original_parent_id       VARCHAR2(32 CHAR)        DEFAULT NULL,
    node_type                VARCHAR2(32 CHAR)        NOT NULL,
    size                     NUMBER(19)               NOT NULL DEFAULT 0,
    deleted_time             TIMESTAMP                NOT NULL,
    purge_time               TIMESTAMP                NOT NULL,
    status                   VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'in_trash',
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_trash_item PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_trash_item IS '回收站条目（记录被逻辑删除的文件/文件夹，支持恢复和自动清理）';
COMMENT ON COLUMN ydsz_trash_item.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_trash_item.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_trash_item.file_node_id IS '原文件节点ID';
COMMENT ON COLUMN ydsz_trash_item.original_name IS '原文件名';
COMMENT ON COLUMN ydsz_trash_item.original_path IS '原始路径';
COMMENT ON COLUMN ydsz_trash_item.original_parent_id IS '原始父节点ID';
COMMENT ON COLUMN ydsz_trash_item.node_type IS '节点类型：folder / file';
COMMENT ON COLUMN ydsz_trash_item.size IS '文件大小（字节）';
COMMENT ON COLUMN ydsz_trash_item.deleted_time IS '删除时间';
COMMENT ON COLUMN ydsz_trash_item.purge_time IS '预计永久删除时间';
COMMENT ON COLUMN ydsz_trash_item.status IS '状态：in_trash / restored / purged';
COMMENT ON COLUMN ydsz_trash_item.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_trash_item.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_trash_item.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_trash_item.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_trash_item.created_by IS '创建人';
COMMENT ON COLUMN ydsz_trash_item.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_trash_item_file_node_id ON ydsz_trash_item (file_node_id);
CREATE INDEX idx_ydsz_trash_item_deleted_time ON ydsz_trash_item (deleted_time);
CREATE INDEX idx_ydsz_trash_item_purge_time ON ydsz_trash_item (purge_time);
CREATE INDEX idx_ydsz_trash_item_tenant_deleted ON ydsz_trash_item (tenant_id, deleted);

CREATE TABLE ydsz_search_index (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    file_node_id             VARCHAR2(32 CHAR)        NOT NULL,
    name                     VARCHAR2(255 CHAR)       NOT NULL,
    path                     VARCHAR2(1024 CHAR)      DEFAULT NULL,
    content                  CLOB                    ,
    suffix                   VARCHAR2(64 CHAR)        DEFAULT NULL,
    mime_type                VARCHAR2(128 CHAR)       DEFAULT NULL,
    size                     NUMBER(19)               NOT NULL DEFAULT 0,
    tags                     VARCHAR2(512 CHAR)       DEFAULT NULL,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_search_index PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_search_index_file_node_id UNIQUE (file_node_id)
);

COMMENT ON TABLE ydsz_search_index IS '文件搜索索引（数据库 fallback 搜索，ES 不可用时提供文件名/路径/内容搜索）';
COMMENT ON COLUMN ydsz_search_index.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_search_index.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_search_index.file_node_id IS '关联的文件节点ID';
COMMENT ON COLUMN ydsz_search_index.name IS '文件名（用于搜索）';
COMMENT ON COLUMN ydsz_search_index.path IS '目录路径';
COMMENT ON COLUMN ydsz_search_index.content IS '索引内容（文件名 + 路径 + 提取的文本）';
COMMENT ON COLUMN ydsz_search_index.suffix IS '文件后缀';
COMMENT ON COLUMN ydsz_search_index.mime_type IS 'MIME 类型';
COMMENT ON COLUMN ydsz_search_index.size IS '文件大小（字节）';
COMMENT ON COLUMN ydsz_search_index.tags IS '标签（逗号分隔）';
COMMENT ON COLUMN ydsz_search_index.status IS '状态标识';
COMMENT ON COLUMN ydsz_search_index.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_search_index.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_search_index.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_search_index.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_search_index.created_by IS '创建人';
COMMENT ON COLUMN ydsz_search_index.updated_by IS '最后更新人';

-- 原 MySQL FULLTEXT 索引: Oracle 使用普通复合索引, 全文检索建议由 ES/应用层承担 (或升级为 Oracle Text CONTEXT 索引)
CREATE INDEX idx_ydsz_search_index_ft_search_name_content ON ydsz_search_index (name, content);
CREATE INDEX idx_ydsz_search_index_tenant_deleted ON ydsz_search_index (tenant_id, deleted);

CREATE TABLE ydsz_user_favorite (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    user_id                  VARCHAR2(64 CHAR)        NOT NULL,
    node_id                  VARCHAR2(64 CHAR)        NOT NULL,
    sort_order               NUMBER(10)               NOT NULL DEFAULT 0,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    deleted_time             TIMESTAMP                DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_user_favorite PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_user_favorite_user_node UNIQUE (user_id, node_id)
);

COMMENT ON TABLE ydsz_user_favorite IS '用户收藏夹（记录用户收藏的文件/目录节点，支持排序与软删除）';
COMMENT ON COLUMN ydsz_user_favorite.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_user_favorite.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_user_favorite.user_id IS '用户ID';
COMMENT ON COLUMN ydsz_user_favorite.node_id IS '收藏的文件/目录节点ID';
COMMENT ON COLUMN ydsz_user_favorite.sort_order IS '排序序号（值越小越靠前）';
COMMENT ON COLUMN ydsz_user_favorite.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_user_favorite.deleted_time IS '删除时间';
COMMENT ON COLUMN ydsz_user_favorite.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_user_favorite.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_user_favorite.created_by IS '创建人';
COMMENT ON COLUMN ydsz_user_favorite.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_user_favorite_user_sort ON ydsz_user_favorite (user_id, sort_order);
CREATE INDEX idx_ydsz_user_favorite_tenant_deleted ON ydsz_user_favorite (tenant_id, deleted);

CREATE TABLE ydsz_user_recent (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    user_id                  VARCHAR2(64 CHAR)        NOT NULL,
    node_id                  VARCHAR2(64 CHAR)        NOT NULL,
    access_type              VARCHAR2(32 CHAR)        NOT NULL DEFAULT 'view',
    accessed_at              TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_user_recent PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_user_recent_user_node UNIQUE (user_id, node_id)
);

COMMENT ON TABLE ydsz_user_recent IS '用户最近访问记录（同一节点只保留一条，支持按访问时间倒序查询）';
COMMENT ON COLUMN ydsz_user_recent.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_user_recent.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_user_recent.user_id IS '用户ID';
COMMENT ON COLUMN ydsz_user_recent.node_id IS '访问的文件/目录节点ID';
COMMENT ON COLUMN ydsz_user_recent.access_type IS '访问类型：view / edit / download';
COMMENT ON COLUMN ydsz_user_recent.accessed_at IS '最近访问时间（排序字段）';
COMMENT ON COLUMN ydsz_user_recent.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_user_recent.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_user_recent.updated_at IS '最后更新时间';

CREATE INDEX idx_ydsz_user_recent_user_accessed ON ydsz_user_recent (user_id, accessed_at);
CREATE INDEX idx_ydsz_user_recent_access_type ON ydsz_user_recent (user_id, access_type);
CREATE INDEX idx_ydsz_user_recent_tenant_deleted ON ydsz_user_recent (tenant_id, deleted);

CREATE TABLE ydsz_storage_quota (
    id                       VARCHAR2(32 CHAR)        NOT NULL,
    tenant_id                VARCHAR2(32 CHAR)        NOT NULL DEFAULT '0',
    scope_type               VARCHAR2(32 CHAR)        NOT NULL,
    scope_id                 VARCHAR2(64 CHAR)        NOT NULL,
    quota_limit              NUMBER(19)               NOT NULL DEFAULT 0,
    quota_used               NUMBER(19)               NOT NULL DEFAULT 0,
    file_count_limit         NUMBER(10)               DEFAULT NULL,
    file_count_used          NUMBER(10)               NOT NULL DEFAULT 0,
    status                   VARCHAR2(32 CHAR)        DEFAULT NULL,
    deleted                  NUMBER(1)                NOT NULL DEFAULT 0,
    revision                 NUMBER(10)               NOT NULL DEFAULT 0,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    updated_by               VARCHAR2(64 CHAR)        DEFAULT NULL,
    CONSTRAINT pk_ydsz_storage_quota PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_storage_quota_scope UNIQUE (scope_type, scope_id)
);

COMMENT ON TABLE ydsz_storage_quota IS '存储配额（按用户/租户/项目维度设置存储上限，上传时校验配额）';
COMMENT ON COLUMN ydsz_storage_quota.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_storage_quota.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_storage_quota.scope_type IS '配额维度：user / tenant / project';
COMMENT ON COLUMN ydsz_storage_quota.scope_id IS '维度ID（用户ID / 租户ID / 项目ID）';
COMMENT ON COLUMN ydsz_storage_quota.quota_limit IS '配额上限（字节）';
COMMENT ON COLUMN ydsz_storage_quota.quota_used IS '已使用量（字节）';
COMMENT ON COLUMN ydsz_storage_quota.file_count_limit IS '文件数量上限';
COMMENT ON COLUMN ydsz_storage_quota.file_count_used IS '已使用文件数量';
COMMENT ON COLUMN ydsz_storage_quota.status IS '状态标识';
COMMENT ON COLUMN ydsz_storage_quota.deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_storage_quota.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_storage_quota.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_storage_quota.updated_at IS '最后更新时间';
COMMENT ON COLUMN ydsz_storage_quota.created_by IS '创建人';
COMMENT ON COLUMN ydsz_storage_quota.updated_by IS '最后更新人';

CREATE INDEX idx_ydsz_storage_quota_tenant_deleted ON ydsz_storage_quota (tenant_id, deleted);

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (Oracle)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_file_node_updated_at
BEFORE UPDATE ON ydsz_file_node
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_file_version_updated_at
BEFORE UPDATE ON ydsz_file_version
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_tag_updated_at
BEFORE UPDATE ON ydsz_tag
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_file_tag_updated_at
BEFORE UPDATE ON ydsz_file_tag
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_file_comment_updated_at
BEFORE UPDATE ON ydsz_file_comment
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_file_acl_updated_at
BEFORE UPDATE ON ydsz_file_acl
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_share_link_updated_at
BEFORE UPDATE ON ydsz_share_link
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_share_recipient_updated_at
BEFORE UPDATE ON ydsz_share_recipient
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_share_access_log_updated_at
BEFORE UPDATE ON ydsz_share_access_log
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_space_updated_at
BEFORE UPDATE ON ydsz_space
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_space_member_updated_at
BEFORE UPDATE ON ydsz_space_member
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_space_template_updated_at
BEFORE UPDATE ON ydsz_space_template
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_trash_item_updated_at
BEFORE UPDATE ON ydsz_trash_item
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_search_index_updated_at
BEFORE UPDATE ON ydsz_search_index
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_user_favorite_updated_at
BEFORE UPDATE ON ydsz_user_favorite
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_user_recent_updated_at
BEFORE UPDATE ON ydsz_user_recent
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_ydsz_storage_quota_updated_at
BEFORE UPDATE ON ydsz_storage_quota
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
