<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.njydsz</groupId>
        <artifactId>ydsz-cloud</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>ydsz-auth</artifactId>
    <packaging>pom</packaging>
    <name>ydsz-auth</name>
    <description>OAuth2 Authorization Server - 基于 Spring Authorization Server 的认证中心</description>
    <modules>
        <module>ydsz-auth-domain</module>
        <module>ydsz-auth-infra</module>
        <module>ydsz-auth-server</module>
        <module>ydsz-auth-api</module>
        <module>ydsz-auth-web</module>
    </modules>
</project>
