<!-- Generated by Trae Work -->
<script setup lang="ts">
/**
 * @file BPMN 2.0 专业流程设计器（基于 bpmn.js）
 * @module components/BpmnDesigner
 * @description P0-01: 引入 bpmn.js 替换自绘 SVG，对标炎黄盈动/奥哲 BPMN 建模工具。
 *   P1-02: 新增自定义属性面板（Vue 组件式），支持节点名称/审批人/会签/条件表达式等编辑。
 *   支持拖拽式 BPMN 2.0 建模、属性编辑、XML 导入导出、模板加载。
 */
import { ref, reactive, onMounted, onBeforeUnmount, watch, nextTick } from 'vue'
import { ElMessage } from 'element-plus'
import { ArrowDown } from '@element-plus/icons-vue'
import BpmnModeler from 'bpmn-js/lib/Modeler'
import type { Element as BpmnElement } from 'bpmn-js/lib/model/Types'
import 'bpmn-js/dist/assets/diagram-js.css'
import 'bpmn-js/dist/assets/bpmn-js.css'
import 'bpmn-js/dist/assets/bpmn-font/css/bpmn.css'
import { deployDefinition } from '@/api/workflow'
import type { FlowDeployDTO } from '@/api/workflow/types'
import FormFieldPermissions from './FormFieldPermissions.vue'
import SlaRuleConfig from './SlaRuleConfig.vue'
import { autoLayout } from './bpmn/autoLayout'
import { logger } from '@/utils/logger'

// ==================== Props ====================
const props = defineProps<{
  /** 初始 BPMN XML（编辑已有流程时传入） */
  initialXml?: string
  /** 流程编码 */
  flowCode?: string
  /** 流程名称 */
  flowName?: string
  /** 流程类别 */
  category?: string
  /** P0-3: 流程定义 ID（用于字段权限配置） */
  definitionId?: number | null
}>()

const emit = defineEmits<{
  (e: 'save', xml: string, svg: string): void
  (e: 'deploy', flowCode: string, flowName: string, xml: string): void
}>()

// ==================== State ====================
const containerRef = ref<HTMLDivElement>()
const loading = ref(false)
const saving = ref(false)
const currentXml = ref('')
const currentSvg = ref('')
const modeler = ref<BpmnModeler | null>(null)

const deployForm = ref({
  flowCode: props.flowCode || '',
  flowName: props.flowName || '',
  category: props.category || 'GENERAL',
  formPath: '',
})

// ==================== 属性面板 ====================
const selectedElement = ref<BpmnElement | null>(null)
const panelData = reactive({
  elementType: '',      // bpmn type (e.g. bpmn:UserTask)
  elementId: '',        // BPMN id
  elementName: '',      // 显示名称
  assignee: '',         // 审批人（flowable:assignee）
  assigneeType: '',     // 审批人类型（user/role/dept/initiator/leader/superior）
  performType: '',      // 会签类型（none/sequential/parallel/vote）
  formKey: '',          // 表单 key
  dueDate: '',          // 超期时间
  priority: 0,          // 优先级
  conditionExpression: '', // 条件表达式（sequenceFlow）
  documentation: '',    // 节点说明
  // P0-5: 表单字段权限（每个审批节点可配置字段的可见/可编辑/只读/隐藏权限）
  fieldPermissions: [] as Array<{ fieldName: string; permission: 'EDITABLE' | 'READONLY' | 'HIDDEN' }>,
})

// 节点类型中文映射
const elementTypeLabel = (type: string): string => {
  const map: Record<string, string> = {
    'bpmn:StartEvent': '开始事件',
    'bpmn:EndEvent': '结束事件',
    'bpmn:UserTask': '审批节点',
    'bpmn:ServiceTask': '服务节点',
    'bpmn:ScriptTask': '脚本节点',
    'bpmn:ExclusiveGateway': '排他网关',
    'bpmn:ParallelGateway': '并行网关',
    'bpmn:InclusiveGateway': '包容网关',
    'bpmn:SequenceFlow': '连线',
    'bpmn:Process': '流程',
  }
  return map[type] || type
}

// 是否显示审批人配置（仅 UserTask）
const isUserTask = (): boolean => {
  return selectedElement.value?.type === 'bpmn:UserTask'
}

// 是否显示条件表达式（仅 SequenceFlow）
const isSequenceFlow = (): boolean => {
  return selectedElement.value?.type === 'bpmn:SequenceFlow'
}

// 是否显示通用属性
const hasGeneralProps = (): boolean => {
  return selectedElement.value !== null && selectedElement.value !== undefined && selectedElement.value.type !== 'bpmn:Process'
}

// 读取 BPMN 元素属性到面板
function readElementProperties(element: BpmnElement) {
  const bo = element.businessObject
  panelData.elementType = element.type || ''
  panelData.elementId = bo.id || ''
  panelData.elementName = bo.name || ''
  panelData.assignee = bo.get?.('flowable:assignee') || ''
  panelData.assigneeType = bo.get?.('flowable:assigneeType') || ''
  panelData.performType = bo.get?.('flowable:performType') || ''
  panelData.formKey = bo.formKey || ''
  panelData.dueDate = bo.get?.('flowable:dueDate') || ''
  panelData.priority = bo.get?.('flowable:priority') || 0
  panelData.conditionExpression = ''
  if (element.type === 'bpmn:SequenceFlow' && bo.conditionExpression) {
    panelData.conditionExpression = bo.conditionExpression.body || ''
  }
  // 文档
  panelData.documentation = ''
  if (bo.documentation && bo.documentation.length > 0) {
    panelData.documentation = bo.documentation[0].text || ''
  }
}

// 更新 BPMN 元素属性
function updateElementProperty(propertyName: string, value: string | number) {
  if (!selectedElement.value || !modeler.value) return
  const element = selectedElement.value
  // bpmn-js 的 get() 返回 unknown，这里用类型断言收敛到具体的服务类型（避免引入 any）
  const modeling = modeler.value.get('modeling') as {
    updateProperties: (el: BpmnElement, attrs: Record<string, unknown>) => void
  }
  const bpmnFactory = modeler.value.get('bpmnFactory') as {
    create: (type: string, attrs?: Record<string, unknown>) => BpmnElement
  }

  if (propertyName === 'elementName') {
    modeling.updateProperties(element, { name: value })
  } else if (propertyName === 'elementId') {
    modeling.updateProperties(element, { id: value })
  } else if (propertyName === 'conditionExpression') {
    // 条件表达式需要创建 formalExpression
    const conditionExpr = bpmnFactory.create('bpmn:FormalExpression', {
      body: value as string,
    })
    modeling.updateProperties(element, { conditionExpression: conditionExpr })
  } else if (propertyName === 'formKey') {
    modeling.updateProperties(element, { formKey: value })
  } else if (propertyName === 'documentation') {
    const doc = bpmnFactory.create('bpmn:Documentation', { text: value as string })
    modeling.updateProperties(element, { documentation: [doc] })
  } else {
    // flowable: 命名空间扩展属性
    const attrs: Record<string, unknown> = {}
    attrs[`flowable:${propertyName}`] = value
    modeling.updateProperties(element, attrs)
  }
}

// 属性变更处理
function onPropertyChange(propertyName: string, value: string | number) {
  updateElementProperty(propertyName, value)
}

// ==================== Lifecycle ====================
onMounted(async () => {
  await nextTick()
  initModeler()
})

onBeforeUnmount(() => {
  if (modeler.value) {
    modeler.value.destroy()
    modeler.value = null
  }
})

watch(() => props.initialXml, (newVal) => {
  if (newVal && modeler.value) {
    loadXml(newVal)
  }
})

// ==================== Init ====================
function initModeler() {
  if (!containerRef.value) return

  loading.value = true
  try {
    const m = new BpmnModeler({
      container: containerRef.value,
      keyboard: { bindTo: document },
      additionalModules: [],
    })

    modeler.value = m

    // 加载初始 XML 或空白模板
    if (props.initialXml) {
      loadXml(props.initialXml)
    } else {
      loadBlankDiagram()
    }

    // 监听变化
    m.on('commandStack.changed', async () => {
      try {
        const result = await m.saveXML({ format: true })
        currentXml.value = result.xml || ''
        const svgResult = await m.saveSVG()
        currentSvg.value = svgResult.svg || ''
      } catch {
        // ignore
      }
    })

    // P1-02: 监听元素选中变化 → 更新属性面板
    m.on('selection.changed', (event: { newSelection: BpmnElement[] }) => {
      const selection = event.newSelection
      if (selection && selection.length > 0) {
        selectedElement.value = selection[0]
        readElementProperties(selection[0])
      } else {
        selectedElement.value = null
      }
    })

    // 监听元素直接点击（不通过 selection）
    m.on('element.click', (event: { element: BpmnElement }) => {
      if (event.element && event.element.type !== 'bpmn:Process') {
        selectedElement.value = event.element
        readElementProperties(event.element)
      }
    })
  } catch (e) {
    ElMessage.error('BPMN 设计器初始化失败：' + (e as Error).message)
    logger.error('[BpmnDesigner]', e, { phase: 'init' })
  } finally {
    loading.value = false
  }
}

async function loadXml(xml: string) {
  if (!modeler.value) return
  loading.value = true
  try {
    await modeler.value.importXML(xml)
    const result = await modeler.value.saveXML({ format: true })
    currentXml.value = result.xml || ''
  } catch (e) {
    ElMessage.error('BPMN XML 导入失败：' + (e as Error).message)
    logger.error('[BpmnDesigner]', e, { phase: 'importXML' })
  } finally {
    loading.value = false
  }
}

async function loadBlankDiagram() {
  const blank = `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:flowable="http://flowable.org/bpmn"
  targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_1" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="开始">
      <bpmn:outgoing>Flow_1</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="EndEvent_1" name="结束">
      <bpmn:incoming>Flow_1</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="EndEvent_1" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="StartEvent_1_di" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="EndEvent_1_di" bpmnElement="EndEvent_1">
        <dc:Bounds x="432" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1_di" bpmnElement="Flow_1">
        <di:waypoint x="215" y="177" />
        <di:waypoint x="432" y="177" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>`
  await loadXml(blank)
}

// ==================== Actions ====================
async function handleExportXml() {
  if (!currentXml.value) {
    ElMessage.warning('请先设计流程')
    return
  }
  const blob = new Blob([currentXml.value], { type: 'application/xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${deployForm.value.flowCode || 'process'}.bpmn`
  a.click()
  URL.revokeObjectURL(url)
  ElMessage.success('BPMN XML 已导出')
}

/**
 * P1: 导出流程图为 SVG 文件
 *
 * <p>对标钉钉/飞书审批流设计器，支持将流程图导出为 SVG 矢量图，用于文档归档。
 * bpmn-js 的 saveSVG 结果已缓存在 currentSvg，直接下载即可。
 */
async function handleExportSvg() {
  if (!currentSvg.value) {
    ElMessage.warning('请先设计流程')
    return
  }
  const blob = new Blob([currentSvg.value], { type: 'image/svg+xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${deployForm.value.flowCode || 'process'}.svg`
  a.click()
  URL.revokeObjectURL(url)
  ElMessage.success('流程图 SVG 已导出')
}

/**
 * P1: 导出流程图为 PNG 文件
 *
 * <p>将 SVG 转为 Canvas 再导出 PNG，适用于非矢量场景的截图分享。
 * 通过 Image 加载 SVG data URL → drawImage 到 canvas → toDataURL('image/png') 下载。
 */
async function handleExportPng() {
  if (!currentSvg.value) {
    ElMessage.warning('请先设计流程')
    return
  }
  try {
    const svgDataUrl = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(currentSvg.value)
    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = img.naturalWidth || img.width
      canvas.height = img.naturalHeight || img.height
      const ctx = canvas.getContext('2d')
      if (!ctx) {
        ElMessage.error('Canvas 2D 上下文不可用，无法导出 PNG')
        return
      }
      ctx.fillStyle = '#ffffff'
      ctx.fillRect(0, 0, canvas.width, canvas.height)
      ctx.drawImage(img, 0, 0)
      canvas.toBlob((blob) => {
        if (!blob) {
          ElMessage.error('PNG 生成失败')
          return
        }
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${deployForm.value.flowCode || 'process'}.png`
        a.click()
        URL.revokeObjectURL(url)
        ElMessage.success('流程图 PNG 已导出')
      }, 'image/png')
    }
    img.onerror = () => {
      ElMessage.error('SVG 加载失败，无法导出 PNG')
    }
    img.src = svgDataUrl
  } catch (e) {
    ElMessage.error('PNG 导出失败：' + (e as Error).message)
  }
}

async function handleImportXml() {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = '.bpmn,.xml'
  input.onchange = async (e: Event) => {
    const file = (e.target as HTMLInputElement).files?.[0]
    if (!file) return
    const text = await file.text()
    await loadXml(text)
    ElMessage.success('BPMN XML 已导入')
  }
  input.click()
}

async function handleSave() {
  if (!currentXml.value) {
    ElMessage.warning('请先设计流程')
    return
  }
  saving.value = true
  try {
    emit('save', currentXml.value, currentSvg.value)
    ElMessage.success('流程已保存')
  } finally {
    saving.value = false
  }
}

async function handleDeploy() {
  if (!currentXml.value) {
    ElMessage.warning('请先设计流程')
    return
  }
  if (!deployForm.value.flowCode.trim()) {
    ElMessage.warning('请输入流程编码')
    return
  }
  if (!deployForm.value.flowName.trim()) {
    ElMessage.warning('请输入流程名称')
    return
  }
  saving.value = true
  try {
    const payload: FlowDeployDTO = {
      flowCode: deployForm.value.flowCode.trim(),
      flowName: deployForm.value.flowName.trim(),
      category: deployForm.value.category,
      formPath: deployForm.value.formPath,
      bpmnXml: currentXml.value,
    }
    const res = await deployDefinition(payload)
    if (res.data?.code === 0) {
      ElMessage.success(`流程部署成功，定义 ID: ${res.data.data}`)
      emit('deploy', deployForm.value.flowCode, deployForm.value.flowName, currentXml.value)
    } else {
      ElMessage.error(res.data?.message || '部署失败')
    }
  } catch (e) {
    ElMessage.error('部署失败：' + (e as Error).message)
  } finally {
    saving.value = false
  }
}

function handleReset() {
  loadBlankDiagram()
  ElMessage.success('已重置为空白流程')
}

/**
 * P2-3: 一键自动布局（dagre 分层有向图）
 *
 * <p>解决 bpmn-js 内置 BpmnAutoPlace 对网关分叉/并行汇聚场景节点重叠、连线交叉的问题。
 * 用户点击按钮触发，不破坏手动调整结果；坐标通过 moveShape 写入 BPMNDI 段，
 * 部署后实例详情/回放均能透传。
 */
function handleAutoLayout() {
  if (!modeler.value) return
  try {
    autoLayout(modeler.value)
    ElMessage.success('已自动布局')
  } catch (e) {
    ElMessage.error('自动布局失败：' + (e as Error).message)
  }
}

/**
 * P2-5: 画布缩放与适配视图
 *
 * <p>对标钉钉/飞书审批流设计器，提供放大/缩小/适配画布三件套。
 * 基于 bpmn-js 内置 zoomScroll 与 canvas 服务，无需额外依赖。
 */
function handleZoomIn() {
  if (!modeler.value) return
  // bpmn-js 的 get() 返回 unknown，用类型断言收敛
  const zoomScroll = modeler.value.get('zoomScroll') as { stepZoom: (step: number) => void }
  zoomScroll.stepZoom(1)
}

function handleZoomOut() {
  if (!modeler.value) return
  const zoomScroll = modeler.value.get('zoomScroll') as { stepZoom: (step: number) => void }
  zoomScroll.stepZoom(-1)
}

function handleFitView() {
  if (!modeler.value) return
  const canvas = modeler.value.get('canvas') as { zoom: (level: string | number, position?: string) => void }
  canvas.zoom('fit-viewport', 'auto')
}

// ==================== Templates ====================
const templates = [
  {
    label: '空白流程',
    xml: '', // triggers loadBlankDiagram
  },
  {
    label: '请假审批（2级）',
    xml: `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:flowable="http://flowable.org/bpmn" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_Leave" name="请假审批" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="发起请假"/>
    <bpmn:userTask id="Task_Manager" name="直属上级审批" flowable:assignee="\${leader}"/>
    <bpmn:userTask id="Task_HR" name="HR审批" flowable:assignee="\${hr}"/>
    <bpmn:endEvent id="EndEvent_1" name="结束"/>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="Task_Manager"/>
    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Manager" targetRef="Task_HR"/>
    <bpmn:sequenceFlow id="Flow_3" sourceRef="Task_HR" targetRef="EndEvent_1"/>
  </bpmn:process>
</bpmn:definitions>`,
  },
  {
    label: '报销审批（含条件）',
    xml: `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:flowable="http://flowable.org/bpmn" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_Expense" name="报销审批" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="发起报销"/>
    <bpmn:userTask id="Task_Manager" name="直属上级审批" flowable:assignee="\${leader}"/>
    <bpmn:exclusiveGateway id="Gateway_Amount" name="金额判断"/>
    <bpmn:userTask id="Task_Director" name="总监审批" flowable:assignee="\${director}"/>
    <bpmn:userTask id="Task_Finance" name="财务审批" flowable:assignee="\${finance}"/>
    <bpmn:endEvent id="EndEvent_1" name="结束"/>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="Task_Manager"/>
    <bpmn:sequenceFlow id="Flow_2" sourceRef="Task_Manager" targetRef="Gateway_Amount"/>
    <bpmn:sequenceFlow id="Flow_3" sourceRef="Gateway_Amount" targetRef="Task_Director">
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">\${amount > 5000}</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_4" sourceRef="Gateway_Amount" targetRef="Task_Finance">
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">\${amount <= 5000}</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_Director" targetRef="Task_Finance"/>
    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_Finance" targetRef="EndEvent_1"/>
  </bpmn:process>
</bpmn:definitions>`,
  },
  {
    label: '合同审批（并行）',
    xml: `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:flowable="http://flowable.org/bpmn" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_Contract" name="合同审批" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="发起合同"/>
    <bpmn:parallelGateway id="Gateway_Split" name="并行分支"/>
    <bpmn:userTask id="Task_Legal" name="法务审核" flowable:assignee="\${legal}"/>
    <bpmn:userTask id="Task_Finance" name="财务审核" flowable:assignee="\${finance}"/>
    <bpmn:userTask id="Task_Biz" name="业务审核" flowable:assignee="\${biz}"/>
    <bpmn:parallelGateway id="Gateway_Join" name="并行汇聚"/>
    <bpmn:userTask id="Task_CEO" name="CEO审批" flowable:assignee="\${ceo}"/>
    <bpmn:endEvent id="EndEvent_1" name="结束"/>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="StartEvent_1" targetRef="Gateway_Split"/>
    <bpmn:sequenceFlow id="Flow_2" sourceRef="Gateway_Split" targetRef="Task_Legal"/>
    <bpmn:sequenceFlow id="Flow_3" sourceRef="Gateway_Split" targetRef="Task_Finance"/>
    <bpmn:sequenceFlow id="Flow_4" sourceRef="Gateway_Split" targetRef="Task_Biz"/>
    <bpmn:sequenceFlow id="Flow_5" sourceRef="Task_Legal" targetRef="Gateway_Join"/>
    <bpmn:sequenceFlow id="Flow_6" sourceRef="Task_Finance" targetRef="Gateway_Join"/>
    <bpmn:sequenceFlow id="Flow_7" sourceRef="Task_Biz" targetRef="Gateway_Join"/>
    <bpmn:sequenceFlow id="Flow_8" sourceRef="Gateway_Join" targetRef="Task_CEO"/>
    <bpmn:sequenceFlow id="Flow_9" sourceRef="Task_CEO" targetRef="EndEvent_1"/>
  </bpmn:process>
</bpmn:definitions>`,
  },
]

function applyTemplate(tpl: (typeof templates)[0]) {
  if (!tpl.xml) {
    loadBlankDiagram()
  } else {
    loadXml(tpl.xml)
  }
  ElMessage.success(`已加载模板：${tpl.label}`)
}
</script>

<template>
  <div class="bpmn-designer">
    <!-- 工具栏 -->
    <div class="bpmn-toolbar">
      <div class="bpmn-toolbar-left">
        <el-dropdown @command="(cmd: string) => { const t = templates.find(x => x.label === cmd); if (t) applyTemplate(t) }">
          <el-button size="small">
            模板 <el-icon class="el-icon--right"><ArrowDown /></el-icon>
          </el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item
                v-for="tpl in templates"
                :key="tpl.label"
                :command="tpl.label"
              >{{ tpl.label }}</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </div>
      <div class="bpmn-toolbar-right">
        <el-button size="small" @click="handleImportXml">导入 XML</el-button>
        <el-dropdown @command="(cmd: string) => { switch (cmd) { case 'xml': handleExportXml(); break; case 'svg': handleExportSvg(); break; case 'png': handleExportPng(); break } }" :disabled="!currentXml">
          <el-button size="small" :disabled="!currentXml">
            导出 <el-icon class="el-icon--right"><ArrowDown /></el-icon>
          </el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item command="xml">BPMN XML</el-dropdown-item>
              <el-dropdown-item command="svg">SVG 矢量图</el-dropdown-item>
              <el-dropdown-item command="png">PNG 图片</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
        <el-button-group class="zoom-group">
          <el-button size="small" @click="handleZoomOut" :disabled="!currentXml" title="缩小">－</el-button>
          <el-button size="small" @click="handleFitView" :disabled="!currentXml" title="适配画布">适配</el-button>
          <el-button size="small" @click="handleZoomIn" :disabled="!currentXml" title="放大">＋</el-button>
        </el-button-group>
        <el-button size="small" @click="handleAutoLayout" :disabled="!currentXml">自动布局</el-button>
        <el-button size="small" @click="handleReset">重置</el-button>
        <el-button size="small" type="primary" @click="handleSave" :loading="saving" :disabled="!currentXml">
          保存
        </el-button>
      </div>
    </div>

    <!-- 画布 + 属性面板 -->
    <div class="bpmn-body">
      <div class="bpmn-canvas" ref="containerRef" v-loading="loading">
        <div v-if="loading" class="bpmn-loading-overlay">
          <span>正在加载 BPMN 设计器...</span>
        </div>
      </div>

      <!-- P1-02: 自定义属性面板 -->
      <div class="bpmn-property-panel">
        <div v-if="!selectedElement" class="panel-empty">
          <el-empty description="选择一个元素查看属性" :image-size="60" />
        </div>

        <template v-else>
          <div class="panel-header">
            <span class="panel-title">{{ elementTypeLabel(panelData.elementType) }}</span>
            <el-tag size="small" type="info">{{ panelData.elementType }}</el-tag>
          </div>

          <el-form label-width="80px" size="small" class="panel-form">
            <!-- 通用属性 -->
            <template v-if="hasGeneralProps()">
              <el-divider content-position="left">基本信息</el-divider>
              <el-form-item label="节点ID">
                <el-input
                  v-model="panelData.elementId"
                  @change="(v: string) => onPropertyChange('elementId', v)"
                />
              </el-form-item>
              <el-form-item label="节点名称">
                <el-input
                  v-model="panelData.elementName"
                  @change="(v: string) => onPropertyChange('elementName', v)"
                />
              </el-form-item>
            </template>

            <!-- 审批节点属性 -->
            <template v-if="isUserTask()">
              <el-divider content-position="left">审批配置</el-divider>
              <el-form-item label="审批人">
                <el-input
                  v-model="panelData.assignee"
                  placeholder="${leader} 或用户ID"
                  @change="(v: string) => onPropertyChange('assignee', v)"
                />
              </el-form-item>
              <el-form-item label="审批人类型">
                <el-select
                  v-model="panelData.assigneeType"
                  placeholder="选择审批人类型"
                  @change="(v: string) => onPropertyChange('assigneeType', v)"
                >
                  <el-option label="指定用户" value="user" />
                  <el-option label="指定角色" value="role" />
                  <el-option label="指定部门" value="dept" />
                  <el-option label="发起人自己" value="initiator" />
                  <el-option label="直属上级" value="leader" />
                  <el-option label="上级的上级" value="superior" />
                </el-select>
              </el-form-item>
              <el-form-item label="会签类型">
                <el-select
                  v-model="panelData.performType"
                  placeholder="选择会签类型"
                  @change="(v: string) => onPropertyChange('performType', v)"
                >
                  <el-option label="单人审批" value="" />
                  <el-option label="依次审批" value="sequential" />
                  <el-option label="并行审批" value="parallel" />
                  <el-option label="投票审批" value="vote" />
                </el-select>
              </el-form-item>
              <el-form-item label="表单Key">
                <el-input
                  v-model="panelData.formKey"
                  placeholder="表单标识"
                  @change="(v: string) => onPropertyChange('formKey', v)"
                />
              </el-form-item>
              <el-form-item label="超期时间">
                <el-input
                  v-model="panelData.dueDate"
                  placeholder="如 PT48H（48小时）"
                  @change="(v: string) => onPropertyChange('dueDate', v)"
                />
              </el-form-item>
              <el-form-item label="优先级">
                <el-input-number
                  v-model="panelData.priority"
                  :min="0"
                  :max="100"
                  @change="(v: number | undefined) => onPropertyChange('priority', v ?? 0)"
                />
              </el-form-item>

              <!-- P1-2: SLA 超时策略配置（仅已部署流程可配置） -->
              <el-divider content-position="left">SLA 策略</el-divider>
              <div v-if="props.definitionId" class="field-perm-wrap">
                <SlaRuleConfig
                  :definition-id="props.definitionId"
                  :node-code="panelData.elementId"
                />
              </div>
              <div v-else class="field-perm-tip">
                请先发布部署流程后再配置 SLA 策略
              </div>

              <!-- P0-3: 字段权限配置（仅已部署流程可配置） -->
              <el-divider content-position="left">字段权限</el-divider>
              <div v-if="props.definitionId" class="field-perm-wrap">
                <FormFieldPermissions
                  :definition-id="props.definitionId"
                  :node-code="panelData.elementId"
                />
              </div>
              <div v-else class="field-perm-tip">
                请先发布部署流程后再配置字段权限
              </div>
            </template>

            <!-- 连线条件表达式 -->
            <template v-if="isSequenceFlow()">
              <el-divider content-position="left">条件路由</el-divider>
              <el-form-item label="条件表达式">
                <el-input
                  v-model="panelData.conditionExpression"
                  type="textarea"
                  :rows="3"
                  placeholder='${amount > 5000}'
                  @change="(v: string) => onPropertyChange('conditionExpression', v)"
                />
                <div class="form-tip">使用 ${expr} 语法，支持 SpEL 表达式</div>
              </el-form-item>
            </template>

            <!-- 节点说明 -->
            <template v-if="hasGeneralProps()">
              <el-divider content-position="left">其他</el-divider>
              <el-form-item label="节点说明">
                <el-input
                  v-model="panelData.documentation"
                  type="textarea"
                  :rows="2"
                  placeholder="节点备注说明"
                  @change="(v: string) => onPropertyChange('documentation', v)"
                />
              </el-form-item>
            </template>
          </el-form>
        </template>
      </div>
    </div>

    <!-- 部署面板 -->
    <div class="bpmn-deploy-bar">
      <el-input
        v-model="deployForm.flowCode"
        placeholder="流程编码（如 project_initiation）"
        size="small"
        style="width: 200px"
      />
      <el-input
        v-model="deployForm.flowName"
        placeholder="流程名称（如 项目立项审批）"
        size="small"
        style="width: 200px"
      />
      <el-select
        v-model="deployForm.category"
        size="small"
        style="width: 140px"
      >
        <el-option label="通用" value="GENERAL" />
        <el-option label="项目" value="PROJECT" />
        <el-option label="财务" value="FINANCE" />
        <el-option label="人事" value="HR" />
        <el-option label="行政" value="ADMIN" />
        <el-option label="采购" value="PURCHASE" />
      </el-select>
      <el-input
        v-model="deployForm.formPath"
        placeholder="表单路径（可选）"
        size="small"
        style="width: 180px"
      />
      <el-button size="small" type="success" @click="handleDeploy" :loading="saving" :disabled="!currentXml">
        发布部署
      </el-button>
    </div>
  </div>
</template>

<style scoped>
.bpmn-designer {
  display: flex;
  flex-direction: column;
  height: 100%;
  border: 1px solid var(--el-border-color);
  border-radius: 8px;
  overflow: hidden;
  background: #fff;
}

.bpmn-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 12px;
  border-bottom: 1px solid var(--el-border-color-light);
  background: #fafbfc;
  flex-shrink: 0;
}

.bpmn-toolbar-left,
.bpmn-toolbar-right {
  display: flex;
  gap: 8px;
  align-items: center;
}

.bpmn-body {
  flex: 1;
  display: flex;
  min-height: 0;
  overflow: hidden;
}

.bpmn-canvas {
  flex: 1;
  min-height: 500px;
  position: relative;
  overflow: hidden;
}

.bpmn-property-panel {
  width: 320px;
  flex-shrink: 0;
  border-left: 1px solid var(--el-border-color-light);
  background: #fff;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
}

.panel-empty {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 14px;
  border-bottom: 1px solid var(--el-border-color-lighter);
  background: #fafbfc;
}

.panel-title {
  font-size: 14px;
  font-weight: 600;
  color: #1e293b;
}

.panel-form {
  padding: 8px 14px 16px;
}

.panel-form :deep(.el-divider) {
  margin: 12px 0;
}

.panel-form :deep(.el-divider__text) {
  font-size: 12px;
  color: #64748b;
}

.form-tip {
  font-size: 11px;
  color: #94a3b8;
  margin-top: 2px;
  line-height: 1.4;
}

/* P0-3: 字段权限配置区块 */
.field-perm-wrap {
  padding: 4px 0 8px;
}

.field-perm-tip {
  font-size: 12px;
  color: #94a3b8;
  padding: 8px 12px;
  background: #f8fafc;
  border-radius: 4px;
  line-height: 1.5;
}

.bpmn-canvas :deep(.bjs-powered-by) {
  display: none;
}

.bpmn-canvas :deep(.djs-palette) {
  left: 8px;
  top: 8px;
  border-radius: 6px;
  border-color: var(--el-border-color);
}

.bpmn-canvas :deep(.djs-context-pad) {
  border-radius: 6px;
}

/* P2-5: 节点悬停 / 选中高亮 — 对标钉钉/飞书审批流设计器视觉反馈 */
.bpmn-canvas :deep(.djs-element.djs-hover:not(.djs-connection)) {
  outline: 2px solid var(--el-color-primary);
  outline-offset: 1px;
}

.bpmn-canvas :deep(.djs-element.selected:not(.djs-connection)) {
  outline: 2px dashed var(--el-color-primary);
  outline-offset: 2px;
}

/* 连线悬停高亮 */
.bpmn-canvas :deep(.djs-element.djs-hover.djs-connection .djs-visual > path) {
  stroke: var(--el-color-primary);
  stroke-width: 2px;
}

.bpmn-canvas :deep(.djs-element.selected.djs-connection .djs-visual > path) {
  stroke: var(--el-color-primary);
  stroke-width: 2px;
}

/* zoom 按钮组紧凑显示 */
.zoom-group {
  display: inline-flex;
}

.zoom-group :deep(.el-button) {
  padding-left: 10px;
  padding-right: 10px;
  font-weight: 600;
}

.bpmn-loading-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.85);
  z-index: 10;
  color: var(--el-text-color-secondary);
  font-size: 14px;
}

.bpmn-deploy-bar {
  display: flex;
  gap: 8px;
  align-items: center;
  padding: 8px 12px;
  border-top: 1px solid var(--el-border-color-light);
  background: #fafbfc;
  flex-shrink: 0;
  flex-wrap: wrap;
}

/* P2-4: 移动端响应式适配 */
@media (max-width: 768px) {
  .bpmn-designer {
    .bpmn-toolbar {
      flex-wrap: wrap;
      padding: 6px 8px;
    }

    .bpmn-body {
      flex-direction: column;
    }

    .bpmn-property-panel {
      width: 100%;
      max-height: 240px;
      border-left: none;
      border-top: 1px solid var(--el-border-color-light);
    }

    .bpmn-canvas {
      min-height: 300px;
    }
  }
}
</style>