<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.remisoft</groupId>
        <artifactId>remi-nextwiki</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>remi-nextwiki-api</artifactId>
    <name>remi-nextwiki-api</name>
    <description>API Layer - Feign 客户端与跨服务 DTO</description>
    <dependencies>
        <dependency>
            <groupId>com.remisoft</groupId>
            <artifactId>remi-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.remisoft</groupId>
            <artifactId>remi-common-feign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
    </dependencies>
</project>
