# PROD HPA:对流量大的服务做自动伸缩
# 需要集群安装 metrics-server

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-gateway
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-gateway
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-system
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-system
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-userinfo
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-userinfo
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-project
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-project
  minReplicas: 4
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-message
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-message
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-workflow
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-workflow
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ydsz-pmis-agent
  namespace: pmis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ydsz-pmis-agent
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
