-- ----------------------------------------------------------------------------
-- 模块名   : ydsz-system（系统管理模块）
-- 说明     : 基于 ydsz-system-infra 实体类整理的完整建表脚本
--            （租户/套餐、字典、配置、应用、变量、实体版本）
-- 日期     : 2026-09-07
-- @author  : ydsz-team
-- ----------------------------------------------------------------------------

-- ============================================================================
-- 租户 / 套餐
-- ============================================================================

-- 租户主表（SaaS 多租户核心元数据）
-- ============================================================================
-- 转换说明: 由 MySQL 8.0 版本自动转译生成 (PostgreSQL 11+)
--   - 类型映射: JSON→JSONB / TINYINT(1)→SMALLINT / INT→INTEGER / DATETIME→TIMESTAMP
--   - ON UPDATE CURRENT_TIMESTAMP → BEFORE UPDATE 触发器 (文件末尾统一生成)
--   - AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   - 索引/约束名按 schema 级唯一性命名: idx_{table}_{core} / uk_{table}_{core}
--   - 原 MySQL 前缀索引 path(255) → 表达式索引 left(path,255)
--   - 原 MySQL FULLTEXT 索引 → GIN to_tsvector('simple', ...) 全文索引
--   - 执行方式: psql -U <user> -d <db> -f ydsz-system.sql
-- ============================================================================


CREATE TABLE IF NOT EXISTS ydsz_sys_tenant (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    tenant_code              VARCHAR(64)              NOT NULL,
    tenant_name              VARCHAR(128)             NOT NULL,
    contact_name             VARCHAR(64)              DEFAULT NULL,
    contact_phone            VARCHAR(32)              DEFAULT NULL,
    contact_email            VARCHAR(128)             DEFAULT NULL,
    plan_id                  VARCHAR(32)              DEFAULT NULL,
    expire_at                TIMESTAMP                DEFAULT NULL,
    datasource_key           VARCHAR(64)              DEFAULT NULL,
    remark                   VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_tenant PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_tenant_tenant_code UNIQUE (tenant_code)
);

COMMENT ON TABLE ydsz_sys_tenant IS '租户主表';
COMMENT ON COLUMN ydsz_sys_tenant.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_tenant.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_tenant.tenant_code IS '租户编码（唯一业务标识，租户登录/调用使用）';
COMMENT ON COLUMN ydsz_sys_tenant.tenant_name IS '租户名称（展示用）';
COMMENT ON COLUMN ydsz_sys_tenant.contact_name IS '联系人姓名';
COMMENT ON COLUMN ydsz_sys_tenant.contact_phone IS '联系电话（脱敏返回）';
COMMENT ON COLUMN ydsz_sys_tenant.contact_email IS '联系邮箱（脱敏返回）';
COMMENT ON COLUMN ydsz_sys_tenant.plan_id IS '关联套餐 ID（ydsz_sys_tenant_plan.id）';
COMMENT ON COLUMN ydsz_sys_tenant.expire_at IS '订阅到期时间（到期后租户被自动锁定/降级）';
COMMENT ON COLUMN ydsz_sys_tenant.datasource_key IS '独立数据源标识（ISOLATE_DB 模式下使用）';
COMMENT ON COLUMN ydsz_sys_tenant.remark IS '备注';
COMMENT ON COLUMN ydsz_sys_tenant.status IS '状态标识（ENABLED/DISABLED，启用状态值）';
COMMENT ON COLUMN ydsz_sys_tenant.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_tenant.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_tenant.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_tenant.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_tenant.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_tenant.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_tenant_plan_id ON ydsz_sys_tenant (plan_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_sys_tenant_tenant_deleted ON ydsz_sys_tenant ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_tenant_plan (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    plan_code                VARCHAR(64)              NOT NULL,
    plan_name                VARCHAR(128)             NOT NULL,
    description              TEXT                     DEFAULT NULL,
    sort               INTEGER                  NOT NULL DEFAULT 0,
    quota_json               JSONB                    DEFAULT NULL,
    feature_json             JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_tenant_plan PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_tenant_plan_plan_code UNIQUE (plan_code)
);

COMMENT ON TABLE ydsz_sys_tenant_plan IS '租户套餐表';
COMMENT ON COLUMN ydsz_sys_tenant_plan.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.plan_code IS '套餐编码（唯一标识，如 TRIAL/STANDARD/ENTERPRISE）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.plan_name IS '套餐名称（展示用，如「试用版」「企业版」）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.description IS '套餐描述（包含价格、功能清单、配额上限）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.sort IS '排序号（升序，影响前端套餐选择器顺序）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.quota_json IS '资源配额 JSON（如 {"maxUsers":50,"maxProjects":10,"storageGb":100}）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.feature_json IS '功能开关 JSON（如 {"workflow":true,"dataAnalytics":false}）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_tenant_plan.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_tenant_plan.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_tenant_plan.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_tenant_plan.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_tenant_plan.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_tenant_plan.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_tenant_plan_tenant_deleted ON ydsz_sys_tenant_plan ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_tenant_plan_menu (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    plan_id                  VARCHAR(32)              NOT NULL,
    menu_id                  VARCHAR(64)              NOT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_tenant_plan_menu PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_tenant_plan_menu_plan_menu UNIQUE (plan_id, menu_id)
);

COMMENT ON TABLE ydsz_sys_tenant_plan_menu IS '租户套餐菜单关联表';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.plan_id IS '套餐 ID（ydsz_sys_tenant_plan.id）';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.menu_id IS '菜单 ID（ydsz_menu.id 或权限码 ydsz:xxx）';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_tenant_plan_menu.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_tenant_plan_menu_tenant_deleted ON ydsz_sys_tenant_plan_menu ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_dict_type (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    type_code                VARCHAR(64)              NOT NULL,
    type_name                VARCHAR(128)             NOT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_dict_type PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_dict_type_type_code UNIQUE (type_code)
);

COMMENT ON TABLE ydsz_sys_dict_type IS '字典类型表';
COMMENT ON COLUMN ydsz_sys_dict_type.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_dict_type.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_dict_type.type_code IS '类型编码（唯一标识，用于业务引用）';
COMMENT ON COLUMN ydsz_sys_dict_type.type_name IS '类型名称（展示用）';
COMMENT ON COLUMN ydsz_sys_dict_type.description IS '类型描述';
COMMENT ON COLUMN ydsz_sys_dict_type.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_dict_type.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_dict_type.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_dict_type.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_dict_type.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_dict_type.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_dict_type.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_dict_type_tenant_deleted ON ydsz_sys_dict_type ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_dict_item (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    type_code                VARCHAR(64)              NOT NULL,
    item_code                VARCHAR(64)              NOT NULL,
    item_value               VARCHAR(128)             NOT NULL,
    sort               INTEGER                  NOT NULL DEFAULT 0,
    parent_id                VARCHAR(32)              DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    ext_json                 JSONB                    DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_dict_item PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_dict_item_type_item_code UNIQUE (type_code, item_code)
);

COMMENT ON TABLE ydsz_sys_dict_item IS '字典项表';
COMMENT ON COLUMN ydsz_sys_dict_item.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_dict_item.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_dict_item.type_code IS '所属字典类型编码（逻辑外键 → ydsz_sys_dict_type.type_code）';
COMMENT ON COLUMN ydsz_sys_dict_item.item_code IS '字典项编码（同 typeCode 内唯一）';
COMMENT ON COLUMN ydsz_sys_dict_item.item_value IS '字典项真实值（业务代码引用的枚举值，如 "PAID"）';
COMMENT ON COLUMN ydsz_sys_dict_item.sort IS '展示排序序号（升序）';
COMMENT ON COLUMN ydsz_sys_dict_item.parent_id IS '父级字典项 ID（支持树形字典，如行政区划）';
COMMENT ON COLUMN ydsz_sys_dict_item.description IS '字典项描述';
COMMENT ON COLUMN ydsz_sys_dict_item.ext_json IS '扩展属性 JSON（承载自定义属性，如色值、图标、URL 等）';
COMMENT ON COLUMN ydsz_sys_dict_item.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_dict_item.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_dict_item.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_dict_item.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_dict_item.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_dict_item.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_dict_item.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_dict_item_parent_id ON ydsz_sys_dict_item (parent_id);
CREATE INDEX IF NOT EXISTS idx_ydsz_sys_dict_item_tenant_deleted ON ydsz_sys_dict_item ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_config (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    config_group             VARCHAR(64)              NOT NULL,
    config_key               VARCHAR(128)             NOT NULL,
    config_value             TEXT                     DEFAULT NULL,
    value_type               VARCHAR(32)              NOT NULL,
    default_value            TEXT                     DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    is_public                SMALLINT                 NOT NULL DEFAULT 0,
    sort               INTEGER                  NOT NULL DEFAULT 0,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_config PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_config_config_group_key UNIQUE (config_group, config_key)
);

COMMENT ON TABLE ydsz_sys_config IS '系统配置表';
COMMENT ON COLUMN ydsz_sys_config.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_config.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_config.config_group IS '配置分组（按业务域分类管理配置）';
COMMENT ON COLUMN ydsz_sys_config.config_key IS '配置键（同组内唯一标识）';
COMMENT ON COLUMN ydsz_sys_config.config_value IS '配置值';
COMMENT ON COLUMN ydsz_sys_config.value_type IS '值类型（STRING/NUMBER/BOOLEAN/JSON）';
COMMENT ON COLUMN ydsz_sys_config.default_value IS '默认值（配置未设置时使用）';
COMMENT ON COLUMN ydsz_sys_config.description IS '配置描述';
COMMENT ON COLUMN ydsz_sys_config.is_public IS '是否公开配置（1=公开，前端可查；0=私有，仅后端可查）';
COMMENT ON COLUMN ydsz_sys_config.sort IS '排序序号';
COMMENT ON COLUMN ydsz_sys_config.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_config.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_config.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_config.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_config.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_config.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_config.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_config_tenant_deleted ON ydsz_sys_config ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_variable (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    variable_key             VARCHAR(128)             NOT NULL,
    variable_value           TEXT                     DEFAULT NULL,
    value_type               VARCHAR(32)              NOT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_variable PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_variable_variable_key UNIQUE (variable_key)
);

COMMENT ON TABLE ydsz_sys_variable IS '系统变量表';
COMMENT ON COLUMN ydsz_sys_variable.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_variable.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_variable.variable_key IS '变量键（唯一标识，全局唯一）';
COMMENT ON COLUMN ydsz_sys_variable.variable_value IS '变量值（按 valueType 反序列化为 String/Number/Boolean/JSON）';
COMMENT ON COLUMN ydsz_sys_variable.value_type IS '值类型（STRING/NUMBER/BOOLEAN/JSON）';
COMMENT ON COLUMN ydsz_sys_variable.description IS '变量描述（业务含义说明）';
COMMENT ON COLUMN ydsz_sys_variable.status IS '状态标识（ENABLED/DISABLED）';
COMMENT ON COLUMN ydsz_sys_variable.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_variable.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_variable.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_variable.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_variable.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_variable.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_variable_tenant_deleted ON ydsz_sys_variable ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_app_info (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    app_code                 VARCHAR(64)              NOT NULL,
    app_name                 VARCHAR(128)             NOT NULL,
    app_key                  VARCHAR(64)              NOT NULL,
    app_secret               VARCHAR(128)             NOT NULL,
    redirect_url             VARCHAR(1024)            DEFAULT NULL,
    scopes                   VARCHAR(512)             DEFAULT NULL,
    bound_ips                VARCHAR(512)             DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_app_info PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_app_info_app_code UNIQUE (app_code),
    CONSTRAINT uk_ydsz_sys_app_info_tenant_app_key UNIQUE (tenant_id, app_key)
);

COMMENT ON TABLE ydsz_sys_app_info IS '应用信息表';
COMMENT ON COLUMN ydsz_sys_app_info.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_app_info.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_app_info.app_code IS '应用业务编码（对外展示/业务标识，全局唯一）';
COMMENT ON COLUMN ydsz_sys_app_info.app_name IS '应用名称';
COMMENT ON COLUMN ydsz_sys_app_info.app_key IS '应用唯一标识（认证查询入口，语义等价 OAuth2 client_id，租户内唯一）';
COMMENT ON COLUMN ydsz_sys_app_info.app_secret IS '应用安全密钥（BCrypt 哈希存储，语义等价 OAuth2 client_secret）';
COMMENT ON COLUMN ydsz_sys_app_info.redirect_url IS 'OAuth2 授权回调地址';
COMMENT ON COLUMN ydsz_sys_app_info.scopes IS 'OAuth2 授权范围（CSV 格式，如 "user.read,order.write"）';
COMMENT ON COLUMN ydsz_sys_app_info.bound_ips IS 'IP 绑定白名单（CSV 格式；为空表示不限制 IP）';
COMMENT ON COLUMN ydsz_sys_app_info.description IS '应用描述';
COMMENT ON COLUMN ydsz_sys_app_info.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_app_info.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_app_info.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_app_info.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_app_info.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_app_info.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_app_info.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_app_info_tenant_deleted ON ydsz_sys_app_info ((tenant_id, is_deleted));

CREATE TABLE IF NOT EXISTS ydsz_sys_entity_version (
    id                       VARCHAR(32)             ,
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    resource_type            VARCHAR(32)              NOT NULL,
    resource_key             VARCHAR(128)             NOT NULL,
    resource_group           VARCHAR(64)              DEFAULT NULL,
    version                  VARCHAR(32)              NOT NULL,
    change_log               VARCHAR(512)             DEFAULT NULL,
    snapshot_json            JSONB                    DEFAULT NULL,
    effective_date           TIMESTAMP                DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT NULL,
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_entity_version PRIMARY KEY (id)
);

COMMENT ON TABLE ydsz_sys_entity_version IS '统一实体版本表';
COMMENT ON COLUMN ydsz_sys_entity_version.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_entity_version.tenant_id IS '租户 ID（多租户隔离）';
COMMENT ON COLUMN ydsz_sys_entity_version.resource_type IS '资源类型（CONFIG/DICT/VARIABLE）';
COMMENT ON COLUMN ydsz_sys_entity_version.resource_key IS '资源唯一标识（configKey/typeCode/variableKey）';
COMMENT ON COLUMN ydsz_sys_entity_version.resource_group IS '资源分组（仅 CONFIG 类型使用，其他为 null）';
COMMENT ON COLUMN ydsz_sys_entity_version.version IS '版本号字符串';
COMMENT ON COLUMN ydsz_sys_entity_version.change_log IS '变更说明';
COMMENT ON COLUMN ydsz_sys_entity_version.snapshot_json IS '变更前 JSON 快照（用于回滚）';
COMMENT ON COLUMN ydsz_sys_entity_version.effective_date IS '生效时间';
COMMENT ON COLUMN ydsz_sys_entity_version.status IS '状态标识';
COMMENT ON COLUMN ydsz_sys_entity_version.is_deleted IS '逻辑删除标识（0=未删除，1=已删除）';
COMMENT ON COLUMN ydsz_sys_entity_version.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_entity_version.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_entity_version.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_entity_version.updated_by IS '最后更新人';
COMMENT ON COLUMN ydsz_sys_entity_version.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_entity_version_resource_type_key_version ON ydsz_sys_entity_version (resource_type, resource_key, version);
CREATE INDEX IF NOT EXISTS idx_ydsz_sys_entity_version_tenant_deleted ON ydsz_sys_entity_version ((tenant_id, is_deleted));

-- ============================================================================
-- ON UPDATE CURRENT_TIMESTAMP 自动更新触发器 (PostgreSQL)
-- ============================================================================

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_tenant_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_tenant_updated_at ON ydsz_sys_tenant;
CREATE TRIGGER trg_ydsz_sys_tenant_updated_at
BEFORE UPDATE ON ydsz_sys_tenant
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_tenant_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_tenant_plan_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_tenant_plan_updated_at ON ydsz_sys_tenant_plan;
CREATE TRIGGER trg_ydsz_sys_tenant_plan_updated_at
BEFORE UPDATE ON ydsz_sys_tenant_plan
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_tenant_plan_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_tenant_plan_menu_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_tenant_plan_menu_updated_at ON ydsz_sys_tenant_plan_menu;
CREATE TRIGGER trg_ydsz_sys_tenant_plan_menu_updated_at
BEFORE UPDATE ON ydsz_sys_tenant_plan_menu
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_tenant_plan_menu_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_dict_type_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_dict_type_updated_at ON ydsz_sys_dict_type;
CREATE TRIGGER trg_ydsz_sys_dict_type_updated_at
BEFORE UPDATE ON ydsz_sys_dict_type
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_dict_type_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_dict_item_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_dict_item_updated_at ON ydsz_sys_dict_item;
CREATE TRIGGER trg_ydsz_sys_dict_item_updated_at
BEFORE UPDATE ON ydsz_sys_dict_item
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_dict_item_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_config_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_config_updated_at ON ydsz_sys_config;
CREATE TRIGGER trg_ydsz_sys_config_updated_at
BEFORE UPDATE ON ydsz_sys_config
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_config_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_variable_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_variable_updated_at ON ydsz_sys_variable;
CREATE TRIGGER trg_ydsz_sys_variable_updated_at
BEFORE UPDATE ON ydsz_sys_variable
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_variable_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_app_info_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_app_info_updated_at ON ydsz_sys_app_info;
CREATE TRIGGER trg_ydsz_sys_app_info_updated_at
BEFORE UPDATE ON ydsz_sys_app_info
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_app_info_set_updated_at();

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_entity_version_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_entity_version_updated_at ON ydsz_sys_entity_version;
CREATE TRIGGER trg_ydsz_sys_entity_version_updated_at
BEFORE UPDATE ON ydsz_sys_entity_version
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_entity_version_set_updated_at();

-- ============================================================================
-- 接口权限注册表（启动时由 AppPermissionScanRunner 自动扫描 @AuthApiPermission 注解注册）
-- ============================================================================

CREATE TABLE IF NOT EXISTS ydsz_sys_api_permission (
    id                       VARCHAR(32),
    tenant_id                VARCHAR(32)              NOT NULL DEFAULT '0',
    api_code                 VARCHAR(128)             NOT NULL,
    api_name                 VARCHAR(256)             DEFAULT NULL,
    http_method              VARCHAR(10)              DEFAULT NULL,
    url_pattern              VARCHAR(512)             DEFAULT NULL,
    controller_class         VARCHAR(512)             DEFAULT NULL,
    method_name              VARCHAR(128)             DEFAULT NULL,
    description              VARCHAR(512)             DEFAULT NULL,
    status                   VARCHAR(32)              DEFAULT 'ENABLED',
    is_deleted               SMALLINT                 NOT NULL DEFAULT 0,
    revision                 INTEGER                  NOT NULL DEFAULT 0,
    created_by               VARCHAR(64)              DEFAULT NULL,
    created_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(64)              DEFAULT NULL,
    updated_at               TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ydsz_sys_api_permission PRIMARY KEY (id),
    CONSTRAINT uk_ydsz_sys_api_permission_tenant_api UNIQUE (tenant_id, api_code)
);

COMMENT ON TABLE ydsz_sys_api_permission IS '接口权限注册表';
COMMENT ON COLUMN ydsz_sys_api_permission.id IS '主键 ID（Snowflake）';
COMMENT ON COLUMN ydsz_sys_api_permission.tenant_id IS '租户 ID';
COMMENT ON COLUMN ydsz_sys_api_permission.api_code IS '权限码（如 sys:config:list）';
COMMENT ON COLUMN ydsz_sys_api_permission.api_name IS '接口名称/描述';
COMMENT ON COLUMN ydsz_sys_api_permission.http_method IS 'HTTP 方法';
COMMENT ON COLUMN ydsz_sys_api_permission.url_pattern IS 'URL 模式';
COMMENT ON COLUMN ydsz_sys_api_permission.controller_class IS 'Controller 完全限定名';
COMMENT ON COLUMN ydsz_sys_api_permission.method_name IS '方法名';
COMMENT ON COLUMN ydsz_sys_api_permission.description IS '接口描述';
COMMENT ON COLUMN ydsz_sys_api_permission.status IS '状态: ENABLED/DISABLED';
COMMENT ON COLUMN ydsz_sys_api_permission.is_deleted IS '逻辑删除: 0=未删除, 1=已删除';
COMMENT ON COLUMN ydsz_sys_api_permission.revision IS '乐观锁版本号';
COMMENT ON COLUMN ydsz_sys_api_permission.created_by IS '创建人';
COMMENT ON COLUMN ydsz_sys_api_permission.created_at IS '创建时间';
COMMENT ON COLUMN ydsz_sys_api_permission.updated_by IS '更新人';
COMMENT ON COLUMN ydsz_sys_api_permission.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ydsz_sys_api_permission_tenant_deleted ON ydsz_sys_api_permission ((tenant_id, is_deleted));
CREATE INDEX IF NOT EXISTS idx_ydsz_sys_api_permission_api_code ON ydsz_sys_api_permission (api_code);

-- 自动更新 updated_at（原 MySQL ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION fn_ydsz_sys_api_permission_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ydsz_sys_api_permission_updated_at ON ydsz_sys_api_permission;
CREATE TRIGGER trg_ydsz_sys_api_permission_updated_at
BEFORE UPDATE ON ydsz_sys_api_permission
FOR EACH ROW
EXECUTE FUNCTION fn_ydsz_sys_api_permission_set_updated_at();

-- ============================================================================
-- 初始化数据
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 默认租户套餐
-- ----------------------------------------------------------------------------
INSERT INTO ydsz_sys_tenant_plan (id, plan_code, plan_name, description, sort, quota_json, feature_json, status, is_deleted, revision)
VALUES ('plan_trial_001', 'TRIAL', '试用版', '30 天试用，基础功能体验', 1, '{"maxUsers":3,"maxProjects":2,"storageGb":1}', '{"workflow":false,"dataAnalytics":false}', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_tenant_plan (id, plan_code, plan_name, description, sort, quota_json, feature_json, status, is_deleted, revision)
VALUES ('plan_std_001', 'STANDARD', '标准版', '中小团队标准配置，含工作流引擎', 2, '{"maxUsers":50,"maxProjects":20,"storageGb":50}', '{"workflow":true,"dataAnalytics":false}', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_tenant_plan (id, plan_code, plan_name, description, sort, quota_json, feature_json, status, is_deleted, revision)
VALUES ('plan_ent_001', 'ENTERPRISE', '企业版', '大型企业级套餐，全功能无限制', 3, '{"maxUsers":null,"maxProjects":null,"storageGb":500}', '{"workflow":true,"dataAnalytics":true}', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2. 系统配置默认值 (config_group='SYSTEM')
-- ----------------------------------------------------------------------------
INSERT INTO ydsz_sys_config (id, config_group, config_key, config_value, value_type, default_value, description, public, sort, status, is_deleted, revision)
VALUES ('cfg_sys_001', 'SYSTEM', 'app.name', '云顶数据中台', 'STRING', '云顶数据中台', '系统显示名称', 1, 1, 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_config (id, config_group, config_key, config_value, value_type, default_value, description, public, sort, status, is_deleted, revision)
VALUES ('cfg_sys_002', 'SYSTEM', 'app.logoUrl', '/assets/logo.png', 'STRING', '/assets/logo.png', '系统 Logo 地址', 1, 2, 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_config (id, config_group, config_key, config_value, value_type, default_value, description, public, sort, status, is_deleted, revision)
VALUES ('cfg_sys_003', 'SYSTEM', 'i18n.defaultLanguage', 'zh-CN', 'STRING', 'zh-CN', '默认语言编码', 1, 3, 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_config (id, config_group, config_key, config_value, value_type, default_value, description, public, sort, status, is_deleted, revision)
VALUES ('cfg_sys_004', 'SYSTEM', 'security.passwordMinLength', '8', 'NUMBER', '8', '密码最小长度', 0, 10, 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_config (id, config_group, config_key, config_value, value_type, default_value, description, public, sort, status, is_deleted, revision)
VALUES ('cfg_sys_005', 'SYSTEM', 'security.maxLoginFailCount', '5', 'NUMBER', '5', '最大连续登录失败次数', 0, 11, 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- 3. 字典类型初始化
-- ----------------------------------------------------------------------------
INSERT INTO ydsz_sys_dict_type (id, type_code, type_name, description, status, is_deleted, revision)
VALUES ('dict_type_001', 'EXCEPTION_LEVEL', '异常严重级别', '后端异常响应 level 字段枚举', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_type (id, type_code, type_name, description, status, is_deleted, revision)
VALUES ('dict_type_002', 'TENANT_STATUS', '租户状态', '租户生命周期状态枚举', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_type (id, type_code, type_name, description, status, is_deleted, revision)
VALUES ('dict_type_003', 'JOB_STATUS', '任务状态', '定时任务执行状态枚举', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_type (id, type_code, type_name, description, status, is_deleted, revision)
VALUES ('dict_type_004', 'CONFIG_VALUE_TYPE', '配置值类型', '系统配置 value_type 字段枚举', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- 4. 字典项初始化
-- ----------------------------------------------------------------------------
-- EXCEPTION_LEVEL 字典项
INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_001', 'EXCEPTION_LEVEL', 'INFO', '提示', 1, '信息级别，业务可忽略', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_002', 'EXCEPTION_LEVEL', 'WARN', '警告', 2, '警告级别，需关注但非阻断', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_003', 'EXCEPTION_LEVEL', 'ERROR', '错误', 3, '错误级别，阻断业务流程', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_004', 'EXCEPTION_LEVEL', 'CRITICAL', '致命', 4, '致命级别，需立即处理', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

-- CONFIG_VALUE_TYPE 字典项
INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_010', 'CONFIG_VALUE_TYPE', 'STRING', '字符串', 1, '普通字符串', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_011', 'CONFIG_VALUE_TYPE', 'NUMBER', '数字', 2, '数值型', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_012', 'CONFIG_VALUE_TYPE', 'BOOLEAN', '布尔值', 3, 'true/false', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO ydsz_sys_dict_item (id, type_code, item_code, item_value, sort, description, status, is_deleted, revision)
VALUES ('dict_item_013', 'CONFIG_VALUE_TYPE', 'JSON', 'JSON', 4, '结构化 JSON', 'ENABLED', 0, 0)
ON CONFLICT DO NOTHING;
