package com.njydsz.pmis.agent.engine.llm;

import com.njydsz.pmis.agent.engine.AgentContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.slf4j.MDC;

import java.util.concurrent.Callable;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * AbstractHttpLlmProvider 单元测试 (批次 22 P1-5)
 *
 * <p>覆盖: 超时 / 重试 / TraceId 透传 / 降级 / 指数退避 / 失败时不降级
 */
@DisplayName("AbstractHttpLlmProvider 调用守卫")
class AbstractHttpLlmProviderTest {

    /** 测试用 Provider, 继承 AbstractHttpLlmProvider, 暴露内部逻辑 */
    static class TestProvider extends AbstractHttpLlmProvider {
        final Callable<String> callToRun;
        TestProvider(Callable<String> c) { this.callToRun = c; }
        @Override public String name() { return "test"; }
        @Override
        public String chat(String systemPrompt, String userPrompt, AgentContext context) {
            return executeWithGuard(callToRun, context);
        }
    }

    private AgentContext ctx;

    @BeforeEach
    void setUp() {
        ctx = new AgentContext();
        ctx.setBizType("TEST");
        ctx.setBizId(1L);
        ctx.setTraceId("trace-test-001");
    }

    @Test
    @DisplayName("成功路径: 第一次就成功, 不重试")
    void successFirstTry() {
        TestProvider p = new TestProvider(() -> "ok");
        String r = p.chat("sys", "user", ctx);
        assertThat(r).isEqualTo("ok");
    }

    @Test
    @DisplayName("重试 2 次后成功: 指数退避生效")
    void retryThenSuccess() {
        AtomicInteger n = new AtomicInteger(0);
        TestProvider p = new TestProvider(() -> {
            if (n.incrementAndGet() < 3) throw new RuntimeException("transient");
            return "after-retries";
        });
        p.maxRetries = 3;
        long t0 = System.currentTimeMillis();
        String r = p.chat("s", "u", ctx);
        long elapsed = System.currentTimeMillis() - t0;
        assertThat(r).isEqualTo("after-retries");
        assertThat(n.get()).isEqualTo(3);
        // 指数退避: 200ms + 600ms = 至少 800ms
        assertThat(elapsed).isGreaterThanOrEqualTo(700L);
    }

    @Test
    @DisplayName("全部失败 + 降级开启: 返回 mock 结果")
    void allFailedFallback() {
        TestProvider p = new TestProvider(() -> { throw new RuntimeException("net error"); });
        p.maxRetries = 1;
        p.fallbackToMockOnError = true;
        String r = p.chat("s", "u", ctx);
        // MockLlmProvider 缺省返回 NORMAL 等级 JSON
        assertThat(r).contains("NORMAL");
    }

    @Test
    @DisplayName("全部失败 + 降级关闭: 抛 RuntimeException")
    void allFailedNoFallback() {
        TestProvider p = new TestProvider(() -> { throw new RuntimeException("boom"); });
        p.maxRetries = 1;
        p.fallbackToMockOnError = false;
        assertThatThrownBy(() -> p.chat("s", "u", ctx))
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("test");
    }

    @Test
    @DisplayName("超时控制: 阻塞 5s 应触发 timeout")
    void timeout() {
        TestProvider p = new TestProvider(() -> {
            Thread.sleep(5_000L);
            return "should-not-reach";
        });
        p.timeoutMillis = 200L;
        p.maxRetries = 0;
        p.fallbackToMockOnError = true;
        long t0 = System.currentTimeMillis();
        String r = p.chat("s", "u", ctx);
        long elapsed = System.currentTimeMillis() - t0;
        assertThat(r).contains("NORMAL"); // 降级到 mock
        assertThat(elapsed).isLessThan(2_000L); // 不会真等 5s
    }

    @Test
    @DisplayName("TraceId 透传: 回调内 MDC.get(\"traceId\") == context.traceId")
    void traceIdPropagation() {
        String[] captured = new String[1];
        TestProvider p = new TestProvider(() -> {
            captured[0] = MDC.get("traceId");
            return "ok";
        });
        ctx.setTraceId("trace-xyz-999");
        p.chat("s", "u", ctx);
        assertThat(captured[0]).isEqualTo("trace-xyz-999");
    }

    @Test
    @DisplayName("TraceId 为空时自动生成 agent-<ts>")
    void traceIdAutoGenerated() {
        ctx.setTraceId(null);
        String[] captured = new String[1];
        TestProvider p = new TestProvider(() -> {
            captured[0] = MDC.get("traceId");
            return "ok";
        });
        p.chat("s", "u", ctx);
        assertThat(captured[0]).startsWith("agent-");
    }

    @Test
    @DisplayName("MDC 恢复: 回调后 MDC.traceId 还原")
    void mdcRestore() {
        MDC.put("traceId", "outer-trace");
        try {
            TestProvider p = new TestProvider(() -> "ok");
            ctx.setTraceId("inner-trace");
            p.chat("s", "u", ctx);
            assertThat(MDC.get("traceId")).isEqualTo("outer-trace");
        } finally {
            MDC.clear();
        }
    }

    @Test
    @DisplayName("interrupt: Callable 立即返回异常时, 总耗时仅取决于退避 sleep")
    void interruptDuringBackoff() {
        // Callable 立即抛错, 重试 1 次 (退避 200ms). 验证 base case 总时长合理
        TestProvider p = new TestProvider(() -> { throw new RuntimeException("x"); });
        p.maxRetries = 1;
        p.fallbackToMockOnError = true;
        long t0 = System.currentTimeMillis();
        p.chat("s", "u", ctx);
        long elapsed = System.currentTimeMillis() - t0;
        // 1 次重试: 1 次 Callable + 1 次 200ms 退避 + 1 次 Callable, 总 < 600ms
        assertThat(elapsed).isLessThan(600L);
    }
}
