-- =====================================================================
-- PMIS 工作流历史数据归档表 DDL
-- ---------------------------------------------------------------------
-- 模块: ydsz-pmis-workflow
-- 版本: V1.0.0_042
-- 关联: P2-3 历史数据归档 / P2-8 历史数据级别可配
-- 说明:
--   1. pmis_flow_his_instance  —— 流程实例冷存储表（保留原 ID 便于业务反查）
--   2. pmis_flow_his_variable  —— 流程变量冷存储表（拆分 JSON 为独立行，提升查询效率）
--   3. pmis_flow_his_task      —— 历史任务表（P2-3 已存在，此处仅补充注释说明）
--
-- 归档策略:
--   - 已结束实例（COMPLETED/TERMINATED/REJECTED）结束时间超过 retention-days 后归档
--   - 归档时保留原 instance.id，便于按业务 ID 反查
--   - 主表归档后物理删除（避免逻辑删除后的二次扫描）
--   - archived_at 记录归档时间，用于 purge 清理判定
--
-- 索引策略:
--   - his_instance: tenant_id + flow_code + archived_at（按租户+流程聚合查询归档数据）
--   - his_instance: archived_at（purge 清理时按时间扫描）
--   - his_variable: instance_id（按实例查询变量）
--   - his_variable: var_key（按变量键反查，用于跨实例变量分析）
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. 流程实例归档表
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pmis_flow_his_instance (
    id                BIGINT       NOT NULL,
    flow_code         VARCHAR(64)  NOT NULL,
    flow_name         VARCHAR(128),
    definition_id     BIGINT,
    flow_version      VARCHAR(32),
    business_type     VARCHAR(64),
    business_id       VARCHAR(64),
    business_no       VARCHAR(64),
    title             VARCHAR(255),
    initiator_id      BIGINT,
    initiator_name    VARCHAR(64),
    current_node_code VARCHAR(64),
    current_node_name VARCHAR(128),
    variable          TEXT,
    flow_status       VARCHAR(32)  NOT NULL,
    activity_status   SMALLINT,
    start_at          TIMESTAMP,
    end_at            TIMESTAMP,
    duration_ms       BIGINT,
    created_by        BIGINT,
    created_at        TIMESTAMP,
    updated_by        BIGINT,
    updated_at        TIMESTAMP,
    archived_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tenant_id         BIGINT,
    provider_trace_id VARCHAR(64),
    CONSTRAINT pk_pmis_flow_his_instance PRIMARY KEY (id)
);

COMMENT ON TABLE  pmis_flow_his_instance IS '流程实例归档冷存储表（保留原 ID）';
COMMENT ON COLUMN pmis_flow_his_instance.id                IS '原实例 ID（与 pmis_flow_instance.id 一致）';
COMMENT ON COLUMN pmis_flow_his_instance.flow_code         IS '流程编码';
COMMENT ON COLUMN pmis_flow_his_instance.flow_name         IS '流程名称（冗余）';
COMMENT ON COLUMN pmis_flow_his_instance.definition_id     IS '流程定义 ID';
COMMENT ON COLUMN pmis_flow_his_instance.flow_version      IS '流程版本';
COMMENT ON COLUMN pmis_flow_his_instance.business_type     IS '业务类型';
COMMENT ON COLUMN pmis_flow_his_instance.business_id       IS '业务单据 ID';
COMMENT ON COLUMN pmis_flow_his_instance.business_no       IS '业务单据编号';
COMMENT ON COLUMN pmis_flow_his_instance.title             IS '流程标题';
COMMENT ON COLUMN pmis_flow_his_instance.initiator_id      IS '发起人 ID';
COMMENT ON COLUMN pmis_flow_his_instance.initiator_name    IS '发起人姓名';
COMMENT ON COLUMN pmis_flow_his_instance.current_node_code IS '当前节点编码';
COMMENT ON COLUMN pmis_flow_his_instance.current_node_name IS '当前节点名称';
COMMENT ON COLUMN pmis_flow_his_instance.variable          IS '流程变量 JSON（原始）';
COMMENT ON COLUMN pmis_flow_his_instance.flow_status       IS '实例状态（COMPLETED/TERMINATED/REJECTED）';
COMMENT ON COLUMN pmis_flow_his_instance.activity_status   IS '激活状态：0 挂起 / 1 激活';
COMMENT ON COLUMN pmis_flow_his_instance.start_at          IS '启动时间';
COMMENT ON COLUMN pmis_flow_his_instance.end_at            IS '结束时间';
COMMENT ON COLUMN pmis_flow_his_instance.duration_ms       IS '耗时（毫秒）';
COMMENT ON COLUMN pmis_flow_his_instance.created_by        IS '创建人 ID';
COMMENT ON COLUMN pmis_flow_his_instance.created_at        IS '创建时间';
COMMENT ON COLUMN pmis_flow_his_instance.updated_by        IS '更新人 ID';
COMMENT ON COLUMN pmis_flow_his_instance.updated_at        IS '更新时间';
COMMENT ON COLUMN pmis_flow_his_instance.archived_at       IS '归档时间（用于 purge 清理判定）';
COMMENT ON COLUMN pmis_flow_his_instance.tenant_id         IS '租户 ID';
COMMENT ON COLUMN pmis_flow_his_instance.provider_trace_id IS '链路追踪 ID';

-- 按租户+流程聚合查询归档统计
CREATE INDEX IF NOT EXISTS idx_pmis_flow_his_instance_tenant_code_archived
    ON pmis_flow_his_instance (tenant_id, flow_code, archived_at);

-- purge 清理时按时间扫描
CREATE INDEX IF NOT EXISTS idx_pmis_flow_his_instance_archived_at
    ON pmis_flow_his_instance (archived_at);

-- 按业务单据反查（运维排查问题）
CREATE INDEX IF NOT EXISTS idx_pmis_flow_his_instance_business
    ON pmis_flow_his_instance (business_type, business_id);


-- ---------------------------------------------------------------------
-- 2. 流程变量归档表（将 instance.variable JSON 拆分为独立行）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pmis_flow_his_variable (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    instance_id  BIGINT       NOT NULL,
    var_key      VARCHAR(128) NOT NULL,
    var_value    TEXT,
    archived_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pmis_flow_his_variable PRIMARY KEY (id),
    CONSTRAINT fk_pmis_flow_his_variable_instance
        FOREIGN KEY (instance_id) REFERENCES pmis_flow_his_instance (id) ON DELETE CASCADE
);

COMMENT ON TABLE  pmis_flow_his_variable IS '流程变量归档冷存储表（拆分 JSON 为独立行）';
COMMENT ON COLUMN pmis_flow_his_variable.id          IS '主键 ID（自增）';
COMMENT ON COLUMN pmis_flow_his_variable.instance_id IS '归档实例 ID（对应 pmis_flow_his_instance.id）';
COMMENT ON COLUMN pmis_flow_his_variable.var_key     IS '变量键（非 JSON 格式时为 __raw__）';
COMMENT ON COLUMN pmis_flow_his_variable.var_value   IS '变量值（字符串形式）';
COMMENT ON COLUMN pmis_flow_his_variable.archived_at IS '归档时间';

-- 按实例查询变量
CREATE INDEX IF NOT EXISTS idx_pmis_flow_his_variable_instance
    ON pmis_flow_his_variable (instance_id);

-- 按变量键反查（跨实例变量分析）
CREATE INDEX IF NOT EXISTS idx_pmis_flow_his_variable_key
    ON pmis_flow_his_variable (var_key);


-- ---------------------------------------------------------------------
-- 3. 验证脚本
-- ---------------------------------------------------------------------
-- 验证表创建成功
SELECT 'pmis_flow_his_instance' AS table_name, COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_name = 'pmis_flow_his_instance'
UNION ALL
SELECT 'pmis_flow_his_variable' AS table_name, COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_name = 'pmis_flow_his_variable';
