apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-userinfo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-project
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-cronjob
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydsz-pmis-workflow
spec:
  replicas: 1
